### PR TITLE
Fix `declaration-block-no-redundant-longhand-properties` false negatives for shorthand-then-longhand

### LINKED ISSUE #8349: Fix `declaration-block-no-shorthand-property-overrides` false-negative with `background`
### What minimal example or steps are needed to reproduce the bug?

```css
a {
  background: red;
  background-color: red;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "declaration-block-no-shorthand-property-overrides" : true
  }
}
```

### How did you run Stylelint?

https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdilAjJYA1gOYBOEArplPCqTFANxY75FmXUC0kANhKVr0mWAL4gANCABmAS14wAckgC2cRDAAeqgA4KAdGADORyeAiY5xBCAzYU6EKQoKjj2nZw5HsMLySkSAAushZcuPxEXJgQXEYAFgJB8UjcOuQ6MKRBAJ5cEABuWaSysG4gKLRBzjAsKKJiZpCWssQAYgIqwTYAVkYWZrA6poieDiBGuQq8sphB7uP+QTCTjhJ1jpM507NBPBZWcUGpUAFQC45LK-MgjaJAA

### Which Stylelint-related dependencies are you using?

stylelint@16.13.2

### What did you expect to happen?

Problem to be flagged because `background` is a shorthand for `background-color`.

### What actually happened?

No errors being reported.

### Do you have a proposal to fix the bug?

I think it is safe to treat `background` and `background-color` as overriding each other, at least with a single argument to `background`.

### PR DESCRIPTION
**Pull request by nathannewyen**
## Summary
Fixes #8349

This PR detects redundant longhand properties when they follow a shorthand property with the same value.

### Before
```css
a {
  background: red;
  background-color: red; /* No warning - false negative */
}
```

### After
```css
a {
  background: red;
  background-color: red; /* Warning: Unexpected longhand property "background-color" after shorthand property "background" with same value */
}
```

## Changes
- Track declared shorthand properties and their values during declaration block traversal
- Check if longhand properties have a covering shorthand with the same value
- Add new message type `redundantLonghand` for clear error reporting
- Add auto-fix support to remove redundant longhands
- Add test cases for both accept (different values) and reject (same values) scenarios

## Test Plan
- [x] Added accept tests for shorthand + longhand with **different** values (should pass)
- [x] Added reject tests for shorthand + longhand with **same** values (should warn)
- [x] All existing tests pass
- [x] Lint and type checks pass

### CODE REVIEW

**Review by ybiquitous — CHANGES_REQUESTED** [review]
@nathannewyen Thanks for the pull request.

We've started working on the `v17` branch, not `main`, toward the next major version, so can you please recreate the feature branch from `v17` and change the base branch of this PR?

**Comment by nathannewyen** [comment]
I just rebased onto v17 and updated the base branch, can you double check?

File: lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs [hunk 1]
```diff
@@ -15,6 +15,9 @@ const ruleName = 'declaration-block-no-redundant-longhand-properties';
 
 const messages = ruleMessages(ruleName, {
 	expected: (property) => `Expected shorthand property "${property}"`,
+	// Message for when a longhand is redundant because the shorthand was already declared with the same value
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs]: [suggestion] Can you remove such verbose comments?


```suggestion
```

File: lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs [hunk 2]
```diff
@@ -262,6 +265,9 @@ const rule = (primary, secondaryOptions) => {
 			const longhandDeclarations = new Map();
 			/** @type {Map<string, Declaration[]>} */
 			const longhandDeclarationNodes = new Map();
+			// Track declared shorthand properties and their values for detecting redundant longhands
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs]: [suggestion] Same here.

```suggestion
```

File: lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs [hunk 3]
```diff
@@ -15,6 +15,9 @@ const ruleName = 'declaration-block-no-redundant-longhand-properties';
 
 const messages = ruleMessages(ruleName, {
 	expected: (property) => `Expected shorthand property "${property}"`,
+	// Message for when a longhand is redundant because the shorthand was already declared with the same value
+	redundantLonghand: (longhand, shorthand) =>
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs]: [suggestion] Comparing the existing `expected` message, what if renaming the new message prop like this?

```suggestion
	unexpectedLonghand: (longhand, shorthand) =>
```

File: lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs [hunk 4]
```diff
@@ -272,12 +278,52 @@ const rule = (primary, secondaryOptions) => {
 				const prop = decl.prop.toLowerCase();
 				const unprefixedProp = vendor.unprefixed(prop);
 				const prefix = vendor.prefix(prop);
+
+				// Check if this is a shorthand property and track it
+				const shorthandLonghands = longhandSubPropertiesOfShorthandProperties.get(
+					/** @type {import('stylelint').ShorthandProperties} */ (unprefixedProp),
+				);
+
+				if (shorthandLonghands) {
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs]: [suggestion] Can you refactor it like this?

- Use `has` instead of `get`
- Inline the local variable (avoid adding a new variable)

```suggestion
				if (longhandSubPropertiesOfShorthandProperties.has(/** @type {import('stylelint').ShorthandProperties} */ (unprefixedProp))) {
```

File: lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs [hunk 5]
```diff
@@ -272,12 +278,52 @@ const rule = (primary, secondaryOptions) => {
...
+					// This is a shorthand property, store it with its value
+					declaredShorthands.set(prop, decl.value.trim());
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs]: [suggestion] Can you reduce repeated `decl.value.trim()` by adding a new local variable?

```js
eachDecl((decl) => {
  const declValue = decl.value.trim();
```

```suggestion
					declaredShorthands.set(prop, declValue);
```

File: lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs [hunk 6]
```diff
@@ -272,12 +278,52 @@ const rule = (primary, secondaryOptions) => {
...
+				}
+
 				const shorthandProperties = longhandToShorthands.get(unprefixedProp);
 
 				if (!shorthandProperties) {
 					return;
 				}
 
+				// Check if a covering shorthand was declared earlier with the same value
+				for (const shorthandProperty of shorthandProperties) {
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs:296]: [suggestion] I'd like to avoid increasing a `for` loop. Can you integrate the new loop into the existing one?

https://github.com/stylelint/stylelint/blob/01786e9e5281c153ff6a983d770b749fa0f8252f/lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs#L327

File: lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs [hunk 7]
```diff
@@ -272,12 +278,52 @@ const rule = (primary, secondaryOptions) => {
...
+					const prefixedShorthandProperty = prefix + shorthandProperty;
+					const shorthandValue = declaredShorthands.get(prefixedShorthandProperty);
+
+					// If the shorthand was declared and values match, report redundant longhand
+					if (shorthandValue !== undefined && shorthandValue === decl.value.trim()) {
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs]: [suggestion] Can you simplify the condition?

```suggestion
					if (shorthandValue === declValue) {
```

File: lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs [hunk 8]
```diff
@@ -84,6 +84,18 @@ testRule({
...
+			description: 'shorthand then longhand with different values (not redundant)',
+		},
+		{
+			code: 'a { margin: 10px; margin-left: 20px; }',
+			description: 'shorthand then longhand with different values (not redundant)',
+		},
+		{
+			code: 'a { padding: 5px; padding-top: 10px; }',
+			description: 'shorthand then longhand with different values (not redundant)',
+		},
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs]: [suggestion] I think the latter 2 cases are redundant. Can you please remove them?


```suggestion
```

File: lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs [hunk 9]
```diff
@@ -1022,6 +1034,48 @@ testRule({
...
+			message: messages.redundantLonghand('padding-top', 'padding'),
+			line: 1,
+			column: 19,
+			endLine: 1,
+			endColumn: 30,
+			fix: {
+				range: [18, 36],
+				text: '',
+			},
+		},
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs:1081]: [suggestion] Same here.

```suggestion
```

File: lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs [hunk 10]
```diff
@@ -1022,6 +1034,48 @@ testRule({
...
 	],
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs:1082]: [suggestion] Can you add some test cases with multiple warnings? E.g.

```css
/* all longhands have the same value */
a { margin: 1px; margin-left: 1px; margin-right: 1px }
```

```css
/* only one longhand has the same value across another declaration */
a { margin: 1px; margin-left: 2px; margin-right: 1px; }
```

File: lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs [hunk 11]
```diff
@@ -272,12 +278,52 @@ const rule = (primary, secondaryOptions) => {
...
+							decl.remove();
+						};
+
+						report({
+							ruleName,
+							result,
+							node: decl,
+							word: decl.prop,
+							message: messages.redundantLonghand,
+							messageArgs: [prop, prefixedShorthandProperty],
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs]: [suggestion] Can you report a real value instead?

```suggestion
							messageArgs: [decl.prop, prefixedShorthandProperty],
```

**Comment by nathannewyen** [comment]
Hi sorry for taking a bit long, can you check again. Thanks alot!

File: lib/rules/declaration-block-no-redundant-longhand-properties/README.md [hunk 12]
```diff
@@ -137,6 +137,16 @@ a {
 }
 ```
 
+<!-- prettier-ignore -->
+```css
+a {
+  top: 0;
+  right: 5px;
+  bottom: 10px;
+  left: 5px;
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/README.md]: [suggestion] Can you modify the example code to satisfy the new problem?

```suggestion
  margin: 1px;
  margin-left: 1px;
```

File: lib/rules/declaration-block-no-redundant-longhand-properties/README.md [hunk 13]
```diff
@@ -160,6 +170,13 @@ a {
 }
 ```
 
+<!-- prettier-ignore -->
+```css
+a {
+  inset: 0 5px 10px 5px;
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/README.md]: [suggestion] Same here:

```suggestion
  margin: 1px;
  margin-left: 2px;
```

Also, please move this example to the last in this section.

File: lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs:1]: [suggestion] Can you please add more test cases to verify that the new problem works with `ignoreShorthands` and `ignoreLonghands`?

If possible, you can add them to the existing `testRule`s.

Comment (nathannewyen) [reply lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.mjs:1]: Thanks for the review:
  - Added test cases for ignoreShorthands and ignoreLonghands

**Review by jeddy3 — APPROVED** [review]
@nathannewyen LGTM, thank you!

@ybiquitous Thank you for reviewing and helping shape the PR 🙇

**Comment by Mouvedia** [comment]
> We've started working on the v17 branch, not main, toward the next major version, so…

Shouldn't the fixes go to `main` for the time being?
i.e. only the breaking changes would be on v17
