### PR TITLE
Fix `lightness-notation` false negatives for relative colors

### LINKED ISSUE #8986: Fix `lightness-notation` false negatives for relative color
### What minimal example or steps are needed to reproduce the bug?

```css
a {
  color: lch(from red 1 0 0);
}
```

### What minimal configuration is needed to reproduce the bug?

```js
export default {
  rules: {'lightness-notation': 'percentage'}
};
```

### How did you run Stylelint?

https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdilkA2EATvCnmABYAUAZoRALYqExQoCMKADFwJQDcWAL4gANCGoBLPDABySenEQwAHvIAO0gHRgAzjtHgImSQHMEIFWqIAXFLGpIArnlsZsTZzB0lgAcjwSJuTWmF46ALSYENZI1hJGviS+ajCEYDCYMSYwvoJCApgGkMaBAGJE9LHmOtYAntIBmdpGppr0AFb6YrBq+ohuOOggNfUwjdZDJEN4sV4ToliDw3UNEpnhxabhNUiYUEiEUJMo07M1Q0JYIIJAA

### Which Stylelint-related dependencies are you using?

[stylelint](https://stylelint.io/)@17.0.0
 [stylelint-config-standard](https://www.npmjs.com/package/stylelint-config-standard)@40.0.0

### What did you expect to happen?

An error should be reported for a lightness value of `1` when expecting a percentage

### What actually happened?

No problems reported

### Do you have a proposal to fix the bug?

Detect relative color, and shift reporting column

### PR DESCRIPTION
**Pull request by jamesnw**
Closes #8986 

In #7359, it was determined to not handle `hsl`, so all handled colors have lightness as the first channel. This assumption and check would need to be updated to support hsl.

### CODE REVIEW

File: lib/rules/lightness-notation/index.mjs [hunk 1]
```diff
@@ -155,7 +155,13 @@ function roundToNumberOfDigits(num, value) {
...
  */
 function findLightness({ nodes }) {
-	return nodes.find(({ type }) => type === 'word' || type === 'function');
+	const words = nodes.filter(({ type }) => type === 'word' || type === 'function');
+
+	if (words[0] && words[0].value.toLowerCase() === 'from') {
+		return words[2];
+	}
+
+	return words[0];
```
Comment (jeddy3) [inline lib/rules/lightness-notation/index.mjs]:
```suggestion
	const args = nodes.filter(({ type }) => type === 'word' || type === 'function');
	const isRelativeColor = args[0]?.value.toLowerCase() === 'from';

	return isRelativeColor ? args[2] : args[0];
```

Let's refactor to be self-documenting and precise in our language.

Comment (jamesnw) [reply lib/rules/lightness-notation/index.mjs]: Much improved- thanks!

File: .changeset/selfish-eyes-battle.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"stylelint": minor
+---
+
+Fixed `lightness-notation` false negatives for relative colors
```
Comment (romainmenke) [inline .changeset/selfish-eyes-battle.md]:
```suggestion
Fixed: `lightness-notation` false negatives for relative colors
```

Missing `:`
