### PR TITLE
Fix false positives for non-standard variables in `function-calc-no-unspaced-operator`

### LINKED ISSUE #6052: Fix false positives for SCSS variables in function-calc-no-unspaced-operator
### What steps are needed to reproduce the bug?

```scss
textarea {
  min-height: calc(#{$line-height} * 5);
}
```

### What Stylelint configuration is needed to reproduce the bug?

```js
module.exports = {
  plugins: [
    'stylelint-scss',
  ],
  extends: ['stylelint-config-standard-scss'],
  rules: { },
}

```

### How did you run Stylelint?

CLI with `stylelint 'css/**/*.scss'`

### Which version of Stylelint are you using?

`14.8.1`

### What did you expect to happen?

Behavior like in previous versions <= 14.8.0

### What actually happened?

```shell
css/components/_forms.scss
 213:27  ✖  Expected single space before "-" operator  function-calc-no-unspaced-operator
 213:28  ✖  Expected single space after "-" operator   function-calc-no-unspaced-operator

```

### Does the bug relate to non-standard syntax?

Yes it happens with SCSS variables inside calc()

### Proposal to fix the bug

This happens only in the newest version 14.8.1 with this fixed: https://github.com/stylelint/stylelint/pull/6045

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

Closes #6052

> Is there anything in the PR that needs further explanation?

This pull request aims to fix false positives for non-standard variables (e.g. SCSS, Less, and so on.) in the `function-calc-no-unspaced-operator` rule.

I think [`isStandardSyntaxValue()`](https://github.com/stylelint/stylelint/blob/e017583128863ee75634cb15e721779163b571e5/lib/utils/isStandardSyntaxValue.js) is more appropriate than [`isStandardSyntaxMathFunction()`](https://github.com/stylelint/stylelint/blob/e017583128863ee75634cb15e721779163b571e5/lib/utils/isStandardSyntaxMathFunction.js) suggested on <https://github.com/stylelint/stylelint/issues/6052#issuecomment-1114004679> because `isStandardSyntaxMathFunction()` fails the cases using non-standard variables. E.g.

https://github.com/stylelint/stylelint/blob/e017583128863ee75634cb15e721779163b571e5/lib/rules/function-calc-no-unspaced-operator/__tests__/index.js#L535-L543

### CODE REVIEW

File: lib/rules/function-calc-no-unspaced-operator/index.js [hunk 1]
```diff
@@ -166,6 +167,8 @@ const rule = (primary, _secondaryOptions, context) => {
 
 				if (firstNode.type !== 'word') return false;
 
+				if (!isStandardSyntaxValue(firstNode.value)) return false;
+
 				const operatorIndex = firstNode.value.search(OPERATOR_REGEX);
```
Comment (ybiquitous) [inline lib/rules/function-calc-no-unspaced-operator/index.js:172]: [note] If the `isStandardSyntaxValue()` check is not performed, `firstNode.value` like `#{$foo-bar}` matches `/[+-]/` (`OPERATOR_REGEX`):

https://github.com/stylelint/stylelint/blob/e017583128863ee75634cb15e721779163b571e5/lib/rules/function-calc-no-unspaced-operator/index.js#L26

**Review by jeddy3 — APPROVED** [review]
LGTM, thank you!

**Comment by ybiquitous** [comment]
Changelog entry added:

> - Fixed: `function-calc-no-unspaced-operator` false positives for non-standard variables ([#6053](https://github.com/stylelint/stylelint/pull/6053)).
