### PR TITLE
Fix `declaration-property-value-keyword-no-deprecated` false positives for non-standard syntax values

### LINKED ISSUE #8327: Fix `declaration-property-value-keyword-no-deprecated` false positives
### What minimal example or steps are needed to reproduce the bug?

```typescript
const SensitiveContentInner = styled.div`
  background-color: ${palette(({ background }) => background.primary)};
  border: 1px solid ${palette(({ border }) => border.primary)};
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100%;
  width: 100%;
`;

const RewardNoticeHolder = styled.div`
  position: absolute;
  background: ${palette(({ background }) => background.tertiary)};
  border-radius: ${shape(({ wrapperBorderRadius }) => wrapperBorderRadius)};
  border-top-right-radius: 0;
  padding: ${spacing(0.5)} ${spacing(1)};
  text-align: right;
  &::before {
    content: '';
    position: absolute;
    right: 0;
    bottom: 100%;
    width: 0;
    height: 0;
    border-style: solid;
    border-width: 0 0 12px 16px;
    border-color: transparent transparent
      ${palette(({ background }) => background.tertiary)} transparent;
  }
`;
```

### What minimal configuration is needed to reproduce the bug?

```js
/** @type {import('stylelint').Config} */
module.exports = {
  extends: ['stylelint-config-recommended'],
  customSyntax: 'postcss-styled-syntax',
  plugins: ['stylelint-plugin-logical-css'],
  rules: {
    'plugin/use-logical-properties-and-values': [
      true,
      {
        severity: 'warning',
        ignore: [
          'height',
          'max-height',
          'min-height',
          'width',
          'max-width',
          'min-width',
          'contain-intrinsic-height',
          'contain-intrinsic-width',
          'overflow-x',
          'overflow-y',
          'overscroll-behavior-x',
          'overscroll-behavior-y',
          'box-orient: vertical',
          'box-orient: horizontal',
          '-webkit-box-orient: vertical',
          '-webkit-box-orient: horizontal',
          'resize: horizontal',
          'resize: vertical'
        ]
      }
    ],
    'plugin/use-logical-units': [true, { severity: 'warning' }],
    'value-no-vendor-prefix': true,
    'property-no-vendor-prefix': true,
    'no-empty-source': null,
    'unit-no-unknown': [
      true,
      {
        ignoreUnits: ['svh']
      }
    ],
    'selector-type-no-unknown': [
      true,
      {
        ignoreTypes: [
          'Texteffecttext-shadow',
          'znipe-multi-view-player',
          'znipe-single-view-player',
          'dropFile'
        ]
      }
    ],
    'property-no-unknown': [
      true,
      {
        ignoreProperties: [
          'margin-vertical',
          'margin-horizontal',
          'padding-horizontal',
          'padding-vertical',
          'tint-color',
          'resize-mode',
          'aspect-ratio',
          'shadow-radius',
          'shadow-color',
          'shadow-offset',
          'shadow-opacity',
          'theme'
        ]
      }
    ]
  }
};
```

### How did you run Stylelint?

VSCode Extension

### Which Stylelint-related dependencies are you using?

```json
  "stylelint": "^16.12.0",
    "stylelint-config-recommended": "^14.0.1",
    "stylelint-formatter-gitlab": "^1.0.2",
    "stylelint-plugin-logical-css": "^1.2.1",
```

### What did you expect to happen?

No errors

### What actually happened?

The following problems were reported:

```
Expected "${palette(({ background }) => background.primary)}" to be "canvas" (declaration-property-value-keyword-no-deprecated)Stylelint[declaration-property-value-keyword-no-deprecated](https://stylelint.io/user-guide/rules/declaration-property-value-keyword-no-deprecated)
```

```
Expected "transparent transparent
      ${palette(({ background }) => background.tertiary)} transparent" to be "canvas" (declaration-property-value-keyword-no-deprecated)
```

### Do you have a proposal to fix the bug?

_No response_

### PR DESCRIPTION
**Pull request by Mouvedia**
> Which issue, if any, is this issue related to?

Closes #8327

> Is there anything in the PR that needs further explanation?

`${foo(({ background }) => background.bar)}` cannot be tested in the `accept` array because it gives a `CssSyntaxError` without `postcss-styled-syntax` which shan't be added as a dependency.
i.e. no `customSyntax: 'postcss-styled-syntax',` testRule
see discussion in #6556

ref: https://styled-components.com/docs/advanced#tagged-template-literals

### CODE REVIEW

File: lib/rules/declaration-property-value-keyword-no-deprecated/index.mjs [hunk 1]
```diff
@@ -129,10 +129,17 @@ const rule = (primary, secondaryOptions) => {
 			if (!keywords) return;
 
 			const parsedValue = valueParser(getDeclarationValue(decl));
+			let flag = false;
 
 			parsedValue.walk((node) => {
+				if (flag) return;
```
Comment (Mouvedia) [inline lib/rules/declaration-property-value-keyword-no-deprecated/index.mjs:135]: @romainmenke I tried returning `false` + setting bubble to `true`; how do you break from `walk`?

File: lib/rules/declaration-property-value-keyword-no-deprecated/index.mjs [hunk 2]
```diff
@@ -129,10 +129,17 @@ const rule = (primary, secondaryOptions) => {
...
+
 				if (node.type !== 'word') return;
 
+				// FIXME once we support shorthands
+				// e.g. border-color: green red yellow ActiveBorder;
+				flag = true;
```
Comment (Mouvedia) [inline lib/rules/declaration-property-value-keyword-no-deprecated/index.mjs:141]: @ybiquitous what's better in your opinion a flag like I did or `try`/`catch`?

Comment (romainmenke) [reply lib/rules/declaration-property-value-keyword-no-deprecated/index.mjs:141]: A `throw` + `try/catch` is extremely slow.
When an actual exception needs to happen or needs to caught, then this is fine. But using it as a way to escape early will most likely be slower than just letting the `walk` run to completion.

Comment (Mouvedia) [reply lib/rules/declaration-property-value-keyword-no-deprecated/index.mjs:141]: > A `throw` + `try/catch` is extremely slow.

I know…

File: lib/rules/declaration-property-value-keyword-no-deprecated/index.mjs (hunk 1 above)
Comment (Mouvedia) [reply lib/rules/declaration-property-value-keyword-no-deprecated/index.mjs:135]: > Can you add failing tests?

I can't.
see https://github.com/stylelint/stylelint/issues/8327#issuecomment-2596623482

But you can try `npm i -D postcss-styled-syntax` +
```js
testRule({
	ruleName,
	customSyntax: 'postcss-styled-syntax',
	config: [true],

	accept: [
		{
			code: `
				export const s = styled.a\`
					background-color: \${palette(({ background }) => background.primary)};
				\`;
			`,
		},
	],
});
```

Comment (romainmenke) [reply lib/rules/declaration-property-value-keyword-no-deprecated/index.mjs:135]: Shouldn't we just return early when the value isn't a standard syntax value?
Currently we only check the property, not the value.

Comment (Mouvedia) [reply lib/rules/declaration-property-value-keyword-no-deprecated/index.mjs:135]: I think that not running the code unnecessarily is still a good thing.
It will also skip cases that are invalid.

e.g.
someone who erroneously used `background-color` instead of `background-color`
`background-color: border-box WindowFrame;`

---

> Ill try to come up with a non css-in-js test.

I can't come up with a non-invalid CSS test case because we don't support shorthands yet.
i.e. the properties are filtered
see also #8328

Comment (romainmenke) [reply lib/rules/declaration-property-value-keyword-no-deprecated/index.mjs:135]: If there is no failing test or real world use case then I can't really advise :/

Comment (romainmenke) [reply lib/rules/declaration-property-value-keyword-no-deprecated/index.mjs:135]: If the concern is purely performance and that this change isn't intended to change the behavior then I would suggest adding an early check that the value at least contains one of the candidates. see: https://github.com/stylelint/stylelint/issues/6869

Skipping the parsing step will be much more impactful than stopping the walk early.

If however there is an intended behavior change, then there should be some illustration of why the current behavior isn't ideal :)
I am still trying to understand what the issue is and how this change relates to it.
Given that the title is also `TBD` I really have too little information to be helpful.
My advice is likely wrong purely because I don't have sufficient information.

Comment (Mouvedia) [reply lib/rules/declaration-property-value-keyword-no-deprecated/index.mjs:135]: > Shouldn't we just return early when the value isn't a standard syntax value?

Ill just do that.

File: .changeset/violet-shirts-dream.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"stylelint": patch
+---
+
+Fixed: `declaration-property-value-keyword-no-deprecated` false positives in styled component interpolations
```
Comment (romainmenke) [inline .changeset/violet-shirts-dream.md:5]:
```suggestion
Fixed: `declaration-property-value-keyword-no-deprecated` false positives for non-standard syntax values
```

Because the change will also prevent false positives in other kinds of non-standard syntax.

Can you also change the title?

**Review by romainmenke — COMMENTED** [review]
Looks good! Thank you!
I've made a suggestion for a more general title and changelog entry.

**Comment by romainmenke** [comment]
> i.e. no `customSyntax: 'postcss-styled-syntax'`, hence codecov warning can be ignored

But we can have a test for a simpler value containing `$`. We don't have to test `postcss-styles-syntax`, we only have to test any non-standard value. Most (all?) rules with such conditions also have some samples of non-standard syntax.

For example: `lib/rules/declaration-block-no-duplicate-properties/__tests__/index.mjs`

```
		{
			code: 'a { $scss: 0; $scss: $scss + 1; }',
		},
		{
			code: 'a { @less: 0; @less: @less + 1; }',
		},
```

File: .changeset/violet-shirts-dream.md (hunk 3 above)
Comment (romainmenke) [inline .changeset/violet-shirts-dream.md:5]:
```suggestion
Fixed: `declaration-property-value-keyword-no-deprecated` false positives for non-standard syntax values
```

I think this was lost when you force pushed?

**Review by romainmenke — APPROVED** [review]
Thank you. LGTM 👍
