### PR TITLE
Fix `nesting-selector-no-missing-scoping-root` false positives for CSS-in-JS

### LINKED ISSUE #8727: Fix nesting-selector-no-missing-scoping-root for CSS-in-JS
### What minimal example or steps are needed to reproduce the bug?

```
const Root = styled.div`
  &::before {
    color: red;
  }
`;
```

### What minimal configuration is needed to reproduce the bug?

```
{
  "nesting-selector-no-missing-scoping-root": true
}
```

### How did you run Stylelint?

VS Code extension.

### Which Stylelint-related dependencies are you using?

```
    "stylelint": "16.23.1",
    "stylelint-config-recommended": "17.0.0",
```

### What did you expect to happen?

No error.

### What actually happened?

Unexpected missing scoping root (nesting-selector-no-missing-scoping-root)

### Do you have a proposal to fix the bug?

_No response_

### PR DESCRIPTION
**Pull request by kovsu**
> Which issue, if any, is this issue related to?

Closes #8727 

> Is there anything in the PR that needs further explanation?

No

### CODE REVIEW

**Comment by kovsu** [comment]
WTF. It has passed in my end.

CleanShot 2025-12-06 at 23 42 17@2x

File: lib/rules/nesting-selector-no-missing-scoping-root/__tests__/index.mjs [hunk 1]
```diff
@@ -259,3 +261,18 @@ testRule({
...
+	config: [true],
+	customSyntax: naiveCssInJs,
+
+	accept: [
+		{
+			code: 'css` &::before {} `;',
+		},
+		{
+			code: 'css` @media all { & {} } `;',
+		},
```
Comment (jeddy3) [inline lib/rules/nesting-selector-no-missing-scoping-root/__tests__/index.mjs:276]:
```suggestion
		},
		{
			code: 'css` @scope (&) {} `;',
		},
```
