### PR TITLE
Fix `no-descending-specificity` & `no-duplicate-selectors` false negatives for equivalent compound selectors

### LINKED ISSUE #7869: Fix `no-duplicate-selectors` false negatives for equivalent compound selectors
### What minimal example or steps are needed to reproduce the bug?

```css
.a.b {}
/* … */
.b.a {}
```

```css
#a.b {}
/* … */
.b#a {}
```

```css
div.a.b {}
/* … */
div.b.a {}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "no-duplicate-selectors": true
  }
}
```

ref: https://drafts.csswg.org/selectors/#compound

### PR DESCRIPTION
**Pull request by kovsu**
> Which issue, if any, is this issue related to?

Closes #7869

> Is there anything in the PR that needs further explanation?

No

### CODE REVIEW

File: lib/utils/normalizeSelector.mjs [hunk 1]
```diff
@@ -81,4 +81,79 @@ function normalizeSelectorNodesOrder(node) {
...
+
+/**
+ * @param {Node[]} nodes
+ * @returns {Node[]}
+ */
+function sortCompoundSelectors(nodes) {
+	/** @type {Node[][]} */
+	const compoundSelectors = [];
+	/** @type {Node[]} */
+	let currentCompoundSelector = [];
```
Comment (ybiquitous) [inline lib/utils/normalizeSelector.mjs]: [suggestion] What if we could rename the variables for better readability?

```suggestion
	const compoundSelectorGroups = [];
	/** @type {Node[]} */
	let currentCompoundSelectorGroup = [];
```

File: lib/utils/normalizeSelector.mjs [hunk 2]
```diff
@@ -81,4 +81,79 @@ function normalizeSelectorNodesOrder(node) {
...
+
+	nodes.forEach((childNode) => {
+		if (parser.isCombinator(childNode) || parser.isPseudoElement(childNode)) {
+			if (currentCompoundSelector.length > 0) {
+				compoundSelectors.push(currentCompoundSelector);
+			}
+
+			compoundSelectors.push([childNode]);
```
Comment (ybiquitous) [inline lib/utils/normalizeSelector.mjs]: [suggestion] What about refactoring the code like so? It could reduce unnecessary `if` blocks.

```suggestion
			compoundSelectors.push(currentCompoundSelector, [childNode]);
```

File: lib/utils/normalizeSelector.mjs [hunk 3]
```diff
@@ -81,4 +81,79 @@ function normalizeSelectorNodesOrder(node) {
...
+			currentCompoundSelector = [];
+		} else {
+			currentCompoundSelector.push(childNode);
+		}
+	});
+
+	if (currentCompoundSelector.length > 0) {
+		compoundSelectors.push(currentCompoundSelector);
+	}
```
Comment (ybiquitous) [inline lib/utils/normalizeSelector.mjs]: [suggestion] Eventually, empty arrays are flattened by `compoundSelectors.flat()`, so removing `length` checks should not be harmful. 

```suggestion
	compoundSelectors.push(currentCompoundSelector);
```

File: lib/utils/normalizeSelector.mjs [hunk 4]
```diff
@@ -81,4 +81,79 @@ function normalizeSelectorNodesOrder(node) {
...
+
+	compoundSelectors.forEach((group) => {
+		if (group.length > 1) {
+			group.sort(byPriority);
+		}
+	});
```
Comment (ybiquitous) [inline lib/utils/normalizeSelector.mjs]: [suggestion] 

```suggestion
	compoundSelectors.forEach((group) => group.sort(byPriority));
```

**Review by ybiquitous — COMMENTED** [review]
Thanks for the pull request, and sorry for the late review.

Can you take a look at my comments? Thanks.

**Comment by ybiquitous** [comment]
Also, can you please avoid including `#` in your branches? 🙏🏼 

I guess the `#` character breaks the link below on <https://github.com/stylelint/stylelint/pull/8977#issuecomment-3766187290>:

> [Click here if you're a maintainer who wants to add another changeset to this PR](https://github.com/kovsu/stylelint/new/fix-#7869?filename=.changeset/twelve-shoes-reflect.md&value=---%0A%22%40fake-scope%2Ffake-pkg%22%3A%20patch%0A---%0A%0AFix%20%60no-duplicate-selectors%60%20false%20negatives%20for%20equivalent%20compound%20selectors%0A)

File: .changeset/tough-apes-provide.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+"stylelint": minor
+---
+
+Fixed: `no-duplicate-selectors` false negatives for equivalent compound selectors
```
Comment (jeddy3) [inline .changeset/tough-apes-provide.md]:
```suggestion
Fixed: `no-descending-specificity` & `no-duplicate-selectors` false negatives for equivalent compound selectors
```

From https://github.com/stylelint/stylelint/pull/8934#discussion_r2649722332.

**Comment by jeddy3** [comment]
@kovsu Thanks for continuing to work on this feature.

We recently added caching to `normalizeSelector` because cloning is expensive. There's a minor conflict in the utility that you'll need to resolve before continuing, thanks!

**Comment by kovsu** [comment]
Sorry for late response. I have updated my code and apply your suggestions.
