### PR TITLE
Fix `declaration-block-no-shorthand-property-overrides` false negatives for `border`

### LINKED ISSUE #7506: Fix `declaration-block-no-shorthand-property-overrides` false negatives for `border`
### What minimal example or steps are needed to reproduce the bug?

```css
a {
	border-color: red;
	border: 1px solid blue;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "declaration-block-no-shorthand-property-overrides": true
  }
}
```

### How did you run Stylelint?

All ways.

### Which Stylelint-related dependencies are you using?

```json
"stylelint": "16.2.0"
```

### What did you expect to happen?

To get a violation:

```
Unexpected shorthand "border" after "border-color"
```

### What actually happened?

No violation is reported.

### Do you have a proposal to fix the bug?

Update [shorthands reference](https://github.com/stylelint/stylelint/blob/328544d8dfe4abfb1d75ab6631528f2e3c605a74/lib/reference/properties.mjs#L15).

Looking at the reference, it could be further improved. E. g. `border` doesn't have `border-block`, `border-block-end`, etc. in it's set. Which means that there are more unreported violations.

### PR DESCRIPTION
**Pull request by fpetrakov**
> Which issue, if any, is this issue related to?

Closes #7506

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

### CODE REVIEW

File: lib/rules/declaration-block-no-shorthand-property-overrides/index.mjs [hunk 1]
```diff
@@ -37,9 +37,9 @@ const rule = (primary) => {
 					longhandSubPropertiesOfShorthandProperties
 				).get(unprefixedProp);
 
-				if (!overrideables) {
-					declarations.set(prop.toLowerCase(), prop);
+				declarations.set(prop.toLowerCase(), prop);
```
Comment (Mouvedia) [inline lib/rules/declaration-block-no-shorthand-property-overrides/index.mjs:40]: nit

This can moved after l44.

File: lib/rules/declaration-block-no-shorthand-property-overrides/__tests__/index.mjs [hunk 2]
```diff
@@ -47,6 +47,46 @@ testRule({
...
+			endColumn: 40,
+		},
+		{
+			code: 'a { border-block-start: 1px solid; border: 20px dashed black; }',
+			message: messages.rejected('border', 'border-block-start'),
+			line: 1,
+			column: 36,
+			endLine: 1,
+			endColumn: 42,
+		},
```
Comment (Mouvedia) [inline lib/rules/declaration-block-no-shorthand-property-overrides/__tests__/index.mjs:73]: These are incorrect and have to be removed.
You could add them as passing if you want to detect regressions though.

File: lib/rules/declaration-block-no-shorthand-property-overrides/index.mjs [hunk 3]
```diff
@@ -37,9 +37,9 @@ const rule = (primary) => {
 					longhandSubPropertiesOfShorthandProperties
 				).get(unprefixedProp);
 
-				if (!overrideables) {
-					declarations.set(prop.toLowerCase(), prop);
```
Comment (Mouvedia) [inline lib/rules/declaration-block-no-shorthand-property-overrides/index.mjs:41]: question
medium

Shouldn't this being in this `if` block have produced a bug?
i.e. a test is probably missing to cover that case or the setter was useless

**Review by Mouvedia — CHANGES_REQUESTED** [review]

File: lib/reference/properties.mjs [hunk 4]
```diff
@@ -58,6 +58,11 @@ export const longhandSubPropertiesOfShorthandProperties = new Map([
 			'border-right-color',
 			'border-bottom-color',
 			'border-left-color',
+			'border-color',
+			'border-style',
+			'border-block',
+			'border-block-end',
+			'border-block-start',
```
[the remark this answers is not in the document]
Comment (ybiquitous) [reply lib/reference/properties.mjs:65]: Right. This `longhandSubPropertiesOfShorthandProperties` is exposed under the `reference` type, so we need to keep its correctness.

https://github.com/stylelint/stylelint/blob/a5965a09b557fd4a5420a6b48f1c1353ecf83aa2/types/stylelint/index.d.ts#L826-L831

[the remark this answers is not in the document]
Comment (ybiquitous) [reply lib/reference/properties.mjs:65]: So, I guess some specific logic for this rule is necessary.

---

Also, supporting `border-image` seems reasonable to me because the [CSS spec](https://drafts.csswg.org/css-backgrounds/#propdef-border) says:

> The [border](https://drafts.csswg.org/css-backgrounds/#propdef-border) shorthand also resets [border-image](https://drafts.csswg.org/css-backgrounds/#propdef-border-image) to its initial value.

E.g.

```css
a {
  border-image: url('...'); /* this is ignored by border */
  border: 1px solid black; /* here, border-image is reset */
}
```

File: .changeset/mighty-cows-behave.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+"stylelint": minor
```
Comment (ybiquitous) [inline .changeset/mighty-cows-behave.md:2]: [note] This fix will increase Stylelint errors, so "minor" is correct according to our versioning policy.

https://github.com/stylelint/stylelint/blob/a5965a09b557fd4a5420a6b48f1c1353ecf83aa2/docs/about/semantic-versioning.md?plain=1#L17-L21

File: lib/rules/declaration-block-no-shorthand-property-overrides/index.mjs (hunk 1 above)
Comment (ybiquitous) [reply lib/rules/declaration-block-no-shorthand-property-overrides/index.mjs:40]: I think this cannot be moved after L44. The move breaks some test cases.

File: lib/reference/properties.mjs (hunk 4 above)
[the remark this answers is not in the document]
Comment (ybiquitous) [reply lib/reference/properties.mjs:65]: > So, I guess some specific logic for this rule is necessary.

Sorry, this comment was inaccurate. I mean that the following 3 properties addition makes sense:

```js
'border-width',
'border-style',
'border-color',
```

This order reflects the `border` shorthand's [values order](https://developer.mozilla.org/en-US/docs/Web/CSS/border#values).

But `border-image` cannot be added here because it's for resetting a value, unlike other properties. If we'd like to support `border-image`, we should write custom logic in `declaration-block-no-shorthand-property-overrides/index.mjs`.

File: lib/rules/declaration-block-no-shorthand-property-overrides/index.mjs (hunk 3 above)
Comment (ybiquitous) [reply lib/rules/declaration-block-no-shorthand-property-overrides/index.mjs:41]: I feel like this logic change makes sense because test cases other than `border-block*` properties pass.

File: lib/reference/properties.mjs (hunk 4 above)
[the remark this answers is not in the document]
Comment (ybiquitous) [reply lib/reference/properties.mjs:65]: If supporting `border-image` is difficult, I think only `border-width`, `border-style`, and `border-color` are enough for this PR. 👌🏼

File: lib/rules/declaration-block-no-shorthand-property-overrides/index.mjs (hunk 3 above)
Comment (Mouvedia) [reply lib/rules/declaration-block-no-shorthand-property-overrides/index.mjs:41]: If I understand the change, a new passing test is needed or it needs to be kept in the `if`.
I gotta checkout your branch to check.

**Review by Mouvedia — APPROVED** [review]
LGTM

File: lib/reference/properties.mjs (hunk 4 above)
[the remark this answers is not in the document]
Comment (Mouvedia) [reply lib/reference/properties.mjs]: > I think only border-width, border-style, and border-color are enough for this PR.

👍 

> The border shorthand also resets border-image to its initial value.

@ybiquitous can you create a separate issue?

[the remark this answers is not in the document]
Comment (ybiquitous) [reply lib/reference/properties.mjs]: Sure. Just opened #7586.

**Review by ybiquitous — APPROVED** [review]
@fpetrakov LGTM. Thanks a lot for actively fixing bugs! 😊

**Comment by fpetrakov** [comment]
@ybiquitous thanks for the kindness and actively reviewing my PRs!
