### PR TITLE
Fix SVG tags whitelist in selector-type-no-unknown rule (#4472)

### LINKED ISSUE #4472: FP 'selector-type-no-unknown' for 'foreignObject' from svg
There are false positives for 'foreignObject' selector for rule 'selector-type-no-unknown'.
```css
.test foreignObject {
  color: white
}
```

With config:
```json
{
  "rules": {
    "selector-type-no-unknown": true
  }
}
```

To reproduce I used https://stylelint.io/demo, following issue is reported
```
1:7 error Unexpected unknown type selector "foreignObject" (selector-type-no-unknown)
```

There should be no issue as [`foreignObject` tag is part of SVG definition](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject).

### PR DESCRIPTION
**Pull request by webschik**
Fix for `selector-type-no-unknown` rule

Closes #4472

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -1,3 +1,4 @@
+.idea
```
Comment (hudochenkov) [inline .gitignore]: Remove this, please. You can setup global Git config on your machine to ignore files for your editor.

File: lib/rules/selector-type-no-unknown/__tests__/index.js [hunk 2]
```diff
@@ -85,6 +85,10 @@ testRule(rule, {
 			code: 'circle {}',
 			description: 'svg tags',
 		},
+		{
+			code: '.test foreignObject { color: white }',
```
Comment (hudochenkov) [inline lib/rules/selector-type-no-unknown/__tests__/index.js]: Sorry, didn't spot it right away:

```suggestion
			code: 'foreignObject { }',
```

It's for consistency with other test cases. Could you also adjust description to `case-sensitive svg tags`, please?

**Comment by hudochenkov** [comment]
> -   Fixed: `selector-type-no-unknown` false positives for SVG tags ([#4495](https://github.com/stylelint/stylelint/pull/4495)).
