### PR TITLE
Fix `function-no-unknown` false positives for `scroll`, `-webkit-gradient`, `color-stop`, `from`, and `to`

### LINKED ISSUE #5960: Unexpected unknown function `"-webkit-gradient"` & `"color-stop"`  function-no-unknown
### What steps are needed to reproduce the bug?

I'm having this css class in my project. It has `-webkit-gradient` and inside of it, it has `color-stop`.

```css
.text-line {
  -webkit-animation-duration: 1.25s;
  animation-duration: 1.25s;
  -webkit-animation-fill-mode: forwards;
  animation-fill-mode: forwards;
  -webkit-animation-iteration-count: infinite;
  animation-iteration-count: infinite;
  -webkit-animation-name: placeHolderShimmer;
  animation-name: placeHolderShimmer;
  -webkit-animation-timing-function: linear;
  animation-timing-function: linear;
  background: #f6f6f6;
  background: -webkit-gradient(
    linear,
    left top,
    right top,
    color-stop(8%, #f6f6f6),
    color-stop(18%, #f0f0f0),
    color-stop(33%, #f6f6f6)
  );
  background: linear-gradient(to right, #f6f6f6 8%, #f0f0f0 18%, #f6f6f6 33%);
  background-size: 800px 104px;
  height: 96px;
  position: relative;
}
```

### What Stylelint configuration is needed to reproduce the bug?

It's [Nuxt stylelint-module](https://github.com/nuxt-community/stylelint-module)
```js
module.exports = {
  extends: "stylelint-config-recommended-vue",
  rules: {
    "at-rule-no-unknown": [
      true,
      {
        ignoreAtRules: [
          "tailwind",
          "apply",
          "variants",
          "responsive",
          "screen",
        ],
      },
    ],
    "declaration-block-trailing-semicolon": null,
    "no-descending-specificity": null,
  },
};

```

### How did you run Stylelint?

Nuxt.js handles that.

### Which version of Stylelint are you using?

`14.4.0`

### What did you expect to happen?

To not have bugs or to find it supported in Stylelint documentations.

### What actually happened?

```bash
 64:15  ✖  Unexpected unknown function "-webkit-gradient"  function-no-unknown
 68:5   ✖  Unexpected unknown function "color-stop"        function-no-unknown
 69:5   ✖  Unexpected unknown function "color-stop"        function-no-unknown
 70:5   ✖  Unexpected unknown function "color-stop"        function-no-unknown

```

### Does the bug relate to non-standard syntax?

No.

### Proposal to fix the bug

_No response_

### LINKED ISSUE #6537: Fix `function-no-unknown` false positive for `scroll()`
### What steps are needed to reproduce the bug?

use [`scroll()`](https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timeline/scroll)
with `layout.css.scroll-linked-animations.enabled` enabled

### Question

My question is more general; should we preemptively fix stuff or should we wait for issues to pop up once it's not behind a flag anymore?
i.e. preemptive measures or late fixes

ref
- https://www.w3.org/TR/scroll-animations-1/#scroll-notation
- https://caniuse.com/mdn-css_properties_animation-timeline_scroll

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "function-no-unknown": "true"
  }
}
```

### Proposal to fix the bug

maybe PR https://github.com/niksy/css-functions-list/

### PR DESCRIPTION
**Pull request by Mouvedia**
> Which issue, if any, is this issue related to?

Closes #6537

> Is there anything in the PR that needs further explanation?

see https://github.com/stylelint/stylelint/issues/6537#issuecomment-1363471880

### CODE REVIEW

File: lib/rules/function-no-unknown/index.js [hunk 1]
```diff
@@ -43,7 +43,16 @@ const rule = (primary, secondaryOptions) => {
...
 		}
 
-		const functionsList = JSON.parse(fs.readFileSync(functionsListPath.toString(), 'utf8'));
+		const functionsList = [
+			...JSON.parse(fs.readFileSync(functionsListPath.toString(), 'utf8')),
+			// #5960
+			'-webkit-gradient',
+			'color-stop',
+			'from',
+			'to',
```
Comment (ybiquitous) [inline lib/rules/function-no-unknown/index.js:52]: [ask] Adding `-webkit-gradient` seems reasonable because [`css-function-list` includes vendor-prefixed functions](https://github.com/niksy/css-functions-list/blob/0c17ffe6f4fcc43afb4dcf4befca3ceb7dd23b6b/index.json#L122). However, adding `color-stop`, `from`, and `to` may cause false negatives. Are they described on any specs?

Comment (Mouvedia) [reply lib/rules/function-no-unknown/index.js:52]: They are part of the functions used by `-webkit-gradient` value.
check https://github.com/stylelint/stylelint/pull/6539/files#diff-ec67c2191547de2436754f5cc78f9a4f61564730f4215b69cd3829a0d58af7b6R26

**Comment by Mouvedia** [comment]
@jeddy3 @ybiquitous
Should I edit the CHANGELOG and add a changeset for all PRs?

File: lib/rules/function-no-unknown/index.js (hunk 1 above)
Comment (ybiquitous) [reply lib/rules/function-no-unknown/index.js:52]: Understood. But I'm still concerned about potential false negatives. The following report would not be emitted if this change would be merged:

```css
a { background: color-stop(...); }
             /* ↑ Unexpected unknown function "color-stop" */
```

Comment (Mouvedia) [reply lib/rules/function-no-unknown/index.js:52]: AFAIK we have the same problem with all functions that required nesting.

e.g.
```
width: cos(pi); // invalid (but passes)
width: calc(100px * cos(pi)); // valid
```

The rule name is `function-no-unknown` so I consider the problem a non-issue.

Comment (ybiquitous) [reply lib/rules/function-no-unknown/index.js:52]: That makes sense. 👍🏼

**Comment by ybiquitous** [comment]
> Should I edit the CHANGELOG and add a changeset for all PRs?

Yes, please. I've updated the PR title for a changeset.

**Review by ybiquitous — APPROVED** [review]

**Comment by Mouvedia** [comment]
I didn't update the CHANGELOG because #6409 is not 14.6.1

File: .changeset/itchy-seas-care.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"stylelint": patch
+---
+
+Fix `function-no-unknown` false positives for `scroll`, `-webkit-gradient`, `color-stop`, `from`, and `to`
```
Comment (ybiquitous) [inline .changeset/itchy-seas-care.md:5]: [suggest] Can you please change `Fix` to `Fixed:` (the common prefix in `CHANGELOG.md`)?

```suggestion
Fixed: `function-no-unknown` false positives for `scroll`, `-webkit-gradient`, `color-stop`, `from`, and `to`
```

https://github.com/stylelint/stylelint/blob/e30ec863f8bc1d5ed87c23e3c5a554a01bc4350b/CHANGELOG.md?plain=1#L7

Comment (Mouvedia) [reply .changeset/itchy-seas-care.md:5]: Will do. I just thought you wanted that when you said "I've updated the PR title for a changeset.".

Comment (ybiquitous) [reply .changeset/itchy-seas-care.md]: Oh, sorry. 🙇🏼

**Review by ybiquitous — APPROVED** [review]

**Comment by ybiquitous** [comment]
Thank you!
