### PR TITLE
Fix `function-calc-no-unspaced-operator` false negatives for some math functions

### LINKED ISSUE #7618: `function-calc-no-unspaced-operator` should support newer calc functions
### What is the problem you're trying to solve?

> [fix the false negatives for `round` and other calc-sum functions by broadening the meaning of calc to calc-sum](https://github.com/stylelint/stylelint/issues/5695#issuecomment-1079960257)

> [It doesn't validate any of the newer math functions.](https://github.com/stylelint/stylelint/issues/7181#issuecomment-1713643664)

compare https://www.w3.org/TR/css-values-4/#calc-syntax and https://www.w3.org/TR/css-values-3/#calc-syntax

### What solution would you like to see?

I already have it working on a local branch for a subset of these.

- [x] `abs`
- [x] `acos`
- [x] `asin`
- [x] `atan`
- [x] `calc`
- [x] `cos`
- [x] `exp`
- [x] `sign`
- [x] `sin`
- [x] `sqrt`
- [x] `tan`
- [x] `min`
- [x] `max`
- [x] `hypot`
- [x] `clamp`
- [x] `round`
- [x] `mod`
- [x] `rem`
- [x] `atan2`
- [x] `pow`
- [x] `log`

### PR DESCRIPTION
**Pull request by Mouvedia**
> Which issue, if any, is this issue related to?

Closes #7618

> Is there anything in the PR that needs further explanation?

A follow-up PR will be necessary to support these: `min`, `max`, `hypot`, `clamp`, `round`, `mod`, `rem`, `atan2`, `pow`, `log`.

> [As it's fixing false negatives, it'd be a minor release, in line with our semantic-versioning policy.](https://github.com/stylelint/stylelint/issues/5695#issuecomment-1079960257)

### CODE REVIEW

File: lib/rules/function-calc-no-unspaced-operator/index.mjs [hunk 1]
```diff
@@ -142,7 +152,7 @@ const rule = (primary, _secondaryOptions, context) => {
 						return true;
 					}
 
-					if (currentNode.type === 'function') {
+					if (isFunction(currentNode)) {
```
Comment (Mouvedia) [inline lib/rules/function-calc-no-unspaced-operator/index.mjs:155]: I don't know why Codecov is complaining.
The util does the exact same thing.

**Review by ybiquitous — CHANGES_REQUESTED** [review]
Thanks for the pull request. Can you check my comments?

File: lib/rules/function-calc-no-unspaced-operator/index.mjs (hunk 1 above)
Comment (ybiquitous) [reply lib/rules/function-calc-no-unspaced-operator/index.mjs:155]: I'm fixing Codecov upload error with #7622.

Comment (ybiquitous) [reply lib/rules/function-calc-no-unspaced-operator/index.mjs:155]: The Codecov problem is resolved. Can you merge `main` into this PR branch?

File: .changeset/funny-jobs-work.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"stylelint": minor
+---
+
+Added: support for `sin`, `cos`, `tan`, `exp`, `abs`, `sign`, `asin`, `acos`, `atan`, `sqrt` to `function-calc-no-unspaced-operator`
```
[the remark this answers is not in the document]
Comment (Mouvedia) [reply .changeset/funny-jobs-work.md:5]:
```suggestion
Fixed: `function-calc-no-unspaced-operator` false negatives for some math functions
```

File: lib/rules/function-calc-no-unspaced-operator/index.mjs (hunk 1 above)
Comment (Mouvedia) [reply lib/rules/function-calc-no-unspaced-operator/index.mjs:155]: > Maybe we can refactor this file.

Not in this PR.

> The Codecov problem is resolved.

Thanks.

Comment (Mouvedia) [reply lib/rules/function-calc-no-unspaced-operator/index.mjs:150]: > Maybe we can refactor this file.

Not in this PR.

> The Codecov problem is resolved.

Are you sure? Should I simply revert and move on instead?

Comment (ybiquitous) [reply lib/rules/function-calc-no-unspaced-operator/index.mjs:150]: > Are you sure? Should I simply revert and move on instead?

Sorry, I meant the upload problem. This file's uncovered problem has already occurred on the `main` branch. See:

https://app.codecov.io/gh/stylelint/stylelint/blob/main/lib%2Frules%2Ffunction-calc-no-unspaced-operator%2Findex.mjs

In this PR, we can just ignore it. And, in another PR, we can refactor this file and improve the coverage.

Comment (ybiquitous) [reply lib/rules/function-calc-no-unspaced-operator/index.mjs:150]: It would be greatly appreciated if you could work on the refactoring in another PR.

**Review by ybiquitous — APPROVED** [review]
Thank you. LGTM 👍🏼

**Comment by ybiquitous** [comment]
Feel free to merge approved PRs 👍🏼
