### PR TITLE
Fix `declaration-block-no-redundant-longhand-properties` autofix for `border-width` shorthand

### LINKED ISSUE #6947: Fix `declaration-block-no-redundant-longhand-properties` autofix for `border-width` shorthand
### What steps are needed to reproduce the bug?

This syntax will raise the warning `Expected shorthand property "border-width" (declaration-block-no-redundant-longhand-properties)Stylelint[declaration-block-no-redundant-longhand-properties](https://stylelint.io/user-guide/rules/declaration-block-no-redundant-longhand-properties)`.

```CSS
div {
    border-top-width: 0px;
    border-right-width: 1px;
    border-bottom-width: 2px;
    border-left-width: 3px;
}
```

It will be fixed to the following code. (The order of the original items is not relevant.)

```CSS
div {
    border-width: 0 2px 3px 1px;
}
```

If two values should be combined, this leads to the same error:

```CSS
div {
    border-top-width: 0px;
    border-right-width: 1px;
    border-bottom-width: 2px;
    border-left-width: 1px;
}
```

becomes:

```CSS
div {
    border-width: 0 2px 1px 1px;
}
```

### What Stylelint configuration is needed to reproduce the bug?

{
  "extends": [
    "stylelint-config-standard"
  ]
}

### How did you run Stylelint?

Stylelint demo

### Which version of Stylelint or dependencies are you using?

[stylelint](https://stylelint.io/)@15.8.0
[stylelint-config-standard](https://www.npmjs.com/package/stylelint-config-standard)@33.0.0

### What did you expect to happen?

```CSS
div {
    border-top-width: 0px;
    border-right-width: 1px;
    border-bottom-width: 2px;
    border-left-width: 3px;
}
```

Should become:

```CSS
div {
    border-width: 0 1px 2px 3px;
}
```

If two values should be combined, this leads to the same error:

```CSS
div {
    border-top-width: 0px;
    border-right-width: 1px;
    border-bottom-width: 2px;
    border-left-width: 1px;
}
```

Should become:

```CSS
div {
    border-width: 0 1px 2px;
}
```

### What actually happened?

```CSS
div {
    border-top-width: 0px;
    border-right-width: 1px;
    border-bottom-width: 2px;
    border-left-width: 3px;
}
```

Wrongly becomes:

```CSS
div {
    border-width: 0 2px 3px 1px;
}
```

If two values should be combined, this leads to the same error:

```CSS
div {
    border-top-width: 0px;
    border-right-width: 1px;
    border-bottom-width: 2px;
    border-left-width: 1px;
}
```

Wrongly becomes:

```CSS
div {
    border-width: 0 2px 1px 1px;
}
```

### Does the bug relate to non-standard syntax?

_No response_

### Proposal to fix the bug

_No response_

### PR DESCRIPTION
**Pull request by mattxwang**
> Which issue, if any, is this issue related to?

Closes #6947.

> Is there anything in the PR that needs further explanation?

Sorry that I missed this! Happy to quickly cut a new release if we'd like.

### CODE REVIEW

File: lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js [hunk 1]
```diff
@@ -206,6 +206,12 @@ testRule({
 			description: 'autofixer should not mangle css functions with comma separated values',
 			message: messages.expected('transition'),
 		},
+		{
+			code: 'a { border-top-width: 0px; border-right-width: 1px; border-bottom-width: 2px; border-left-width: 3px; }',
+			fixed: 'a { border-width: 0px 1px 2px 3px; }',
+			description: 'explicit border-width test',
+			message: messages.expected('border-width'),
+		},
 	],
```
Comment (Mouvedia) [inline lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js:215]: Can you add an example for `margin` or `border-width` or `padding` for `top | left/right | bottom`.
If if it's not supported yet add `skip: true,`.

**Comment by Mouvedia** [comment]
Can you add a test for `border-radius` ?
It should be `top-left | top-right | bottom-right | bottom-left`.
see https://github.com/stylelint/stylelint/blob/b900c7b5b310fedfa96ca1ee79f80a84f28ea1ff/lib/reference/properties.js#L144

File: lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js (hunk 1 above)
Comment (mattxwang) [reply lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js:215]: Sorry, a bit confused -- what do you mean by `top | left/right | bottom`? Do you mean when all four are specified, or when some of the values are inferred/collapsed? The latter isn't covered by this rule.

**Review by ybiquitous — APPROVED** [review]
Thank you. LGTM! 👍🏼

File: lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js (hunk 1 above)
Comment (Mouvedia) [reply lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js:215]: > The latter isn't covered by this rule.

That's why I was proposing to add `skip: true` for now.
It could be an enhancement; it's expected by users.
cf #6947
