### PR TITLE
Fix `GlobbyOptions` TypeScript errors

### LINKED ISSUE #8991: Fix `GlobbyOptions` TypeScript errors
### What minimal example or steps are needed to reproduce the bug?

1. Create a package that depends on stylelint
2. Run TypeScript build with globby v16 in the dependency tree

### What minimal configuration is needed to reproduce the bug?

`tsconfig.json`
```json
{
  "compilerOptions": {
    "strict": true,
    "moduleResolution": "node"
  }
}
```

### How did you run Stylelint?

`npm run build:types`

### Which Stylelint-related dependencies are you using?

```json
{
  "stylelint": "17.0.0"
}
```

### What did you expect to happen?

TypeScript should compile without errors.

### What actually happened?

```
node_modules/stylelint/types/stylelint/index.d.ts(2,15): error TS2305: Module '"globby"' has no exported member 'GlobbyOptions'.
node_modules/stylelint/types/stylelint/index.d.ts(2,36): error TS1541: Type-only import of an ECMAScript module from a CommonJS module must have a 'resolution-mode' attribute.
```

### Do you have a proposal to fix the bug?

In globby v16, `GlobbyOptions` was renamed to `Options`. The fix is to update the import and handle the `cwd` type change from `string` to `string | URL`.

### PR DESCRIPTION
**Pull request by zalishchuk**
> Which issue, if any, is this issue related to?

Closes #8991

> Is there anything in the PR that needs further explanation?

In globby v16, `GlobbyOptions` was renamed to `Options` and `cwd` type was expanded from `string` to `string | URL`. This PR:

1. Updates the type import to use `Options as GlobbyOptions`
2. Adds a `toPath` utility to convert URL to string when needed
3. Applies conversion in `standalone.mjs` and `printConfig.mjs` where `cwd` is passed to Node.js path functions

### CODE REVIEW

**Comment by zalishchuk** [comment]
Note: This issue wasn't caught by `lint:types` because `skipLibCheck: true` was enabled in #8875 for performance reasons.

While `skipLibCheck` speeds up type checking by skipping `.d.ts` validation, it can hide type errors that downstream consumers will encounter when they have stricter TypeScript configurations.

It may be worth considering disabling `skipLibCheck` in CI to catch these issues early, while keeping it enabled locally for faster development feedback.

**Comment by jeddy3** [comment]
@zalishchuk Thank you for the pull request and for the clear breakdown of the issue.

The changes look good.

A new test is currently failing on Windows due to a platform difference in `pathToFileURL`, though.

```console
FAIL lib/utils/__tests__/toPath.test.mjs
  ● toPath › converts URL to string path

    expect(received).toBe(expected) // Object.is equality

    Expected: "/foo/bar"
    Received: "D:\\foo\\bar"
```

Is this something you can look into, please?

> It may be worth considering disabling `skipLibCheck` in CI to catch these issues early

I've opened an issue for this: https://github.com/stylelint/stylelint/issues/8993

**Comment by zalishchuk** [comment]
@jeddy3 Windows tests should be fine now

**Comment by zalishchuk** [comment]
@jeddy3 Should we address any issues with Codecov?

File: lib/printConfig.mjs [hunk 1]
```diff
@@ -34,7 +35,7 @@ export default async function printConfig({
 
 	return (
 		(await resolveConfig(filePath, {
-			cwd: (globbyOptions && globbyOptions.cwd) || cwd,
+			cwd: toPath(globbyOptions && globbyOptions.cwd) || cwd,
```
Comment (ybiquitous) [inline lib/printConfig.mjs]:
```suggestion
			cwd: toPath(globbyOptions?.cwd) || cwd,
```

File: lib/standalone.mjs [hunk 2]
```diff
@@ -181,7 +182,7 @@ export default async function standalone({
 	}
 
 	let fileList = [files].flat().map((entry) => {
-		const globCWD = (globbyOptions && globbyOptions.cwd) || cwd;
+		const globCWD = toPath(globbyOptions && globbyOptions.cwd) || cwd;
```
Comment (ybiquitous) [inline lib/standalone.mjs]:
```suggestion
		const globCWD = toPath(globbyOptions?.cwd) || cwd;
```

Comment (zalishchuk) [reply lib/standalone.mjs]: Done in https://github.com/stylelint/stylelint/pull/8992/commits/11d45041388d3bbc4593ac3e76c3c140cfc1c216

File: lib/utils/__tests__/toPath.test.mjs [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+
+import toPath from '../toPath.mjs';
+
+describe('toPath', () => {
+	test('returns string as-is', () => {
+		expect(toPath('/foo/bar')).toBe('/foo/bar');
+	});
+
+	test('converts URL to string path', () => {
+		const url = pathToFileURL(process.cwd());
```
Comment (ybiquitous) [inline lib/utils/__tests__/toPath.test.mjs]: [suggestion] Optional. Using `import.meta.url` could simplify the test code a bit: no need for `process` or related modules.

```suggestion
		const url = new URL(import.meta.url);
```

Comment (zalishchuk) [reply lib/utils/__tests__/toPath.test.mjs]: Done in https://github.com/stylelint/stylelint/pull/8992/commits/3b4b2dc1a79033a603e1ffa585ea20df86c96b22
