### PR TITLE
Fix false positives for `:is()` and `:where()` in `*-specificity` (again)

### LINKED ISSUE #5065: Fix false positives for :is() and :where() in *-specificity
I noticed a false positive error coming from a pending release of normalize that uses `:where()`.

Here is a sample of the CSS being flagged.

```css
/**
 * Remove the margin on nested lists in Chrome, Edge, and Safari.
 */

:where(dl :is(dl, ol, ul), :is(ol, ul) dl) {
  margin-block-end: 0;
  margin-block-start: 0;
}

/**
 * 1. Add the correct box sizing in Firefox.
 * 2. Correct the inheritance of border color in Firefox.
 */

:where(hr) {
  box-sizing: content-box; /* 1 */
  color: inherit; /* 2 */
  height: 0; /* 1 */
}

/**
 * 1. Correct the inheritance and scaling of font size in all browsers.
 * 2. Correct the odd `em` font sizing in all browsers.
 */

:where(pre) {
  font-family: monospace, monospace; /* 1 */
  font-size: 1em; /* 2 */
}
```

And here are the errors reported from that sample:

```
✖  Expected selector ":where(hr)" to come     no-descending-specificity
   before selector ":where(dl :is(dl, ol,
   ul), :is(ol, ul) dl)"
✖  Expected selector ":where(pre)" to come    no-descending-specificity
   before selector ":where(dl :is(dl, ol,
   ul), :is(ol, ul) dl)"
✖  Expected selector ":where(b, strong)" to   no-descending-specificity
   come before selector ":where(dl :is(dl,
   ol, ul), :is(ol, ul) dl)"
```

The `:where()` CSS pseudo-class function takes a selector list as its argument, and selects any element that can be selected by one of the selectors in that list.

This is useful for writing large selectors in a more compact form, and also for writing selectors with 0 specificity.

> Which rule, if any, is the bug related to?

```
:where()
```

> What code is needed to reproduce the bug?

☝️See the top comment.

> What stylelint configuration is needed to reproduce the bug?

e.g.

```json
{
  "extends": "stylelint-config-standard"
}
```

> Which version of stylelint are you using?

e.g. `13.8.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

```
stylelint evergreen.css
```

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No, `:switch()` ships Firefox 78, Safari 14, & Chrome 88 📌.

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors did you get)?

☝️See the top comment.

> Additional notes:

📌 _Chrome is v87 at the time of this writing. Firefox shipped v78 in June, and Safari shipped v14 in September_

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

Closes #5065
Closes #6083
Ref <https://github.com/stylelint/stylelint/issues/5065#issuecomment-1145403964>

> Is there anything in the PR that needs further explanation?

This PR aims to fix false positives in the rules below about selector specificity:

- [`no-descending-specificity`](https://stylelint.io/user-guide/rules/list/no-descending-specificity)
- [`selector-max-specificity`](https://stylelint.io/user-guide/rules/list/selector-max-specificity)

Also, this PR uses the [`@csstools/selector-specificity`](https://www.npmjs.com/package/@csstools/selector-specificity) package, instead of the [`specificity`](https://www.npmjs.com/package/specificity) package. (`specificity` is uninstalled)

### CODE REVIEW

**Comment by ybiquitous** [comment]
Hi @romainmenke, I'm trying your package now and have two questions:

- In CJS, the package raises a type error `TS2349: This expression is not callable`. Is it possible to fix the error?
  (see the line 100 in `lib/rules/no-descending-specificity/index.js`)
- Do you have a plan to provide a compare function like [the `specificity` package has](https://www.npmjs.com/package/specificity#comparing-two-selectors)?
  (see the line 160 in `lib/rules/no-descending-specificity/index.js`)

**Comment by ybiquitous** [comment]
Thanks for the quick response.

The interop between CJS and ESM is a difficult problem. I believe it will not be a big problem in this project. 😅 

> Not at this time but PR's are welcome.
> Our focus was on implementing and sharing the hard parts with as little bloat as possible.

Yeah, I try it. 💪🏼

**Comment by ybiquitous** [comment]
@romainmenke I've opened PR https://github.com/csstools/postcss-plugins/pull/426

**Comment by romainmenke** [comment]
@ybiquitous We have released an updated version of the package.

**Comment by ybiquitous** [comment]
@romainmenke Thank you for letting me know. The new version has resolved the concerns 👍🏼

**Comment by jeddy3** [comment]
The [@csstools/selector-specificity](https://www.npmjs.com/package/@csstools/selector-specificity) package is a good fit.

Am I right in thinking that the capabilities of the package makes a large part of this code redundant? 

https://github.com/stylelint/stylelint/blob/8258c07ec6e0575adeb03b2abcb9732d3c304eb6/lib/rules/selector-max-specificity/index.js#L77-L177

If so, shall we remove it in this pull request?

**Comment by ybiquitous** [comment]
> Am I right in thinking that the capabilities of the package makes a large part of this code redundant?

Maybe, I think most parts of the code are necessary still. But I'll reduce the code as much as possible in this pull request. 💪🏼

File: lib/rules/selector-max-specificity/index.js [hunk 1]
```diff
@@ -77,49 +79,52 @@ const rule = (primary, secondaryOptions) => {
...
+				return zeroSpecificity();
+			}
+
+			let ownSpecificity;
+
+			if (optionsMatches(secondaryOptions, 'ignoreSelectors', ownValue)) {
+				ownSpecificity = zeroSpecificity();
+			} else {
+				ownSpecificity = selectorSpecificity(node.clone({ nodes: [] }));
+			}
```
Comment (ybiquitous) [inline lib/rules/selector-max-specificity/index.js:127]: [note] We need to keep the current logic parsing each selector node AST because the `ignoreSelectors` option needs to check pseudo-class arguments.

File: lib/rules/selector-max-specificity/index.js [hunk 2]
```diff
@@ -192,32 +195,23 @@ const rule = (primary, secondaryOptions) => {
...
-									message: messages.expected(resolvedSelector, primary),
-									word: selector,
-								});
-							}
-						});
-					} catch {
-						result.warn('Cannot parse selector', {
-							node: ruleNode,
-							stylelintType: 'parseError',
-						});
```
Comment (ybiquitous) [inline lib/rules/selector-max-specificity/index.js:219]: [note] Since `parseSelector()` internally uses `try ... catch`, it's unnecessary here:

https://github.com/stylelint/stylelint/blob/3633e44eb9093c392fe92d9f6a20f4772b22fe92/lib/utils/parseSelector.js#L15-L17

**Comment by ybiquitous** [comment]
This pull request is now ready to review!

**Review by jeddy3 — APPROVED** [review]
Fantastic, thank you!

LGTM. Feel free to merge.

**Comment by ybiquitous** [comment]
@romainmenke @jeddy3 Thank you for the help! 😊

**Comment by romainmenke** [comment]
@ybiquitous Thank you for doing all the work 🎉

**Comment by ybiquitous** [comment]
Changelog entry added:

> - Fixed: `no-descending-specificity` and `selector-max-specificity` false positives for `:is()` and `:where()` ([#6131](https://github.com/stylelint/stylelint/pull/6131)).
