### PR TITLE
Fixed 5 autofixes #3620

### LINKED ISSUE #3620: Fix autofix for 5 whitespace rules
> Clearly describe the bug

Autofix of the following five rules was sometimes incorrect.

- selector-list-comma-newline-before
- selector-list-comma-space-after
- selector-list-comma-space-before
- value-list-comma-space-after
- value-list-comma-space-before

> Which rule, if any, is the bug related to?

- selector-list-comma-newline-before
- selector-list-comma-space-after
- selector-list-comma-space-before
- value-list-comma-space-after
- value-list-comma-space-before

> What CSS is needed to reproduce the bug?

e.g.

- selector-list-comma-newline-before
- selector-list-comma-space-after
- selector-list-comma-space-before

```css
a,b,c,d,e,f,g {}
```

- value-list-comma-space-after
- value-list-comma-space-before

```css
a{b: 0,0,0,0,0,0,0,0; }"
```

> What stylelint configuration is needed to reproduce the bug?

enable each rule and use the `--fix` option.

> Which version of stylelint are you using?

- 9.4.0
    - selector-list-comma-space-before
- 9.5.0
    - selector-list-comma-newline-before
    - selector-list-comma-space-after
- master
    - value-list-comma-space-after 
    - value-list-comma-space-before 

> How are you running stylelint: CLI, PostCSS plugin, Node API?

jest

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

standard

> What did you expect to happen?

The autofix was supposed to be correct.

> What actually happened (e.g. what warnings or errors did you get)?

Each result is incorrect as follows.

- selector-list-comma-newline-before

```css
a
,b
,c
,d
,
e
,f,g {}
```
- selector-list-comma-space-after

```css
a, b, c, d, e , f,g {}
```

- selector-list-comma-space-before

```css
a ,b ,c ,d , e ,f,g {}
```

- value-list-comma-space-after

```css
a{b: 0, 0, 0, 0 ,0 ,0 ,0,0; }
```

- value-list-comma-space-before

```css
a{b: 0 ,0 ,0  , 0, 0, 0,0,0; }
```

### PR DESCRIPTION
**Pull request by ota-meshi**
> Which issue, if any, is this issue related to?

fixed #3620

> Is there anything in the PR that needs further explanation?

e.g. "No, it's self explanatory."

### CODE REVIEW

File: lib/rules/selector-list-comma-newline-before/index.js [hunk 1]
```diff
@@ -49,7 +49,7 @@ const rule = function(expectation, options, context) {
           ? ruleNode.raws.selector.raw
           : ruleNode.selector;
         commaIndices
-          .sort()
+          .sort((a, b) => a - b)
```
Comment (boccob) [inline lib/rules/selector-list-comma-newline-before/index.js]: Maybe `.sort((a, b) => b - a)` is a bit better than `.sort((a, b) => a - b).reverse()`

**Comment by ota-meshi** [comment]
@boccob 
I changed `sort.reverse` to one `sort`.

**Comment by jeddy3** [comment]
> -   Fixed: autofix for 5 whitespace rules ([#3621](https://github.com/stylelint/stylelint/pull/3621)).
