### PR TITLE
Fix normalizing of windows drive letter

### LINKED ISSUE #5594: Fix `ignoreFiles` being evaluated case-sensitively on Windows
Tested on Stylelint 14

`ignoreFiles` is evaluated case-sensitively on Windows, leading to a few issues downstream in vscode-stylelint. I stumbled into this while migrating from the deprecated vscode-languageserver URI API to the new vscode-uri API. The new API generates lowercase drive letters for paths instead of uppercase letters as the old API did.

Let's say the project is in `C:\Users\Adaline\Code\my-project`. Suppose that there is a file named `should-be-ignored.css` and the Stylelint config is:

```json
{ "ignoreFiles": "*-ignored.css" }
```

If you pass `C:\Users\Adaline\Code\my-project\should-be-ignored.css` to Stylelint, it ignores the file, as it should. But if you pass `c:\...\should-be-ignored.css` or any other case of any part of the path, Stylelint doesn't ignore it even though it can read the file correctly using the differently-cased path.

Node.js's API's behaviour, for reference, correctly sees these paths as equal on Windows:

```js
const path = require('path');

path.win32.relative('C:\\Path\\to\\file.css', 'c:\\path\\To\\File.css')
// Evaluates to ''
```

I haven't checked any other config properties or functionality, so I'm unaware if there are other cases of this behaviour elsewhere in the project.

### PR DESCRIPTION
**Pull request by adalinesimonian**
Fixes #5594.

- Add shared normalizeFilePath utility to align drive-letter casing.
- Apply normalization to ignoreFiles, config cache, and postcss cache.

### CODE REVIEW

File: lib/isPathIgnored.mjs [hunk 1]
```diff
@@ -29,7 +29,12 @@ export default async function isPathIgnored(stylelint, filePath) {
 	const ignoreFiles = result.config.ignoreFiles || [];
 	const absoluteFilePath = isAbsolute(filePath) ? filePath : resolve(cwd, filePath);
 
-	if (micromatch([absoluteFilePath], ignoreFiles).length > 0) {
+	const normalizedAbsolutePath = normalizeFilePath(absoluteFilePath);
+	const normalizedIgnoreFiles = ignoreFiles.map((/** @type {string} */ glob) =>
+		normalizeFilePath(String(glob)),
+	);
+
+	if (micromatch([normalizedAbsolutePath], normalizedIgnoreFiles).length > 0) {
```
Comment (Mouvedia) [inline lib/isPathIgnored.mjs:37]: micromatch accepts `string | readonly string[]` for its second parameter and the type of `ignoreFiles` is

https://github.com/stylelint/stylelint/blob/39d8be97930679b7ced40a41bb7ce44caef55f53/types/stylelint/index.d.ts#L9

hence I think that `.map` will throw for `string`.

---

If I am right, should we add a test?

File: .changeset/beige-spoons-sit.md
Comment (Mouvedia) [inline .changeset/beige-spoons-sit.md:1]: note

probably prompted by https://github.com/stylelint/vscode-stylelint/blob/06b1220a9b28efa205af146bebfc32a688c41c98/src/server/services/stylelint-runtime/stylelint-runner.service.ts#L308-L314

File: lib/isPathIgnored.mjs (hunk 1 above)
Comment (adalinesimonian) [reply lib/isPathIgnored.mjs:37]: `augmentConfig` runs `absolutizePaths`, which in turn [always converts `ignoreFiles` to an array](https://github.com/stylelint/stylelint/blob/1c1ef9aa7ff1b6e6b7e3f6ea90627c8a7fa536f3/lib/augmentConfig.mjs#L147). As a result, we don't end up needing to handle the case for if `ignoreFiles` is a string, since it will never be one by the time it reaches this code. To be extra sure, I added a [test case for the drive-letter logic directly on isPathIgnored](https://github.com/stylelint/stylelint/blob/1c1ef9aa7ff1b6e6b7e3f6ea90627c8a7fa536f3/lib/__tests__/isPathIgnored.test.mjs#L27-L44), which is [passing on Windows](https://github.com/stylelint/stylelint/actions/runs/20487346870/job/58872352791?pr=8941#step:9:262).
