### PR TITLE
Fix `function-url-quotes` false positives when URLs require quoting

### LINKED ISSUE #8544: Fix `function-url-quotes` false positives when URLs require quoting
### What minimal example or steps are needed to reproduce the bug?

```css
a {
	background-image: url('data:image/svg+xml;utf8,<svg height="100" width="100" xmlns="http://www.w3.org/2000/svg"><circle r="45" cx="50" cy="50" fill="red"/></svg>');
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "function-url-quotes": "never"
  }
}
```

### How did you run Stylelint?

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLgIyTAGsBzAJwgFdMoBaASwFskSZ4VKyAbACgHIoSHEnhMWMAPQBnAG4kA1AA9GXANyUcAMwAcAGgA8skigAWMeiRM4AvOhABGAAyO7KAO70oOE7YfPXylyYUr5WOAAO8BISbrEAdG4AzHEQZCQSAEzOjtJydgB8+mD0ZGBcMChkvgAsAKyuYIq+tS4gKGAAns2tKJr0XFy+ZDBQdhKFuST5fACUqlgAvlgguiB95QBySIxwiDCK2+HlcWBSUivgEJh9JAggGJgoKHZklOVSduwPT092mtRgHD0K60ThcWgAR0oEBwMA+CGeIEwMBkMDIdiwTyWmAWF0g1wsADFUswcHcAFZSK4XWDhc6Ib6IqQ4DrlLj0TA4T6IrhCOFclaYpkstkcnC0fE3WjMpA0JBkUYIuy82HMjE4kALIA)

### Which Stylelint-related dependencies are you using?

```json
{
  "stylelint": "latest",
  "stylelint-config-standard": "latest"
}
```

### What did you expect to happen?

No errors and no fix applied.

### What actually happened?

```
2:24-159 ERROR Unexpected quotes around "url" function argument (function-url-quotes)
```

### Do you have a proposal to fix the bug?

Some inspiration could be taken from `font-family-name-quotes`.

In instances where the `url()` content has quotes or spaces inside, it'd be best to leave it alone by default.

Alternatively or in addition, a secondary option might be adding `ignoreURL`, ignoring the contents if it matches a specific pattern.

### PR DESCRIPTION
**Pull request by taearls**
> Which issue, if any, is this issue related to?

Closes #8544.

> Is there anything in the PR that needs further explanation?

**Changes made:**
- Added test cases covering the bug (unquoted URLs with special characters that require quotes)
- Fixed the rule to not report errors when quotes are required in `url()` functions

**Scope note:** This PR focuses on fixing the false positive when quotes are required. It does not add validation for proper escaping of URL values.

### CODE REVIEW

File: lib/rules/function-url-quotes/index.mjs [hunk 1]
```diff
@@ -152,6 +152,23 @@ const rule = (primary, secondaryOptions) => {
 			}
 		}
 
+		/**
+		 * Check if a URL requires quotes for valid CSS
+		 * According to CSS spec, unquoted URLs cannot contain:
+		 * - spaces
+		 * - quotes (" or ')
+		 * - parentheses
+		 * - certain special characters
```
Comment (romainmenke) [inline lib/rules/function-url-quotes/index.mjs]: The regex below doesn't seem to check for any special characters 🤔

File: lib/rules/function-url-quotes/index.mjs [hunk 2]
```diff
@@ -152,6 +152,23 @@ const rule = (primary, secondaryOptions) => {
...
+		 *
+		 * @param {string} url - The URL content (without quotes if present)
+		 * @returns {boolean} - True if quotes are required
+		 */
+		function quotesRequired(url) {
+			// Check for characters that require quoting
+			// Spaces, quotes, parentheses, and other special characters
+			return /[\s"'()]/.test(url);
+		}
```
Comment (romainmenke) [inline lib/rules/function-url-quotes/index.mjs]: Another approach could be to check if tokenizing a url without quotes results in a `Bad URL` token. This way we use existing validation in the tokenizer.

```ts
		function quotesRequired(url) {
			const [urlToken] = tokenize({ css: `url(${url})` });

			if (!urlToken) true;

			if (isTokenBadURL(urlToken)) return true;

			return false;
		}
```

We can then accurately detect when a quoted url already has proper escaping and could be unquoted, even when certain characters are present:

```ts
		{
			code: `a { background-image: url( "data:image/svg+xml,<svg\\ viewBox=\\"0\\ 0\\ 10\\ 10\\"></svg>" ); }`,
			fixed: 'a { background-image: url( data:image/svg+xml,<svg\\ viewBox=\\"0\\ 0\\ 10\\ 10\\"></svg> ); }',
			fix: {
				range: [27, 85],
				text: 'data:image/svg+xml,<svg\\ viewBox=\\"0\\ 0\\ 10\\ 10\\"></svg>',
			},
			message: messages.rejected('url'),
			line: 1,
			column: 28,
			endLine: 1,
			endColumn: 87,
		},
```

File: lib/rules/function-url-quotes/index.mjs [hunk 3]
```diff
@@ -170,6 +187,27 @@ const rule = (primary, secondaryOptions) => {
...
+				const quote = leftTrimmedArgs[0];
+
+				if (quote) {
+					const endQuoteIndex = leftTrimmedArgs.lastIndexOf(quote);
+
+					if (endQuoteIndex > 0) {
+						urlContent = leftTrimmedArgs.slice(1, endQuoteIndex);
+					}
+				}
+			}
```
Comment (romainmenke) [inline lib/rules/function-url-quotes/index.mjs]: [suggestion] Should this be part of the `quotesRequired` function?

File: lib/rules/function-url-quotes/index.mjs [hunk 4]
```diff
@@ -152,6 +152,23 @@ const rule = (primary, secondaryOptions) => {
...
+		 * According to CSS spec, unquoted URLs cannot contain:
+		 * - spaces
+		 * - quotes (" or ')
+		 * - parentheses
+		 * - certain special characters
+		 *
+		 * @param {string} url - The URL content (without quotes if present)
+		 * @returns {boolean} - True if quotes are required
+		 */
+		function quotesRequired(url) {
```
Comment (romainmenke) [inline lib/rules/function-url-quotes/index.mjs]: `requiresQuotes` is maybe more in line with the naming conventions

File: lib/rules/function-url-quotes/index.mjs (hunk 1 above)
Comment (taearls) [reply lib/rules/function-url-quotes/index.mjs]: ah good catch I meant to add that in. I'll take a look and add some more tests

File: lib/rules/function-url-quotes/index.mjs (hunk 4 above)
Comment (taearls) [reply lib/rules/function-url-quotes/index.mjs]: done

File: lib/rules/function-url-quotes/index.mjs (hunk 2 above)
Comment (taearls) [reply lib/rules/function-url-quotes/index.mjs]: This makes a lot of sense. I implemented your suggestion.

File: lib/rules/function-url-quotes/index.mjs (hunk 3 above)
Comment (taearls) [reply lib/rules/function-url-quotes/index.mjs]: yeah good call. done

File: lib/rules/function-url-quotes/index.mjs (hunk 1 above)
Comment (taearls) [reply lib/rules/function-url-quotes/index.mjs]: I implemented your suggestion below and updated the jsdoc comment for this function to describe the new behavior. I added some additional testing as well. the only test case I have _not_ added is for this source code from your [comment](https://github.com/stylelint/stylelint/issues/8544#issuecomment-2825394948) regarding automatically escaping:

```css
body {
	background-image: url( data:image/svg+xml,<svg\ viewBox=\"0\ 0\ 10\ 10\"></svg> );
}
```

If you'd like, I can try taking a stab at implementing this, though I might need some guidance or time to figure out a reasonable way to do it. Let me know what you think!

Comment (romainmenke) [reply lib/rules/function-url-quotes/index.mjs]: Thank you for wanting to work on this, but maybe better if we defer this for now.

Automatic escaping isn't well defined in the CSS specification.
The specification requires adding quotes, where no escaping is required.
The unquoted url format is also a legacy notation and not a current best practice.

File: lib/rules/function-url-quotes/index.mjs [hunk 5]
```diff
@@ -152,6 +153,48 @@ const rule = (primary, secondaryOptions) => {
...
+		 *
+		 * This function determines if a URL needs to be quoted when used in a CSS url() function.
+		 * It tokenizes the URL and checks if it would be parsed as a bad-url token, which indicates
+		 * that quotes are necessary for valid CSS.
+		 *
+		 * According to CSS spec, unquoted URLs cannot contain:
+		 * - spaces
+		 * - quotes (" or ')
+		 * - parentheses (unescaped)
+		 * - certain special characters (like \, newlines)
```
Comment (romainmenke) [inline lib/rules/function-url-quotes/index.mjs]:
```suggestion
```

I would omit this list.
The specification itself is the best source of information.
This list, as it exists now, isn't very accurate and might cause confusion.

File: lib/rules/function-url-quotes/index.mjs [hunk 6]
```diff
@@ -152,6 +153,48 @@ const rule = (primary, secondaryOptions) => {
...
+				}
+			}
+
+			const [urlToken] = tokenize({ css: `url(${urlContent})` });
+
+			if (!urlToken) return true;
+
+			if (isTokenBadURL(urlToken)) return true;
+
+			return false;
```
Comment (romainmenke) [inline lib/rules/function-url-quotes/index.mjs]: There are two cases I didn't consider when making the previous suggestion:

## Urls with closing parenthesis:

```
url("foo)bogus")
```

When removing the quotes this becomes:

```
url(foo)bogus)
```

Where `url(foo)` would not be bad url token

## Urls with quotes:

```
url("'foo'")
```

When removing the quotes this becomes:

```
url('foo')
```

Where `url('foo')` would not be bad url token but instead a function token

------

So maybe better to do this instead:

```
			const tokens = tokenize({ css: `url(${urlContent})` });

			if (tokens.length !== 1) return true;

			if (!isTokenURL(urlToken)) return true;
```

Then we check that there is only one token and that it is a url token.

File: lib/rules/function-url-quotes/index.mjs [hunk 7]
```diff
@@ -170,6 +213,12 @@ const rule = (primary, secondaryOptions) => {
 
 			const hasQuotes = leftTrimmedArgs.startsWith("'") || leftTrimmedArgs.startsWith('"');
 
+			// Check if quotes are required for valid CSS
+			const required = requiresQuotes(leftTrimmedArgs, hasQuotes);
+
+			// If quotes are required, don't complain about them being present
+			if (required && hasQuotes) return;
```
Comment (romainmenke) [inline lib/rules/function-url-quotes/index.mjs]:
```suggestion
			if (hasQuotes && requiresQuotes(leftTrimmedArgs)) return;
```

And drop the `hasQuotes` argument:

```js
		function requiresQuotes(url) {
			let urlContent = url;

			const quote = url[0];
			const endQuoteIndex = url.lastIndexOf(quote);

			if (endQuoteIndex > 0) {
				urlContent = url.slice(1, endQuoteIndex);
			}

// ...
```

**Review by romainmenke — COMMENTED** [review]
Thank you for applying the feedback @taearls 🙇 
I've left a few more suggestions to cover more cases and simplify the code.

File: lib/rules/function-url-quotes/index.mjs (hunk 6 above)
Comment (taearls) [reply lib/rules/function-url-quotes/index.mjs]: @romainmenke  I looked into this. I added those two scenarios as test cases. 

however, doing a length check of 1 on the tokens returned from `tokenize()` was causing almost all the tests for `function-url-quotes` to fail. from what I can tell, the tokens length is never 1 because there's always an EOF token that is returned. 

that being said, I changed it to `if (tokens.length !== 2) return true;` and left a comment explaining the EOF token being included since it is not intuitive.

all the tests, including the new ones, are passing. I think this should cover the scenarios you were thinking of but let me know what you think!

Comment (romainmenke) [reply lib/rules/function-url-quotes/index.mjs]: Thank you @taearls 🙇 
Sorry for the wait between feedback

Comment (taearls) [reply lib/rules/function-url-quotes/index.mjs]: No worries at all! I appreciate your feedback on this

**Review by jeddy3 — APPROVED** [review]
LGTM, thank you!
