### PR TITLE
Fix `declaration-property-value-no-unknown` false negatives for `text-wrap` and `text-wrap-mode`

### LINKED ISSUE #7952: Fix `declaration-property-value-no-unknown` false negatives for `text-wrap` and `text-wrap-mode`
### What minimal example or steps are needed to reproduce the bug?

```
a {
  text-wrap: foo;
  text-wrap-mode: foo;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": { "declaration-property-value-no-unknown": true }
}
```

### Resources

https://csstree.github.io/docs/validator.html
https://caniuse.com/mdn-css_properties_text-wrap
https://caniuse.com/mdn-css_properties_text-wrap-mode

### PR DESCRIPTION
**Pull request by sidverma32**
> Which issue, if any, is this issue related to?

Closes #7952 

> Is there anything in the PR that needs further explanation?

Details are mentioned in Issue link.

Resources:
https://csstree.github.io/docs/validator.html
https://caniuse.com/mdn-css_properties_text-wrap
https://caniuse.com/mdn-css_properties_text-wrap-mode

### CODE REVIEW

File: lib/rules/declaration-property-value-no-unknown/index.mjs [hunk 1]
```diff
@@ -71,6 +71,8 @@ const rule = (primary, secondaryOptions) => {
 			'text-spacing-trim': 'normal | space-all | space-first | trim-start',
 			'text-wrap-style': 'auto | balance | pretty | stable',
 			'word-break': '| auto-phrase',
+			'text-wrap': 'wrap | nowrap | balance | pretty | stable',
+			'text-wrap-mode': 'wrap | nowrap',
```
Comment (Mouvedia) [inline lib/rules/declaration-property-value-no-unknown/index.mjs:75]:
```suggestion
			'text-wrap-mode': 'wrap | nowrap',
			'text-wrap': "<'text-wrap-mode'> || <'text-wrap-style'>",
```

**Review by Mouvedia — CHANGES_REQUESTED** [review]

File: lib/rules/declaration-property-value-no-unknown/index.cjs [hunk 2]
```diff
@@ -74,6 +74,8 @@ const rule = (primary, secondaryOptions) => {
 			'text-spacing-trim': 'normal | space-all | space-first | trim-start',
 			'text-wrap-style': 'auto | balance | pretty | stable',
```
Comment (Mouvedia) [inline lib/rules/declaration-property-value-no-unknown/index.cjs:75]: nit

Maybe put them in this order

1. text-wrap-mode
2. text-wrap-style
3. text-wrap

so that they are grouped.

If `text-wrap` uses previous definitions I suppose it should come after them.

**Comment by Mouvedia** [comment]
Could you add a changeset?

i.e.
```console
npx changeset
```

**Comment by Mouvedia** [comment]
@sidverma32 thanks for the PR.
Could you add a changeset?

i.e.
```console
npx changeset
```

File: lib/rules/declaration-property-value-no-unknown/index.mjs (hunk 1 above)
Comment (sidverma32) [reply lib/rules/declaration-property-value-no-unknown/index.mjs:75]: Just confirming:
	`'text-wrap': "<'text-wrap-mode'> || <'text-wrap-style'>",`

wrapping under this `<>` will be recognised while parsing the `propertiesSyntax`?

File: lib/rules/declaration-property-value-no-unknown/index.cjs (hunk 2 above)
Comment (sidverma32) [reply lib/rules/declaration-property-value-no-unknown/index.cjs:75]: yes, make sense! will update

File: lib/rules/declaration-property-value-no-unknown/index.mjs (hunk 1 above)
Comment (Mouvedia) [reply lib/rules/declaration-property-value-no-unknown/index.mjs:75]: You can try to add a test if you don't believe me :)

**Review by Mouvedia — APPROVED** [review]
LGTM

File: .changeset/khaki-singers-drive.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"stylelint": patch
```
Comment (romainmenke) [inline .changeset/khaki-singers-drive.md:2]:
```suggestion
"stylelint": minor
```

See: https://github.com/stylelint/stylelint/blob/main/docs/about/semantic-versioning.md#minor-release

> Minor release
> 
> Might break your lint build:
> 
> a bug fix in a rule that results in Stylelint reporting more errors

**Comment by romainmenke** [comment]
Also see: https://github.com/stylelint/stylelint/pull/7957#pullrequestreview-2258877156

**Comment by Mouvedia** [comment]
@sidverma32 thanks.

We will update the CHANGELOG before the next release to add a list and merge the 3 PRs into one changeset.
