### PR TITLE
Fix `shorthand-property-no-redundant-values` false negatives for additional radius

### LINKED ISSUE #8248: Fix deprecation warnings to only display once per (custom) rule
### What minimal example or steps are needed to reproduce the bug?

Run Stylelint on multiple files using a (custom) rule that triggers deprecation warnings.

Ref: https://github.com/stylelint/stylelint/pull/8244#issuecomment-2564728166

### What minimal configuration is needed to reproduce the bug?

```js
/** @type {import('stylelint').Config} */
export default {
  plugins: ["stylelint-declaration-strict-value"],
  rules: {
    "scale-unlimited/declaration-strict-value": "color",
  },
};
```

### How did you run Stylelint?

```shell
npx stylelint "code/*.css"   
```

### Which Stylelint-related dependencies are you using?

```
"stylelint": "latest",
"stylelint-declaration-strict-value": "latest"
```

### What did you expect to happen?

One deprecation warning per rule is displayed.

### What actually happened?

A warning for each file checked is displayed.

```console
npx stylelint "code/*.css"   
(node:48662) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "scale-unlimited/declaration-strict-value" instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:48662) [stylelint:005] DeprecationWarning: `context.fix` is being deprecated.
Please pass a `fix` callback to the `report` utility of "scale-unlimited/declaration-strict-value" instead.
```

### Do you have a proposal to fix the bug?

Display one warning and, if possible, clean it up to:

> [stylelint:005] DeprecationWarning: `context.fix` is being deprecated. Please pass a `fix` callback to the `report` utility of "scale-unlimited/declaration-strict-value" instead.

### LINKED ISSUE #8428: Fix `shorthand-property-no-redundant-values` false negatives for additional radius
### What minimal example or steps are needed to reproduce the bug?

```css
a {
  border-radius: 1px 1px 1px 1px / 2px 2px 2px 2px;
}
```

I encountered this while looking into https://github.com/stylelint/stylelint/issues/8412. I couldn't find it coming up before, I guess because additional radii are rarely used.

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
     "shorthand-property-no-redundant-values": true
   }
}
```

### How did you run Stylelint?

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLgIwgCdZCBaQpKASwFcBneFARgAcAPZ9zj1jgehQAmLsI6ih7ANxYAvlhAAaEADMqAGxgA5JAFs4iGG10sNAOjB06i8BEyqA5ghAZMKFOhCGcMTFDofGAG0sNzcPOhwATw01KkwcUkg7KntSCKRfJGIPEJQAXVlrJIcAMSIdJBwnACs6W2tYFitEFzCQCOiYWPiA9xA1SpgIjwVc8KiYuITilLScDKgsqF6PAe9hkEKZIA).

### Which Stylelint-related dependencies are you using?

```json
{
  "stylelint": "latest",
  "stylelint-config-standard": "latest"
}
```

### What did you expect to happen?

Both sets of redundant values in the radii to be reported.

### What actually happened?

No problems reported.

### Do you have a proposal to fix the bug?

Account for additional radius.

### PR DESCRIPTION
**Pull request by ryo-manba**
> Which issue, if any, is this issue related to?

Closes #8428 

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

### CODE REVIEW

File: lib/rules/shorthand-property-no-redundant-values/index.mjs [hunk 1]
```diff
@@ -112,6 +112,47 @@ function canCondenseToThreeValues(_top, right, _bottom, left) {
...
+				continue;
+			}
+
+			// Any other divider means we cannot safely lint
+			return { horizontal: [], vertical: [], sawSlash: false };
+		}
+
+		if (isVarFunction(node)) return { horizontal: [], vertical: [], sawSlash: false };
+
+		if (isValueWord(node) || isValueFunction(node)) {
```
Comment (ybiquitous) [inline lib/rules/shorthand-property-no-redundant-values/index.mjs:142]: [question] Just to confirm, is it possible to improve the test coverage around this line?

File: lib/rules/shorthand-property-no-redundant-values/index.mjs [hunk 2]
```diff
@@ -134,6 +175,57 @@ const rule = (primary) => {
 
 			if (!isSupportedShorthand(normalizedProp)) return;
 
+			// Special handling for `border-radius` when a slash is present
+			if (normalizedProp === 'border-radius') {
+				const { horizontal, vertical, sawSlash } = splitBorderRadius(value);
+
+				if (sawSlash) {
```
Comment (ybiquitous) [inline lib/rules/shorthand-property-no-redundant-values/index.mjs:182]: [suggestion] To make the main rule function more readable, how about extracting a function like `splitBorderRadius`? E.g.

```js
if (sawSlash) {
	processBorderRadiusValue(result, decl, horizontal, vertical);
	return;
}
```

**Review by ybiquitous — COMMENTED** [review]
@ryo-manba Thank you for the pull request. Overall LGTM, but can you take a look at my reviews?

File: lib/rules/shorthand-property-no-redundant-values/index.mjs (hunk 2 above)
Comment (ryo-manba) [reply lib/rules/shorthand-property-no-redundant-values/index.mjs:270]: Thank you, I've fixed it.
https://github.com/stylelint/stylelint/pull/8539/commits/c9b5ec8162ccbb08fad9f392684a9ce1ee227b6

**Review by ybiquitous — APPROVED** [review]
Oops. Miss click 😅
