### PR TITLE
fix: ignore non-standard selectors for rule no-duplicate-selectors

### LINKED ISSUE #6103: `no-duplicate-selectors` throws `postcss-selector-parser` error with SCSS nested property
### What steps are needed to reproduce the bug?

```scss
font: {
  size: 10px;
  weight: 400;
}
```

https://github.com/1stG/configs/tree/stylelint_scss

Branch `stylelint_scss`

`yarn && yarn lint:style`

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "extends": [
    "@1stg/stylelint-config",
    "@1stg/stylelint-config/modules"
  ]
}
```

### How did you run Stylelint?

stylelint . --cache

### Which version of Stylelint are you using?

14.8.3

### What did you expect to happen?

No error

### What actually happened?

```log
Error: Expected a pseudo-class or pseudo-element.
    at /Users/JounQin/Workspaces/GitHub/configs/tests/test.scss:6:3
    at Root._error (/Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss-selector-parser/dist/parser.js:174:16)
    at Root.error (/Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss-selector-parser/dist/selectors/root.js:43:19)
    at Parser.error (/Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss-selector-parser/dist/parser.js:740:21)
    at Parser.expected (/Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss-selector-parser/dist/parser.js:1133:19)
    at Parser.pseudo (/Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss-selector-parser/dist/parser.js:875:19)
    at Parser.parse (/Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss-selector-parser/dist/parser.js:1084:14)
    at Parser.loop (/Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss-selector-parser/dist/parser.js:1043:12)
    at new Parser (/Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss-selector-parser/dist/parser.js:164:10)
    at Processor._root (/Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss-selector-parser/dist/processor.js:53:18)
    at Processor._runSync (/Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss-selector-parser/dist/processor.js:100:21)
    at Processor.processSync (/Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss-selector-parser/dist/processor.js:197:23)
    at normalize (/Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint/lib/rules/no-duplicate-selectors/index.js:164:26)
    at /Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint/lib/rules/no-duplicate-selectors/index.js:68:74
    at Array.map (<anonymous>)
    at /Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint/lib/rules/no-duplicate-selectors/index.js:68:56
    at /Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss/lib/container.js:96:18
    at /Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss/lib/container.js:55:18
    at Rule.each (/Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss/lib/container.js:41:16)
    at Rule.walk (/Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss/lib/container.js:52:17)
    at /Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss/lib/container.js:60:24
    at Root.each (/Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss/lib/container.js:41:16)
    at Root.walk (/Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss/lib/container.js:52:17)
    at Root.walkRules (/Users/JounQin/Workspaces/GitHub/configs/node_modules/postcss/lib/container.js:94:19)
    at /Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint/lib/rules/no-duplicate-selectors/index.js:54:8
    at /Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint/lib/lintPostcssResult.js:113:8
    at Array.map (<anonymous>)
    at lintPostcssResult (/Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint/lib/lintPostcssResult.js:104:18)
    at lintSource (/Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint/lib/lintSource.js:91:8)
    at async /Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint/lib/standalone.js:228:27
    at async Promise.all (index 12)
    at async standalone (/Users/JounQin/Workspaces/GitHub/configs/node_modules/stylelint/lib/standalone.js:267:22)
```

### Does the bug relate to non-standard syntax?

Yes, but I've already used `customSyntax: 'postcss-scss'`, and it does not throw on `14.8.2`

### Proposal to fix the bug

image

It could be related to `normalize-selector` been removed.

### PR DESCRIPTION
**Pull request by JounQin**
> Which issue, if any, is this issue related to?

Closes #6103

> Is there anything in the PR that needs further explanation?

<del>

I'm getting the following error, so I have to add `skip: true` like the other test case for `postcss-css-in-js` above in the same test file:

```log
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'nodes' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    --- property 'parent' closes the circle
    at stringify (<anonymous>)
    at writeChannelMessage (node:internal/child_process/serialization:127:20)
    at process.target._send (node:internal/child_process:839:17)
    at process.target.send (node:internal/child_process:739:19)
    at reportSuccess (/Users/JounQin/Workspaces/GitHub/stylelint/node_modules/jest-worker/build/workers/processChild.js:59:11)
```

</del>

### CODE REVIEW

**Review by ybiquitous — CHANGES_REQUESTED** [review]
@JounQin Thanks for creating the pull request!

It's needed to call `isStandardSyntaxSelector()` before calling `normalize()` also here: 👇🏼 

https://github.com/stylelint/stylelint/blob/a2c93ff6e78f0c5071cef81eb5db8271bcd12162/lib/rules/no-duplicate-selectors/index.js#L131

File: lib/rules/no-duplicate-selectors/index.js [hunk 1]
```diff
@@ -62,7 +63,11 @@ const rule = (primary, secondaryOptions) => {
 			);
 			const resolvedSelectorList = [
 				...new Set(
-					ruleNode.selectors.flatMap((selector) => resolvedNestedSelector(selector, ruleNode)),
+					ruleNode.selectors.flatMap((selector) => {
```
Comment (ybiquitous) [inline lib/rules/no-duplicate-selectors/index.js:66]: [trivial] In my opinion, `filter()` can make it a bit readable. But no problem as is. 👍🏼 

```js
ruleNode.selectors
	.filter(isStandardSyntaxSelector)
	.flatMap((selector) => resolvedNestedSelector(selector, ruleNode)),
```

Comment (JounQin) [reply lib/rules/no-duplicate-selectors/index.js:66]: I would prefer current implementation because it does not need to iterate `selectors` twice.

**Review by ybiquitous — APPROVED** [review]
Thank you. LGTM 👍🏼

**Comment by JounQin** [comment]
@ybiquitous Shall we merge and release? This issue breaks us from upgrading to v14.8.3.

**Comment by ybiquitous** [comment]
I'll have time to release it later today or about tomorrow.

**Comment by ybiquitous** [comment]
Changelog entry added:

> Fixed: `no-duplicate-selectors` error with non-standard selectors ([#6106](https://github.com/stylelint/stylelint/pull/6106)).

**Comment by afc163** [comment]
I don't think that `no-duplicate-selectors` works in a correct way now: https://github.com/ant-design/ant-design/runs/6574589909?check_suite_focus=true

**Comment by ybiquitous** [comment]
@afc163 Could you create a new issue with the reproduction info, please?
