### PR TITLE
Fix false positives for no-descending-specificity and scss syntax

### LINKED ISSUE #3417: Fix false positives for #{&} in no-descending-specificity
> Clearly describe the bug

There are false positives for rule `no-descending-specificity` when some manipulations are applied to a selector.

> Which rule, if any, is the bug related to?

`no-descending-specificity`

> What CSS is needed to reproduce the bug?

e.g.

```css
.foo {
    &--a,
    &--a#{&}--b {
      div {
        padding: 10px;
      }
    }
}
```

> What stylelint configuration is needed to reproduce the bug?

default

> Which version of stylelint are you using?

`9.2.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

"CLI with `stylelint '**/*.{css,scss}'`"

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

"Yes, it's related to SCSS injections into selector string."

> What did you expect to happen?

"No warnings to be flagged."

> What actually happened (e.g. what warnings or errors did you get)?

"The following warnings were flagged:"

```shell
file.scss
4:6    Expected selector ".foo--a#{.foo}--b div" to come before selector ".foo--a div" (no-descending-specificity)
```

### PR DESCRIPTION
**Pull request by YozhikM**
> Which issue, if any, is this issue related to?

Closes #3417 

> Is there anything in the PR that needs further explanation?

No.

### CODE REVIEW

File: lib/rules/no-descending-specificity/__tests__/index.js [hunk 1]
```diff
@@ -147,3 +147,15 @@ testRule(rule, {
...
 });
+
+testRule(rule, {
+  ruleName,
+  syntax: "scss",
+  config: [true],
+
+  accept: [
+    {
+      code: ".foo { &--a, &--a#{&}--b {  div { padding: 10px; } } }"
```
Comment (jeddy3) [inline lib/rules/no-descending-specificity/__tests__/index.js]: As [per the conventions](https://github.com/stylelint/stylelint/blob/master/docs/developer-guide/rules.md#example-patterns):

> Use the minimum amount of code possible to communicate the pattern e.g. if the rule targets selectors then use an empty rule e.g. {}.

Can we use the following please?:

```js
.foo { &--a, &--a#{&}--b { div {} } }

File: lib/rules/no-descending-specificity/index.js [hunk 2]
```diff
@@ -55,9 +56,11 @@ const rule = function(actual) {
         const index = rule.selector.indexOf(trimSelector);
         // Resolve any nested selectors before checking
         resolvedNestedSelector(selector, rule).forEach(resolvedSelector => {
-          parseSelector(resolvedSelector, result, rule, s =>
-            checkSelector(s, rule, index, comparisonContext)
-          );
+          parseSelector(resolvedSelector, result, rule, s => {
+            if (isStandardSyntaxSelector(resolvedSelector)) {
```
Comment (jeddy3) [inline lib/rules/no-descending-specificity/index.js]: The convention, in this file and others, is to return early when using the `isStandard*` utils. We should probably follow it here too:

```js
parseSelector(resolvedSelector, result, rule, s => {
  if (isStandardSyntaxSelector(resolvedSelector)) {
    return;
  }
  checkSelector(s, rule, index, comparisonContext);
}
```

**Comment by hudochenkov** [comment]
> -   Fixed: `no-descending-specificity` false positives for #{&} ([#3420](https://github.com/stylelint/stylelint/pull/3420)).
