### PR TITLE
Fix `declaration-block-no-redundant-longhand-properties` autofix for `grid-template`

### LINKED ISSUE #6701: Fix `declaration-block-no-redundant-longhand-properties` autofix for `grid-template`
### What steps are needed to reproduce the bug?

Broken autofix for `declaration-block-no-redundant-longhand-properties` with `grid-template`

I have the next CSS
DEMO: https://codepen.io/shoonia/pen/qBMVPXr
```css
.page {
  display: grid;
  height: 100vh;
  grid-template-rows: var(--header-h) 1fr var(--footer-h);
  grid-template-columns: var(--toolbar-w) 1fr;
  grid-template-areas: "header header" "toolbar main" "footer footer";
}
```

After using autofix with `--fix` , it broken my layout
DEMO: https://codepen.io/shoonia/pen/GRXOMMG
```diff
.page {
  display: grid;
  height: 100vh;
-  grid-template-rows: var(--header-h) 1fr var(--footer-h);
-  grid-template-columns: var(--toolbar-w) 1fr;
-  grid-template-areas: "header header" "toolbar main" "footer footer";
+ grid-template: var(--toolbar-w) 1fr var(--header-h) 1fr var(--footer-h) "header header" "toolbar main" "footer footer";
}
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "extends": [
    "stylelint-config-standard",
    "stylelint-config-css-modules"
  ],
  "rules": {
    "selector-class-pattern": null,
    "selector-pseudo-element-no-unknown": [
      true,
      {
        "ignorePseudoElements": [
          "range-track",
          "range-thumb"
        ]
      }
    ]
  }
}

```

### How did you run Stylelint?

`npx stylelint src/**/*.css --fix`

### Which version of Stylelint are you using?

`15.2.0`

### What did you expect to happen?

it shouldn't be minimized.

### What actually happened?

```diff
-  grid-template-rows: var(--header-h) 1fr var(--footer-h);
-  grid-template-columns: var(--toolbar-w) 1fr;
-  grid-template-areas: "header header" "toolbar main" "footer footer";
+ grid-template: var(--toolbar-w) 1fr var(--header-h) 1fr var(--footer-h) "header header" "toolbar main" "footer footer";
```

### Does the bug relate to non-standard syntax?

NO

### Proposal to fix the bug

Looks like it shouldn't be minimize. I don't know a short syntax for this construction.

### PR DESCRIPTION
**Pull request by mattxwang**
> Which issue, if any, is this issue related to?

Closes #6701.

> Is there anything in the PR that needs further explanation?

A handful of thoughts:

- should I be moving this "custom resolver" logic to a new file?
- I've elected to *not* implement the same fix for the `grid` shorthand, since the situation there is quite a bit more complicated with the `auto-flow` syntax element ([spec ref](https://www.w3.org/TR/css-grid-2/#grid-shorthand))

More broadly, I'm happy to own any other changes that need to be made to this autofixer.

### CODE REVIEW

**Comment by mattxwang** [comment]
After thinking on it a bit more, I'm not sure what the other alternative is to resolve this problem (other than a "custom resolver" methodology). Going to mark this as ready to review, but I'm anticipating that it'll need some changes!

File: lib/rules/declaration-block-no-redundant-longhand-properties/index.js [hunk 1]
```diff
@@ -113,21 +154,24 @@ const rule = (primary, secondaryOptions, context) => {
...
+								prefixedShorthandProperty,
+								prefixedShorthandData,
+								transformedDeclarationNodes,
+							);
 
-							const newShorthandDeclarationNode = firstDeclNode.clone({
-								prop: prefixedShorthandProperty,
-								value: resolvedShorthandValue,
-							});
+							if (resolvedShorthandValue !== null) {
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/index.js:163]: [suggest] This is just my preference, simply checking just a variable seems a bit more readable:

```suggestion
							if (resolvedShorthandValue) {
```

File: lib/rules/declaration-block-no-redundant-longhand-properties/index.js [hunk 2]
```diff
@@ -22,8 +22,49 @@ const meta = {
...
 
+const customResolvers = new Map([
+	[
+		'grid-template',
+		(/** @type {Map<string, Declaration>} */ transformedDeclarationNodes) => {
+			const areas = transformedDeclarationNodes.get('grid-template-areas')?.value.trim();
+			const columns = transformedDeclarationNodes.get('grid-template-columns')?.value.trim();
+			const rows = transformedDeclarationNodes.get('grid-template-rows')?.value.trim();
+
+			if (areas === undefined || columns === undefined || rows === undefined) return;
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/index.js:33]: [suggest] Excluding also `''` seems safer because of using `.trim()` like this:

```suggestion
			if (!(areas && columns && rows)) return;
```

File: lib/rules/declaration-block-no-redundant-longhand-properties/index.js [hunk 3]
```diff
@@ -22,8 +22,49 @@ const meta = {
...
+
+			const splitAreas = [...areas.matchAll(/".+?"/g)].map((x) => x[0]);
+			const splitRows = rows.split(' ');
+
+			if (splitAreas.length !== splitRows.length) return;
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/index.js:38]: [suggest] Just in case, how about checking if the arrays are empty?

```suggestion
			if (splitAreas.length === 0 || splitRows.length === 0) return;

			if (splitAreas.length !== splitRows.length) return;
```

File: lib/rules/declaration-block-no-redundant-longhand-properties/index.js [hunk 4]
```diff
@@ -22,8 +22,49 @@ const meta = {
...
+	[
+		'grid-template',
+		(/** @type {Map<string, Declaration>} */ transformedDeclarationNodes) => {
+			const areas = transformedDeclarationNodes.get('grid-template-areas')?.value.trim();
+			const columns = transformedDeclarationNodes.get('grid-template-columns')?.value.trim();
+			const rows = transformedDeclarationNodes.get('grid-template-rows')?.value.trim();
+
+			if (areas === undefined || columns === undefined || rows === undefined) return;
+
+			const splitAreas = [...areas.matchAll(/".+?"/g)].map((x) => x[0]);
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/index.js:35]: [suggest] How about changing to a bit more accurate regex?

```suggestion
			const splitAreas = [...areas.matchAll(/"[^"]+?"/g)].map((x) => x[0]);
```

**Review by ybiquitous — CHANGES_REQUESTED** [review]
@mattxwang Thanks for the pull request. I've commented on a few refactoring ideas, so can you check them?

**Comment by mattxwang** [comment]
Thanks for the suggestions! I think I've incorporated all of them (in a slightly-messy git history 😅 )

**Review by ybiquitous — APPROVED** [review]
Thanks, LGTM 👍🏼
