### PR TITLE
Fix false positives for longhand grid-column/row-* properties in value-keyword-case

### LINKED ISSUE #4605: Fix false positives for longhand grid-column-* properties in value-keyword-case
Hello!

`value-keyword-case` flags the following instance:

```
grid-column-end: wideBlockRow;
```

However, the rule seems to be primarily designed to impose consistent use of CSS keywords.

Because camel casing seems desirable for (or at least improves the readability of) `longUserDefinedVariables`, it would be neat to disable this feature for such keywords.

Thank you!

### PR DESCRIPTION
**Pull request by fanich37**
> Which issue, if any, is this issue related to?

It should close #4605 .

> Is there anything in the PR that needs further explanation?

I think its necessary to convert prop to lower case before any comparison can be done.

### CODE REVIEW

File: lib/rules/value-keyword-case/__tests__/index.js [hunk 1]
```diff
@@ -311,6 +311,10 @@ testRule(rule, {
 			code: 'a { color: ThreeDShadow; }',
 			description: 'another system color',
 		},
+		{
+			code: 'a { grid-column-start: span camelCaseArea; }',
```
Comment (evilebottnawi) [inline lib/rules/value-keyword-case/__tests__/index.js]: Can we add a test for `a { GRID-COLUMN-START: SPAN camelCaseArea; }`?

**Comment by jeddy3** [comment]
> - Fixed: `value-keyword-case` false positives for longhand `grid-column/row-*` properties ([#4611](https://github.com/stylelint/stylelint/pull/4611)).

**Comment by camiblanch** [comment]
This change caused an issue with having uppercase in css variable properties that you wish to add to the `ignoreProperties` list. See #4644
