### PR TITLE
Fix `selector-max-specificity` false positives with `ignoreSelectors` option for `of <selector>` syntax

### LINKED ISSUE #6615: Fix `selector-max-specificity` false positives with `ignoreSelectors` option for `of <selector>` syntax
### What steps are needed to reproduce the bug?

The following second CSS snippet (selector) reports a `selector-max-specificity` problem:

```css
/* pass */
foo:nth-child(even) { color: red; }

/* fail */
foo:nth-child(even of a) { color: red; }
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "selector-max-specificity": ["0,1,0", { "ignoreSelectors": ["/foo/"] }]
  }
}
```

### How did you run Stylelint?

CLI

### Which version of Stylelint are you using?

`14.16.1`

### What did you expect to happen?

No problems to be reported by the `ignoreSelectors` option.

### What actually happened?

The following problem is reported:

```
5:1  Expected "foo:nth-child(even of a)" to have a specificity no more than "0,1,0"
```

See the [demo](https://stylelint.io/demo#N4Igxg9gJgpiBcID0AqABABwIYGcdpSQB0A7AMwgnhIBcALAWjDoEsAbKAChgDcYSAlGmBpIbCACd4aCTCgBuNAF9SpVGjJZ2BYuUrV6TVh258SaCGTRYhIsZOmyFy0iAA0IHAE9aWAB4I4Hju4BDkLADmgcCkaGhEIBIArmwwOAnSMeZx8Z4wqWA0kgwAtv4MOBgwYCxkLDU0XhloANoJAAxuAIxu7QluwrmRJJIwAMr51UUS6QitCUgUEMQgALrKq7EuJEogSkA).

### Does the bug relate to non-standard syntax?

_No response_

### Proposal to fix the bug

Relevant code:

- https://github.com/stylelint/stylelint/blob/b3af7d2bb8cce81bb7e51e81d980274bb4d14643/lib/rules/selector-max-specificity/__tests__/index.js#L463-L466
- https://github.com/stylelint/stylelint/blob/b3af7d2bb8cce81bb7e51e81d980274bb4d14643/lib/rules/selector-max-specificity/index.js#L129-L131

See also #6140

### PR DESCRIPTION
**Pull request by ybiquitous**
Config:

```json
{"ignoreSelectors": [".foo"]}
```

CSS code:

```css
:nth-child(even of .foo) {}

/* ↓ Calculates specificity ignoring 'of .foo' in `ignoreSelectors` */
:nth-child(even) {}
```

> Which issue, if any, is this issue related to?

Closes #6615

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

### CODE REVIEW

**Review by jeddy3 — APPROVED** [review]

File: lib/rules/selector-max-specificity/index.cjs [hunk 1]
```diff
@@ -104,6 +108,45 @@ const rule = (primary, secondaryOptions) => {
...
+			/** @type {(node: import('postcss-selector-parser').Node | undefined) => boolean} */
+			const isOfSelector = (node) => Boolean(node && node.type === 'tag' && node.value === 'of');
+
+			/** @type {(node: import('postcss-selector-parser').Node | undefined) => boolean} */
+			const isSpace = (node) => Boolean(node && node.type === 'combinator' && node.value === ' ');
+
+			const nodes = pseudo.nodes[0]?.nodes ?? [];
+			const ofSelectorIndex = nodes.findIndex((child, i, children) => {
+				// Find ' of <selector>' nodes
+				return isSpace(child) && isOfSelector(children[i + 1]) && isSpace(children[i + 2]);
```
Comment (Mouvedia) [inline lib/rules/selector-max-specificity/index.cjs:130]: minor nit

not sure if the `node.type ===` check are needed
which could allow a refactoring
e.g. `const foo = (node, value) => Boolean(node && && node.value === value);`

File: lib/rules/selector-max-specificity/index.mjs [hunk 2]
```diff
@@ -105,6 +109,45 @@ const rule = (primary, secondaryOptions) => {
...
+			/** @type {(node: import('postcss-selector-parser').Node | undefined) => boolean} */
+			const isOfSelector = (node) => Boolean(node && node.type === 'tag' && node.value === 'of');
+
+			/** @type {(node: import('postcss-selector-parser').Node | undefined) => boolean} */
+			const isSpace = (node) => Boolean(node && node.type === 'combinator' && node.value === ' ');
+
+			const nodes = pseudo.nodes[0]?.nodes ?? [];
+			const ofSelectorIndex = nodes.findIndex((child, i, children) => {
+				// Find ' of <selector>' nodes
+				return isSpace(child) && isOfSelector(children[i + 1]) && isSpace(children[i + 2]);
```
Comment (Mouvedia) [inline lib/rules/selector-max-specificity/index.mjs:131]: minor nit

not sure if the `node.type ===` checks are needed
which could allow a refactoring
e.g. `const foo = (node, value) => Boolean(node?.value === value);`

Comment (ybiquitous) [reply lib/rules/selector-max-specificity/index.mjs:131]: Yeah, checking `node.type` is necessary for safer parsing. I've refactored the code via 9e0fea060 as you suggested. 👍🏼

Comment (Mouvedia) [reply lib/rules/selector-max-specificity/index.mjs:131]: > for safer parsing

That's reasonable.
