### PR TITLE
Fix `hue-degree-notation` false negatives and positives for relative colors

### LINKED ISSUE #8983: Fix `hue-degree-notation` false negatives and positives for relative colors
### What minimal example or steps are needed to reproduce the bug?

```css
a{
  color: oklch(from red 1 c h)
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  rules: {'hue-degree-notation': 'angle'}
}
```

### How did you run Stylelint?

https://stylelint.io/demo/#N4Igxg9gJgpiBcICGwA6A7ABJyAbCATvJhANa5gAWAFAGYEQC2mBMUmAjDppQJQYBfEABoQtAJa4YAOSSM4iGAA85ABykA6MAGdtI8BHQSA5ghDLVhAC6ZYtJAFdcNtFhZOY24sADklBzAAtLDGrEHoEFZIVuKGPsQ+SOjGUj4CggDcGPqQRuLGAGKEjNFm2lYAnlK44uhWWoYmGowAVnqisKp6iK7YqCDlVTA1df3E-bjRnlb9whh9A5XVtVaBuSaB5UlQSARQY5gTU+X9gtkCQA

### Which Stylelint-related dependencies are you using?

latest- 
[stylelint](https://stylelint.io/)@17.0.0
[stylelint-config-standard](https://www.npmjs.com/package/stylelint-config-standard)@40.0.0

### What did you expect to happen?

No error

### What actually happened?

The following error was reported:

```
Expected "1" to be "1deg" (hue-degree-notation)
```

In the example, 1 is a lightness value, which is not a hue value, and degrees are not valid. However, it's the third value, which in non-relative syntax is hue, which does use degrees.

### Do you have a proposal to fix the bug?

Relative color syntax allows you to create a new color based on a given color, for instance `oklch(from red l c h)`. This shifts the channel values from 1,2,3 to 3,4,5.

Channel values should be shifted to accommodate relative color syntax when the `from` keyword is encountered.

### PR DESCRIPTION
**Pull request by jamesnw**
Closes #8983 

This tests that the first value is `from` to distinguish when the channels should be offset.

### CODE REVIEW

File: lib/rules/hue-degree-notation/__tests__/index.mjs [hunk 1]
```diff
@@ -130,6 +145,45 @@ testRule({
...
+			fix: {
+				range: [25, 26],
+				text: '0deg',
+			},
+			message: messages.expected('10', '10deg'),
+			line: 1,
+			column: 25,
+			endLine: 1,
+			endColumn: 27,
+		},
```
Comment (jeddy3) [inline lib/rules/hue-degree-notation/__tests__/index.mjs:196]:
```suggestion
		{
			code: 'a { color: hsl(FROM lch(0 0 10) 0 s l) }',
			fixed: 'a { color: hsl(FROM lch(0 0 10deg) 0deg s l) }',
			warnings: [
				{
					message: messages.expected('0', '0deg'),
					column: 33,
					endLine: 1,
					endColumn: 34,
					fix: {
						range: [32, 33],
						text: '0deg',
					},
				},
				{
					message: messages.expected('10', '10deg'),
					line: 1,
					column: 29,
					endLine: 1,
					endColumn: 31,
				},
			],
		},
```

Since relative colour syntax allows nested colours, let's update this test to confirm they are fixed as well.

(And testing for case insensitivity.)

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYLIBsICd4oAsBnTACgDEAlAeQFkVMwDSAGFNgRhYEp2UiGvAL4gANCABmAS0wwAckgC2cRDAAeSgA6yAdGCJEx4CADtpAcwQh1m3ABcUsCUgCumB8AA6JlChxuYInwvH18UTxACFxgAWlhzHBhYkwg7JDspUwj8CKQTc1kI718hbyEAbm8jSDMpc3JcRXSrIjsAT1lMKRM7PVMLHUUAK0NxWE1DRBDfCNaOmC6e7PDIuzsJ+AB6Tc0Aa3MdTRwdExgAd025zu67AAEANgBme4AWAE4wCQjRYpWrhZuMRqFhirTyUCQOCgywimHSgTsRRMIiEQA).
