### PR TITLE
fix max-line-length rule

### LINKED ISSUE #4059: Fix false positives for multi-line url() in max-line-length
> Clearly describe the bug

There are false positives for max line length when there are spaces inside `url()` content.

> Which rule, if any, is the bug related to?

`max-line-length`

> What CSS is needed to reproduce the bug?

```css
div {
  background-image: url(
    "data:image/svg+xml;utf8,<svg fill='black' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M7 9l5 5 5-5z'/></svg>"
  );
}
```

> What tests are not passing?

```js
{
  code:
    "a {\n  background: url(\n    'something something  something'\n  );\n}"
}
```

> What stylelint configuration is needed to reproduce the bug?

```yaml
rules:
  max-line-length:
    - 20
```

> Which version of stylelint are you using?

`9.10.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint "**/*.css"`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No.

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged: 

```shell
70:102  ✖  Expected line length to be no more than 80 characters                                               max-line-length
```

### PR DESCRIPTION
**Pull request by vankop**
> Which issue, if any, is this issue related to?

Fixes #4059

> Is there anything in the PR that needs further explanation?

Nothing

### CODE REVIEW

**Comment by hudochenkov** [comment]
So many changes, I don't understand what it does :(

I wonder would this issue be fixed if it was updating RexExp to [accept new lines](https://stackoverflow.com/a/6883270):

```diff
- const urlArgumentsLength = execall(/url\((.*)\)/gi, lineText).reduce(
+ const urlArgumentsLength = execall(/url\(([\s\S]*)\)/gi, lineText).reduce(
```

**Comment by vankop** [comment]
> So many changes, I don't understand what it does :(
> 
> I wonder would this issue be fixed if it was updating RexExp to [accept new lines](https://stackoverflow.com/a/6883270):
> 
> ```diff
> - const urlArgumentsLength = execall(/url\((.*)\)/gi, lineText).reduce(
> + const urlArgumentsLength = execall(/url\(([\s\S]*)\)/gi, lineText).reduce(
> ```

https://github.com/vankop/stylelint/commit/5677f4766d0f550cbc027d2f1c47968cbacc61d9
This test case will fall

**Comment by vankop** [comment]
current code execute regex line-by-line thats why it falls ( `url(` could be splitted between lines)

File: lib/rules/max-line-length/index.js [hunk 1]
```diff
@@ -43,6 +47,21 @@ const rule = function(maxLength, options, context) {
     const ignoreNonComments = optionsMatches(options, "ignore", "non-comments");
     const ignoreComments = optionsMatches(options, "ignore", "comments");
     const rootString = context.fix ? root.toString() : root.source.input.css;
+    // Array of skipped sub strings, i.e `url(...)`, `@import "..."`
+    const skippedSubStrings = [];
+    let skippedSubStringsIndex = 0;
+
+    EXCLUDED_PATTERNS.forEach(pattern =>
```
Comment (vankop) [inline lib/rules/max-line-length/index.js]: all excluded patterns created array of excluded indexes, for instance:
```
url
 (
 "blabla"
)
```
will return `[[7, 15]]`, where 7 is first `"` and 15 is next after `"blabla"`

File: lib/rules/max-line-length/index.js [hunk 2]
```diff
@@ -75,32 +116,21 @@ const rule = function(maxLength, options, context) {
       }
 
       const rawLineLength = nextNewlineIndex - match.endIndex;
+      const excludedLength = skippedSubStrings[skippedSubStringsIndex]
```
Comment (vankop) [inline lib/rules/max-line-length/index.js]: compute excluded substring length (for current line), for instance:
```
url(
\t\t"bla bla"\u0020);
```
will give `excludedLength` equal to `"bla bla".length`

Comment (vankop) [reply lib/rules/max-line-length/index.js]: it is a bit tricky since
```
url("bla \
bla \
");
```

will give `excludedLength` equals to `"bla \\\n".length` on line 1

File: lib/rules/max-line-length/index.js [hunk 3]
```diff
@@ -62,6 +81,28 @@ const rule = function(maxLength, options, context) {
...
+      if (end < startSubString) {
+        return 0;
+      }
+
+      // Compute excluded substring size regarding to current line indexes
+      const excluded =
+        Math.min(end, endSubString) - Math.max(start, startSubString);
+
+      // Current substring is out of range for next lines
+      if (endSubString <= end) {
```
Comment (vankop) [inline lib/rules/max-line-length/index.js]: current line last index + 1 is over current range end

File: lib/rules/max-line-length/index.js [hunk 4]
```diff
@@ -62,6 +81,28 @@ const rule = function(maxLength, options, context) {
       });
     }
 
+    function tryToPopSubString(start, end) {
+      const [startSubString, endSubString] = skippedSubStrings[
+        skippedSubStringsIndex
+      ];
+
+      // Excluded substring does not presented in current line
+      if (end < startSubString) {
```
Comment (vankop) [inline lib/rules/max-line-length/index.js]: current excluded range is not presented on current line

File: lib/rules/max-line-length/index.js [hunk 5]
```diff
@@ -62,6 +81,28 @@ const rule = function(maxLength, options, context) {
...
+        return 0;
+      }
+
+      // Compute excluded substring size regarding to current line indexes
+      const excluded =
```
Comment (vankop) [inline lib/rules/max-line-length/index.js]: Compute excluded substring size regarding to current line indexes =)

**Comment by vankop** [comment]
@hudochenkov i have add some explanation

**Comment by hudochenkov** [comment]
> -   Fixed: `max-line-length` false positives for multi-line url() ([#4169](https://github.com/stylelint/stylelint/pull/4169)).
