### PR TITLE
Fix TypeError for syntaxes that use Document in indentation

### LINKED ISSUE #5767: Fix TypeError for syntaxes that use Document in indentation
### What steps are needed to reproduce the bug?

If you have a `Root` in a `Document` whose css begins on line 1, like so:

```css
  .foo {
    color: hotpink;
  }
```

The indentation rule will throw, as it tries to access `root.raws.beforeStart` which doesn't exist.

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "indentation": 2
  }
}
```

### How did you run Stylelint?

CLI

### Which version of Stylelint are you using?

14

### What did you expect to happen?

Indentation rule would succeed.

### What actually happened?

The rule throws:

```
TypeError: Cannot read properties of undefined (reading 'endsWith')
```

### Does the bug relate to non-standard syntax?

No

### Proposal to fix the bug

https://github.com/stylelint/stylelint/blob/0d2303ef01e065a1005b6b7ebcf51611223655f7/lib/rules/indentation/index.js#L94-L98

Ultimately, we hit this condition. It is comprised of these:

Does `node.raws.before` contain a newline? - No, so we continue.

Is it the first child? - Yes.

Does it's parent have a document? - Yes.

This leads us to then attempting to execute `parent.raws.beforeStart.endsWith('\n')` which will fail if `beforeStart` doesn't exist.

We should null check `parent.raws.beforeStart` as it may never exist, or a plugin could have since removed it.

Btw I am aware of #5674 , so please let me know if you'll never fix this as I can fix it on my end instead (by populating `beforeStart` with an empty string at least).

### PR DESCRIPTION
**Pull request by 43081j**
Fixes #5767 

I changed `beforeStart` to `codeBefore`  and added a truthy check

### CODE REVIEW

File: lib/rules/indentation/__tests__/document-with-roots.js [hunk 1]
```diff
@@ -0,0 +1,38 @@
+'use strict';
+
+const postcssParse = require('postcss/lib/parse');
+const { stringify, Document, Input } = require('postcss');
```
Comment (ybiquitous) [inline lib/rules/indentation/__tests__/document-with-roots.js:4]: [suggestion] I think it's better to avoid internal importing like `require('postcss/lib/parse')` if possible. So how about refactoring like this?

```suggestion
const { parse: postcssParse, stringify, Document, Input } = require('postcss');
```

File: lib/rules/indentation/index.js [hunk 2]
```diff
@@ -628,7 +630,7 @@ function inferRootIndentLevel(root, baseIndentLevel, indentSize) {
 	}
 
 	const indents = [];
-	const foundIndents = /(?:^|\n)([ \t]*)\S/m.exec(root.raws.beforeStart);
+	const foundIndents = root.raws.codeBefore && /(?:^|\n)([ \t]*)\S/m.exec(root.raws.beforeStart);
```
Comment (ybiquitous) [inline lib/rules/indentation/index.js:633]: [suggestion] Isn't it needed to use `beforeStart`?

```suggestion
	const foundIndents = root.raws.codeBefore && /(?:^|\n)([ \t]*)\S/m.exec(root.raws.codeBefore);
```

**Review by ybiquitous — COMMENTED** [review]
@43081j Thank you for creating this PR!
I've left some trivial suggestions, but this is mostly good to me. 👍🏼

File: lib/rules/indentation/index.js (hunk 2 above)
Comment (43081j) [reply lib/rules/indentation/index.js:633]: ah good catch! just missed it

**Comment by 43081j** [comment]
sorry this got a bit lost @jeddy3, i've updated it now with what you said

**Review by ybiquitous — APPROVED** [review]
@43081j Thank you! LGTM 👍🏼

**Review by jeddy3 — COMMENTED** [review]
LGTM, thanks.

**Review by jeddy3 — APPROVED** [review]

**Comment by jeddy3** [comment]
> - Fixed: `indentation` TypeError for syntaxes that use Document node type ([#5771](https://github.com/stylelint/stylelint/pull/5771)).
