### PR TITLE
Fix `declaration-property-value-no-unknown` false positives for descriptors

### LINKED ISSUE #6663: Fix `declaration-property-value-no-unknown` false positives for descriptors
### What steps are needed to reproduce the bug?

```css
@font-face {
    font-family: 'AwesomeVariableFont';
    font-style: normal;
    font-weight: 100 700;
    src: url('./fonts/AwesomeVariableFont.woff2') format('woff2-variations');
}
```

For variable fonts, the `font-weight` descriptor accepts the minimum and maximum weights supported by the font:

* [MDN: `@font-face`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face#font-weight)
* [MDN: `@font-face`'s `font-weight` descriptor](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-weight) (compare also with [MDN: `font-weight` property](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight))

### What Stylelint configuration is needed to reproduce the bug?

```yaml
rules:
  declaration-property-value-no-unknown: true
```

### How did you run Stylelint?

npx stylelint style.css

### Which version of Stylelint are you using?

15.1.0

### What did you expect to happen?

No problems to be reported.

### What actually happened?

The following problem was reported:

```
style.css
 4:22  ✖  Unexpected unknown value "700" for property "font-weight"  declaration-property-value-no-unknown
```

### Does the bug relate to non-standard syntax?

No, only native CSS syntax is involved.

### Proposal to fix the bug

_No response_

### PR DESCRIPTION
**Pull request by FloEdelmann**
> Which issue, if any, is this issue related to?

Closes #6663.

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

### CODE REVIEW

File: lib/rules/declaration-property-value-no-unknown/index.js [hunk 1]
```diff
@@ -108,7 +109,15 @@ const rule = (primary, secondaryOptions) => {
...
-			const { error } = forkedLexer.matchProperty(prop, cssTreeValueNode);
+			let error;
+			const parent = decl.parent;
+
+			if (parent && parent.type === 'atrule') {
+				// @ts-expect-error -- CSSTree types are not complete
+				({ error } = forkedLexer.matchAtruleDescriptor(parent.name, prop, cssTreeValueNode));
+			} else {
+				({ error } = forkedLexer.matchProperty(prop, cssTreeValueNode));
+			}
```
Comment (jeddy3) [inline lib/rules/declaration-property-value-no-unknown/index.js:120]:
```suggestion
				const {error} = decl?.parent?.type === 'atrule'
				// @ts-expect-error -- CSSTree types are not complete
				? forkedLexer.matchAtruleDescriptor(decl.parent?.name, prop, cssTreeValueNode)
				: forkedLexer.matchProperty(prop, cssTreeValueNode);
```

I believe we can use the optional chaining operator in `15.0.0` as we dropped support for Node.js 12.

@ybiquitous may have a better suggestion for refactoring this snippet. He's amazing at them.

File: .changeset/cyan-kangaroos-hope.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"stylelint": patch
+---
+
+Fix false-positives for at-rule descriptors in `declaration-property-value-no-unknown`
```
Comment (jeddy3) [inline .changeset/cyan-kangaroos-hope.md:5]:
```suggestion
Fixed: `declaration-property-value-no-unknown` false positives for descriptors
```

nit for [conventions](https://stylelint.io/maintainer-guide/pull-requests).

**Review by jeddy3 — CHANGES_REQUESTED** [review]
@FloEdelmann This is fantastic, thank you!

It's looking good. I've requested a couple of small changes.

File: .changeset/cyan-kangaroos-hope.md (hunk 2 above)
Comment (FloEdelmann) [reply .changeset/cyan-kangaroos-hope.md:5]: I'd still explicitly mention "at-rules", since most people will probably not know what "descriptors" are.

```suggestion
Fixed: `declaration-property-value-no-unknown` false positives for at-rule descriptors
```

File: lib/rules/declaration-property-value-no-unknown/index.js (hunk 1 above)
Comment (FloEdelmann) [reply lib/rules/declaration-property-value-no-unknown/index.js]: We can actually omit the optional chaining in the `matchAtruleDescriptor` function call because it is already checked to exist in the ternary condition.

I refactored the code to this suggestion (minus the superfluous optional chaining operator, plus formatting via Prettier) in [`ca25f9b`](https://github.com/stylelint/stylelint/pull/6669/commits/ca25f9bb0dac9a81c3118ffe96fc20a76a00e6c0).

File: lib/rules/declaration-property-value-no-unknown/index.js [hunk 3]
```diff
@@ -108,7 +109,11 @@ const rule = (primary, secondaryOptions) => {
 				return;
 			}
 
-			const { error } = forkedLexer.matchProperty(prop, cssTreeValueNode);
+			const { error } =
+				decl?.parent?.type === 'atrule'
+					? // @ts-expect-error -- CSSTree types are not complete
+					  forkedLexer.matchAtruleDescriptor(decl.parent.name, prop, cssTreeValueNode)
```
Comment (ybiquitous) [inline lib/rules/declaration-property-value-no-unknown/index.js:115]: I'll send a patch to `@types/css-tree`. 💪🏼

**Review by ybiquitous — APPROVED** [review]
Cool. LGTM 👏🏼

**Review by jeddy3 — APPROVED** [review]
Thanks for making the changes.

LGTM.

File: lib/rules/declaration-property-value-no-unknown/index.js (hunk 3 above)
Comment (FloEdelmann) [reply lib/rules/declaration-property-value-no-unknown/index.js:115]: Thanks! Note that more functions from the `Lexer` class are missing, so maybe you can add them all in one batch?

Also, I used `@ts-expect-error` instead of `@ts-ignore`, so that this PR can be merged first and will throw an error once the `css-tree` types are fixed.

Comment (FloEdelmann) [reply lib/rules/declaration-property-value-no-unknown/index.js:115]: [`checkAtrulePrelude`](https://github.com/csstree/csstree/blob/612cc5f2922b2304869497d165a0cc65257f7a8b/lib/lexer/Lexer.js#L244) might be needed for #6560.

Comment (ybiquitous) [reply lib/rules/declaration-property-value-no-unknown/index.js:115]: I've opened PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64410. Any feedback is welcome if you have.
