### PR TITLE
Fix #4327

### LINKED ISSUE #4327: Add support for `font-weight` ranges in `@font-face`
> Clearly describe the bug

There are false positives when using `font-weight` inside `@font-face`

https://github.com/stylelint/stylelint/tree/master/lib/rules/font-weight-notation

Reference:

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face#Descriptors
> `font-weight`
> >  A `font-weight` value. Since Firefox 61 (and in other modern browsers) this also accepts two values to specify a range that is supported by a `font-face`, for example `font-weight: 100 400;`

> Which rule, if any, is the bug related to?

`font-weight-notation`

> What CSS is needed to reproduce the bug?

```css

@font-face {
	font-family: "Inter var";
	font-weight: 100 900;
	font-style: normal;
	src: url(./assets/fonts/inter/Inter-upright.var.woff2) format("woff2");
}

```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "font-weight-notation": [ "numeric", {
      ignore: ["relative"],
    } ],
  }
}
```

> Which version of stylelint are you using?

11.0.0

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `./node_modules/.bin/stylelint style.css --config=.stylelintrc.json`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No

> What did you expect to happen?

"No warnings to be flagged."

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged:

```shell
style.css
260:15  ✖  Expected numeric font-weight notation font-weight-notation
```

### PR DESCRIPTION
**Pull request by fanich37**
It should close #4327 . It's my first contribution to this awesome project so it would be great to get any feedback :blush:

### CODE REVIEW

File: lib/rules/font-weight-notation/index.js [hunk 1]
```diff
@@ -103,6 +103,16 @@ const rule = function(expectation, options) {
 			const weightValueOffset = decl.value.indexOf(weightValue);
 
 			if (expectation === 'numeric') {
+				if (decl.parent.type === 'atrule' && decl.parent.name.toLowerCase() === 'font-face') {
+					const weightValueNumbers = weightValue.match(/\d{1,}\.?\d+/g);
```
Comment (evilebottnawi) [inline lib/rules/font-weight-notation/index.js]: I think better use `value` parser here instead regexp, because comments can be between values and it will be false positive

Comment (hudochenkov) [reply lib/rules/font-weight-notation/index.js]: `postcss.list.space()` might works as well. We have it in this rule:

https://github.com/stylelint/stylelint/blob/38d89fefe5569545e9239f7867491043d264dec0/lib/rules/font-weight-notation/index.js#L66

Comment (fanich37) [reply lib/rules/font-weight-notation/index.js]: Thank you for review @evilebottnawi and @hudochenkov ! The edge case that have to processed properly is
```css
font-weight: 400/* 700 */700;
```
In this case we get the ```weightValue``` equals to ```400700```. Probably we need to analyze the ```decl.raws``` data with ```postcss-value-parser``` in such case.

Comment (hudochenkov) [reply lib/rules/font-weight-notation/index.js]: I don't think `font-weight: 400/* 700 */700;` would be valid. Let's consider that we have at least one space before or after comment: `font-weight: 400 /* 700 */700;`.

Comment (fanich37) [reply lib/rules/font-weight-notation/index.js]: In this case I think ```list.space``` would be enough. I updated the PR.

File: lib/rules/font-weight-notation/index.js [hunk 2]
```diff
@@ -103,6 +103,16 @@ const rule = function(expectation, options) {
 			const weightValueOffset = decl.value.indexOf(weightValue);
 
 			if (expectation === 'numeric') {
+				if (decl.parent.type === 'atrule' && decl.parent.name.toLowerCase() === 'font-face') {
+					const weightValueNumbers = postcss.list.space(weightValue)
+
+					if (!weightValueNumbers.every(isNumbery)) {
```
Comment (hudochenkov) [inline lib/rules/font-weight-notation/index.js]: Could you add `reject` cases, please? Currently this condition is not tested.

Comment (fanich37) [reply lib/rules/font-weight-notation/index.js]: Done!

**Comment by fanich37** [comment]
> Great job! Thank you!

Wow! Thank you for your help with this PR! And for fixing the lint.

**Comment by hudochenkov** [comment]
> -   Fixed: `font-weight-notation` false positives for `font-weight` ranges in `@font-face` ([#4372](https://github.com/stylelint/stylelint/pull/4372)).
