### PR TITLE
Fix `declaration-property-value-no-unknown` false positives for `math` of `font-size`

### LINKED ISSUE #8492: Fix `declaration-property-value-no-unknown` false positives for `math` of `font-size`
### What minimal example or steps are needed to reproduce the bug?

```css
math {
	font: math math;
	font-size: math;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
    "declaration-property-value-no-unknown": true
}
```

### How did you run Stylelint?

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIC2BDALgCwATADoDtc0AzCfNeLVTK9DAbgKNPIFoBnASwC8ZLqGBAL4EQAGhDFOAGxgA5FEjiIBAOjDt248GSkBzBCDz4sWXCBgAPNDHxR25ygG0Cp0+fZoAnrOmc2kPj6HGgodigATlDmrlgAusLagfoAYhAR1IYAVuxk2rAADlqIxu4gnj4wfuSOZiDS6DCe5mKxHt6+-misyZx6IWFQkdEIdQ02zSCJQkA)

### Which Stylelint-related dependencies are you using?

```json
{
    "stylelint": "16.16.0"
}
```

### What did you expect to happen?

No problems to be reported.

### What actually happened?

The following problems were reported:

```
test.css
2:8-12    ✖  Unexpected unknown value "math" for property "font" (declaration-property-value-no-unknown)
3:13-17   ✖  Unexpected unknown value "math" for property "font-size" (declaration-property-value-no-unknown)
```

### Do you have a proposal to fix the bug?

This issue is used to split pr #8489.

Related: #8436.

### PR DESCRIPTION
**Pull request by otomad**
> Which issue, if any, is this issue related to?

Closes #8492

> Is there anything in the PR that needs further explanation?

The rule `declaration-property-value-no-unknown` does not consider `math` to be a valid value for `font-size`. This is because [`math` is not a valid syntax for `font-size` in CSSTree](https://csstree.github.io/docs/syntax/#Property:font-size) at this moment. Although [MDN docs formal syntax contains it](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size#formal_syntax).

I have had to put `math` into patches for now, which is not a recommended approach and should be updated into CSSTree.

### CODE REVIEW

**Review by jeddy3 — APPROVED** [review]
@otomad Thanks for the pull request.

While we continue to discuss https://github.com/stylelint/stylelint/issues/8465, I think we can merge this as it's a simple keyword patch to the syntax.

File: lib/rules/declaration-property-value-no-unknown/index.mjs [hunk 1]
```diff
@@ -74,6 +74,7 @@ const rule = (primary, secondaryOptions) => {
 			'text-box-trim': 'none | trim-start | trim-end | trim-both',
 			'view-timeline':
 				"[ <'view-timeline-name'> [ <'view-timeline-axis'> || <'view-timeline-inset'> ]? ]#",
+			'font-size': '| math',
```
Comment (Mouvedia) [inline lib/rules/declaration-property-value-no-unknown/index.mjs:77]: Let's match ours.
i.e.
https://github.com/stylelint/stylelint/blob/6137c5249f317747da1e8fceb82c9f3ad3f791d4/lib/reference/keywords.mjs#L122-L136

```suggestion
			'font-size': '| math | -konq-xxx-large | -webkit-xxx-large',
```

Comment (jeddy3) [reply lib/rules/declaration-property-value-no-unknown/index.mjs:77]: Let's do this in another PR/issue as it changes the scope of this one.

**Review by ybiquitous — APPROVED** [review]
Thanks for the PR, LGTM 👍🏼
