### PR TITLE
Fix false positives for x unit within vendor-prefixed image-set in unit-no-unknown

### LINKED ISSUE #4653: Fix false positives for vendor-prefixed image-set w/ unit "x" in unit-no-unknown
> Clearly describe the bug

The unit-no-unknown rule reports a false positive when using the "x" unit in a value for a vendor-prefixed image-set ~~property~~ value. E.g.

```css
a { background-image: -webkit-image-set('img-1x.jpg' 1x, 'img-2x.jpg' 2x) }
```

caniuse mentions that `-webkit-image-set` is a valid vendor-prefixed version of `image-set`: https://caniuse.com/#feat=css-image-set

(slight change to "ignore `x` unit in image-set" test case in [lib/rules/unit-no-unknown/__tests__/index.js](https://github.com/stylelint/stylelint/blob/master/lib/rules/unit-no-unknown/__tests__/index.js))

> Which rule, if any, is the bug related to?

`unit-no-unknown`

> What code is needed to reproduce the bug?

```css
a { background-image: -webkit-image-set('img-1x.jpg' 1x, 'img-2x.jpg' 2x) }
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "unit-no-unknown": "always"
  }
}
```

> Which version of stylelint are you using?

13.2.1

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI; `npm run test`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged:

```json
{
  "column": 54,
  "line": 1,
  "rule": "unit-no-unknown",
  "severity": "error",
  "text": "Unexpected unknown unit \"x\" (unit-no-unknown)",
}
```

I can write and send a PR.

### PR DESCRIPTION
**Pull request by srawlins**
> Which issue, if any, is this issue related to?

Fixes #4653

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

However, I'm not super familiar with the ASTs involved, and I'm super open to suggestions if this is not an optimal fix.

### CODE REVIEW

File: lib/rules/unit-no-unknown/index.js [hunk 1]
```diff
@@ -116,8 +117,10 @@ function rule(actual, options) {
 							return;
 						}
 
-						if (/^image-set/i.test(value)) {
-							const imageSet = parsedValue.nodes.find((node) => node.value === 'image-set');
+						if (/image-set/i.test(value)) {
```
Comment (evilebottnawi) [inline lib/rules/unit-no-unknown/index.js]: I think better `/^(?:-webkit-)?image-set$/i`, because in theory we can have `image-set-something()` function (yes, it is not exists in CSS), but strict check always better

Comment (jeddy3) [reply lib/rules/unit-no-unknown/index.js]: Yes, let's go with tweaking the RegEx. 

I think we'll be fine with `/^(?:-webkit-)?image-set$/i` as [only the `-webkit` prefix is currently used](https://developer.mozilla.org/en-US/docs/Web/CSS/image-set#Browser_compatibility).

Comment (srawlins) [reply lib/rules/unit-no-unknown/index.js]: Adding `$` at the end does not work here because of what we're matching on. I was able to use `[\s(]` to delimit the end of the function name.

File: lib/rules/unit-no-unknown/index.js [hunk 2]
```diff
@@ -116,8 +117,10 @@ function rule(actual, options) {
 							return;
 						}
 
-						if (/^image-set/i.test(value)) {
-							const imageSet = parsedValue.nodes.find((node) => node.value === 'image-set');
+						if (/^(?:-webkit-)?image-set[\s(]/i.test(value)) {
```
Comment (ybiquitous) [inline lib/rules/unit-no-unknown/index.js:120]: [IMO] If using [`\b` (word boundary)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Assertions#Types), the intent of the code may be clear.

For example:

```suggestion
						if (/^(?:-webkit-)?image-set\b/i.test(value)) {
```

**Comment by jeddy3** [comment]
Changelog entry:

> - Fixed: `unit-no-unknown` false positives for `x` unit within vendor-prefixed `image-set` ([#4654](https://github.com/stylelint/stylelint/pull/4654)).
