### PR TITLE
Fix `declaration-block-no-redundant-longhand-properties` false positives for properties with `!important`

### LINKED ISSUE #8323: Fix `declaration-block-no-redundant-longhand-properties` false positives for properties with `!important`
### What minimal example or steps are needed to reproduce the bug?

```css
a {
	top: 0;
	right: 0;
	bottom: 0 !important;
	left: 0;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "declaration-block-no-redundant-longhand-properties": true
  }
}
```

### How did you run Stylelint?

https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLjiADvCgAwDcWuATgJYDmAFjseZTgEYR4QC2LKAQho8CEKjiSYcFbDgA2MAGbNSMgL5YQAGhCKaCgHJIecRDAAexggoB0YAM73t4CJj10EIDJhQp0ICxwYTCh7f2IAbSxfX397HABPBTkaKQBaSDd6NPjJKCQqKH9olABdLDVnTPcAMTEeJBxPACt7V2dYAidEb1iQeKSYFKlwvxA5Rph4-y0SuMTk1JwM13cciRCCooQxiaDpkAqQNSA

### Which Stylelint-related dependencies are you using?

latest

### What did you expect to happen?

```css
a {
	top: 0;
	right: 0;
	bottom: 0 !important;
	left: 0;
}
```

should not be formatted as 

```css
a {
	inset: 0;
}
```

because of `!important`

### What actually happened?

```css
a {
	top: 0;
	right: 0;
	bottom: 0 !important;
	left: 0;
}
```

formatted as

```css
a {
	inset: 0;
}
```

### Do you have a proposal to fix the bug?

_No response_

### PR DESCRIPTION
**Pull request by immitsu**
> Which issue, if any, is this issue related to?

Closes #8323

> Is there anything in the PR that needs further explanation?

No

### CODE REVIEW

**Review by jeddy3 — COMMENTED** [review]
@immitsu Thank you for the pull request.

Can you please add a reject test (around line 650) for:

```
{
  code: 'a { top: 1px !important; right: 2px !important; bottom: 3px !important; left: 4px !important; }',
  fixed: 'a { inset: 1px 2px 3px 4px !important; }',
  message: messages.expected('inset'),
},
```

i.e. if all the longhand properties have `!important` then they should be fixed into a shorthand property with `!important`.

**Comment by immitsu** [comment]
@jeddy3 I updated the changes because I had overlooked the case. Thank you!

**Review by jeddy3 — APPROVED** [review]
@immitsu Thank you for addressing this use case.

LGTM, thanks.

File: lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs [hunk 1]
```diff
@@ -304,6 +304,16 @@ const rule = (primary, secondaryOptions) => {
 					}
 
 					const declNodes = longhandDeclarationNodes.get(prefixedShorthandProperty) || [];
+
+					const importantDeclNodesCount = declNodes.reduce(
+						(count, declNode) => (declNode.important ? (count += 1) : count),
+						0,
+					);
+
+					if (importantDeclNodesCount > 0 && importantDeclNodesCount < declNodes.length) {
```
Comment (Mouvedia) [inline lib/rules/declaration-block-no-redundant-longhand-properties/index.mjs:313]: nit
non-blocking

```suggestion
					if (importantDeclNodesCount > 0 && importantDeclNodesCount !== declNodes.length) {
```

File: lib/rules/declaration-block-no-redundant-longhand-properties/index.cjs [hunk 2]
```diff
@@ -307,6 +307,16 @@ const rule = (primary, secondaryOptions) => {
 					}
 
 					const declNodes = longhandDeclarationNodes.get(prefixedShorthandProperty) || [];
+
+					const importantDeclNodesCount = declNodes.reduce(
+						(count, declNode) => (declNode.important ? (count += 1) : count),
+						0,
+					);
+
+					if (importantDeclNodesCount > 0 && importantDeclNodesCount < declNodes.length) {
```
Comment (Mouvedia) [inline lib/rules/declaration-block-no-redundant-longhand-properties/index.cjs:316]:
```suggestion
					if (importantDeclNodesCount && importantDeclNodesCount !== declNodes.length) {
```
