### PR TITLE
Fix `*-no-redundant-*` false negatives for `inset` shorthand

### LINKED ISSUE #6613: Fix `declaration-block-no-redundant-longhand-properties` false negatives for `inset` shorthand
### Demand

```
top: 0;
right: 0;
bottom: 0;
left: 0;
```
should get fixed to
```
inset: 0;
```

i.e. add `inset` property to [this list](https://github.com/stylelint/stylelint/blob/autofix-declaration-block-no-redundant-longhand-properties/lib/rules/declaration-block-no-redundant-longhand-properties/README.md?plain=1#L27)

prompted by https://github.com/stylelint/stylelint/pull/6580#discussion_r1096573466

### PR DESCRIPTION
**Pull request by rayrw**
Closes #6613

This PR updates these 2 rules to support the `inset` property

- `declaration-block-no-redundant-longhand-properties`
- `shorthand-property-no-redundant-values`

### CODE REVIEW

File: lib/reference/properties.js [hunk 1]
```diff
@@ -370,6 +370,16 @@ const longhandSubPropertiesOfShorthandProperties = new Map([
...
+	[
+		'inset',
+		new Set([
+			// prettier-ignore
+			'top',
+			'right',
+			'bottom',
+			'left',
+		]),
+	],
```
Comment (ybiquitous) [inline lib/reference/properties.js:382]: [suggest] Could you move `inset` right before `list-style` for alphabetical order?

File: lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js [hunk 2]
```diff
@@ -31,6 +31,21 @@ testRule({
...
+			code: 'div { inset: 1px 2px; }',
+		},
+		{
+			code: 'div { inset: 1px 2px 3px; }',
+		},
+		{
+			code: 'div { inset: 1px 2px 3px 4px; }',
+		},
+		{
+			code: 'div { top: 0; right: 0; bottom: 0; }',
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js:47]: [suggest] Could you use `a` selector instead of `div`?

```suggestion
			code: 'a { inset: 0; }',
		},
		{
			code: 'a { inset: 1px 2px; }',
		},
		{
			code: 'a { inset: 1px 2px 3px; }',
		},
		{
			code: 'a { inset: 1px 2px 3px 4px; }',
		},
		{
			code: 'a { top: 0; right: 0; bottom: 0; }',
```

File: lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js [hunk 3]
```diff
@@ -111,6 +126,16 @@ testRule({
...
 			message: messages.expected('border-width'),
 		},
+		{
+			code: 'div { top: 1px; right: 2px; bottom: 3px; left: 4px; }',
+			fixed: 'div { inset: 1px 2px 3px 4px; }',
+			message: messages.expected('inset'),
+		},
+		{
+			code: 'div { top: 0; right: 0; bottom: 0; left: 0; }',
+			fixed: 'div { inset: 0 0 0 0; }',
```
Comment (ybiquitous) [inline lib/rules/declaration-block-no-redundant-longhand-properties/__tests__/index.js:136]: [suggest] Also here.

```suggestion
			code: 'a { top: 1px; right: 2px; bottom: 3px; left: 4px; }',
			fixed: 'a { inset: 1px 2px 3px 4px; }',
			message: messages.expected('inset'),
		},
		{
			code: 'a { top: 0; right: 0; bottom: 0; left: 0; }',
			fixed: 'a { inset: 0 0 0 0; }',
```

File: types/stylelint/index.d.ts [hunk 4]
```diff
@@ -468,7 +468,8 @@ declare module 'stylelint' {
 		| 'padding'
 		| 'text-decoration'
 		| 'text-emphasis'
-		| 'transition';
+		| 'transition'
+		| 'inset';
```
Comment (ybiquitous) [inline types/stylelint/index.d.ts:472]: [suggest] Could you also move `inset` right before `list-style`?

**Review by ybiquitous — CHANGES_REQUESTED** [review]
@rayrw Thanks for the pull request. Almost LGTM, but I've left several comments about the code style. Could you please consider addressing them?

**Comment by rayrw** [comment]
@ybiquitous Thanks for the reviews!
I've applied your suggestions in https://github.com/stylelint/stylelint/pull/6699/commits/f017239543c5397e00a8d6c5f2ac29ab7750a66d

File: .changeset/mighty-games-kick.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+"stylelint": patch
+---
+
+Fixed: `declaration-block-no-redundant-longhand-properties` and `shorthand-property-no-redundant-values` false negatives for `inset` shorthand
```
Comment (jeddy3) [inline .changeset/mighty-games-kick.md:5]:
```suggestion
Fixed: `*-no-redundant-*` false negatives for `inset` shorthand
```

[Ref](https://stylelint.io/user-guide/rules#redundant) and [conventions](https://stylelint.io/maintainer-guide/issues#titles)

**Review by ybiquitous — APPROVED** [review]
@jeddy3 Thanks for making the title and changelog much simpler! 👍🏼
