### PR TITLE
Run rules for each root of document

### LINKED ISSUE #3862: Fix false positives for styled-components in no-descending-specificity
> Clearly describe the bug

False positives for `no-descending-specificity` in Styled Components. The rule looks into two different components which is not correct. Every styled component should be treated as a separate file if we speak in CSS terms. `Link` and `LinkIcon` are two different components, and stylelint can't know if their rules collapse or not.

This is most likely has to do with how `postcss-styled` parses a file.

Test repository: https://github.com/hudochenkov/styled-component-stylelint-bugs/tree/master/false-positive-no-descending-specificity

> Which rule, if any, is the bug related to?

`no-descending-specificity`

> What CSS is needed to reproduce the bug?

```js
import styled from 'styled-components';
import { NavLink } from 'react-router-dom';

export const Link = styled(NavLink)`
  font-size: 15px;
  font-weight: 700;

  &:hover,
  &.active {
    color: red;

    svg {
      fill: red;
    }
  }
`;

export const LinkIcon = styled.div`
  flex: none;

  svg {
    width: 15px;
    height: 15px;
  }
`;

```

> What stylelint configuration is needed to reproduce the bug?

```json
{
    "extends": ["stylelint-config-recommended", "stylelint-config-styled-components"]
}
```

> Which version of stylelint are you using?

`9.9.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint "**/*.styled.js" --syntax styled`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to styled components.

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged:

```shell
Sidebar.styled.js
 21:3  ✖  Expected selector "svg" to come before selector "&:hover svg"    no-descending-specificity
 21:3  ✖  Expected selector "svg" to come before selector "&.active svg"   no-descending-specificity
```

### PR DESCRIPTION
**Pull request by gucong3000**
> Which issue, if any, is this issue related to?

Closes #3862 #3863

> Is there anything in the PR that needs further explanation?

"No, it's self explanatory."

### CODE REVIEW

**Comment by jeddy3** [comment]
> -   Fixed: `no-descending-specificity` false positives for styled-components ([#3875](https://github.com/stylelint/stylelint/pull/3875)).
> -   Fixed: `no-duplicate-selectors` false positives for styled-components ([#3875](https://github.com/stylelint/stylelint/pull/3875)).

**Comment by vladfaust** [comment]
Thank you! :heart:

File: lib/rules/no-empty-source/index.js [hunk 1]
```diff
@@ -11,25 +10,25 @@ const messages = ruleMessages(ruleName, {
...
-        return;
-      }
-
-      report({
-        message: messages.rejected,
-        node: root,
-        result,
-        ruleName
-      });
+    const rootString = context.fix ? root.toString() : root.source.input.css;
```
Comment (Mouvedia) [inline lib/rules/no-empty-source/index.js:21]: @jeddy3 do you remember why you had to use `context.fix` here?
