### PR TITLE
Fix `declaration-block-no-redundant-longhand-properties` autofix for `transition`

### LINKED ISSUE #6812: Fix `declaration-block-no-redundant-longhand-properties` autofix for `transition`
### What steps are needed to reproduce the bug?

Given code like:
```css
a {
  transition-delay: 500ms;
  transition-duration: 250ms;
  transition-timing-function: ease-in-out;
  transition-property: transform, visibility;
}
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "declaration-block-no-redundant-longhand-properties": true
  }
}
```

### How did you run Stylelint?

https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdilAXATkpgM4CWupEmAtLADZICe8KArAAzsC2xA3FjgJEyFKrQCuhUZhYAmDj37Y8hEuUo0KXUpgDm1AGbjMYaSxhJiMajuoRxuJYNUiN1AA74I7mPlzMVYQMIfC4AGhQAN1IyACNSOnJGJQBfEDCQAwSYADkkLjhEGAAPfPc6GAA6MGJidPAqLN0EEAxldBAS3BhMKGIOlgBtARwUDuJ-CsTMXGpITCbqCaIoJHwoDpGAXSw0jPmmgDEQriRcFoArYip62Hc6xDacccmYadwBsZAGbomOsJGL0YUx0swOpH0y16aw2CC+PxgfxAuxAKSAA

### Which version of Stylelint are you using?

`15.6.0`

### What did you expect to happen?

No problems to be reported, or, if a `declaration-block-no-redundant-longhand-properties` error is reported, the autofix should be 
```css
a {
  transition: transform 250ms ease-in-out 500ms, visibility 250ms ease-in-out 500ms;
}
```

### What actually happened?

An error of `Expected shorthand property "transition"` with an incorrect suggested autofix of:

```css
a {
  transition: transform, visibility 250ms ease-in-out 500ms;
}
```

### Does the bug relate to non-standard syntax?

No

### Proposal to fix the bug

IMO, this error shouldn't be reported at all for transitions with multiple properties (as reported in https://github.com/stylelint/stylelint/issues/4074), but if it is considered an error, then the autofix at least needs to be changed.

### PR DESCRIPTION
**Pull request by mattxwang**
> Which issue, if any, is this issue related to?

Closes #6812.

> Is there anything in the PR that needs further explanation?

This one required some non-trivial CSS spec reading, hence the complicated-ish behaviour!

### CODE REVIEW

**Review by ybiquitous — CHANGES_REQUESTED** [review]
@mattxwang Thanks for the pull request! Please consider addressing my reviews (mainly refactoring).

File: lib/rules/declaration-block-no-redundant-longhand-properties/index.js [hunk 1]
```diff
@@ -47,6 +47,39 @@ const customResolvers = new Map([
...
+
+			if (!(delays && durations && timingFunctions && properties)) return;
+
+			// none, inherit and initial are not permitted as items of lists with more than one identifier
+			// see spec: https://w3c.github.io/csswg-drafts/css-transitions/#transition-property-property
+			if (
+				properties.length > 1 &&
+				('none' in properties || 'inherit' in properties || 'initial' in properties)
+			)
+				return;
```
[the remark this answers is not in the document]
Comment (mattxwang) [reply lib/rules/declaration-block-no-redundant-longhand-properties/index.js]: Ah! Great timing, I had just realized this independently of you submitting the review (got sidetracked while writing this up). I added a test case for the unpermitted keyword (this is a dupe of a previous change I made for this autofix), as well as one for `none`.

**Comment by mattxwang** [comment]
So sorry for the rushed PR, I got sidetracked (in-person) in the middle of finishing it up - meant to mark it as draft 😅 . Hopefully it wasn't too frustrating to review!

I think I've addressed all of the comments (and slightly changed my approach re: the `none` special case, after re-reading the spec). Let me know what you think!

File: lib/rules/declaration-block-no-redundant-longhand-properties/index.js [hunk 2]
```diff
@@ -47,6 +47,43 @@ const customResolvers = new Map([
...
+				input
+					.split(',')
+					.map((s) => s.trim())
+					.filter((s) => s.length > 0);
+			const delays = commaSeparated(decls.get('transition-delay')?.value);
+			const durations = commaSeparated(decls.get('transition-duration')?.value);
+			const timingFunctions = commaSeparated(decls.get('transition-timing-function')?.value);
+			const properties = commaSeparated(decls.get('transition-property')?.value);
+
+			if (!(delays.length && durations.length && timingFunctions.length && properties.length)) {
```
Comment (mattxwang) [inline lib/rules/declaration-block-no-redundant-longhand-properties/index.js:64]: I'm unsure of how to write a test here that isn't invalid syntax (one of the properties would have to be empty) - any thoughts?

Comment (ybiquitous) [reply lib/rules/declaration-block-no-redundant-longhand-properties/index.js:64]: How about specifying an empty declaration value (`transition-delay`) like this?

```css
a { transition-delay: ; transition-duration: 0.1s; transition-timing-function: ease; transition-property: top; }
```

Comment (mattxwang) [reply lib/rules/declaration-block-no-redundant-longhand-properties/index.js:64]: Thanks for the suggestion! Hm, this seems like invalid CSS to me (though I could be wrong) - would that still make it a good test case?

Comment (ybiquitous) [reply lib/rules/declaration-block-no-redundant-longhand-properties/index.js:64]: Surely that CSS seems invalid, but PostCSS can parse it as having an empty value. See the example below:

```js
require("postcss").parse("a { color: ; }")
  .walkDecls(({ prop, value }) => console.log({ prop, value }));
//=> { prop: 'color', value: '' }
```

Adding such a case seems to make sense.

Comment (mattxwang) [reply lib/rules/declaration-block-no-redundant-longhand-properties/index.js:64]: Gotcha; I'm still a bit confused how to proceed, since that case wouldn't be fixable (or in other words, what would I put in `fixed`), but in that case it seems to break the test infrastructure. 

Alternatively, I could extract this out as a utility and have more rigorous tests for the custom resolvers themselves - what do you think?

Comment (ybiquitous) [reply lib/rules/declaration-block-no-redundant-longhand-properties/index.js:64]: How about specifying `unfixable: true` like this?

```js
{
	code: 'a { transition-delay: ; transition-duration: 1s; transition-timing-function: ease; transition-property: top; }',
	unfixable: true,
	message: messages.expected('transition'),
},
```

**Review by ybiquitous — APPROVED** [review]
Thank you! LGTM 👍🏼
