### PR TITLE
Fix `no-invalid-position-declaration` false positives for `@mixin` and `@scope`

### LINKED ISSUE #9119: Case where [no-invalid-position-declaration] rule is not working
### What minimal example or steps are needed to reproduce the bug?

Getting an [**no-invalid-position-declaration error**](https://stylelint.io/user-guide/rules/no-invalid-position-declaration/) for following mixin:

```scss
@mixin text-smart-justification($justify: true) {
  max-inline-size: var(--text-max-inline-size);
  text-align: left;

  @if $justify {
    text-align: justify;
    text-align-last: left;
    hyphens: auto;
    hyphenate-limit-chars: 6 3 3;
    hyphenate-limit-lines: 2;

    @supports (text-wrap: pretty) {
      text-wrap: pretty; // stylelint-disable-line no-invalid-position-declaration
    }
  }
}
```

Image

### What minimal configuration is needed to reproduce the bug?

```json
{
  "no-invalid-position-declaration": true
}
```

### How did you run Stylelint?

`npx stylelint --allow-empty-input --fix --report-needless-disables '**/*.{css,scss}'`

### Which Stylelint-related dependencies are you using?

- stylelint `17.4.0`
- stylelint-config-recommended-scss `17.0.0`
- stylelint-order `7.0.1`

### What did you expect to happen?

The code is valid and should not output an error.

### What actually happened?

**Unexpected invalid position declaration** ([no-invalid-position-declaration](https://stylelint.io/user-guide/rules/no-invalid-position-declaration))

### Do you have a proposal to fix the bug?

_No response_

### PR DESCRIPTION
**Pull request by ragini-pandey**
Closes #9119

## Problem

The `no-invalid-position-declaration` rule incorrectly flags declarations inside nesting-supported at-rules (like `@supports`) when those at-rules are nested inside non-standard/preprocessor at-rules (like SCSS's `@mixin`, `@if`).

For example, the following valid SCSS was producing a false positive:

```scss
@mixin text-smart-justification($justify: true) {
  @if $justify {
    @supports (text-wrap: pretty) {
      text-wrap: pretty; /* ← false positive */
    }
  }
}
```

## Root cause

When a declaration's parent is a nesting-supported at-rule (e.g., `@supports`), the rule walks up the tree using `findNodeUpToRoot` looking for a parent rule (selector) or an ignored at-rule. It walked past non-nesting-supported at-rules like `@if` and `@mixin` without recognizing them as valid contexts — even though declarations *directly* inside those at-rules are already allowed by the rule.

## Fix

Updated the `findNodeUpToRoot` predicate to also treat ancestor non-nesting-supported at-rules as valid contexts. This makes the behavior consistent: if `@mixin { color: red }` is allowed, then `@mixin { @supports (...) { color: red } }` should also be allowed.

## Testing

- Added two accept test cases for declarations inside `@supports`/`@media` nested inside non-standard at-rules
- Updated `ignoreAtRules` reject tests to reflect the corrected behavior
- All 43 tests pass

### CODE REVIEW

**Review by romainmenke — COMMENTED** [review]
Hi @ragini-pandey,

Thank you for working on this issue.

-----

I am unsure how best to fix this.
Consider this [Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcID0AqABAZwC4EMB2UOATlGvqRgBYQCuANqTnXWgEYxoBuTAllPGhRIAOngACGSAAcOACgB0AMwgQAlGmCi0aSHQhEBRGFADcogL6jRYgLY8AHjzxoAtC+URZ6zc50Q9BmhGphZW4naOzm4eXhpaaBI0UlL6WBhosrr68MHe8dpZgcFmvpZ4ZaKoaHgQeC7Y5MT8giLiPIoZ0Sp5voWGxiUVbR2yXWpxvonJqemZ-tm5E9oF80UD8WVDYjV1DQRN9VgAnnQwLkT0HD7aYu2d7t1Ly31B66WheNY7h40khydnC6nJ63EZjHrLBIYJIpIhpDJ9RbXSF+AL9EK+bRlLEfSroJzcOh8ARCUQvYphMQAaxgR0URBwNhg6WR5IGaCqWEoPHSVFoDDQMCIRH0ABo2DQsGgoBBmXgAORYAD8LVx4hpdIZTJZ8VB9w8EOeq3RJg56C5PMw1HopCFIqI4tYkulsowCuVqve5UpGvpjOZILuowe42RN2h0zhs0RxkNkLZGMh2LQmxAopAih4pwAcv6ECAYPZGVJTvIwBgMGnwLVMwBzfOF2FS2CKHD0KXIoHMgRhtDCEA1FwE3hQFwpDA8LA8WouWBgOjEHBT2r9gRYC4cDYWEpVyB4OsAMX0NiX+ewAKJeCwZZrPFr8hsACtK+nYFJK4hkf3z6dL1hV32IALlgzL-mm8Tfscv5OFgLh7nWPz7CQAH9sBoH9h8IDmEAA)

```css
/* standard and should all be valid: */
@scope (.foo) {
  color: red;
}

@mixin --foo() {
  color: red;
}

@mixin --foo() {
  @supports (color:red) {
    color: red;
  }
}

/* non-standard: */
@if (--foo) {
  color: red;
}

@if (--foo) {
  @supports (color:red) {
    color: red;
  }
}

@non-standard-style-rule {
  @if (--foo) {
    color: red;
  }
}

@non-standard-style-rule {
  @if (--foo) {
    @supports (color:red) {
      color: red;
    }
  }
}

/* invalid: */
color: red;

@keyframes {
  color: red; /* this should error, but doesn't? */
}

@keyframes {
  @if (--foo) {
    color: red; /* this should error, but doesn't? */
  }
}

@keyframes {
  @if (--foo) {
    @supports (color:red) {
      color: red;
    }
  }
}
```

_Note how even some invalid positions aren't reported, like in `@keyframes`, you can ignore this, we can tackle that in a separate issue._

If we apply these examples to the proposed fix we get this [Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcID0AqABAZwC4EMB2UOATlGvqRgBYQCuANqTnXWgEYxoBuTAllPGhRIAOngACGSAAcOACgB0AMwgQAlGmCi0aSHQhEBRGFADcogL6jRYgLY8AHjzxoAtC+URZ6zc50Q9BmhGphZW4naOzm4eXhpaaBI0UlL6WBhosrr68MHe8dpZgcFmvpZ4ZaKoaHgQeC7Y5MT8giLiPIoZ0Sp5voWGxiUVbR2yXWpxvonJqemZ-tm5E9oF80UD8WVDYjV1DQRN9VgAnnQwLkT0HD7aYu2d7t1Ly31B66WheNY7h40khydnC6nJ63EZjHrLBIYJIpIhpDJ9RbXSF+AL9EK+bRlLEfSroJzcOh8ARCUQvYphMQAaxgR0URBwNhg6WR5IGaCqWEoPHSVFoDDQMCIRH0ABo2DQsGgoBBmXgAORYAD8LVx4hpdIZTJZ8VB9w8EOeq3RJg56C5PMw1HopCFIqI4tYkulsowCuVqve5UpGvpjOZILuowe42RN2h0zhs0RxkNkLZGMh2LQmxAopAih4pwAcv6ECAYPZGVJTvIwBgMGnwLVMwBzfOF2FS2CKHD0KXIoHMgRhtDCEA1FwE3hQFwpDA8LA8WouWBgOjEHBT2r9gRYC4cDYWEpVyB4OsAMX0NiX+ewAKJeCwZZrPFr8hsACtK+nYFJK4hkf3z6dL1hV32ICUFgWDvvASBIFIVL3lIRDyHgMAAO5ID+MB-mIABMUAYTAWEAGz9qK8Tfscv5OFgLh7nWPz7CQAH9guWDMv+IAWCA5hAA).
This now has some false negatives.

-----

Maybe better if we instead consider `@scope` and `@mixin` to be equivalent to rules?
Both are specified as allowing declarations.

- mixins: https://drafts.csswg.org/css-mixins/#mixin-rule
- scope: https://drafts.csswg.org/css-cascade-6/#scoped-declarations

So instead of checking for something like this: `(isAtRule(node) && !nestingSupportedAtKeywords.has(node.name.toLowerCase()))`

We could instead change each instance of `isRule(node)` to `(isRule(node) || (isAtRule(node) && declarationContainingAtRules.has(node.name.toLowerCase())))`

Where `declarationContainingAtRules` is a set of `mixin` and `scope`.

(The `declarationContainingAtRules` maybe needs some bikeshedding) 

------

I am unsure how best to fix this because the original issue was specifically about non-standard CSS, which we don't support. `@mixin` just so happens to also be a standard rule that is currently being worked on in browsers. So we can fix the original issue while staying within the bounds of standard CSS. However we should then update the issue and PR description to something like:
> Fix ano-invalid-position-declaration` false positives for `@mixin` and `@scope`

But I don't think we can avoid false positives in this rule for non-standard at rules.
For non-standard CSS users should instead use the `ignoreAtRules` plugin option. ([Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcID0AqABAOwhgtAZwBcBDDKIgJynjRSQB0MABASwDM0AKHHViCASjTAGaNJAA2EctXIwoAbgYBfBgxbsuPPoOEZRjPAFcADsakE8nCVPiyoOkaLERJ0tHcV60KjD5AAaEFZmcRgAOSIAWzhEGAAPKONQgDowPDwA8GxggHMEEHizcgI0WFYiQ3ES3VFySpg8ahqnOhAsHGYMADcicWYoHDM8ZgJmbBxYMHEKIlHsVuoAbQI6mH8hNGYcrFkAQQIAJXrGtFa2Vu8AXVOvHyVPTMgMXIAxKUjZ-MIAT1C+jAIqWyW2SkQAVhlArBjBlEM1Wj8-p0CAtTiBpgQGiiAo4EQRfjB-gQcE9cvhiKQKFBUa0MVjWsoGCAlEA))

What do you think?

File: lib/rules/no-invalid-position-declaration/__tests__/index.mjs [hunk 1]
```diff
@@ -370,20 +398,13 @@ testRule({
...
+			code: '@media all { color: red; }',
 			message: messages.rejected,
 			line: 1,
-			column: 23,
+			column: 14,
 			endLine: 1,
-			endColumn: 34,
+			endColumn: 25,
+			description: 'declaration directly in nesting-supported at-rule',
 		},
```
Comment (romainmenke) [inline lib/rules/no-invalid-position-declaration/__tests__/index.mjs:424]: Should we keep the previous tests?

```js
	reject: [
		{
			code: '@foo { @media all { color: red; } }',
			message: messages.rejected,
			line: 1,
			column: 21,
			endLine: 1,
			endColumn: 32,
		},
		{
			code: '@--bar { @media all { color: red; } }',
			message: messages.rejected,
			line: 1,
			column: 23,
			endLine: 1,
			endColumn: 34,
		},
		{
			code: '@media all { color: red; }',
			message: messages.rejected,
			line: 1,
			column: 14,
			endLine: 1,
			endColumn: 25,
			description: 'declaration directly in nesting-supported at-rule',
		},
	],
```

File: lib/reference/atKeywords.mjs [hunk 2]
```diff
@@ -17,6 +17,14 @@ export const nestingSupportedAtKeywords = new Set([
 	'supports',
 ]);
 
+/**
+ * At-rules that are specified as allowing declarations directly within them.
+ * @see https://drafts.csswg.org/css-mixins/#mixin-rule
+ * @see https://drafts.csswg.org/css-cascade-6/#scoped-declarations
+ * @type {ReadonlySet<string>}
+ */
+export const declarationContainingAtRules = new Set(['mixin', 'scope']);
```
Comment (romainmenke) [inline lib/reference/atKeywords.mjs]:
```suggestion
export const declarationContainingAtKeywords = new Set(['mixin', 'scope']);
```

To match the other instances in this file.

**Review by romainmenke — COMMENTED** [review]
Thank you for the changes @ragini-pandey,
I've left a few more notes, please take a look when you have time.

File: lib/rules/no-invalid-position-declaration/__tests__/index.mjs (hunk 1 above)
Comment (ragini-pandey) [reply lib/rules/no-invalid-position-declaration/__tests__/index.mjs:424]: Yes, you are right! I have restored all three reject tests (`@foo`, `@--bar`, and `@media all`) in the `ignoreAtRules` section. They should indeed still reject since `@foo` does not match the configured patterns and `@--bar` does not match `/^--bar-/` (missing trailing dash). Thanks for catching this!

File: lib/rules/no-invalid-position-declaration/__tests__/index.mjs [hunk 3]
```diff
@@ -55,6 +55,22 @@ testRule({
 				}
 			`,
 		},
+		{
+			code: stripIndent`
+				@mixin foo {
```
Comment (jeddy3) [inline lib/rules/no-invalid-position-declaration/__tests__/index.mjs]:
```suggestion
				@mixin --foo() {
```

See https://drafts.csswg.org/css-mixins/#mixin-prelude

File: lib/rules/no-invalid-position-declaration/__tests__/index.mjs [hunk 4]
```diff
@@ -73,6 +89,26 @@ testRule({
...
```
Comment (jeddy3) [inline lib/rules/no-invalid-position-declaration/__tests__/index.mjs]:
```suggestion
				@mixin --foo() {
```

File: lib/rules/no-invalid-position-declaration/index.mjs [hunk 5]
```diff
@@ -41,6 +44,11 @@ const rule = (primary, secondaryOptions) => {
 		const isIgnoredAtRule = (node) =>
 			isAtRule(node) && optionsMatches(secondaryOptions, 'ignoreAtRules', node.name);
 
+		/** @type {(node: import('postcss').Node) => boolean} */
+		const isRuleOrDeclarationContainingAtRule = (node) =>
+			isRule(node) ||
+			(isAtRule(node) && declarationContainingAtKeywords.has(node.name.toLowerCase()));
```
Comment (ybiquitous) [inline lib/rules/no-invalid-position-declaration/index.mjs]: [suggestion] What if we could simply move out `isRule(node) ||` and `RuleOr` (from the function name)?

```suggestion
		const isDeclarationContainingAtRule = (node) =>
			(isAtRule(node) && declarationContainingAtKeywords.has(node.name.toLowerCase()));
```

So that we could easily recognize this bug fix as an extension against the existing code:

```diff
-if (isRule(parent)) return;
+if (isRule(parent) || isDeclarationContainingAtRule(parent)) return;
```

```diff
-(node) => isRule(node) || isIgnoredAtRule(node),
+(node) => isRule(node) || isDeclarationContainingAtRule(node) || isIgnoredAtRule(node),
```
