### PR TITLE
Fix false positives for objects in declaration-block-trailing-semicolon

### LINKED ISSUE #4650: Fix false positives for objects in declaration-block-trailing-semicolon
> Clearly describe the bug

Stylelint emits a warning when declaration-block-trailing-semicolon meets styles in jsx

> Which rule, if any, is the bug related to?

`declaration-block-trailing-semicolon`

> What code is needed to reproduce the bug?

```js
const Component = () => {
  const background = 'white'

  return <div style={{ background }}>Text</div>
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "declaration-block-trailing-semicolon": "always"
  }
}
```

> Which version of stylelint are you using?

e.g. `13.2.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to JSX

> What did you expect to happen?

no warnings

> What actually happened (e.g. what warnings or errors did you get)?

```
Expected a trailing semicolon   declaration-block-trailing-semicolon
```

I've monkeypatched this in my code through patch-package by adding 

```diff
diff --git a/node_modules/stylelint/lib/rules/declaration-block-trailing-semicolon/index.js b/node_modules/stylelint/lib/rules/declaration-block-trailing-semicolon/index.js
index 890dd96..052e43c 100644
--- a/node_modules/stylelint/lib/rules/declaration-block-trailing-semicolon/index.js
+++ b/node_modules/stylelint/lib/rules/declaration-block-trailing-semicolon/index.js
@@ -40,6 +40,10 @@ function rule(expectation, _, context) {
 		});
 
 		root.walkDecls((decl) => {
+			if (decl.parent.type === 'object') {
+				return;
+			}
+
 			if (decl !== decl.parent.last) {
 				return;
 			}
```

### PR DESCRIPTION
**Pull request by srawlins**
> Which issue, if any, is this issue related to?

Fixes #4650 

> Is there anything in the PR that needs further explanation?

Yes; @jeddy3 suggests a solution in https://github.com/stylelint/stylelint/issues/4650#issuecomment-599205149 that did not work for me: `isStandardSyntaxRule` only accepts Rule nodes, but if used in `declaration-block-trailing-semicolon`, it would also be given AtRule nodes (like in the SCSS test case: `a { @foo { color: pink } }`). This complicates things further because `isStandardSyntaxRule` examines the `selector` of the Rule which it receives, and AtRule has no `selector`.

This simple solution seems to work for now.

### CODE REVIEW

File: lib/rules/declaration-block-trailing-semicolon/__tests__/index.js [hunk 1]
```diff
@@ -25,6 +25,10 @@ testRule(rule, {
 			code: 'a { color: red; &:hover { color: pink; }}',
 			description: 'nesting with first-level decl',
 		},
+		{
```
Comment (jeddy3) [inline lib/rules/declaration-block-trailing-semicolon/__tests__/index.js:28]: Let's replace these two tests with a single one at the bottom of the file that tests the problematic syntax, e.g.:

```js
testRule(rule, {
	ruleName,
	config: ['always'],
	syntax: 'css-in-js',
	fix: true,

	accept: [
		{
			code: 'const C = () => { return <a style={{ color: "red" }}></a> }',
			description: 'css-in-js object',
		},
	],

	reject: [
		{
			code: 'const C = styled.a`color: red`;',
			fixed: 'const C = styled.a`color: red;`;',
			description: 'css-in-js template literal',
			message: messages.expected,
			line: 1,
			column: 29,
		},
	],
});
```

So that [we're consistent with the conventions](https://stylelint.io/developer-guide/rules#write-tests):

> You should:
> - use standard CSS syntax by default, and only swap parsers when testing a specific piece of non-standard syntax

I think this will also highlight that template literals are incorrectly excluded by the proposed fix.

File: lib/rules/declaration-block-trailing-semicolon/index.js [hunk 2]
```diff
@@ -42,6 +42,10 @@ function rule(expectation, _, context) {
 		});
 
 		root.walkDecls((decl) => {
+			if (decl.parent.type !== 'rule' && decl.parent.type !== 'atrule') {
```
Comment (jeddy3) [inline lib/rules/declaration-block-trailing-semicolon/index.js:45]: I think we should use:

```js
if (decl.parent.type === 'object') return;
```

As not to exclude template literals, e.g.:

```js
const C = styled.a`color: red;`;
```

File: lib/rules/declaration-block-trailing-semicolon/__tests__/index.js (hunk 1 above)
Comment (jeddy3) [reply lib/rules/declaration-block-trailing-semicolon/__tests__/index.js:28]: I've updated the snippet above to use the new `testRule` signature because we now dogfood our Jest preset for testing rules (https://github.com/stylelint/stylelint/pull/4758).

File: lib/rules/declaration-block-trailing-semicolon/index.js (hunk 2 above)
Comment (srawlins) [reply lib/rules/declaration-block-trailing-semicolon/index.js]: Done

File: lib/rules/declaration-block-trailing-semicolon/__tests__/index.js (hunk 1 above)
Comment (srawlins) [reply lib/rules/declaration-block-trailing-semicolon/__tests__/index.js]: Ah, very nice. Thanks much!

**Comment by jeddy3** [comment]
Changelog entry:

> - Fixed: `declaration-block-trailing-semicolon` false positives for CSS-in-JS object notation ([#4749](https://github.com/stylelint/stylelint/pull/4749)).
