### PR TITLE
Fix `*-case|*-unknown` false positives for CSS-in-JS template literals

### LINKED ISSUE #6659: Fix `*-case|*-unknown` false positives for CSS-in-JS template literals
### What steps are needed to reproduce the bug?

It seems that rule `function-no-unknown` is triggering a false positive when functions are called within an anonymous function

```
import styled from "styled-components"

function getColor() {
  return "red"
}

const Foo = styled.div`
  color: ${() => getColor()}; // Unexpected unknown function "getColor"
`

const Bar = styled.div`
  color: ${getColor()}; // OK
`
```

### What Stylelint configuration is needed to reproduce the bug?

```
module.exports = {
  extends: [
    "stylelint-config-standard",
  ],
  rules: {},
  customSyntax: "postcss-styled-syntax",
}
```

### How did you run Stylelint?

`stylelint \"./src/**/*.tsx\"`

### Which version of Stylelint are you using?

`15.1.0`

```
"postcss-styled-syntax": "0.3.1",
"stylelint": "15.1.0",
"stylelint-config-standard": "30.0.1"
```

### What did you expect to happen?

It should not report `Unexpected unknown function "getColor"` since we are inside a literal expression

### What actually happened?

```
✖  Unexpected unknown function "getColor"  function-no-unknown
```

### Does the bug relate to non-standard syntax?

yes, css-in-js

### Proposal to fix the bug

_No response_

### PR DESCRIPTION
**Pull request by hudochenkov**
> Which issue, if any, is this issue related to?

Fixes #6659.

> Is there anything in the PR that needs further explanation?

All rules has same issues: trying to lint non-standard value. Based on test one rule (`unit-no-unknown`) has a “regression”. Since the fix ignores declaration with non-standard values. It means that previous linted declaration with dollar-variables are now ignored as well. Given focus of Stylelint on standard CSS only, and policy to ignore non-standard syntax, I consider this “regression” acceptable as it doesn't break builds or report new violation.

### CODE REVIEW

File: lib/rules/annotation-no-unknown/index.js [hunk 1]
```diff
@@ -45,6 +46,10 @@ const rule = (primary, secondaryOptions) => {
 		 * @param {import('postcss').Declaration} decl
 		 */
 		function checkStatement(decl) {
+			if (!isStandardSyntaxValue(decl.value)) {
+				return;
+			}
```
Comment (jeddy3) [inline lib/rules/annotation-no-unknown/index.js:51]:
```suggestion
			if (!isStandardSyntaxValue(decl.value)) return;
```

File: .changeset/five-waves-relax.md [hunk 2]
```diff
@@ -0,0 +1,9 @@
+---
+"stylelint": patch
+---
+
+Fixed: `annotation-no-unknown` false positives in CSS-in-JS syntax
+Fixed: `function-name-case` false positives in CSS-in-JS syntax
+Fixed: `function-no-unknown` false positives in CSS-in-JS syntax
+Fixed: `unit-no-unknown` false positives in CSS-in-JS syntax
+Fixed: `value-keyword-case` false positives in CSS-in-JS syntax
```
Comment (jeddy3) [inline .changeset/five-waves-relax.md:9]:
```suggestion
Fixed: `*-case|*-unknown` false positives for CSS-in-JS template literals
```

File: lib/rules/function-name-case/index.js [hunk 3]
```diff
@@ -53,6 +54,10 @@ const rule = (primary, secondaryOptions, context) => {
 		}
 
 		root.walkDecls((decl) => {
+			if (!isStandardSyntaxValue(decl.value)) {
+				return;
+			}
```
Comment (jeddy3) [inline lib/rules/function-name-case/index.js:59]:
```suggestion
			if (!isStandardSyntaxValue(decl.value)) return;
```

File: lib/rules/function-no-unknown/index.js [hunk 4]
```diff
@@ -57,6 +58,10 @@ const rule = (primary, secondaryOptions) => {
 		root.walkDecls((decl) => {
 			const { value } = decl;
 
+			if (!isStandardSyntaxValue(value)) {
+				return;
+			}
```
Comment (jeddy3) [inline lib/rules/function-no-unknown/index.js:63]:
```suggestion
			if (!isStandardSyntaxValue(value)) return;
```

File: lib/rules/unit-no-unknown/index.js [hunk 5]
```diff
@@ -158,7 +159,7 @@ const rule = (primary, secondaryOptions) => {
 			check(atRule, atRule.params, atRuleParamIndex);
 		});
 		root.walkDecls((decl) => {
-			if (!isStandardSyntaxDeclaration(decl)) {
+			if (!isStandardSyntaxDeclaration(decl) || !isStandardSyntaxValue(decl.value)) {
 				return;
 			}
```
Comment (jeddy3) [inline lib/rules/unit-no-unknown/index.js:164]:
```suggestion
			if (!isStandardSyntaxDeclaration(decl)) return;
			
			if (!isStandardSyntaxValue(decl.value)) return;
```

File: lib/rules/value-keyword-case/index.js [hunk 6]
```diff
@@ -79,6 +79,10 @@ const rule = (primary, secondaryOptions, context) => {
 			const propLowerCase = decl.prop.toLowerCase();
 			const value = decl.value;
 
+			if (!isStandardSyntaxValue(value)) {
+				return;
+			}
```
Comment (jeddy3) [inline lib/rules/value-keyword-case/index.js:84]:
```suggestion
			if (!isStandardSyntaxValue(value)) return;
```

**Review by jeddy3 — CHANGES_REQUESTED** [review]
Thank you! Just some minor nits, otherwise LGTM.

(We're adopting a shorthand for early returns as we often use them in rules.)

> Given focus of Stylelint on standard CSS only, and policy to ignore non-standard syntax, I consider this “regression” acceptable as it doesn't break builds or report new violation.

SGTM.

File: .changeset/five-waves-relax.md (hunk 2 above)
Comment (hudochenkov) [reply .changeset/five-waves-relax.md:9]: I think this would be confusing to users. I would understand proposed line as if _all_ rules matching the pattern would have fixed false positives. I fixed only rules that I personally had issues with. I don't know about other rules.

**Comment by hudochenkov** [comment]
OMG! Check out this PR number: 6666! :)

File: .changeset/five-waves-relax.md (hunk 2 above)
Comment (jeddy3) [reply .changeset/five-waves-relax.md:9]: > I fixed only rules that I personally had issues with. I don't know about other rules.

Oh, I didn't clock that. Makes sense. I've updated the suggestion.

**Comment by jeddy3** [comment]
> OMG! Check out this PR number: 6666! :)

Ha, I noticed it too. Nice! It will be another 1111 issues/prs before we see a sequence like that again.

**Review by jeddy3 — APPROVED** [review]
LGTM, thank you.

**Review by ybiquitous — APPROVED** [review]
Thank you. LGTM 👍🏼
