### PR TITLE
Ignore non-standard syntax in function-calc-no-invalid

### LINKED ISSUE #4114: Fix false positives for variables in function-calc-no-invalid
There are false positives for less and scss variables containing `-`

> Which rule, if any, is the bug related to?

`function-calc-no-invalid`

> What CSS is needed to reproduce the bug?

for less

```css
.foo {
	height: calc(100% - (@a-height + @b-margin-top));
}
```
for scss
```css
.foo {
	height: calc(100% - ($a-height + $b-margin-top));
}
```

> What stylelint configuration is needed to reproduce the bug?
```json
{
  "rules": {
    "function-calc-no-invalid": true
  }
}
```

> Which version of stylelint are you using?

`10.1.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint file.less --config myconfig.json`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to less and scss variables

> What did you expect to happen?

No warnings to be flagged

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged (for less case), a pair of issues per dash in a variable name

```shell
 2:25  ✖  Expected space before "-" operator   function-calc-no-invalid
 2:26  ✖  Expected space after "-" operator    function-calc-no-invalid
 2:37  ✖  Expected space before "-" operator   function-calc-no-invalid
 2:38  ✖  Expected space after "-" operator    function-calc-no-invalid
 2:44  ✖  Expected space before "-" operator   function-calc-no-invalid
 2:45  ✖  Expected space after "-" operator    function-calc-no-invalid
```

There was a bug fix done (#3908) to fix variables inside interpolation for both less and scss, but for simple variable there are still FPs. Note that for scss as soon as I wrap variables inside interpolation, issues disappear :
```
.foo {
	height: calc(100% - (#{$a-height} + #{$b-margin-top}));
}
```

### PR DESCRIPTION
**Pull request by hudochenkov**
> Which issue, if any, is this issue related to?

Fixes #4114, #4533.
Closes #4534.

> Is there anything in the PR that needs further explanation?

@jeddy3 [said](https://github.com/stylelint/stylelint/issues/4114#issuecomment-573375622):

> Built-in rules ignore non-standard syntax. This rule should only check the validity of `calc` functions containing standard CSS syntax.

To be honest, I don't think this is a good approach for users. `function-calc-no-invalid` catches many cases of invalid `calc` for preprocessor users. But with this PR, we reduce usefulness of this rule for these users.

### CODE REVIEW

File: lib/utils/isStandardSyntaxMathFunction.js [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+		return false;
+	}
+
+	// Less variable
+	if (mathFunction.includes('@')) {
+		return false;
+	}
+
+	return true;
+};
```
Comment (evilebottnawi) [inline lib/utils/isStandardSyntaxMathFunction.js]: What about interpolation SCSS `#{var}`?

Comment (hudochenkov) [reply lib/utils/isStandardSyntaxMathFunction.js]: Isn't it `#{$var}`?

Comment (evilebottnawi) [reply lib/utils/isStandardSyntaxMathFunction.js]: Oh, yes, what about `$` and `@` in css variable name, can these characters used?

Comment (hudochenkov) [reply lib/utils/isStandardSyntaxMathFunction.js]: I couldn't get straight answer from the spec. But I tried in Chrome putting these symbols in different position in the custom property name, and all were invalid.

Comment (evilebottnawi) [reply lib/utils/isStandardSyntaxMathFunction.js]: Sounds good, approved

**Comment by hudochenkov** [comment]
> The community can create a scss/function-calc-no-invalid plugin (and a less/function-calc-no-invalid one etc). Each would cater to the more specific syntax of their respective languages.

True. Also, there are pieces of code after that PR, that handle most of use cases of variables and interpolations. I don't know where they are, but now it's a dead code. And this is the case most likely with every rule, where we started ignoring non-standard syntax.

**Comment by jeddy3** [comment]
> - Fixed: `function-calc-no-invalid` false positives for SCSS and Less variables ([#4659](https://github.com/stylelint/stylelint/pull/4659)).

**Comment by jonscottclark** [comment]
Thanks everyone involved for your contributions on this :)
