### PR TITLE
Fix `selector-no-qualifying-type` false positives for `:has()`

### LINKED ISSUE #9103: Fix `selector-no-qualifying-type` false positives for `:has()`
### What minimal example or steps are needed to reproduce the bug?

```css
.form-field:has(input:disabled) {
    color: gray;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "selector-no-qualifying-type": true
  }
}
```

### How did you run Stylelint?

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0AzCAnAtgWhQSxgBsp4ALAQwGcAKPAOwAcBXAF3ij0vICNCYoAlAAJgAHTpDJQyIQzwhAc3TkAngG5xAXxAAaEPj4A5cpjiIYADxMM+SMJUq7wEOvgUIQlhhhZDYKciZCXzEJIXQgmEp5UKkhAHJKIhgwFgxsOghsAEcmckI8FBV6BWwWFQYYePkWCJhxSU0dLQ06J0hXPAUAMQxMchYPSnK+AroWOxc3JEwAK0c9WAZHRFihURBhlVH6Fg35DcIBqL3dBvXNkaJd7A63bGHyOihydCh9i6OWE42tcRBNEA)

### Which Stylelint-related dependencies are you using?

```json
{
    "stylelint": "^17.3.0",
    "stylelint-config-standard-scss": "^17.0.0",
}
```

### What did you expect to happen?

No error reported. `:has(input)` is not qualifying the current element. It applies a condition on *child* nodes.

### What actually happened?

This problem is reported:

```
1:17-22
    error
    Unexpected qualifying type selector "input" in ".form-field:has(input:disabled)" (selector-no-qualifying-type)
```

### Do you have a proposal to fix the bug?

_No response_

### PR DESCRIPTION
**Pull request by romainmenke**
> Which issue, if any, is this issue related to?

Closes #9103
Closes https://github.com/stylelint/stylelint/pull/9106

> Is there anything in the PR that needs further explanation?

This continues the patches contributes by @ragini-pandey in https://github.com/stylelint/stylelint/pull/9106

For examples of the cases it fixes see this commit with the original algorithm as found in #9106 : https://github.com/stylelint/stylelint/actions/runs/23617908817/job/68789988265

----

I am unsure if this change is correct and following our conventions and best practices.

The `isSelectorContainingPseudoClass` function is used in multiple locations in this rule including in `groupByCompoundSelectors`. But it isn't a generally useful utility. The definition of selector containing pseudo classes is directly tied to this rule. So I don't want to move it to our general utilities where it might cause confusion.

The same is true for `getCompoundSelectors`, it is a neat function, but I don't think it is ready to be used in other rules.

At the same time there is a need for unit tests for the `groupByCompoundSelectors` function. With our regular rule tests it is only possible to test for expected lint warnings. Validating the behavior of individual functions must always be expressed through triggered warnings.

Is it ok that I added extra files and tests in the directory of this rule?

### CODE REVIEW

File: lib/rules/selector-no-qualifying-type/isSelectorContainingPseudoClass.mjs [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+
+/**
+ * @param {unknown} node
+ * @returns {node is selectorParser.Pseudo}
+ */
+export default function isSelectorContainingPseudoClass(node) {
+	return (
+		selectorParser.isPseudoClass(node) &&
+		SELECTOR_CONTAINING_PSEUDO_CLASSES.has(node.value) &&
+		Boolean(node.nodes.length)
```
Comment (ybiquitous) [inline lib/rules/selector-no-qualifying-type/isSelectorContainingPseudoClass.mjs]: [suggestion] Very minor. You can leave it as-is.

- `length > 0` might be a bit more explicit than `Boolean()`.
- Evaluating `node.nodes.length` before `.has()` might be a bit more efficient.
- `toLowerCase()` might be necessary for more accuracy.

```suggestion
		selectorParser.isPseudoClass(node) &&
	  node.nodes.length > 0 &&
		SELECTOR_CONTAINING_PSEUDO_CLASSES.has(node.value.toLowerCase())
```

File: lib/rules/selector-no-qualifying-type/isSelectorContainingPseudoClass.mjs [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+const SELECTOR_CONTAINING_PSEUDO_CLASSES = new Set(
+	['is', 'matches', 'not', 'where', 'host'].map((s) => `:${s}`),
+);
+
+/** @import { Node, Selector } from 'postcss-selector-parser' */
+
+/**
+ * @typedef {Exclude<Node, Selector>} NonSelector
+ */
+
```
Comment (ybiquitous) [inline lib/rules/selector-no-qualifying-type/isSelectorContainingPseudoClass.mjs]: [suggestion] These types might no longer be needed.

```suggestion
```

**Comment by romainmenke** [comment]
Thank you for the reviews @ybiquitous @jeddy3 🙇
