### PR TITLE
Fix `font-family-no-missing-generic-family-keyword` false positives for `math`

### LINKED ISSUE #8436: Fix `font-family-no-missing-generic-family-keyword` false positives for `math`
### What minimal example or steps are needed to reproduce the bug?

```css
math {
	font-family: "Cambria Math", math;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
    "rules": {
        "font-family-no-missing-generic-family-keyword": true
    }
}
```

### How did you run Stylelint?

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIC2BDALgCwATADoDtc0AzCfNAWmJSQEsAbAT3i1xAGEaAjAJ1pSwBZdBjYAaLKkwBuAgF8CIMSGIMYAORpxEUjADowAZ0NLwZVQHMEIPPiysQMAB5oY+KIbYsA2gXv22QzRGehh6WnIKSHxLCiCUdxQeKDY-LABdeVNoywAxCB4pawArQzJTWAAHE0RbAJAgkLCItC8HenQYIPE0wODQ8Mic2gs4tASoJJSEds7ukCy5IA)

### Which Stylelint-related dependencies are you using?

```json
{
    "stylelint": "16.15.0"
}
```

### What did you expect to happen?

Stylelint [16.15.0](https://github.com/stylelint/stylelint/releases/tag/16.15.0) #8395 fixed #8390 `font-family-no-missing-generic-family-keyword` false positives for `math`, `emoji` and `fangsong`.

In fact, only `emoji` and `fangsong` were available, but `math` was still unavailable.

Note that if font-family contains only `math` itself, it will pass, but if it also contains other fonts, it will still report an error.

### What actually happened?

The following problems were reported:

```
math.css
 2:15   ✖  Unexpected missing generic font family (font-family-no-missing-generic-family-keyword)
```

### Do you have a proposal to fix the bug?

_No response_

### PR DESCRIPTION
**Pull request by otomad**
> Which issue, if any, is this issue related to?

Closes #8436

> Is there anything in the PR that needs further explanation?

Due to a special case `font: math math;` (the first `math` is the `font-size`, the second `math` is the `font-family`), it is not feasible to return the `math` directly in `findFontFamily`.

Currently this is done by checking in `findFontFamily` when the value is a keyword for both `font-family` and `font-size`, if its next node is a comma or it is already the last node, then treat it as a `font-family` keyword, otherwise treat it as a `font-size` keyword.

It seems that when using `css-tree`, it will not pass the invalid examples in the `findFontFamily` test, such as: `12pt/10pt Red/Black`, `12pt/10pt Hawaii 5-0`.

### CODE REVIEW

**Comment by romainmenke** [comment]
Note: 

> As it seems that there is a plan to use the ESLint's CSSTree fork (https://github.com/stylelint/stylelint/issues/8465), so I have not tried to use CSSTree to implement this purpose.

That is entirely unrelated :)
You can use the current `css-tree` dependency.
Using the fork doesn't unlock any new capabilities.

**Comment by otomad** [comment]
> That is entirely unrelated :)
> You can use the current `css-tree` dependency.
> Using the fork doesn't unlock any new capabilities.

No, current `css-tree` doesn't support `math` value for `font-size`, so `font: math math` will be invalid in current `css-tree`.

image

**Comment by romainmenke** [comment]
I meant that the current `css-tree` dependency already has all the needed capabilities.
We can add a custom syntax for this specific rule and use case.
We don't need to switch to the fork for this, right?

----

`declaration-property-value-no-unknown` is unrelated to `font-family-no-missing-generic-family-keyword` right?

**Comment by otomad** [comment]
Should I open a new issue before pull request?

> Fix `declaration-property-value-no-unknown` false positives for `math` of `font-size`

**Comment by romainmenke** [comment]
Our convention indeed is to first open an issue and then a pull request :)
Thank you

**Comment by otomad** [comment]
Oops, it seems that break `font-family-name-quotes`.

image

It seems that it is useful to specify whether the property is `font` or `font-family` in the `findFontFamily` function.

**Review by jeddy3 — APPROVED** [review]
@otomad Thank you for the pull request, and for splitting it into two.

Unless there are any objections, I think we can merge this as it fixes the issue. We can create an issue to investigate whether refactoring to use CSSTree can improve things. Someone can then pick that up if they have time.

File: lib/utils/findFontFamily.mjs [hunk 1]
```diff
@@ -76,12 +83,25 @@ export default function findFontFamily(value) {
...
 		const prevPrevNode = nodes[index - 2];
+		const allPrevNodes = nodes.slice(0, index);
+
+		// When the value is a keyword for both `font-family` and `font-size` (e.g. `math`),
+		// if its next node is a comma, or if it is already the last node, or if there is any comma before it,
+		// then treat it as a `font-family` keyword, otherwise treat it as a `font-size` keyword.
+		if (
+			fontSizeKeywords.has(valueLowerCase) &&
+			fontFamilyKeywords.has(valueLowerCase) &&
+			!(!nextNode || isCommaDiv(nextNode) || allPrevNodes.find(isCommaDiv))
```
Comment (Mouvedia) [inline lib/utils/findFontFamily.mjs:102]: minor

Can you also use `isCommaDiv` at line 118?

File: lib/utils/findFontFamily.mjs [hunk 2]
```diff
@@ -27,6 +28,12 @@ function joinValueNodes(firstNode, secondNode, charactersBetween) {
 	return firstNode;
 }
 
+/**
+ * @param {Node} valueNode
+ * @returns {valueNode is postcssValueParser.DivNode}
+ */
+const isCommaDiv = (valueNode) => valueNode.type === 'div' && valueNode.value === ',';
```
Comment (Mouvedia) [inline lib/utils/findFontFamily.mjs:35]: note

We have 3 rules that have the `foo.type === 'div' && foo.value === ','` condition.
no-duplicate-at-import-rules, declaration-block-no-redundant-longhand-properties and color-function-notation

File: lib/utils/findFontFamily.mjs (hunk 1 above)
Comment (otomad) [reply lib/utils/findFontFamily.mjs:102]: 118 is `isNonCommaDiv`.

Comment (Mouvedia) [reply lib/utils/findFontFamily.mjs:102]: `!isCommaDiv` === `isNonCommaDiv` right?

Comment (otomad) [reply lib/utils/findFontFamily.mjs:102]: `!isCommaDiv` === `isNonCommaDiv` || `isNotDiv`

Comment (Mouvedia) [reply lib/utils/findFontFamily.mjs:102]: The comment just above at line 106 doesn't state anything about `div`.
Anyway it's minor, let's move on.

File: lib/utils/findFontFamily.mjs (hunk 2 above)
Comment (jeddy3) [reply lib/utils/findFontFamily.mjs:35]: Can you open a refactor issue for this, please.

File: lib/utils/findFontFamily.mjs
Comment (ybiquitous) [inline lib/utils/findFontFamily.mjs:1]: [suggestion] For a bit of performance improvement, how about reducing the number of calls for `fontFamilyKeywords.has(valueLowerCase)`? It occurs three times in this PR:

E.g.

```diff
+		const isFontFamilyKeyword = fontFamilyKeywords.has(valueLowerCase);
+
 		// Ignore keywords for other font parts
-		if (fontShorthandKeywords.has(valueLowerCase) && !fontFamilyKeywords.has(valueLowerCase)) {
+		if (!isFontFamilyKeyword && fontShorthandKeywords.has(valueLowerCase)) {
 			return;
 		}

 		// Ignore font-sizes
 		// NOTE: `math` is a keyword for both `font-family` and `font-size`.
-		if (isValidFontSize(valueNode.value) && !fontFamilyKeywords.has(valueLowerCase)) {
+		if (!isFontFamilyKeyword && isValidFontSize(valueNode.value)) {
 			return;
 		}

// ...

		// When the value is a keyword for both `font-family` and `font-size` (e.g. `math`),
 		// if its next node is a comma, or if it is already the last node, or if there is any comma before it,
 		// then treat it as a `font-family` keyword, otherwise treat it as a `font-size` keyword.
 		if (
+			isFontFamilyKeyword &&
 			fontSizeKeywords.has(valueLowerCase) &&
-			fontFamilyKeywords.has(valueLowerCase) &&
```

File: lib/utils/findFontFamily.mjs [hunk 3]
```diff
@@ -76,12 +83,25 @@ export default function findFontFamily(value) {
...
+
+		// When the value is a keyword for both `font-family` and `font-size` (e.g. `math`),
+		// if its next node is a comma, or if it is already the last node, or if there is any comma before it,
+		// then treat it as a `font-family` keyword, otherwise treat it as a `font-size` keyword.
+		if (
+			fontSizeKeywords.has(valueLowerCase) &&
+			fontFamilyKeywords.has(valueLowerCase) &&
+			!(!nextNode || isCommaDiv(nextNode) || allPrevNodes.find(isCommaDiv))
+		)
+			return;
```
Comment (ybiquitous) [inline lib/utils/findFontFamily.mjs:104]: [suggestion] For a minor improvement for readability, how about joining each condition with `&&` like this?

```suggestion
		if (
			fontSizeKeywords.has(valueLowerCase) &&
			fontFamilyKeywords.has(valueLowerCase) &&
			nextNode &&
			!isCommaDiv(nextNode) &&
			!allPrevNodes.some(isCommaDiv)
		) {
			return;
		}
```

**Review by ybiquitous — COMMENTED** [review]
Thank you for addressing the `math` keyword for the font properties. Sounds great 👍🏼 

I've left a few minor suggestions, so could you take a look? 🙏🏼

File: lib/utils/findFontFamily.mjs (hunk 3 above)
Comment (otomad) [reply lib/utils/findFontFamily.mjs:104]: This is to match the comments above.

> if its next node is a comma, or if it is already the last node, or if there is any comma before it,
> then treat it as a `font-family` keyword, otherwise treat it as a `font-size` keyword.

This means that when `!nextNode || isCommaDiv(nextNode) || allPrevNodes.find(isCommaDiv)` is not met, it is the font-size keyword, so it is returned. This is more logical.

**Review by ybiquitous — APPROVED** [review]
LGTM 👍🏼

File: lib/utils/findFontFamily.mjs (hunk 3 above)
Comment (ybiquitous) [reply lib/utils/findFontFamily.mjs]: Make sense, let's keep it as is.
