### PR TITLE
Fix `declaration-block-no-duplicate-properties` false negatives for named colors with `ignore: ['consecutive-duplicates-with-different-syntaxes']`

### LINKED ISSUE #8535: Fix `declaration-block-no-duplicate-properties` false negatives for `ignore: ['consecutive-duplicates-with-different-syntaxes']` and `<named-color>`
### What minimal example or steps are needed to reproduce the bug?

Stylelint does not lint this.

```css
p {
 color: red;
 color:blue;
}
```

### What minimal configuration is needed to reproduce the bug?

```
{
  "extends": ["stylelint-config-standard"]
}
```

### How did you run Stylelint?

```
npx stylelint '**/*.{css,scss}'
```

### Which Stylelint-related dependencies are you using?

```
 "stylelint": "^16.18.0",

```

### What did you expect to happen?

It should have linted the second declaration.  [Also asked about it on SO](https://stackoverflow.com/questions/79563469/should-stylelint-flag-the-declaration-of-the-same-property-twice-within-a-code-b?noredirect=1#comment140314678_79563469)

### What actually happened?

It does not does not lint double declaration of color properties.

### Do you have a proposal to fix the bug?

_No response_

### PR DESCRIPTION
**Pull request by sw1tch3roo**
> Which issue, if any, is this issue related to?

Closes #8535

> Is there anything in the PR that needs further explanation?

This PR fixes a false negative where duplicate named colors were not being flagged when using `ignore: ['consecutive-duplicates-with-different-syntaxes']`.

**The Problem:**
```css
p {
    color: red;
    color: blue;
}
```

Previously, this would not trigger a warning with ignore: `['consecutive-duplicates-with-different-syntaxes']` because the rule incorrectly treated red and blue as having different syntaxes.

  **The Solution:**
  - Added logic to treat named colors (red, blue, green, etc.) as having the same syntax
  - Named colors now correctly trigger warnings even with the ignore option
  - This matches the existing behavior for other color formats like rgb() and hex colors
  - Added comprehensive tests covering various named color scenarios

  **Changes:**
  - Updated isEqualValueNodes function to identify when both values are named colors
  - Added test cases for named color duplicates
  - Fixed import sorting to follow ESLint rules

The fix ensures consistency with how other color formats are handled and prevents unintentional duplicate declarations.

### CODE REVIEW

File: lib/rules/declaration-block-no-duplicate-properties/__tests__/index.mjs
Comment (Mouvedia) [inline lib/rules/declaration-block-no-duplicate-properties/__tests__/index.mjs:1]: Here are 2 tests that currently fail:

```css
a {
	scrollbar-color: rebeccapurple green;
	scrollbar-color: rebeccapurple transparent;
}

p {
	border-color: yellow green #000 red;
	border-color: black;
}
```

**Comment by Mouvedia** [comment]
Hello @sw1tch3roo,

Thanks for your first contribution.

Check my comment above.

You should also filter out the properties using our `singleValueColorProperties` set + some exceptions—e.g. `border-color`.
i.e.
```css
p {
	animation-name: red;
	animation-name: black;
}
```

**Comment by sw1tch3roo** [comment]
Thank u for the review @Mouvedia!!

I've implemented the fix by restricting named color equivalence to only properties in the `singleValueColorProperties` set.

All the test cases you mentioned now pass correctly =)

**Comment by Mouvedia** [comment]
If the goal of the PR is to only target color properties then you have to restrict it to

1. the properties which may only have one value (which we have an existing set for)
2. **and** the ones that accept multiples values (i.e. `scrollbar-color` and `border-color`)

```css
a {
	border-color: red yellow;
	border-color: green;
}
```
won't produce an error in [the demo](https://github.com/stylelint/stylelint/pull/8665#issuecomment-3058994077); is it by design?

> [Ignore consecutive duplicated properties with different value syntaxes (type and unit of value).](https://stylelint.io/user-guide/rules/declaration-block-no-duplicate-properties/#consecutive-duplicates-with-different-syntaxes)

Is the number of values considered a different "type"?
Is it the expected behaviour?

**Comment by sw1tch3roo** [comment]
Oops! I see my mistake now.. I incorrectly removed the named color logic entirely instead of refining it to properly handle both single-value and multi-value color properties while respecting that different value counts represent different syntaxes =)

I'll work on a proper fix that maintains the named color feature but addresses the multi-value property cases you mentioned, ty again

**Comment by sw1tch3roo** [comment]
Honestly, I was a bit confused by all the edge cases at first, but after going through everything again I think we got it right now =D

After that confusion earlier, I kept the named color logic but refined it to only apply to actual color properties and respect that different value counts = different syntaxes. So
```css
a {
    border-color: red yellow;
    border-color: green;
}
```
correctly doesn't error since they have different structures

**Comment by Mouvedia** [comment]
> …correctly doesn't error since they have different structures

[As I asked before](https://github.com/stylelint/stylelint/pull/8665?notification_referrer_id=NT_kwDOAAMvsbIxNzUwMjg1NDY1MjoyMDg4MTc#issuecomment-3067343550), is that the expected behaviour?

ref
https://github.com/stylelint/stylelint/issues/6632#issuecomment-1511761204
https://github.com/stylelint/stylelint/issues/6796#issue-1672458206

In particular

> distinct keywords indicate different syntaxes

seems to indicate that it should error out?
I don't know really. @romainmenke since you are the one who requested the option, can you tell us what should be expected? If it's not obvious, we will have to change the option's description in the rule's README.

**Comment by sw1tch3roo** [comment]
> Is it the expected behaviour?

@Mouvedia yep, this is expected behavior

> Is the number of values considered a different "type"?

I think so.

So this case has different structures:
```css
a {
    border-color: red yellow;
    border-color: green;
}
```

So we treat them as different syntaxes - no error with the ignore option. Our named color logic only kicks in when values have the same structure (like `color: red; color: blue;`).

We're being smarter about it - instead of just comparing keywords, we look at the whole value syntax. This catches real duplicates while allowing legitimate fallback patterns, which is what @romainmenke wanted

**Comment by sw1tch3roo** [comment]
@Mouvedia @romainmenke guys, what do you think about the above?

File: lib/rules/declaration-block-no-duplicate-properties/index.mjs [hunk 1]
```diff
@@ -11,6 +10,10 @@ import ruleMessages from '../../utils/ruleMessages.mjs';
 import validateOptions from '../../utils/validateOptions.mjs';
 import vendor from '../../utils/vendor.mjs';
 
+import { isRegExp, isString } from '../../utils/validateTypes.mjs';
+import { colorProperties } from '../../reference/properties.mjs';
+import { namedColorsKeywords } from '../../reference/keywords.mjs';
```
Comment (jeddy3) [inline lib/rules/declaration-block-no-duplicate-properties/index.mjs]: Let's slot these into the main block of imports. They should be alphabetical (ignoring the starting brace).

**Review by jeddy3 — CHANGES_REQUESTED** [review]
Thank you for your efforts working through the edge cases of this pull request.

I've made one minor request. Otherwise, it LGTM.
