### PR TITLE
Fix invalid option warnings for strings in `*-list` 

### LINKED ISSUE #5933: Fix invalid option warning for string properties in *-list
### What steps are needed to reproduce the bug?

The config below fails in 14.5.2 (but worked in 14.5.1):
```
Invalid Option: Invalid option value "{"/^border/":"none","/^outline/":"none"}" for rule "declaration-property-value-disallowed-list"
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "declaration-property-value-disallowed-list": {
      "/^border/": "none",
      "/^outline/": "none"
    }
  }
}
```
### How did you run Stylelint?

CLI

### Which version of Stylelint are you using?

14.5.2

### What did you expect to happen?

No Invalid Option warning

### What actually happened?

Invalid Option warning

### Does the bug relate to non-standard syntax?

_No response_

### Proposal to fix the bug

_No response_

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

Closes #5933

> Is there anything in the PR that needs further explanation?

This pull request does:

- loosen up the `validateObjectWithArrayProps()` utility to accept also a single value not only an array. E.g.
    ```js
    validateObjectWithArrayProps({ foo: [1, 2], bar: 3 }) //=> true
    ```
- fix or update the undocumented behavior of all rules using `validateObjectWithArrayProps()`

### CODE REVIEW

File: lib/utils/validateObjectWithArrayProps.js [hunk 1]
```diff
@@ -3,41 +3,29 @@
...
  *
- * @template {(value: unknown) => boolean} Validator
- * @param {Validator | Validator[]} validator
- * @returns {(value: unknown) => boolean}
+ * @typedef {(value: unknown) => boolean} Validator
+ * @param {...Validator} validators
+ * @returns {Validator}
  */
-module.exports = function validateObjectWithArrayProps(validator) {
+module.exports = function validateObjectWithArrayProps(...validators) {
```
Comment (ybiquitous) [inline lib/utils/validateObjectWithArrayProps.js:21]: [note] I've changed the argument type for a more straightforward implementation. However, I think it's safe this utility has not been exposed.

**Review by jeddy3 — APPROVED** [review]
This is stellar work, thank you!

The changes to the validate utility are nice, as is the use of the new `flattenArray` utility in the rules.

What should the changelog entry be?

"Fixed: `*-list` invalid option warnings for strings"

**Comment by ybiquitous** [comment]
> "Fixed: `*-list` invalid option warnings for strings"

I agree with your idea. 👍🏼

**Comment by jeddy3** [comment]
Let's merge and I'll put out a patch release.

**Comment by ybiquitous** [comment]
Changelog updated:

> - Fixed: `*-list` invalid option warnings for strings ([#5934](https://github.com/stylelint/stylelint/pull/5934)).
