### PR TITLE
Fix stylelint config usage

### LINKED ISSUE #4479: report-invalid-scope-disables Cannot read property 'rules' of undefined
Error when running stylelint with the flag `report-invalid-scope-disables`.

```
$ stylelint 'src/**/*.scss' --report-invalid-scope-disables --config .stylelintrc.yml
TypeError: Cannot read property 'rules' of undefined
    at module.exports (./node_modules/stylelint/lib/invalidScopeDisables.js:38:47)
    at prepareReturnValue (./node_modules/stylelint/lib/standalone.js:312:39)
    at ./node_modules/stylelint/lib/standalone.js:286:11
$ stylelint --version
12.0.0
$ ls .stylelintrc.yml 
.stylelintrc.yml
```

> What stylelint configuration is needed to reproduce the bug?

```yaml
extends:
  - stylelint-config-standard
```

> Which version of stylelint are you using?

`12.0.0`

### PR DESCRIPTION
**Pull request by webschik**
There was a comment in `lib/standalone.js:312` that `stylelint._options.config` might be `undefined`, but 
`invalidScopeDisables.js` function always expected an object as 2nd parameter.

For me there were 2 ways to fix that:
* adding  a conditional expression to `stylelint._options.config  || {}` for `invalidScopeDisables` call, or
* changing`invalidScopeDisables` interface to accept `undefined` as 2nd parameter.

I've chosen 2nd option, to prevent adding more conditions in the future in we need to call `invalidScopeDisables` somewhere else with the optional config param.

Closes #4479

### CODE REVIEW

**Comment by hudochenkov** [comment]
I think test should look like this:

```js
it('invalidScopeDisables without config', () => {
	return standalone({
		config: {},
		code: 'a {}',
		ignoreDisables: true,
	}).then((linted) => {
		expect(invalidScopeDisables(linted.results)).toEqual([]);
	});
});
```

Because we want to test when config is empty, and code doesn't have any `stylelint-disable` comments. (I'm not sure about `expect` part).

**Comment by webschik** [comment]
Make sense, but then it should look like

```js
return standalone({
    config: {
        rules: {}
    },
    code: 'a {}',
    ignoreDisables: true,
}).then((linted) => {
    expect(invalidScopeDisables(linted.results)).toEqual([]);
});
```

because there is a check for `config.rules` param in `lib/augmentConfig.js:88`

File: lib/invalidScopeDisables.js [hunk 1]
```diff
@@ -6,10 +6,10 @@
 
 /**
  * @param {import('stylelint').StylelintResult[]} results
- * @param {import('stylelint').StylelintConfig} config
+ * @param {import('stylelint').StylelintConfig|undefined} config
```
Comment (hudochenkov) [inline lib/invalidScopeDisables.js]:
```suggestion
 * @param {import('stylelint').StylelintConfig} config
```

It works without `undefined`.

Comment (webschik) [reply lib/invalidScopeDisables.js]: In this case type annotation in JSDoc is not correct, it means the function accepts `config` only with `StylelintConfig` type, but it's not true. I think it's more correct to specify in type that function may accept `undefined`. Also, we can describe `config` as optional - https://jsdoc.app/tags-param.html#optional-parameters-and-default-values, but I think it's a worse approach.

Comment (hudochenkov) [reply lib/invalidScopeDisables.js]: > By default `null` and `undefined` are subtypes of all other types. That means you can assign `null` and `undefined` to something like `number`.

http://www.typescriptlang.org/docs/handbook/basic-types.html#null-and-undefined

While explicitly specifying `undefined` is correct, it's not necessary.

If you want to keep, it's ok.

**Comment by hudochenkov** [comment]
> -   Fixed: `--report-invalid-scope-disables` crash when no rules specified ([#4498](https://github.com/stylelint/stylelint/pull/4498)).
