### PR TITLE
Fix `property-no-unknown` false positives for `corner-shape`

### LINKED ISSUE #9065: Fix `property-no-unknown` false positives for `corner-shape`
### What is the problem you're trying to solve?

Stylelint reports that the new [`corner-shape`](https://developer.mozilla.org/Web/CSS/Reference/Properties/corner-shape) property is unknown. And also `corner-top-left-shape`, `corner-top-right-shape`, `corner-bottom-left-shape`, `corner-bottom-right-shape`...

### What solution would you like to see?

Add these new properties to the [`property-no-unknown`](https://stylelint.io/user-guide/rules/property-no-unknown/) rules.

### PR DESCRIPTION
**Pull request by jeddy3**
> Which issue, if any, is this issue related to?

Closes #9065 

> Is there anything in the PR that needs further explanation?

We try to avoid false positives, as they're more disruptive to our users than false negatives. Now that the `known-css-properties` package is getting out of date, we want to avoid maintaining our own reference of new properties by using the csstree lexer.

<details>
<summary>There are a number of historic properties that differ.</summary>

- `acelerator`
- `additive-symbols`
- `alt`
- `animation-trigger-behavior`
- `animation-trigger-exit-range`
- `animation-trigger-exit-range-end`
- `animation-trigger-exit-range-start`
- `animation-trigger-range`
- `animation-trigger-range-end`
- `animation-trigger-range-start`
- `animation-trigger-timeline`
- `app-region`
- `ascent-override`
- `audio-level`
- `base-palette`
- `buffered-rendering`
- `chains`
- `color-profile`
- `color-rendering`
- `column-progression`
- `column-rule-outset`
- `descent-override`
- `display-align`
- `elevation`
- `enable-background`
- `epub-caption-side`
- `epub-hyphens`
- `epub-text-combine`
- `epub-text-emphasis`
- `epub-text-emphasis-color`
- `epub-text-emphasis-style`
- `epub-text-orientation`
- `epub-text-transform`
- `epub-word-break`
- `epub-writing-mode`
- `fallback`
- `flow`
- `font-display`
- `inherits`
- `initial-value`
- `input-format`
- `inset-area`
- `item-slack`
- `layout-flow`
- `layout-grid`
- `layout-grid-char`
- `layout-grid-line`
- `layout-grid-mode`
- `layout-grid-type`
- `line-gap-override`
- `line-increment`
- `marker-knockout-left`
- `marker-knockout-right`
- `marker-offset`
- `marker-pattern`
- `marker-segment`
- `marks`
- `mask-position-x`
- `mask-position-y`
- `mask-source-type`
- `max-zoom`
- `min-zoom`
- `motion`
- `motion-offset`
- `motion-path`
- `motion-rotation`
- `nav-down`
- `nav-index`
- `nav-left`
- `nav-right`
- `nav-up`
- `navigation`
- `negative`
- `offset-block-end`
- `offset-block-start`
- `offset-inline-end`
- `offset-inline-start`
- `offset-rotation`
- `orientation`
- `override-colors`
- `pad`
- `page-orientation`
- `pen-action`
- `perspective-origin-x`
- `perspective-origin-y`
- `pitch`
- `pitch-range`
- `play-during`
- `position-try-options`
- `prefix`
- `property-name`
- `range`
- `richness`
- `row-rule-outset`
- `rule-outset`
- `rule-paint-order`
- `running`
- `scroll-snap-margin`
- `scroll-snap-margin-bottom`
- `scroll-snap-margin-left`
- `scroll-snap-margin-right`
- `scroll-snap-margin-top`
- `scroll-start-target`
- `scrollbar-arrow-color`
- `scrollbar-base-color`
- `scrollbar-dark-shadow-color`
- `scrollbar-darkshadow-color`
- `scrollbar-face-color`
- `scrollbar-highlight-color`
- `scrollbar-shadow-color`
- `scrollbar-track-color`
- `scrollbar3d-light-color`
- `scrollbar3dlight-color`
- `size`
- `size-adjust`
- `snap-height`
- `solid-color`
- `solid-opacity`
- `speak-header`
- `speak-numeral`
- `speak-punctuation`
- `speech-rate`
- `stress`
- `suffix`
- `supported-color-schemes`
- `symbols`
- `syntax`
- `system`
- `text-decoration-blink`
- `text-decoration-line-through`
- `text-decoration-none`
- `text-decoration-overline`
- `text-decoration-skip-inset`
- `text-decoration-trim`
- `text-decoration-underline`
- `text-justify-trim`
- `text-kashida`
- `text-kashida-space`
- `text-line-through`
- `text-line-through-color`
- `text-line-through-mode`
- `text-line-through-style`
- `text-line-through-width`
- `text-overline`
- `text-overline-color`
- `text-overline-mode`
- `text-overline-style`
- `text-overline-width`
- `text-underline`
- `text-underline-color`
- `text-underline-mode`
- `text-underline-style`
- `text-underline-width`
- `touch-action-delay`
- `transform-origin-x`
- `transform-origin-y`
- `transform-origin-z`
- `types`
- `uc-alt-skin`
- `uc-skin`
- `user-zoom`
- `viewport-fill`
- `viewport-fill-opacity`
- `viewport-fit`
- `volume`
</details>

I've added these to our reference to avoid regressions. 

The change introduces false negatives, such as for `-moz-align-self`, but this is fine, as we typically favour false negatives over positives.

No change in performance as `getProperty` is quick:

```
# main
Warnings: 0
Mean: 99.86150898039216 ms
Deviation: 16.122225718391842 ms

# this branch
Warnings: 0
Mean: 97.8256785769231 ms
Deviation: 15.598629079995217 ms
```

### CODE REVIEW

File: lib/reference/properties.mjs [hunk 1]
```diff
@@ -802,3 +802,174 @@ export const marginContextProperties = new Set([
 	'max-width',
 	'z-index',
 ]);
+
+// Known from before migrating to CSSTree
+// @see https://github.com/stylelint/stylelint/issues/9065
+/** @type {ReadonlySet<string>} */
+export const previouslyKnownProperties = new Set([
```
Comment (Mouvedia) [inline lib/reference/properties.mjs:809]: Is this the complete diff between csstree and known-css-properties?

I was dubious when i saw no prefixed properties listed.
I confirmed that at least `-khtml-box-flex-group-transition` and `-konq-js-clip`—which were properties listed in the `all.json` file—were considered invalid by the [csstree validator](https://csstree.github.io/docs/validator.html). There are probably many more.

Is the validator up to date?
We oughta add _all_ the properties even if we end up with a separate json file ourselves.

**Review by Mouvedia — DISMISSED** [review]
I have confirmed in [this demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdilBaA1gBYAuAtgDa4BGAlplHQObwoBmEEA3FusbqRABe1CACdYo3DHq4A7jSjFCLdlx59ZMKvhp8qYiVJnzFyth26ZecrTr0GYk1rpUX1BEhRHjHuQmJpBCExiJEoAZwAHJDAmVzUrDVtdb0N-UUDg0Ijo2MxmcwTrIjJKfR9JADdHYhowMNwomLjCy2tNbRTyw2rRWvqc5vz4tr4Sr30AD1xWchhpxlEIAFdI3GJRJExw3RpgkfckSMi53CgkcMJ9JHFcURhGPcwDxI9Ss4uriBuoO4enl7tZJ8c6Xa63e6PfatdzjSizCCyfjQGCAsbBACOM3IiORsDRby87BCjUCMDOMHIoQJHTsMyypME5NgVKQNOBfhojEI5C5JAJcL8ASCIQa3V8TTyBVUoxsnT4hAAnpFCNIkMRybzSCkkKwNaIBZjcAArcK4MC8yLs+W4XmYclhLnPGGvWkpO3kqbmrJIOgCzyUUg3R6YETEYgQUje8jkI7hVEuoE2oOiENhiNRyAxuMJmWwgP8YN0aOxyLx610lNprOl8uJvgCYRV4vSKAVlLN0Ot-3vTuNUJ9AmNwup4vhAfEdsNouh8c3Sf1wmBmfrCBrGs5qcjtMR9cQbNl3NuV1HEcY5YwZk0A2LwUp8+Xs7XmBgWrQvOujn3i9X+6vgG3gW36PnQYD3KQ0gLh+SaVjcD7kqB4GQT2XjAUeRQaKeaG2hwVqAb2cE-n8kQwLUb7OtBSTJoRj73CRZEAZRS5nkRUSXm2i6yFhNHkmxMAcUxbrTqI8GNCR-EocuImscQipzDS3HSY+45yehspCSxymyfJnFfjxW5BuE+CNCsohgOSskkZJhbEGAhC4PaNwwOOhY0GUOJgPg54QBq0ZiAZ6p2Q5MBOS5QZudQHlecsPnklm-n4V4mBUFEeJqe4GnJalAj4ollDRFADD5P285DkIuAFUVjAlYOuk2pVTA1VBx7FAWfSUA4GTDHVdLtbgnUtExgoapMIIvmI6pPGaLasKwL7NRhcp0iNY2QJs5HTV2s3zS8AC+WAgAANCAzhzAAckgEEICA8yXScMAAHRgOE4RHeAwTOIw13zJEYjECgsCsEgyxUmgWA4OgICiCDzmQywGDYDgKCQ5ESwkX0ioORAuDLJg+CYIiVgICgADaGwXodaDI+AqqeQACvcziTPxcMoOTMAoLtAC64Oc1gu2WG9kCYJ9ABiYhBsQ10qXMdrEE9H1cg9pCmm9sBltdCMQyAMuUnQxCs5DJDEGW8AAPRm5E+CMA9qMPfashm7rcsAAJIEgAAsAAcABsrBe5Dh285Dzv696ItciV9A-IbICxhq46Q-zIC7UAA) that at least 28 properties are not detected as known anymore.
cf [main](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdilBaA1gBYAuAtgDa4BGAlplHQObwoBmEEA3FusbqRABe1CACdYo3DHq4A7jSjFCLdlx59ZMKvhp8qYiVJnzFyth26ZecrTr0GYk1rpUX1BEhRHjHuQmJpBCExiJEoAZwAHJDAmVzUrDVtdb0N-UUDg0Ijo2MxmcwTrIjJKfR9JADdHYhowMNwomLjCy2tNbRTyw2rRWvqc5vz4tr4Sr30AD1xWchhpxlEIAFdI3GJRJExw3RpgkfckSMi53CgkcMJ9JHFcURhGPcwDxI9Ss4uriBuoO4enl7tZJ8c6Xa63e6PfatdzjSizCCyfjQGCAsbBACOM3IiORsDRby87BCjUCMDOMHIoQJHTsMyypME5NgVKQNOBfhojEI5C5JAJcL8ASCIQa3V8TTyBVUoxsnT4hAAnpFCNIkMRybzSCkkKwNaIBZjcAArcK4MC8yLs+W4XmYclhLnPGGvWkpO3kqbmrJIOgCzyUUg3R6YETEYgQUje8jkI7hVEuoE2oOiENhiNRyAxuMJmWwgP8YN0aOxyLx610lNprOl8uJvgCYRV4vSKAVlLN0Ot-3vTuNUJ9AmNwup4vhAfEdsNouh8c3Sf1wmBmfrCBrGs5qcjtMR9cQbNl3NuV1HEcY5YwZk0A2LwUp8+Xs7XmBgWrQvOujn3i9X+6vgG3gW36PnQYD3KQ0gLh+SaVjcD7kqB4GQT2XjAUeRQaKeaG2hwVqAb2cE-n8kQwLUb7OtBSTJoRj73CRZEAZRS5nkRUSXm2i6yFhNHkmxMAcUxbrTqI8GNCR-EocuImscQipzDS3HSY+45yehspCSxymyfJnFfjxW5BuE+CNCsohgOSskkZJhbEGAhC4PaNwwOOhY0GUOJgPg54QBq0ZiAZ6p2Q5MBOS5QZudQHlecsPnklm-n4V4mBUFEeJqe4GnJalAj4ollDRFADD5P285DkIuAFUVjAlYOuk2pVTA1VBx7FAWfSUA4GTDHVdLtbgnUtExgoapMIIvmI6pPGaLasKwL7NRhcp0iNY2QJs5HTV2s3zS8AC+WAgAANCAzhzAAckgEEICA8yXScMAAHRgOE4RHeAwTOIw13zJEYjECgsCsEgyxUmgWA4OgICiCDzmQywGDYDgKCQ5ESwkX0ioORAuDLJg+CYIiVgICgADaGwXodaDI+AqqeQACvcziTPxcMoOTMAoLtAC64Oc1gu2cG9kCYJ9ABiYhBsQ10qXMdrEE9H1cg9pCmm9sBltdCMQyAMuUnQxCs5DsYauOkOHbzkO63L3oi1yJX0D8hsgMbzkGyA-MHbtQA)

All the previously known properties should still be valid.

---

I stopped when I reached 100 but at least all of these are now unknown:

```
-epub-text-combine
-internal-text-autosizing-status
accelerator
-wap-accesskey
-webkit-alt
-webkit-app-region
-webkit-background-composite
-moz-background-inline-policy
-khtml-binding
-webkit-border-after-color
-webkit-border-after-style
-webkit-border-after
-webkit-border-after-width
-moz-border-end-color
-webkit-border-end-color
-moz-border-end
-moz-border-end-style
-webkit-border-end-style
-webkit-border-end
-moz-border-end-width
-webkit-border-end-width
-webkit-border-fit
-khtml-border-horizontal-spacing
-webkit-border-horizontal-spacing
-moz-border-start-color
-webkit-border-start-color
-moz-border-start
-moz-border-start-style
-webkit-border-start-style
-webkit-border-start
-moz-border-start-width
-webkit-border-start-width
-khtml-border-vertical-spacing
-webkit-border-vertical-spacing
-khtml-box-flex-group-transition
-webkit-color-correction
-apple-color-filter
-webkit-column-axis
-webkit-column-progression
-webkit-composition-fill-color
-webkit-composition-frame-color
-webkit-cursor-visibility
-apple-dashboard-region
-khtml-dashboard-region
-webkit-dashboard-region
-webkit-flex-align
-webkit-flex-item-align
-webkit-flex-line-pack
-webkit-flex-order
-webkit-flex-pack
-khtml-flow-mode
-konq-flow-mode
-khtml-font-size-delta
-webkit-font-size-delta
-webkit-grid-after
-webkit-grid-before
-ms-grid-column-span
-webkit-grid-columns
-webkit-grid-end
-ms-grid-row-span
-webkit-grid-rows
-webkit-grid-start
-webkit-highlight
-khtml-horizontal-border-spacing
-webkit-hyphenate-limit-after
-webkit-hyphenate-limit-before
-wap-input-format
-wap-input-required
-konq-js-clip
-webkit-line-align
-webkit-line-box-contain
-webkit-line-grid-snap
-o-link
-o-link-source
-webkit-locale
-webkit-logical-height
-webkit-logical-width
-webkit-margin-after-collapse
-webkit-margin-after
-webkit-margin-before-collapse
-webkit-margin-before
-khtml-margin-bottom-collapse
-webkit-margin-bottom-collapse
-khtml-margin-collapse
-webkit-margin-collapse
-moz-margin-end
-webkit-margin-end
-khtml-margin-start
-moz-margin-start
-webkit-margin-start
-khtml-margin-top-collapse
-webkit-margin-top-collapse
-wap-marquee-dir
-khtml-marquee-direction
-webkit-marquee-direction
-khtml-marquee-increment
-webkit-marquee-increment
-khtml-marquee
-wap-marquee-loop
etc.
```

What's even weirder is that it also affects a non-prefixed one.
i.e. `accelerator`

File: lib/reference/properties.mjs (hunk 1 above)
Comment (jeddy3) [reply lib/reference/properties.mjs:809]: Thanks for the catch. I've pushed a commit to include the prefixed properties.

**Comment by jeddy3** [comment]
> What's even weirder is that it also affects a non-prefixed one. i.e. `accelerator`

Typo in the Set. I've pushed a commit to fix.

[Demo with every property from the package looks clean](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdlluUFoYAHAVwCN8wkiAXASwk3wGc7Z4UAGAbhz0NIUAFgE8iQmJmYcefXAPL4aMAB41KEALZk6mGDN6Y8BYouVrCm8UlbSuh4worn1MK0Jt1mGgDYQATgZyJoJKqq7unt7MNCI++vbBTmEWAXSSNEj0jEFG-KbO4Ur+SFIAZgGauY4F+ADuAVD4ZP4wSADW1fmhdf509JgA5via0AmyefK6yv6YSD4p6kgkNBCsAF66wzFZJHYTxkhgYDDxJauBiZMoRyeY6pB+lwf8ddT4tzDMzO0wIl24JBQKD9OgANxgLBE2ggPn2Djw8zogyYkHuGQBBDqMDI7X6Hx8yNRjGU90xSJR+H6bnhSWxuPxFKY1M0tOuTJYpzKmPqOLxS0JlOYXPJgswmgyzRsp104wRgJ8PlFNB59P5BJVV0OmDAQgC+DmEvJOr1-hYkCIcuCpTomiyDEwxtt9sYGisa1BOS1iMwzuyTFgPiQ-298lG6w+vrt-vwgeDPNZkb9Dtjp3joaxfMZUZdAbTIZegJzMZBrTA-oTEAjNujKdLMHLDoT3hrudjdDLFYzvIZS2LdY7Da7hZu-ddUBI5yb3fDSdr48nuebc7bE6nXpHPfVrZLi+H8tHyddZToipGY0r1bHTBPZ9G7BnLev+FvC3vVuuW+zR5vp7fF4zHcU2pddiRIMkZyrFcYxAttIHAzVN0TIDXVgmN4Igzc1W-edmRmOCIAQy9oOnJCnx-J1cINJAjUgq8f2o2iyJI11DQ-RxsL7Bi2MotsiCDEQWEyZRiJQph+ODISsnY-hkOfCTBJ2ETu04ljxIEqTlJHMT8BKIYZKLBi9MGSFJCgXiY2MyEdn8RCDx0+gJUJPQLJTRythfcDGw3A9z3oqj3KGTydX3JI5IYwLhjKLzQs-VSHNtDzopC0j7OfGg+kGEznjSiLMuy5oYA8MEGBy610vymAzVUfErNc10MuRAqavUKzCEwczAIqpqqsIFRatKEypNs+qmEarLerqrq8p6s02rM0bilm3TBuszIRumgLKrNRyZRclSsy4rbZtVQ61PJIgiF0mBBlSukzuoK7WlunzrUuto9JOHl2iEGhNAWR6PtKL66I+d6kE+gzM17MHLQh4GoZsO51AgCF-D6B9tOYS1yxW7JTphmwcdal1yRIEEIHweIISVQDNk0FYhExMgjnaKB-AgK7bxmAn1RZsA2Y5rnTx5jN+faMojkhErWB0QlYmI8XJZOfAZboOX+gLXzEyVqXVa8dXT013n8V1lW1Y1hWxdZwYOfAzqR3F23CI6j4aEyXUJUw3zVKdu3XayD2hC9uzgj9l2mjIeJXffZmbf9powEJIhFfjiPKGTk31HD+2M7oFPrYF53c8eAIs6lIuE98MuDphnPXcgd1WC0g966aZ0TPLtuqTtTvQe73RnMhIhYToMAtbDtPc7SW7HX7qfXZn3Qu4Xpol7nx3V-wEfm7uuKzu7nfPQ31ut6PmMVBXyv0-PlNL8L9pi9d2-XQn-e67Pj0Yzf4xu9aOHQ7vz5lvf+bRAG-xAcQMB+B76b2vrnUBWR8A-zwN3DYUM-IV0flXdBV9sHp1wbXYB8COpx2FNveYMB3ZQxZsKIeLAhB0DKOA1B0p6HMEIv4EGjsipIBKjXTcP0-oLB0B1LYitdAgiGMzPwAtCCKnzrYZcUcIByKIBzW2XxWCvWuCouRhDHayPaEJYgMjVHGJiMQAkRIzH6OUFdXQwoNqGPMSYp6EdbEWPsSwOg6waEQAgO0O0-hjFBjIKcZmASgkQ1CTAGmkTAnBK8dJSJ-hYBlSAabRovUkDMN6qXDJHED7ZLNLkmYQk4gYN9iUj4eTCmvGKWknJdT6hsBoEzIhWSmlmnCRUVo1d6nyGqd0wqfS1qVK7jU3pAQqmNPSaMmZrSoDtNSfMvRnQxZTKMQM1ZvV1ntQdq3LZrizI7M2SM-ZpyYgTPOWs7Zpy6htI6Y7Y5diIYsNwGQV5yTbJnJeRc7ZNl1DXPiLsnpgL1rqEecs55RyAWuJBf4+FcjoUrNuXsiA7stBguaJi1Ymg-naygl8i5eKtADLZL-KZZKCXxGYStEEexJmkqxbSmA9KSiMspag6lrLdLIl+gyugTLOnZ15fi-lgxBWcuFdyz54ryWIpxV8vlqLYVh2pfbCGKD5UjMeEGIgwocUFMVjU05JrRW4pGea2EAi4XzNOacmVIqkLErNaQ9F1VXZAqFS6olEYSUOu9bEUFlrA29SuSG2Zdd3WHLCm661rs1XMqDU0ZNYaakng+QQIR-0rXzNNL4kk8wWBECOOIjNIzC3rGLQsbG5bpGep7kgPurqA01I7hgym4azSdpxZ2-AhEaDCmzV+MVIyB1DpHf23ukJEGjuGfMgd86Z0tusoSbhPs5m9QHcwDdSKl2zpYJwzd90Y0TqPRwycp7MnjsPWu1dQ101YW3b2o9z77U7swEPft37ZSEo1ROv9egDm-voTap4YH-2Rpuf8pdwHTJJqeVBkDQKUNrXeQB3RHaEPDWBVG9DeGllorg1+9hBGm2D3-R+wD8y6XZp7VTdlDxbWDIILORj9GKU4q40qptXGaPYZGc6uV7GE3zJE7i1l9HTXCaBLKqT+LMq-VkxJ+Tfr43trk1ypQnMZP9xqZJ1Y6iBULtfb60TjHlMMcM6ZrDjgOO2alSxp4lmnOCr46RuadnBNUpGfWsAFa235t6j6i1L7z3zLC6xnFPqnXqdE5gxjaGm0+p9SJ1ToXIUVNDRFvmNS0sUby10qLkLMtmh9b5hpkWsuYaq7q0rsHP07U5ji4z9nZLid6u1gpbmRnta4xlyt8yBvMYs21zmkrpUJZTd1yb1nxtNva555rumrr1Zzb9PNjG0b0CoHWstgXG3Fbvb1XbY8S0BaC6tjbKr8XfS2yIiAKhrEolNS9pkkyPtikiS92AkBQLNFaB0L7qYAdthaG0DZgjHu4r+4ObyJ9NNw-bJ2PeRSY3w7RzoxwuansvbKPEF7xcC4w+ESjwnqh8Ak+KKUXeOPqv5YJ0T6ndtSe+TxxTon72Xzc4zcz1QD3ydfJe0PRL1TReykS5zkXg60m6BLSTnnjQFcLCV-zuXUjFds6F9t57cv0je2R7LtIGINem6N5+GX+vDvQ-9Sj23oPHca9aJT8sv2GFAggHUHnzAPBQG96Dv3XufebJexsa7xv9cR+O1uzHPjNix41eHuY7Ow7A+MWUqqzMM8LNaDnqHVIpBsBoSQMoZQqowCaK0DqVVI-XCoLQFMrBMYHioK0bN7eqHnQzF3lzdrgh9895aTEuokCONH-ECGk-84z6umWkjcf1RJ3zhQxfg-k66RILltvMXe+sY+FAAAVnsMzMMCkaHRkOdH-BHrxAGS+EW2f99PCLzMEeQZYrGAv9MKqH+2zcxVSiYX7qIQC3hQwX417pL17f4H7MC6huDRrL6wgkCaBMBID9Ti5nSPCoFMCQ4dC1Kiwna+C4FA6F7TL56Wo4FoFkEEGOIl6j4oE0EYSjqzjUFgSW4Y7IE+CkEsGME8E0GvjETsGP6KjlwiFCEv6kGDDUDCFMFMAyFp63okE0GKH8GkESCmbqE0GgGaLfA35DLYHyHbwaKtD6EM64AiH+Db4QHGHWH374F26D52E2EdZhhQRWGuHhZL74ieH37eHI5+G2ECFMD2GQhTpULaGhGuEraBEuH36xHKFBE5ZIG+HxHBGkFhHEbqqfhsHpHZHiH5EbYiH1pI65EeHGGlGFEhGlqlBREFGgwiEbZjoqFMDFHGG9CyFSFoGJZ5EhFYHn7yEDHIFNzHyiELABFJFaAvw3glAShuEoBoiZDLz773Dj7Mj3B9DF5gDNCAq+K2FrG6Bv5bGsA7GaHOaMGHEbGNTbFF7sL7GXHLHXEnFjwJ4HFPHHH0E7HtFXHP4jhLHrG9Q8SrFPHdZiDvFm7-EkiSgWxGxWzMRLGSg1rkpj66AwGyTeCIn3D4DIm0qJTqB2iwLayYnQnYm4lUz4kjArEImknqDkmEiaD9DLhYl0kBIErMCp7Mm0k4lsksCp7bwQDTC9Eknohkm8kcnvCxAj6PgaCimslaDomWEki6AkC2EIRfpgCtAhyMHqlzRfCRH766mcid6qmj6qmEF-Ft7mkUEQGTgcJsYtFgB2n6iwnyw6qLFEmD7ulxqfh36QhQA2BCBfIQzV43QGGbbk4Bl+7BlpLXQvRlFcH4hRlBkQAhlxnhmwDwGSioxVQYxQz1iI6YggjYwCRFleAKSvYJl4AB6MlzDYm0J7T5kiCGivFtQMlMkZinBxJLidlWCxCUCnBwiYiSBIBRyQhtzDmhCN4xgt5Qy1CiDiCSCia1AuBuiiJzmhCrluDWBKKdmblFDbkeC2ALErkHmRDHmJHGCnmpB9AZA9kjjXnqAZR059JVB7mKANCxmOGTkfl9ADDDCxwZiSyKjiyYgninBNAx6DBgV-gwVnjflAV-gLGvjNqtoHgoWczlrwnoVIXrxwULAzH4XXQAJEVhFEUGI4U+BEHEmiHUVnrqiAFsaU6em5HeDMWVnlzsWfZAUs60JeCcW8VRBgUs4Flf4Ym85U6iXhktHsVSUWEoDsWE6B4ymKV+Ch7EGqXKUjjsXOzqU+HqA6Ucx6VhRsUs4sgcWWrsXmXcXMTsX0LO4aUs72WszLjMWuUs56AyH0AQjuVU4lICV+XdK+UvYOX6USUhUuUqUs63w+VRVU7qLsq5lV5vHCVU5+5bFOHKHsXpW6CZWJkGV87aUs6dFKEOamVU4lUBUvaVU8WpnZpKVIKwAV4OmzgNWuBQBoXBBtWDrl7Tq1VIKu6V46hQxKXQDIV+BjWYWBbYVdVqXCXe4vgcxvm2VqWLXYqWWrVlBLXzV1Bv4QDuULXTD7UbWHX3DHVk55pKW7WAWCKMAACOvOC1N16FJIYFJI7YJZ6Y2l71ksjJPg7pFQ2JFeuw-SI6-5vRUEgNBlYCk41kVC4NrlP1MNoN8NWwwx+IUNL4yNcN7saNb12Jvwswip0MDF71hNvoSe1wmNQYQwJAa6g6aMeZxE1Ng0dNQ0OZ6MDBQF71nMe2l2vixNmNZa8Q1C+NwKDx3N2J6Ch+J+MQuuCwmN0tgYmQnF71StpwKtllatowmKjClNxgitGUVCuoYtKRptzAzZ7SXw-FktwKltEgx5hFttUI9wDtXgLAdoZ4jeomit9t1t0QRWL1Utftx52IWhztYIEMdApQ9V71kdfQMdGoVUcwygPtcdUdid3tpt8d0d2JbQMQHwrAdREdGdedowR+dA2dpd6ggoINXwqt2JOdidtdNAsNadjd1dBoqBdeYAVdCd2JTt31HdCdM5qNQw7dUKMA4dQ9UKyG3NmKmAmK-p5ZpZ89NAi9ygApG67pmCfSKsLQgSkgqFkIY88le9yVF+QIst2aahGYgw-14gBud5MY1atamI99YgQgT9axMY52+279GM5ctsbAFpbGwDTQEMbQADIDywqwrR6N6g4DHwKwlM7BomSDsDlMV1QDGMyDcD2Dd9uDmDuk3uCDrOMDKDJDdQZDSDNp0Dic8hy4SDIhNlB4zDxhC0hDIDIht9zE7DIRTDuDJRZaVZuA-DpBKWxB4jaBgj3DQxODcj-RCjTQnDI4SDvDbDuDRlsj1eC1rDwQSDRloGXDuju1GjJl5DpjOjVDtRojKAhjC1kjYVDjxlrFljVDNDWjpDyjeG9DYQVgn+UMSDygAT0kHwwO6DuDITEkm9aDfj0TgTHjmIHgQwHkpAIUdNYluA5xKmMpjCUqspz5BdV9p+5c+TQggouTF1Cwr9axT2-mh2xNC5EgKdkIY+JQ5Ylp9F+IzTI5sTHgHTdFyhvTrTFJjJSwdSZTn9fTkI7Z2c7KMyyT0zozczlAAzwp+AIzYTqz7TomWzm9qzQYctGY+zszlJYuy4pzYz+IFzlqVzhzUuSzi5KzlJNa+0zE9zrzjAUMIzENEYvzlzyzZDALGYk6t5P90ls4y6YZ8l0LteWx0FoLR6ZhKBWT7G3gtokI+j1wmL54rewQugEgf5omaJ9AJaItQzxgpL0dCwFLOSP2lq1L5L8NXTOLvoZLtLLLZoNVI4TLCwkdPBUMVGqGEtvLuGUFmIugpABllQWQqo7wUrKwL4srC6CrmA0r10d1JAg4PpVL6rSrwoTpf57pjiBpYrI64TUDoLUg3e6ykrNr2c9yHq5rtrEK7y9rFrwrQrDrdx0GzrB4pr6gXrvj1r+EjYJUM1bL7+sIYTFFFjv+-g-+MYz1BLHCn+4Z5lmpawJLITqO1+sLubBDvLuboVBLube6kVxbbgtOAskrubPLHO91+AR+mJmcGY19TCgkLJ5cHbZQXbtJmIvbgkLIZDQ7VIITomY7dC3IlqU7IoGY5NxNAkQ6j1rjxgy7Sr4DmIG7iDQjAz27wYK7SDP6GYO77jKb1wZ7wT4J27zGt71CFWjT+teAlT-5CxLR9C2L+VFJIGsuAJ1JB49CCF1TP745Ge5cQH4Hp7-6ScNEpVt+l09+9CsHVg8toHGccHEHMHQYqH0HIGWahAHVUM9CihDNuZXNI4JHgDlqVHIDEp8HhhMMtHurL7-6OT2a9C7Hbi27-6ugmpiBnBrHIGZawIS7-69HWHqGnJ3YlMzkeV-AsnuVx616xHXg+GTWwQhIBdiKx9PH2nUaAp9OdjWn6n9+UpqRNdqilCEHEAt0+2mzU9FxNHtnF2CwG2wSs85cHnRxWeZo+q1ARqlq3n6BkzQXEMs8eebTsIBqgXxBwXkXmI8XdrGYSXTrLHuAqXCKZWKX4XRxd261IHSXNKvgMXFnIwuXeBxX-nhqUMSXUHhXFXJXAXZX8X1XsX9u8XqjYVnX-rwQ8XXriXjXwbXXfXQ34r2XI48X+mk3jX1maH8XTjyOC3E33XjXi31w8Xxm83jXPW0XzXXnO3k2bXtXO3fQy1B4SSrLxgl3Xq6XKAN3+A7Qi9AsK703F3MSvUT35iK7c3OXISvUjJd3D3YBZQfVM3-3ZoC+MwdjD3wogw2pf3hNPi+LG3H3FWK3o3IS4u7wwSWrMAy9DpnOuPqpBP+bdjLRxP+PebhZ3YRPEMePJ9OoWpkJq3-gDPRe-HCPDXbPJP8rV0lPszASDHEZeaAvxFVCx8B3PPVPoC9AaLj3sOYv2M+Pd39QOP9PJPpaKvUv7PyvVe230v4yO+dI6vhvZtYXZvl5jO+IAvg3PwB3PwbsQcXP73jvPadvxijGF713NgnvNSER2adobvhmUCcrOXwf-m+6HvIWFWJ6J3Ef8yzRqkQffvL2k6KwYPq3wfafyLofZ+6oKfKOu6UfYX2fx9ynXCLXvvRfs6Dvqf5f7n1fK+wvFPTfbbM3jvjc58Vfnf0xX88fxifapfg-tf4fxi3veAhfeFw-BunnY-hnkvM-g9rvxiMxMCdfC-F80fa-O9yf1fO-0fK6M-R-cX1f866-x-efyC0fcbyhhft-PvjvV6lfSgN7M-z-Ks5n0fX-w-23NAuoBoD6F8AJLj4RERiLVkvXfZ79-+X9PQJAwLp2hTwuxcxBANiZ74Zu7SVMLQByI+9MBfuJhIHyyBf0reGXDAsgP0Sit3uL2djoNzT7itKBo3SXHoDIaEkqYLnezjQLC6i52BJaRvtVTnozcXsuJRLnlz2J+IRBTATgZNyOLBsH+k-GQZsS+IJ5iaFPI4n4Ds4lopB3XNQTwLc4CCLuRxdzkcWEEpc6AL2McjHAAiTdMU4ZUYDGBB6Z8+uNg10AvhwGT9nBoRTFPeQPBzAwQsYb3HY18FF5YALFYwEELe7BAghv3EcEEJIDC9fByIbwUkE5yYAyA2MPFmV1SHpCJ+uATyvaFiojgIAZAI-EOEfyjpKYRQkobjCzSYhKhpQ5fkkAqHFD6hX8cMnUNxglQYAu1EXLUN6pmsDwDg7vMDFNC9DQerrE5L12uCDDHWWXd1hmGmEfVMgw1UYZ61wwjcphfQoNuNzmGFDNha+NwbgAWENCNhYw1qF4JbjBAFhHMYSG0MaaRtccsOKasbFBhPD7h1vFGHcPdL+VLU3w4LBbmzT-CkhUwxNikz+aDpmABObWgEnaTE0h0J7QoSsGQ7oD7ccImDsiORyoj3mAwxEf+mmHERMR4RTYfiJxEgZJM+Xf6HexeEki50CWRTFoGiEojqRi2P4UyKMx6ZKRLImgPQjZEmYnOCIrkeJ0DoYimRJAlAASIaKcj6EG2DmkWwGFowrqkYXUAPimHyjVqyXQoaqIWrN9yu-gOfhqKqgKjtRmXWtvMM1G7UjRjXS5JMOMAyjVqFo3UaINmHOI5RBou0ZviK6spahZovOPzzG7wiXR-gQ0e6L9F+s7utorUcGIdEbFyMOwgMUGNXxTcORcYt0QmNm7T1kxEY1MVGLWxejXRp1f0d0xRjej4CHMBRM+zDDeBwxu1UUVWPqAlBhetY0IXgFrFfC0Yq9fUZzVgDcZTRQBLNvBV4T8I2MHNEsdF0KjFRSo5A+TocLRgjj+x44-UANx7H+BZxIiAcROKbHTjexpY1cfOLNDukROmIETlIkRbEEjxHkXzuXDPFBQ6GGYK8cMHVEHg7xk44xiOCfH7J1uxgN8TSmIhPj1h37X8daLwBPjFxr4oEMeN9YgY-xQEsCR5FkEY9rgT4iIQhJglBQGRyQ2HE+I-GdYIwmE+Cf+JQnbA8J0E0TkFC263iH05EoaI4VAaHj6a1Em8aBKom556CKPT8fTUBFosy00wTXFd2gl7AoYZafiTRPIlCSGJvkP0hQkEhkAVgqwJgKKNhj34y0UkmSQ1Df6vij6RwTiUAWJjggMEs4S0MuJ0kFCaKBk5XuGwEnaTr8EIWfgB2RymSjJ4RTKLZLcb2SrJjk5EM5P-GWTzJNkuxq5J8nrwL+p47yd5XckRcNxKAfyaFN8nX9LUUU3STFN35nR4pxk4IEQH6Am1bxGUr+lNFfFBgVY3bW8flJPoTtDxxUzkD4BnZ5TJIa4YmiPATaEAIQ9wUTMcM-GtDXQww5UW1KM6WskAh49qWNH8D7iBpxQQSMBR8DiwWpI0jKIJF5oOgppPUmaTxLYxr9XSzw18a7jMGHiti-eUpMflKZxSdpD+Epscw2mcwqo-ZYEiOFQH10MwbGXKQeGBzgTZRwQJ6R5F+FhVnoKYaiReMtRfTXQ9EhZpQWIL-S8CzE4vKxLwCgzFqLaF3oWPTLHgSg8PFnvDOhlVjMQZhBgdcDMLZocZwkkcHjLEmvSx4QgZgaJjQnYzzhUMIxuY0pm7UyKd0halkWA6PSmZXhdEXTK3z34A+GMtmQkSFGcysizRTnLZAWAlIVBqkUWctOJrWEyAgkL9lDPICCQJQuo6mUrLI7+AUmJ4x6erNanvCt8cszfuGQZkEzXCLM16ezMgx3TXCPM62YpPWIowgqdso3mrPvwbZrCmACmtrNekRShpmIeAtZwzArixxfCUqMuGDmokvZ-svsQsD5ZKBwu-QixsHLmbhyY51zdQC9kJKpztx6cmBFSXJ6Jhk5lJZWRgWzmjjVmyszyXgGDnBdo5Oc40VOJQA1zLRaXOuaOIbkhsRwzc7MeSLbl3gQxWI4IN3Ii7DdAJuAYeQoJjHOih5acxMcwj7lvg0xfIg8BPLGitYg5s8tHqzkIjC9g5d4heRQhIn3ijEB8t8a3I3k5yz5To7NHvIIl0jzuM8y+XfJAkry05wEtYWPKblvzn52w6edcFvlHymM88i+aOKfEUzjAAC8CWROYjBySgp4UTMHPo4WUu5acpBZABVytNy4iC-kugvlyYKQFZ4JBZmQGBAjv22C94MQoVxotyFvoqMQfKQUej7sBCutPyTnk3zUFrCpeVU1fk5yGFh3XeRwveD1TmpQUmijQoFJClRF8M8RcIuHRSL-5gi+fIKREU71C5iiiRSoqwXqLZF3gd0uIpiDryUFvC-kj-xgXqLTFYVcRRYsfmjikF5neRRAvMXglYpZi4xe8AikjBog6ivRaguyzrQTI7CnOf4u7zq4jFo43aAWIUVBLMWn7TAgfIiX-orpYitOc+SkDpt5KK4lmKUnRhaiOZji7cVkqlDkJJi+S6LoUpKXVyY5hSgMiEk9wB5zReSypQUohixgYkweepQsUyUtLlYUXK2WEpAotLBgMk3iePKqUtLymr7TpWMoqz+5clfSnhWUpaXPk5EFS0Zc0u5b6CbFAy-wAAGYmgky1ZV-PWV7KDljS8eR4EtDl92kZhPUD4FV6qRg8lygdNcq+C3K7ujyxnrOSwUXLPlFHFeT8p1F6jLFAK2uUHIBVTo-l0i8FRn0hXKEPlh848f7IBVQE685YpuVjIgX7EZaB0ruYSHmQcTwySCrQUPNHgMN5lJKvFYOk+H+yF8NLaiCVC8ophNJhK2lSWgSGMrXQ-7OxvWg5b0rEhMYZKDTy7lwxG5yvAgjYBpWF4JAQIEZU3JFVd0VZ8wSVQQXSblhMmLK-HgAPOBQxmAXCYiDsAoGJ5vZ-83buSpNWTZXheio2t8H9k3Ftgick1RzF+C2qnVWLBll3IyiH1KycMx1V6vNm+rfgnSz1YGuTKX49AbGGIK6taV+5m2p+Tti6q9XJkTpN84Nf6UDIQwSgVqqNcmQBzhqE1IawMniKDmprdOxaqNUPEbz5qzmegI-MoqrVUkZgKcstV6stX1rp+HqqNXrPHklqT+K8ktXIO7VRqNszAMvCeAikjrLoAQZQGSv1DwEJAEoMhswDBDbBZla7audCC+RDkg5ltUudussQPzrgmQCgAOrEwRgj1KVGTvHOPUYqFOV6hwmwllCYgj1SHQ9isHLiZAroEyuzIctXIKzcAv6sUASFpgjgANRIKmDYFYJQRQNlII5tml-UmgupeAX9SgwCx6SoNRQKOLlSfUYbns2GiwLLirydVD1OGl7I1APVlVFga5NjmkDeaZBgNB4Vco3HXL4A4h4C-WYxq0Drk8N6gf7AEFIVIaigvGwHJhswCNzVyQmgiGaoczoaLAEm9CGcpJr4hxNDYPjfJqk0CbZNKmwHJEuk1nrBNWmtsDpo008aDNMYehNcsIhSp31+m8HGZsfUZhlNtmlMIvUHnEbNNTm10BzSM3-qbNqm5vHiGF6Oa-NroH4Kvh6EObfNgOULQ4lE3cawcwWuSQFqLyOC3NJmjzYltXzTs4tcm-zZlsOy3TiCQWqLQFuy2mbm8As3TZRpy0haKt7GyLW2FFFFa2wMIgWGTNK3palo5G4zfFsBz2wqo3mxTU+Xq3y9OcTW-0BiyYDsoK87uS1GNvmlF5CA5eIcHFsPJCUItFgVbceUOUtEty55d2j+rPI7l3aXawbZRs23HaBpK2vbdEBK3raIgR2gOhp2UK7aHt5vQrYdqPI213tFgFCgdosA04-1KAVcpIhRmpbY1MQeNXdvB30A+2nWuLe0EDJsA+pUOhHfgIDK1Eb0xgVcuZqEB2wrNUOnHXjq-p-aa6-6CzSQAKY5CgdRQQnZZuIG1afNFgWnRTq-obZVyBK+SjtqKAc67G7Os0XFq832aQN3OtsWiPU2M6ix-W-9FTr51S7UMDO6nakFF0gY2dRQFFQi2s0WBDWk4daQxqKDtKtKeurXViuTU8gJJq5aWqbtp6w4LdJu-aadPty26-E2Kh3RYyd1Yt7d+fJTfrrt3X04tV2NFRbqfbDAyNmu-DFGu22qQLdqasPUJCHWbKwdqS5gK+Ti19b-AA21cmnqRHi7Fd6gLPdLqsFG6898LehEWuF0WB89wnS7bNqKCV7h41e8vcXvSTkYntWO2vSXuowJ629FgBtsEFXIlUMhcWgffJKj1FATBIGmJeJwtBQxoFDGwiAAOZXyVVgJABfYjlTDtiaKy+1ffLyj3z7id8wPwG+plJb7iBXZGbZuHN1wLnIwwT8ndyT0p6HNekZPZUDhzER79lQZcO-v8Bdb5AlML-T-qB1P7Xyvkt-UAZf3trN9YB7-SAcvX-6YDhWqAwSggN97EDMUjxVHtQOBSIpcBwKUlJhg4GnJTAd0gQY8lMB1g76zA4QZxJPrUD8k2cHAboPeAGDCunbbQZYMYGXyH+x-XTkX4gan9YxcJLuJoM8GSw+YUAyIbrBiHj9-B0QxvsaG05i8shr6mFST1jE4wxBmQ3WD3CQsoNmhhcKBE-16GAw2hznX-qMOxgTD5PDg4oa0MGHQYqh+XomAcPSUzDEhpfeYdAIGS3h7hM9R4aFgXTVFTBvw+dNsg71XDNhlwf4dCMUG3D4kKI94cAOxGlAiUIKIKscO6GkjkUYKEKsgOZGUjUUGKC4YUOLT8j2RnfWdGcMNRSjaR6StYaM7CG0lKSBzeCVEwr6NQLAPEHYzaOhaujvoSAF2J0AghMQ4EU+l2IenoTyc-Es0OzBbTlwpjsYJGcRHmMVAnSYI+Y4q1HSc55j94SHcFm2PQBdjYVfYyCD7bDGnEFU5bdbsmPnG6ElxvYzcbP2sFvA8x24+fqOMPH4gbx4IPMfH0HgIQ5YfUFNruN-GLprnZBRzlhx-0S0yWYPZiE6G7UElrm4wPCeSNOR-0GBL7X8fSAInJ9IGQNnCexOonGyjEKGCicqOogjmomMk+YdCVYmuhxRsYkkuCDwmR4vySQiOBZNTrxiVKrCu6U5NsmOyHJg2JbD5OCl968wBGHCbFP+lLDUpseJCF+qnhRT8p7eNlLlMqxxj1wMENKbxikmdTkarROqelhME9TAhKGHUEYSb1UNmIC09SAx29LSuNpy09ZHy1w7LU0KAJQjLsbQpvGGYDbI8i9pay0NEYR5B1AWozGsoKg2cKGY6UG611uAW-bQUbmJnUNxRh-SOBTOwm-TjQOsV0QzP1j8ZB4AfUTOuAD6XpbjMs3NXdMFnyzxgAfSxL0neAB9oK4gs2Yq7lwB9+86s+8HhUNmOzBZ+FRCshkJmCz5O-HcxAH1jmDhp2yc7jrp39m8zRZv8h5Cp0tFegoIIKFToinukIwIOiKb8awBYAAAviAAAA0IAcAgADkaIcARAKoDg7xAAAdGAG+BnnwAjAE8IMAQAgBVArJmgCgCarLAqKaAPgOgBABhFmAYFjgBgGuBgXPDARg0JTHAhfc6g2ABACgAADaGUVUqebQAoAwLCBAWAAAVNpKgKvFBcAOqkUAR5gALp8Ajzx5wwG+bRCfmAAYiq2-OIpnINAZ8x+eRCPnNALbN87AENTfmYLuAMC1xemAUWwLv0GgIangAAB6RS0QEfiPn1Ej5vQHUEUtSX7gAAAQACcAANiQAAAWMoGQB2VgXTzoFkALpZYyYBPzUkDqCGRksgBAmMQMC8eZABHmgAA), so I think no regressions.

File: lib/rules/property-no-unknown/README.md
Comment (Mouvedia) [inline lib/rules/property-no-unknown/README.md:1]: Check l207–212.
Did `-moz-align-self` exist?
Based on l19, it probably was supported at one point.
At least it is recognised as known now, so the README will have to be updated.

Comment (jeddy3) [reply lib/rules/property-no-unknown/README.md:1]: Updated the README.

**Comment by Mouvedia** [comment]
Looking at #8155 and #8203, we might have to remove the descriptors from the `previouslyKnownProperties` set, right?
e.g. [`syntax`](https://github.com/stylelint/stylelint/pull/9099/changes#diff-a983e3355e08be51e90ed8711403d7b7fe0556a2dbc44065d00ae86991924d67R936)

If we do let's do it in a separate PR.

**Comment by Mister-Hope** [comment]
@jeddy3 Can you check https://github.com/stylelint/stylelint/issues/9115? We are meeting issues when upgrading to 17.4.0 from 17.2.0
