### PR TITLE
Fix `string` formatter for unexpected truncation on non-ASCII characters

### LINKED ISSUE #6860: `stringFormatter.js` truncate non-ASCII characters unexpectedly
### What steps are needed to reproduce the bug?

To put it simply, this test case will fail (in `lib/formatters/__tests__/stringFormatter.test.js`):
```typescript
it('outputs warnings contains non-ASCII characters', () => {
		const results = [
			{
				source: 'path/to/file.css',
				warnings: [
					{
						line: 1,
						column: 1,
						rule: 'bar',
						severity: 'error',
						text: '简体中文こんにちは안녕하세요',
					},
				],
			},
		];

		const output = prepareFormatterOutput(results, stringFormatter);

		expect(output).toBe(stripIndent`
path/to/file.css
 1:1  ×  简体中文こんにちは안녕하세요  bar
1 problem (1 error, 0 warnings)`);
	});
```
in fact,  if a stylelint rule report error which `text` is '简体中文こんにちは안녕하세요', it will display '简体中文こんに'  inside the terminal(some characters are missing).

After locating it,  I found that the reason is:
the package `table` can't wrap non-ascii characters very well.
The smallest reproducible example:
```typescript
const table = require("table");

let config,
  data,
  output;

data = [
  ['简体中文'],
];

config = {
  columns: {
    0: {
      width: 20,
      wrapWord: true, // Note, enable `wrapWord`
    }
  }
};

output = table.table(data, config);

console.log(output); 
/*
╔══════════════════════╗
║ 简体                 
╚══════════════════════╝
*/
```
but if you disbale `wrapWord`, like: 
```typescript
// ...
config = {
  columns: {
    0: {
      width: 20,
      wrapWord: false, // Note, disable `wrapWord`
    }
  }
};
// ...
console.log(output); 
/*
╔══════════════════════╗
║ 简体中文             
╚══════════════════════╝
*/
```
it works well

### What Stylelint configuration is needed to reproduce the bug?

```typescript
{
  "rules": {
    "selector-class-pattern": [/foo/, { "message": '简体中文' }]
  }
}
```

```css
.bar {}
```

### How did you run Stylelint?

```shell
npx stylelint 'foo.css'
```

### Which version of Stylelint or dependencies are you using?

15.6.2

### What did you expect to happen?

output:
```shell
foo.css
 1:1  × 简体中文  selector-class-pattern

1 problem (1 error, 0 warnings)`);
```

### What actually happened?

output:
```shell
foo.css
 1:1  × 简体  selector-class-pattern

1 problem (1 error, 0 warnings)`);
```

note: '中文' is missing

### Does the bug relate to non-standard syntax?

No

### Proposal to fix the bug

disable `wrapWord` if error message contains non-ASCII characters.
if it is possible, i will open a PR for it later

### PR DESCRIPTION
**Pull request by Max10240**
> Which issue, if any, is this issue related to?

See issus: [stringFormatter.js truncate non-ASCII characters unexpectedly](https://github.com/stylelint/stylelint/issues/6860)

Closes #6860

> Is there anything in the PR that needs further explanation?

The reason that why don't I just contribute code to repository `table`, is: make it to support full ability about non-ASCII seems like a lot of work. before it, we can solve the problem in this way first。

### CODE REVIEW

File: lib/formatters/stringFormatter.js [hunk 1]
```diff
@@ -200,6 +203,8 @@ function formatter(messages, source, cwd) {
 		return row;
 	});
 
+	const hasNonAsciiChar = messages.some((msg) => NON_ASCII_OR_WS_PATTERN.test(msg.text));
```
Comment (ybiquitous) [inline lib/formatters/stringFormatter.js:206]: [suggest] I'm unsure why, but it seems we don't need to call `getMessageWidth()` twice. Could you please reduce evaluation times?

```suggestion
	const messageWidth = getMessageWidth(columnWidths);
	const hasNonAsciiChar = messages.some((msg) => NON_ASCII_OR_WS_PATTERN.test(msg.text));
```

Comment (ybiquitous) [inline lib/formatters/stringFormatter.js:206]: [suggset] We can now use a [unicode character class escape](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Unicode_character_class_escape) because the spec has been available since Node.js 10.

So, could you simplify the regex like this?

```suggestion
	const hasNonAsciiChar = messages.some((msg) => /\P{ASCII}/u.test(msg.text));
```

**Review by ybiquitous — CHANGES_REQUESTED** [review]
Thanks for the pull request. There seem to be no big problems. 👍🏼 
Please consider addressing my refactoring suggestions.

**Comment by Max10240** [comment]
> Thanks for the pull request. There seem to be no big problems. 👍🏼 
> Please consider addressing my refactoring suggestions.

OK， thanks for your review，i will refactor it soon～

**Review by ybiquitous — APPROVED** [review]
Thank you. LGTM 👍🏼
