### PR TITLE
Fix `media-feature-name-no-unknown` false positives for namespaced variables

### LINKED ISSUE #8818: Fix `media-feature-name-no-unknown` false positives for namespaced dollar variables and range context queries
### What minimal example or steps are needed to reproduce the bug?

media-query-sizes.scss

```scss
$data-table-view-create-button-compact: 600px;
```

CreateButton.vue

```scss
@use '~@/assets/sass/base/measurements/media-query-sizes.scss';

.create-button{
  &__button {
    &--view-type-full {
      @media (max-width: media-query-sizes.$data-table-view-create-button-compact) {
        display: none;
      }
    }
  }
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
   "extends": [ "stylelint-config-standard-scss", "stylelint-config-standard-vue/scss" ]
}
```

### How did you run Stylelint?

Can't do a demo because it requires several style files.

config:
```javascript
const STYLELINT_CONFIG = {
   extends: [ 'stylelint-config-standard-scss', 'stylelint-config-standard-vue/scss' ],
}

export default STYLELINT_CONFIG
```

### Which Stylelint-related dependencies are you using?

```json
      "stylelint": "^16.20.0",
      "stylelint-config-standard-scss": "^15.0.1",
      "stylelint-config-standard-vue": "^1.0.0",
      "stylelint-scss": "^6.12.0",
```

### What did you expect to happen?

The media query passes fine, either right in Stylelint, either thanks to something stylelint-scss is doing.

### What actually happened?

Warning:

```
Unexpected unknown media feature name "media-query-sizes"  media-feature-name-no-unknown
```

By the way, using #{} variable interpolation works fine. I just feel like it should probably not be required?

### Do you have a proposal to fix the bug?

_No response_

### PR DESCRIPTION
**Pull request by kovsu**
> Which issue, if any, is this issue related to?

Closes #8818 

> Is there anything in the PR that needs further explanation?

No

### CODE REVIEW

File: lib/utils/findMediaFeatureNames.mjs [hunk 1]
```diff
@@ -118,10 +118,11 @@ function topLevelTokenNodes(node) {
...
 	let lastWasDollarSign = false;
 
-	components.forEach((component) => {
-		// Only preserve top level tokens (idents, delims, ...)
-		// Discard all blocks, functions, ...
-		if (component && isTokenNode(component)) {
+	// Only preserve top level tokens (idents, delims, ...)
+	// Discard all blocks, functions, ...
+	components
+		.filter((component) => component && isTokenNode(component))
```
Comment (ybiquitous) [inline lib/utils/findMediaFeatureNames.mjs]: [suggestion] Nice with `filter` 👍🏼 Furthermore, what if simplifying the code by just `isTokenNode` like this? `isTokenNode` can check falsy values as well.

```suggestion
		.filter(isTokenNode)
```

File: lib/utils/findMediaFeatureNames.mjs [hunk 2]
```diff
@@ -134,9 +135,24 @@ function topLevelTokenNodes(node) {
...
+			}
+
+			if (component.value[0] === TokenType.Delim && component.value[4].value === '.') {
+				return;
+			}
+
 			relevantTokens.push(component.value);
-		}
-	});
+		});
```
Comment (ybiquitous) [inline lib/utils/findMediaFeatureNames.mjs]: [suggestion] Thanks to `index` and `tokenNodes`, I believe it's a good chance to make the `forEach` loop content more readable. What about the refactoring below?

```js
.forEach((component, index, tokenNodes) => {
	const [tokenType, , , ,] = component.value;

	// E.g. $var
	if (isScssVariableDelim(component)) {
		return;
	}
	if (tokenType === TokenType.Ident && isScssVariableDelim(tokenNodes[index - 1])) {
		return;
	}

	// E.g. namespace.$var
	if (tokenType === TokenType.Ident && isScssNamespaceDelim(tokenNodes[index + 1])) {
		return;
	}
	if (isScssNamespaceDelim(component)) {
		return;
	}

	relevantTokens.push(component.value);
});
```

File: lib/utils/findMediaFeatureNames.mjs [hunk 3]
```diff
@@ -115,28 +115,41 @@ function topLevelTokenNodes(node) {
...
-			}
+		// E.g. namespace.$var
+		if (tokenType === TokenType.Ident && isScssNamespaceDelim(tokenNodes[index + 1])) {
+			return;
+		}
 
-			relevantTokens.push(component.value);
+		if (isScssNamespaceDelim(component)) {
+			return;
 		}
```
Comment (ybiquitous) [inline lib/utils/findMediaFeatureNames.mjs:135]: [suggestion] Thank you for refactoring. In addition, can you align the use of `isScssVariableDelim` and `isScssNamespaceDelim`?

```js
// E.g. $var
if (isScssVariableDelim(component)) {

if (tokenType === TokenType.Ident && isScssVariableDelim(tokenNodes[index - 1])) {

// E.g. namespace.$var
if (isScssNamespaceDelim(component)) {

if (tokenType === TokenType.Ident && isScssNamespaceDelim(tokenNodes[index + 1])) {
```

**Comment by kovsu** [comment]
> @kovsu You're on a roll with these fixes, thank you!
> 
> LGTM.

Glad to do something that helps you. Feel free to ping me if anything i can help.
