### PR TITLE
Fix `block-no-empty` false positives for `reportNeedlessDisables`

### LINKED ISSUE #5388: Fix `block-no-empty` false positives for `reportNeedlessDisables`
Needless disable is being reported for `block-no-empty` even though the rule is set to `true`. Removing the `stylelint-disable-line` will give an `Unexpected empty block` error

> Which rule, if any, is the bug related to?

`block-no-empty`

> What code is needed to reproduce the bug?

```css
li { /* stylelint-disable-line block-no-empty */
}

dl { /* stylelint-disable-line block-no-empty */
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "reportNeedlessDisables": true,
  "rules": {
    "block-no-empty": true,
  }
}
```

> Which version of stylelint are you using?

`13.13.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

`stylelint "./styles/**/*.[s]css"`

> What did you expect to happen?

No needless disables reported

> What actually happened (e.g. what warnings or errors did you get)?

```shell
test.css
7:5    Needless disable for "block-no-empty"
10:5    Needless disable for "block-no-empty"
```

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

Closes #5388

> Is there anything in the PR that needs further explanation?

As suggested in <https://github.com/stylelint/stylelint/issues/5388#issuecomment-879005796>, this PR extracts a new utility from `assignDisabledRanges.js`, and then it ignores a Stylelint command comment in the `block-no-empty` rule by using the new utility.

### CODE REVIEW

File: lib/utils/hasEmptyBlock.js [hunk 1]
```diff
@@ -1,13 +1,13 @@
...
  * Check if a statement has an empty block.
  *
  * @param {import('postcss').Rule | import('postcss').AtRule} statement - postcss rule or at-rule node
  * @return {boolean} True if the statement has a block and it is empty
  */
 module.exports = function hasEmptyBlock(statement) {
-	return (
-		statement.nodes !== undefined && statement.nodes.length === 0 // has block
-	); // and is empty
+	return hasBlock(statement) && statement.nodes.length === 0;
```
Comment (ybiquitous) [inline lib/utils/hasEmptyBlock.js:12]: [note] It should be more readable and less duplicated thanks to `hasBlock`:

https://github.com/stylelint/stylelint/blob/736bc297da67b1bb520ad4ec03ac5445fb1ae178/lib/utils/hasBlock.js#L9-L11

File: lib/utils/stylelintCommand.js [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+/**
+ * Extract a command from a given comment.
+ *
+ * @param {Comment} comment
+ * @returns {string}
+ */
+function extractStylelintCommand(comment) {
+	const [command] = comment.text.split(/\s/, 1);
+
+	assertString(command);
```
Comment (ybiquitous) [inline lib/utils/stylelintCommand.js:28]: [note] Since `''.split(/\s/, 1)` returns `['']`, this `assertString` should prevent `command` is `undefined`.

**Review by jeddy3 — APPROVED** [review]
This is fantastic, thanks!

LGTM.

**Comment by AlexSkrypnyk** [comment]
Looks like this change broke correct ignore rules that worked before:

```
  &__top__content-top1 {
    // stylelint-disable-line block-no-empty
  }
```

results in 
```
 24:24  ✖  Unexpected empty block  block-no-empty
 ```


```
$ npm list stylelint
├─┬ stylelint-config-standard-scss@2.0.1
│ ├─┬ stylelint-config-recommended-scss@5.0.2
│ │ ├─┬ stylelint-scss@4.3.0
│ │ │ └── stylelint@14.14.0 deduped
│ │ └── stylelint@14.14.0 deduped
│ └── stylelint@14.14.0 deduped
├─┬ stylelint-config-standard@23.0.0
│ ├─┬ stylelint-config-recommended@6.0.0
│ │ └── stylelint@14.14.0 deduped
│ └── stylelint@14.14.0 deduped
└── stylelint@14.14.0

```

**Comment by AlexSkrypnyk** [comment]
Ok, this works
```
  &__middle__content-middle1 {
    // stylelint-disable-block block-no-empty
  }
```

I could not find any information in this PR or the release about changes to the disable rule for blocks: from `stylelint-disable-line` to `stylelint-disable-block`

**Comment by ybiquitous** [comment]
@AlexSkrypnyk `stylelint-disable-block` is not a valid Stylelint command. So the code above is equal to the following code using a non-special comment:

```scss
&__middle__content-middle1 {
  // This block is not empty because of including this comment
}
```

You can see it on the [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIBkB9FBbAllKAbGakAdgC4ykC0WO+AjAATAA6R99A9O-QCoAWmAZ3oAjXBDABreoPpEIJejHQAHEgE8RMMAEMArgJj0IAM2lEwuXVExEA5vRL8hkdOnIkWAXxYtUKEhDKhBCk7hQBygzAHFwC6vi4NiQU1gLaojAUiUSGouISFHIUSqpqXj5EnPRxaglJKYLp+IUwAB7J2blikoUQxSrqvmgRwaGUEVHlRCAANCACaqTarQjzYAICs+Ahxpi2q8ys9EwgAE4wyhCnJAByMDB4MBsAIo0ZAifwDqe6MDMsbBOP3wHwQjABbGOIDyPSKJUGYJIPxgEO8RE8IE8QA).

It seems you need to fix the code as below:

```scss
&__top__content-top1 { // stylelint-disable-line block-no-empty
}
```

Or

```scss
// stylelint-disable-next-line block-no-empty
&__top__content-top1 {
}
```

Or

```scss
&__top__content-top1 {
  // You can put any command except for the Stylelint commands here.
}
```
