### PR TITLE
Fix turning off autofix for sources containing scoped disable comments

### LINKED ISSUE #4704: Fix autofix running on files containing scoped disable comments
> Clearly describe the bug

`npx stylelint --fix` corrects violations of the rule `color-hex-length` even after disabling it with `// stylelint-disable color-hex-length`.

> Which rule, if any, is the bug related to?

`color-hex-length`

> What code is needed to reproduce the bug?

This is part of a bigger file located (in my system) at `_sass/layout/syntax-lighlighting.scss`.

```scss
// https://github.com/richleland/pygments-css/blob/master/vs.css
// stylelint-disable color-hex-length, color-named, font-weight-notation, selector-class-pattern
.highlight .hll { background-color: #ffffcc; }
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "extends": [
    "stylelint-config-twbs-bootstrap/scss"
  ],
  "rules": {
    "string-quotes": null,
    "indentation": null,
    "value-list-comma-newline-after": null,
    "value-list-comma-space-after": null,
    "function-calc-no-unspaced-operator": null,
    "scss/operator-no-unspaced": null,
    "declaration-no-important": null,
    "declaration-colon-newline-after": null,
    "order/properties-order": null,
    "scss/at-function-named-arguments": null
  }
}
```

> Which version of stylelint are you using?

13.3.1

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

`npx stylelint _sass/**/*.scss --fix`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No.

> What did you expect to happen?

No corrections made.

> What actually happened (e.g. what warnings or errors did you get)?

`npx stylelint _sass/**/*.scss` yields nothing, as expected. But `npx stylelint _sass/**/*.scss --fix` ignores the disabling comment and yields:
```scss
// https://github.com/richleland/pygments-css/blob/master/vs.css
// stylelint-disable color-hex-length, color-named, font-weight-notation, selector-class-pattern
.highlight .hll { background-color: #ffc; }
```

### PR DESCRIPTION
**Pull request by jeddy3**
> Which issue, if any, is this issue related to?

Closes #4704

> Is there anything in the PR that needs further explanation?

We were only disabling autofix on files containing unscoped disable comments. This pull request disables it for both scoped and unscoped.

### CODE REVIEW

**Comment by amyspark** [comment]
This version of stylelint works correctly with my toolchain (`npm i https://github.com/stylelint/stylelint/tarball/issue-4704`).

File: lib/lintSource.js [hunk 1]
```diff
@@ -251,15 +251,16 @@ function createEmptyPostcssResult(filePath) {
...
- * literals, it will duplicate some code. More info in issue #4119.
  *
  * @param {PostcssResult} postcssResult
  * @returns {boolean}
  */
 function isFixCompatible({ stylelint }) {
 	// Check for issue #2643
-	if (stylelint.disabledRanges.all.length) return false;
+	const hasUnscopedDisabledRanges = stylelint.disabledRanges.all.length > 0;
+	const hasScopedDisabledRanges = Object.keys(stylelint.disabledRanges).length > 1;
```
Comment (ota-meshi) [inline lib/lintSource.js:261]: I think you can turn off autofix for each scoped rule.
Change the scope data to be passed to the third argument of `ruleFunction`.

Comment (jeddy3) [reply lib/lintSource.js:261]: > I think you can turn off autofix for each scoped rule.

Am I right in thinking that would give us a more granular workaround where autofix is turned off (for the entire source):

- for all rules, if the source contains unscoped disable comments
- for only the applicable rules, if the source only contains scoped disable comments

Would you mind pulling down the pull request and showing me what you mean? And is it something we should add to this pull request or a follow-up?

Comment (ota-meshi) [reply lib/lintSource.js:261]: Hi @jeddy3.
I want to fix it like this:

https://github.com/stylelint/stylelint/compare/issue-4704..issue-4704-2

Comment (ota-meshi) [reply lib/lintSource.js:261]: The color-hex-length rule does not autofix.

https://github.com/stylelint/stylelint/compare/issue-4704..issue-4704-2#diff-01cbf9c2079c6adc0ce42f035fd16a45R245

Comment (jeddy3) [reply lib/lintSource.js:261]: That's a much better approach, thanks!

If possible, can you:

- use `require('common-tags').stripIndent` to indent the `indentation` rule code snippets, like so:

```js
                          .lint({
				code: stripIndent`
                                     /* stylelint-disable color-hex-length */
                                    a {
                                       color: #ffffff;
                                    }
                                `,
```


- add a comment above the following:

```
// Next two conditionals are temporary measures until #2643 is resolved
isFileFixCompatible &&
!postcssResult.stylelint.disabledRanges[ruleName],
```

As their intent isn't immediately clear.

We should then merge your changes into this branch.

Comment (ota-meshi) [reply lib/lintSource.js]: I fixed it and merged it into this branch.

**Comment by jeddy3** [comment]
I've added a commit to this pull request to update the docs to reflect the new behaviour introduced by this fix. I believe that autofix is now useful and stable for the majority of users. Those using scoped disable comments are only slightly inconvenienced when using the `fix` option. The minority of users using unscoped disable comments are more inconvenienced, but `fix` remains safe for them to use.

**Comment by jeddy3** [comment]
> - Fixed: autofix will respect scoped disable comments by turning off autofix for the scoped rules for the entire source; this is a continuation of the workaround added in `13.2.0` ([#4705](https://github.com/stylelint/stylelint/pull/4705)).
