### PR TITLE
Fix `declaration-property-value-no-unknown` false positives for `calc-size()` containing `size` keyword

### LINKED ISSUE #9104: Fix `declaration-property-value-no-unknown` when using `calc-size()` function
### What minimal example or steps are needed to reproduce the bug?

```css
.example {
  width: calc-size(auto, round(up, size, 1px));
}
```

### What minimal configuration is needed to reproduce the bug?

```js
export default {
	extends: ['stylelint-config-standard']
};
```

### How did you run Stylelint?

vscode plugin

### Which Stylelint-related dependencies are you using?

```json
{
	"@stylistic/stylelint-config": "^4.0.0",
	"@stylistic/stylelint-plugin": "^5.0.1",
	"stylelint": "^17.3.0",
	"stylelint-config-standard": "^40.0.0",
	"stylelint-config-standard-vue": "^1.0.0",
}
```

### What did you expect to happen?

There is also #8320 but it seems it stalled.

### What actually happened?

See vscode tooltip screenshot:

Image

### Do you have a proposal to fix the bug?

_No response_

### PR DESCRIPTION
**Pull request by hriztam**
It closes #9104 

- Added a skip path for values that include calc-size(...) with a size keyword inside the function arguments to avoid false positives.

- Added acceptance tests for the reported cases and for calc-size without size

### CODE REVIEW

File: lib/rules/declaration-property-value-no-unknown/__tests__/index.mjs [hunk 1]
```diff
@@ -200,6 +200,19 @@ testRule({
...
+				.example {
+					width: calc-size(auto, round(up, size, 1px));
+					height: calc-size(max-content, size + 2rem);
+					height: calc-size(calc-size(max-content, size), size + 2rem);
+				}
+			`,
+		},
+		{
+			code: 'a { height: calc-size(any, 300px * 1.5); }',
+			description: 'calc-size without size keyword is still validated',
```
Comment (jeddy3) [inline lib/rules/declaration-property-value-no-unknown/__tests__/index.mjs]: Let's make this a _reject_ test where the `<calc-size-basis>` is unknown to test that other `calc-sizes` are still checked, i.e.:

```css
a { height: calc-size(foo, 10px * 1.5); }
```

File: lib/rules/declaration-property-value-no-unknown/__tests__/index.mjs [hunk 2]
```diff
@@ -200,6 +200,19 @@ testRule({
...
 		},
+		{
+			code: stripIndent`
+				.example {
+					width: calc-size(auto, round(up, size, 1px));
+					height: calc-size(max-content, size + 2rem);
+					height: calc-size(calc-size(max-content, size), size + 2rem);
+				}
+			`,
+		},
```
Comment (jeddy3) [inline lib/rules/declaration-property-value-no-unknown/__tests__/index.mjs]: Let's follow our [documented conventions](https://stylelint.io/contributor-guide/rules#write-tests) and those inherint in the file, i.e. :

- one declaration per test case
- using `a` as the selector for each

File: lib/rules/declaration-property-value-no-unknown/index.mjs [hunk 3]
```diff
@@ -312,6 +314,60 @@ function containsFunctionsNotSupportedInCSSTree(cssTreeNode) {
...
 }
 
+/**
+ * Detect calc-size() with the `size` keyword inside its arguments.
+ * If present, skip validation to avoid false positives until csstree supports it.
+ *
+ * @param {string} value
+ * @returns {boolean}
+ */
+function containsCalcSizeWithSizeKeyword(value) {
```
Comment (jeddy3) [inline lib/rules/declaration-property-value-no-unknown/index.mjs]: Let's follow [our conventions around construct parsers](https://stylelint.io/contributor-guide/rules#construct-specific-parsers).

This rule uses the tokeniser. We should use it and find a way to avoid redundant tokenisation.

**Comment by hriztam** [comment]
I have made the changes as per requested, let me know if these seems right @jeddy3

File: lib/rules/declaration-property-value-no-unknown/index.mjs [hunk 4]
```diff
@@ -312,6 +317,31 @@ function containsFunctionsNotSupportedInCSSTree(cssTreeNode) {
...
+		if (contains || !isFunctionNode(node) || node.getName().toLowerCase() !== 'calc-size') return;
+
+		contains = node
+			.tokens()
+			.some(
+				(token) =>
+					token[0] === TokenType.Ident &&
+					token[4]?.value !== undefined &&
+					token[4].value.toLowerCase() === 'size',
+			);
```
Comment (ybiquitous) [inline lib/rules/declaration-property-value-no-unknown/index.mjs]: [suggestion] Is it reasonable to halt the `walk()` loop if `contains` becomes `true` for efficiency?

```suggestion
		if (!isFunctionNode(node) || node.getName().toLowerCase() !== 'calc-size') return;

		contains = node
			.tokens()
			.some(
				(token) =>
					token[0] === TokenType.Ident &&
					token[4]?.value !== undefined &&
					token[4].value.toLowerCase() === 'size',
			);

		if (contains) return false; // halt
```

File: lib/rules/declaration-property-value-no-unknown/index.mjs [hunk 5]
```diff
@@ -312,6 +317,31 @@ function containsFunctionsNotSupportedInCSSTree(cssTreeNode) {
...
+	walk(componentValues, ({ node }) => {
+		if (contains || !isFunctionNode(node) || node.getName().toLowerCase() !== 'calc-size') return;
+
+		contains = node
+			.tokens()
+			.some(
+				(token) =>
+					token[0] === TokenType.Ident &&
+					token[4]?.value !== undefined &&
+					token[4].value.toLowerCase() === 'size',
```
Comment (ybiquitous) [inline lib/rules/declaration-property-value-no-unknown/index.mjs]: [suggestion] How about simplifying the code a bit more?

```suggestion
					token[4]?.value.toLowerCase() === 'size',
```
