### PR TITLE
Fix `no-duplicate-selectors` false negatives for matching escaped selectors

### LINKED ISSUE #3972: New rule for avoiding escaping selector and normal selectors
> What is the problem you're trying to solve?

Input (same selectors):
```css
.u-m\00002b {}

.u-m\+ {}
```

> What solution would you like to see?

New rule what warning when you use identical selectors like above.

Maybe `no-duplicate-escape-selectors`, need discussion about name

### PR DESCRIPTION
**Pull request by bjnewman**
## Summary

Fixes #3972

The `no-duplicate-selectors` rule now correctly detects duplicate class selectors that use different CSS escape sequence formats. For example, `.u-m\00002b` and `.u-m\+` are now recognized as duplicates since both represent `.u-m+`.

## Changes

- Added `normalizeNodeEscaping()` helper in `normalizeSelector.mjs` that uses postcss-selector-parser's getter/setter behavior to normalize CSS escaping
- Added test cases for escaped selector duplicates

## How it works

The fix leverages postcss-selector-parser's built-in value getter/setter behavior for ClassName nodes. The getter returns the unescaped value, while the setter re-escapes it in a normalized form. By doing `node.value = node.value`, we trigger this normalization, ensuring equivalent selectors compare as equal regardless of their original escape format.

Reference: https://github.com/postcss/postcss-selector-parser/blob/1b1e9c3bc10ccc3bc5f07a987caa7f2684c0b52f/src/selectors/className.js#L13-L28

### CODE REVIEW

File: lib/utils/normalizeSelector.mjs [hunk 1]
```diff
@@ -2,6 +2,23 @@ import parser from 'postcss-selector-parser';
...
+ * This ensures selectors like `.u-m\00002b` and `.u-m\+` are treated as equivalent.
+ *
+ * @see https://github.com/postcss/postcss-selector-parser/blob/1b1e9c3bc10ccc3bc5f07a987caa7f2684c0b52f/src/selectors/className.js#L13-L28
+ * @param {Node} node
+ */
+function normalizeNodeEscaping(node) {
+	// Self-assignment triggers the setter which normalizes CSS escaping.
+	if (parser.isClassName(node)) {
+		// eslint-disable-next-line no-self-assign -- Intentional: setter normalizes escaping
+		node.value = node.value;
```
Comment (ryo-manba) [inline lib/utils/normalizeSelector.mjs]: For performance, we could skip nodes without escapes by checking `node.raws.value`.

```suggestion
		// @ts-expect-error -- raws.value exists at runtime but not in type definition
		if (!node.raws?.value) return;
		// eslint-disable-next-line no-self-assign -- Intentional: setter normalizes escaping
		node.value = node.value;
```

File: lib/utils/normalizeSelector.mjs [hunk 2]
```diff
@@ -2,6 +2,23 @@ import parser from 'postcss-selector-parser';
...
+ * Field getters return unescaped values, setters handle re-escaping.
+ * Setting a field to itself normalizes the escaping representation.
+ * This ensures selectors like `.u-m\00002b` and `.u-m\+` are treated as equivalent.
+ *
+ * @see https://github.com/postcss/postcss-selector-parser/blob/1b1e9c3bc10ccc3bc5f07a987caa7f2684c0b52f/src/selectors/className.js#L13-L28
+ * @param {Node} node
+ */
+function normalizeNodeEscaping(node) {
+	// Self-assignment triggers the setter which normalizes CSS escaping.
+	if (parser.isClassName(node)) {
```
Comment (ryo-manba) [inline lib/utils/normalizeSelector.mjs]: [Q] Is this PR scoped to ClassName only?
It might be difficult to support ID and attribute selectors due to limitations in `postcss-selector-parser` 🤔

**Review by ryo-manba — COMMENTED** [review]
@bjnewman 
Thank you for your pull request. Generally looks good.

I've left some comments. Can you also add a `patch` changeset:

```
Fixed: `no-duplicate-selectors` false negatives for matching escaped selectors
```

Lastly, can you change the base to `v17`, please? We're gearing up for a major release and are trying to minimise conflicts between `main` and it.

**Comment by bjnewman** [comment]
Yes, scoped to ClassName only. I checked postcss-selector-parser source - only ClassName has the getter/setter that normalizes escaping (via cssesc). ID inherits from Node without this, and Attribute has a different (deprecated) setter behavior. Supporting ID/Attribute would require upstream changes to postcss-selector-parser.

File: lib/utils/normalizeSelector.mjs [hunk 3]
```diff
@@ -2,6 +2,25 @@ import parser from 'postcss-selector-parser';
...
+		if (!node.raws?.value) return;
```
Comment (ybiquitous) [inline lib/utils/normalizeSelector.mjs]: [suggestion] Can you suppress the type error by leaving a justification comment?

E.g.

```suggestion
		// @ts-expect-error -- The `raws` property exists, but isn't exposed in the type. This check provides a performance benefit by avoiding extra escaping.
		if (!node.raws?.value) return;
```

File: lib/utils/normalizeSelector.mjs [hunk 4]
```diff
@@ -2,6 +2,25 @@ import parser from 'postcss-selector-parser';
...
+/**
+ * Normalize CSS escaping in selector node values.
+ * Field getters return unescaped values, setters handle re-escaping.
+ * Setting a field to itself normalizes the escaping representation.
+ * This ensures selectors like `.u-m\00002b` and `.u-m\+` are treated as equivalent.
+ *
+ * @see https://github.com/postcss/postcss-selector-parser/blob/1b1e9c3bc10ccc3bc5f07a987caa7f2684c0b52f/src/selectors/className.js#L13-L28
+ * @param {Node} node
+ */
+function normalizeNodeEscaping(node) {
```
Comment (ybiquitous) [inline lib/utils/normalizeSelector.mjs]: [suggestion] Can you move the `normalizeNodeEscaping()` definition to the last of this file, like other module-private functions?

File: lib/utils/normalizeSelector.mjs [hunk 5]
```diff
@@ -10,6 +29,10 @@ import parser from 'postcss-selector-parser';
  * @returns {T}
  */
 export default function normalizeSelector(node) {
+	// Normalize CSS escape sequences so that equivalent selectors match
+	normalizeNodeEscaping(node);
+	node.walk(normalizeNodeEscaping);
+
 	normalizeSelectorNodeWhitespaceAndComments(node);
 
 	node.walk(normalizeSelectorNodeWhitespaceAndComments);
```
Comment (ybiquitous) [inline lib/utils/normalizeSelector.mjs]: [suggestion]

- Remove the extra comment `Normalize CSS ...`. The function name clearly describes what it does.
- Reduce the number of `node.walk()` calls for performance.

```suggestion
	normalizeNodeEscaping(node);
	normalizeSelectorNodeWhitespaceAndComments(node);

	node.walk((child) => {
		normalizeNodeEscaping(child);
		normalizeSelectorNodeWhitespaceAndComments(child);
	});
```

**Review by ybiquitous — CHANGES_REQUESTED** [review]
@bjnewman Thanks for the pull request, and sorry for the late response.

Can you please take a look at my reviews? Thanks.

**Comment by bjnewman** [comment]
Updated the PR with all the review feedback — rebased onto main, combined the walks, added the raws.value early-return with @ts-expect-error, moved the function, and added a patch changeset. Thanks for the helpful reviews!

File: .changeset/fix-escaped-selector-duplicates.md [hunk 6]
```diff
@@ -0,0 +1,5 @@
+---
+"stylelint": patch
```
Comment (ybiquitous) [inline .changeset/fix-escaped-selector-duplicates.md]: For false negatives, it should be minor, not patch. Can you fix it?

Comment (jeddy3) [inline .changeset/fix-escaped-selector-duplicates.md]:
```suggestion
"stylelint": minor
```

Comment (jeddy3) [reply .changeset/fix-escaped-selector-duplicates.md]: Committed suggestion to get into the upcoming release.

**Review by jeddy3 — APPROVED** [review]
LGTM, thank you.
