### PR TITLE
selector-no-id: Don't warn about interpolation inside Sass loops, fixes #592

### LINKED ISSUE #592: selector-no-id reports interpolation inside Sass loops
stylelint is reporting interpolation inside of Sass loops as ID selectors.

This can be confirmed with unit tests:
https://github.com/stylelint/stylelint/blob/master/src/rules/selector-no-id/__tests__/index.js

```js
import scss from "postcss-scss"
const scssTestRule = ruleTester(rule, ruleName, {
  postcssOptions: { syntax: scss },
})

scssTestRule(undefined, tr => {
  tr.ok("@for $n from 1 through 10 { .page-#{$n} { color: blue; } }", "ignore sass interpolation inside @for")
  tr.ok("@each $n in $vals { .page-#{$n} { color: blue; } }", "ignore sass interpolation inside @each")
  tr.ok("@while $n < 10 { .page-#{$n} { color: blue; } }", "ignore sass interpolation inside @while")
})
```

```sh
# tests 8808
# pass  8805
# fail  3
```

### PR DESCRIPTION
**Pull request by kristerkari**

### CODE REVIEW

File: src/rules/selector-no-id/index.js [hunk 1]
```diff
@@ -19,6 +19,7 @@ export default function (actual) {
     root.walkRules(rule => {
       selectorParser(selectorAST => {
         selectorAST.eachId(id => {
+          if (/#{.+}/.test(id)) { return }
```
Comment (davidtheclark) [inline src/rules/selector-no-id/index.js]: I'd be willing to work in this special case. @jeddy3 what do you think? I guess the only time it would backfire is if somebody wanted to use a real id that like `{something}`.

Comment (kristerkari) [inline src/rules/selector-no-id/index.js]: > I guess the only time it would backfire is if somebody wanted to use a real id that like {something}

Do you mean CSS ID selectors? It should not be possible to have a name like that: https://stackoverflow.com/questions/448981/which-characters-are-valid-in-css-class-names-selectors/449000#449000

Comment (ben-eb) [inline src/rules/selector-no-id/index.js]: More performant as it doesn't use a regex;

```js
if (id.value[0] === '{' && id.value.slice(-1) === '}')
```

Comment (kristerkari) [inline src/rules/selector-no-id/index.js]: Thanks, I'll update to that.

**Comment by davidtheclark** [comment]
Nice job @kristerkari. Thanks.
