### PR TITLE
Fix false positives for hex colours in color-function-notation

### LINKED ISSUE #5638: Fix false positives for hex colours in color-function-notation
> Clearly describe the bug

After upgrading to the latest major, I experienced an issue with `color-function-notation`, and turns out it wasn't an issue per-say, but I think `stylelint` could've made a better job at telling me the issue.

So I had this rule prior to the upgrade

```scss
background-color: rgba(#fff, 0.85);
```

After running stylelint, I had the warning I should use `color-function-notation` (nice!). So what I did is the following

```scss
background-color: rgba(#fff / 0.85);
```

After that, stylelint passed. However, it was a false-positive as when I built my SCSS, it actually failed. I discovered that hex colors aren't allowed. The correct syntax is the following

```scss
background-color: rgba(255 255 255 / 0.85);
```

> Which rule, if any, is the bug related to?

`color-function-notation`

> What code is needed to reproduce the bug?

```css
a {
  background-color: rgba(#fff / 0.85);
}
```

> What Stylelint configuration is needed to reproduce the bug?

Default one or the following

```json
{
  "rules": {
    "color-function-notation": "modern"
  }
}
```

> Which version of Stylelint are you using?

```
"stylelint": "14.0.0",
```

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

```
npx stylelint
```

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

I don't think so?

> What did you expect to happen?

A warning from stylelint directly in my code (with a tooltip)

> What actually happened (e.g. what warnings or errors did you get)?

✅  from stylelint when it actually was invalid code

### PR DESCRIPTION
**Pull request by lachieh**
Resolves #5638

* Added `isStandardSyntaxColorFunction` util and tests
* Updated `color-function-notation` rule to use above function

### CODE REVIEW

File: lib/utils/isStandardSyntaxColorFunction.js [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+ *
+ * @param {import('postcss-value-parser').FunctionNode} node
+ * @returns {boolean}
+ */
+module.exports = function isStandardSyntaxColorFunction(node) {
+	if (!isStandardSyntaxFunction(node)) return false;
+
+	// scss rgba() function can accept a hex as the first param
+	for (const fnNode of node.nodes) {
+		if (fnNode.type === 'word' && fnNode.value.startsWith('#')) return false;
```
Comment (kamechb) [inline lib/utils/isStandardSyntaxColorFunction.js:16]: Scss users probably use a color variable like `$black` in the function, then it should still return false.

Comment (jeddy3) [reply lib/utils/isStandardSyntaxColorFunction.js:16]: @kamechb See https://github.com/stylelint/stylelint/issues/5671.

That issue is labelled as ready to implement. Please consider [contributing](https://stylelint.io/contributing) if you have time.

There are [steps on how to fix a bug in a rule](https://stylelint.io/developer-guide/rules#fix-a-bug-in-a-rule) in the Developer guide.
