### PR TITLE
fix `no-unit-unknown` rule for variable usage

### LINKED ISSUE #4162: `no-unit-unknown` should ignore less variable
> Clearly describe the bug

`@56789a` is considered as a number with unknown unit in less, instead of a valid variable name in less.

> Which rule, if any, is the bug related to?

`no-unit-unknown`

> What CSS is needed to reproduce the bug?

```less
@56789a: #56789a; // when you can't find a proper word for this color
a {
  color: @56789a;
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "no-unit-unknown": "always"
  }
}
```

> Which version of stylelint are you using?

10.1.0

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to LESS variable usage

> What did you expect to happen?

No warning should be reported.

> What actually happened (e.g. what warnings or errors did you get)?

The following warnings were flagged:

```shell
test.css
2:4    Unexpected unknown unit "a"   unit-no-unknown
```

### PR DESCRIPTION
**Pull request by laysent**
> Which issue, if any, is this issue related to?

Closes #4162 

> Is there anything in the PR that needs further explanation?

I noticed that lint-staged changed the way how it's configured. From [their document](https://github.com/okonet/lint-staged/blob/master/README.md#ignoring-files), they encourage to use ignore configuration of each linter. And since this file is already in `.eslintignore` and `.prettierignore`, I believe it's safe to remote corresponding line in lint-staged config.

### CODE REVIEW

**Comment by hudochenkov** [comment]
I wonder why it wasn't catched by `!isStandardSyntaxValue(value)` function? I think we need to fix this function instead of proposed fix.

**Comment by evilebottnawi** [comment]
hm, https://github.com/stylelint/stylelint/blob/master/lib/utils/isStandardSyntaxValue.js#L23 should be

**Comment by laysent** [comment]
> I wonder why it wasn't catched by `!isStandardSyntaxValue(value)` function? I think we need to fix this function instead of proposed fix.

`blurInterpolation` removes `@` and thus it won't be recognized correctly by `isStandardSyntaxValue` here.

I have changed the way how this issue is fixed, i.e. use `node.value` instead of transformed `value` in `isStandardSyntaxValue`. Please kindly have a look.

**Comment by laysent** [comment]
> Nice solution!
> 
> Could remove lint-stages changes, please? We squash commits on merge and this change would be confusing in unrelated commit.

Sure, I have removed lint-stages changes.

Would you like me to send another PR for this lint-staged changes? Seems at least on my side, lint-staged won't work without changing the config in package.json.

**Comment by hudochenkov** [comment]
> Would you like me to send another PR for this lint-staged changes?

Yes, please :)

**Comment by hudochenkov** [comment]
> -   Fixed: `no-unit-unknown` false positives for at-variables (Less) starting with numbers ([#4163](https://github.com/stylelint/stylelint/pull/4163)).

File: lib/utils/getUnitFromValueNode.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ module.exports = function(node /*: Object*/) /*: ?string*/ {
 
   if (
     node.type !== "word" ||
-    !isStandardSyntaxValue(value) ||
+    !isStandardSyntaxValue(node.value) ||
```
Comment (evilebottnawi) [inline lib/utils/getUnitFromValueNode.js]: /cc @hudochenkov it is break other case, for example `.selector { property: 20px\9; }`

Comment (hudochenkov) [reply lib/utils/getUnitFromValueNode.js]: But it's a hack for IE8.

All tests were passed.

Comment (evilebottnawi) [reply lib/utils/getUnitFromValueNode.js]: @hudochenkov yes, based, on code test should be failed :confounded: https://github.com/laysent/stylelint/blob/0c68261c43123df7e0ffaabbdc350a8a480fb43a/lib/utils/getUnitFromValueNode.js#L29, maybe postcss-value-parser recognize this as other type for node, i will looks on this today

**Comment by laysent** [comment]
@hudochenkov Hi, just curious when would be the next release of stylelint? With this fixed, I could introduce the tool to our team and use it in our projects. ;-)
