### PR TITLE
fix no-duplicate-selectors

### LINKED ISSUE #4113: False positive in no-duplicate-selector
> Clearly describe the bug
  
`Stylelint marks all the selectors as duplicated. Actually, one selector is duplicate`

> Which rule, if any, is the bug related to?

`no-duplicate-selector`

> What CSS is needed to reproduce the bug?

```css
.a,.a,.b,.c,.d{
color:red;
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "no-duplicate-selector": "always"
  }
}
```

> Which version of stylelint are you using?

 `10.0.1`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

`Node API`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

`NO`
> What did you expect to happen?

`Only one warning should be reported.`

```
Unexpected duplicate selector ".a", first used at line 2
```

> What actually happened (e.g. what warnings or errors did you get)?

```
Unexpected duplicate selector ".a", first used at line 2 (no-duplicate-selectors)
Unexpected duplicate selector ".b", first used at line 2 (no-duplicate-selectors)
Unexpected duplicate selector ".c", first used at line 2 (no-duplicate-selectors)
Unexpected duplicate selector ".d", first used at line 2 (no-duplicate-selectors)
```

### PR DESCRIPTION
**Pull request by vankop**
> Which issue, if any, is this issue related to?

Fixes #4113 

> Is there anything in the PR that needs further explanation?

current test cases can not find this problem, to reproduce in current `master` branch commit ->`1178f2d2d4c7d83d12ad4ec55b686a7bf7e28995` add:
```expect(output.results[0].warnings).toHaveLength(1);```
here https://github.com/stylelint/stylelint/blob/master/jest-setup.js#L92

run `node node_modules/jest/bin/jest.js lib/rules/no-duplicate-selectors/__tests__/index.js`

### CODE REVIEW

File: lib/rules/no-duplicate-selectors/__tests__/index.js [hunk 1]
```diff
@@ -73,6 +73,16 @@ testRule(rule, {
       line: 1,
       column: 1
     },
+    {
+      code: `.a,.b,.a,.c,.d,.a{
```
Comment (hudochenkov) [inline lib/rules/no-duplicate-selectors/__tests__/index.js]: Could you simplify it to the following, please:

```
code: ".a, .b, .a, .c, .d {}"
```

Comment (vankop) [reply lib/rules/no-duplicate-selectors/__tests__/index.js]: done

File: lib/rules/no-duplicate-selectors/__tests__/index.js [hunk 2]
```diff
@@ -73,6 +73,14 @@ testRule(rule, {
       line: 1,
       column: 1
     },
+    {
+      code: ".a, .b, .a, .c, .d, .a {}",
```
Comment (hudochenkov) [inline lib/rules/no-duplicate-selectors/__tests__/index.js]: Could you keep only one `.a`? :)

**Comment by hudochenkov** [comment]
Please, don't force push if someone left review to your PR. This way we could see what have changed since last review.

Don't worry about clean Git history. We always use “squash and merge” so all commit gets squashed into one on PR merge.

**Comment by hudochenkov** [comment]
One more thing. Since you're member of stylelint team you can now use main repository to work on your PRs. This way it's simpler for you, because you don't need to keep your fork updated :)

**Comment by vankop** [comment]
> One more thing. Since you're member of stylelint team you can now use main repository to work on your PRs. This way it's simpler for you, because you don't need to keep your fork updated :)

But then I need delete branches to keep repo clean =)

> Please, don't force push if someone left review to your PR. This way we could see what have changed since last review.

I have forgot about it sorry =(

File: lib/rules/no-duplicate-selectors/__tests__/index.js (hunk 2 above)
Comment (vankop) [reply lib/rules/no-duplicate-selectors/__tests__/index.js]: It was made in favor of https://github.com/stylelint/stylelint/issues/4172 implementation (if it will be). For now I'll fix it.

Comment (vankop) [reply lib/rules/no-duplicate-selectors/__tests__/index.js]: done

**Comment by hudochenkov** [comment]
> But then I need to delete branches to keep repo clean =)

After merge new button “Delete branch” appears in the PR :)

**Comment by vankop** [comment]
@hudochenkov Did not found out why tests failed

**Comment by evilebottnawi** [comment]
Maybe conditional race on windows, we need search place who do this :confused:

**Comment by hudochenkov** [comment]
I happens sometimes for unknown reason.

**Comment by hudochenkov** [comment]
> -   Fixed: `no-duplicate-selectors` false positives for selectors in the same selector list ([#4173](https://github.com/stylelint/stylelint/pull/4173)).
