### PR TITLE
Fix trailing zeroes being removed by autofix in length-zero-no-unit

### LINKED ISSUE #5255: Refactor length-zero-no-unit to remove stylesearch
The code can be simplified by removing stylesearch entirely. At the moment it's a mesh of the value parser and stylesearch.

It'll make adding options like https://github.com/stylelint/stylelint/pull/5250 cleaner.

### PR DESCRIPTION
**Pull request by jeddy3**
> Which issue, if any, is this issue related to?

Closes #5255

> Is there anything in the PR that needs further explanation?

It makes use of patterns found in our more recent rules.

### CODE REVIEW

File: lib/rules/length-zero-no-unit/__tests__/index.js [hunk 1]
```diff
@@ -318,7 +326,7 @@ testRule({
 		},
 		{
 			code: 'a { top: 0.000px; }',
-			fixed: 'a { top: 0; }',
+			fixed: 'a { top: 0.000; }',
```
Comment (jeddy3) [inline lib/rules/length-zero-no-unit/__tests__/index.js:329]: Should have been outside the scope of this rule in favour of [number-no-trailing-zeros](https://stylelint.io/user-guide/rules/number-no-trailing-zeros).

File: lib/rules/length-zero-no-unit/index.js [hunk 2]
```diff
@@ -2,201 +2,162 @@
...
+	return keywordSets.lengthUnits.has(unit.toLowerCase());
+}
+
+function isFraction(unit) {
+	return unit.toLowerCase() === 'fr';
+}
 
-	return `${stringStart}0${stringEnd}`;
+function isZero(number) {
+	return Number.parseFloat(number) !== 0;
```
Comment (ybiquitous) [inline lib/rules/length-zero-no-unit/index.js:160]: [suggestion] The name `isZero` mismatches with the function body. How about fixing it as below?

```suggestion
	return Number.parseFloat(number) === 0;
```

And,

```js
if (!isZero(number)) return;
```

File: lib/rules/length-zero-no-unit/index.js [hunk 3]
```diff
@@ -2,201 +2,162 @@
...
+		nodes[index - 1].value === '/'
+	);
+}
+
+function isLineHeight(prop) {
+	return prop.toLowerCase() === 'line-height';
+}
+
+function isWord({ type }) {
+	return type !== 'word';
```
Comment (ybiquitous) [inline lib/rules/length-zero-no-unit/index.js:148]: [suggestion] The name `isWord` mismatches with the function body. How about fixing it as below?

```suggestion
	return type === 'word';
```

And,

```js
if (!isWord(valueNode)) return;
```

File: lib/rules/length-zero-no-unit/__tests__/index.js (hunk 1 above)
Comment (ybiquitous) [reply lib/rules/length-zero-no-unit/__tests__/index.js:329]: Agreed. 👍🏼 

So, this change may be a bug fix, not a refactoring?
(maybe, this PR title is confusing... 🤔 )

File: lib/utils/setAtRuleParams.js [hunk 4]
```diff
@@ -0,0 +1,20 @@
...
+ */
+module.exports = function setAtRuleParams(atRule, params) {
+	if (_.has(atRule, 'raws.params')) {
+		_.set(atRule, 'raws.params.raw', params);
+	} else {
+		atRule.params = params;
+	}
+
+	return atRule;
+};
```
Comment (ybiquitous) [inline lib/utils/setAtRuleParams.js:20]: Adding `getAtRuleParams()` and `setAtRuleParams()` is so nice! 👍🏼

File: lib/rules/length-zero-no-unit/index.js [hunk 5]
```diff
@@ -2,201 +2,162 @@
...
+				set(node, parsedValue.toString());
 			}
 		}
+
+		root.walkAtRules((atRule) =>
+			checkAtRule(atRule, getAtRuleParams(atRule), setAtRuleParams, atRuleParamIndex),
+		);
+		root.walkDecls((decl) =>
+			checkDecl(decl, getDeclarationValue(decl), setDeclarationValue, declarationValueIndex),
+		);
```
Comment (ybiquitous) [inline lib/rules/length-zero-no-unit/index.js:130]: [suggestion] IMO, it seems not intuitive to me to pass arguments except for a node to `checkAtRule()` and `checkDecl()`, since `getAtRuleParams()` or `getDeclarationValue()` are used only once.

Here is my suggestion to use the utility function in `checkAtRule()` and `checkDecl()`:

```suggestion
		root.walkAtRules(checkAtRule);
		root.walkDecls(checkDecl);
```

or,

```suggestion
		root.walkAtRules((atRule) => checkAtRule(atRule));
		root.walkDecls((decl) => checkDecl(decl));
```

For example, `checkDecl()` will be:

```js
function checkDecl(node) {
	needsFix = false;

	// ...

	const value = getDeclarationValue(node);
	const index = declarationValueIndex(node);
	const parsedValue = valueParser(value);

	parsedValue.walk((valueNode, valueNodeIndex, valueNodes) => {
		if (isLineHeightValue(node, valueNodes, valueNodeIndex)) return;

		return check(node, index, valueNode);
	});

	// ...
}
```

If doing so, we can lazily evaluate `getDeclarationValue(node)` or `declarationValueIndex(node)`. The same applies to `checkAtRule()`.

File: lib/rules/length-zero-no-unit/index.js [hunk 6]
```diff
@@ -2,201 +2,162 @@
...
+				actual: primary,
+			},
+			{
+				actual: secondary,
+				possible: {
+					ignore: ['custom-properties'],
+				},
+				optional: true,
+			},
+		);
```
Comment (ybiquitous) [inline lib/rules/length-zero-no-unit/index.js:43]: This `validateOptions` change is so nice 👍🏼

**Review by ybiquitous — COMMENTED** [review]
Thank you. This PR can make the code very clearer and readable! 👏🏼 

I've left the comments, but this change is totally so good! 😄

File: lib/rules/length-zero-no-unit/index.js (hunk 5 above)
Comment (jeddy3) [reply lib/rules/length-zero-no-unit/index.js]: Excellent suggestion, thanks.

**Comment by jeddy3** [comment]
@ybiquitous Thanks for the review! Good catches and suggestions.

> So, this change may be a bug fix, not a refactoring?

Yes, it started out as a refactor but fixed a bug. I'll change the title, and as such, the changelog entry.

**Review by ybiquitous — APPROVED** [review]
Thank you. LGTM! 👏🏼

**Review by m-allanson — APPROVED** [review]
👍

**Comment by jeddy3** [comment]
> - Fixed: `length-zero-no-unit` autofix removing trailing zeroes ([#5256](https://github.com/stylelint/stylelint/pull/5256)).
