### PR TITLE
Fix incorrect location for matching violating times in `time-min-milliseconds`

### LINKED ISSUE #4751: Fix incorrect location for matching violating times in time-min-milliseconds
> Clearly describe the bug

If there are two or more of the same violating times within a value they will all be reported at the location of the first violations.

We'll need to use the value parser to find the times so that we can make use of its `sourceIndex` property.

Ref: https://github.com/stylelint/stylelint/pull/4743

> Which rule, if any, is the bug related to?

`time-min-milliseconds`

> What code is needed to reproduce the bug?

```css
a { animation: foo 0.01s ease 0.8s, bar 0.8s ease 0.01s; }
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "time-min-milliseconds": "200ms"
  }
}
```

> Which version of stylelint are you using?

`13.3.3`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `stylelint "**/*.css"`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No.

> What did you expect to happen?

Warnings to be flagged at the correct locations.

> What actually happened (e.g. what warnings or errors did you get)?

Each warning is flagged at the first location.

### PR DESCRIPTION
**Pull request by kawaguchi1102**
> Which issue, if any, is this issue related to?

Closes #4751 

> Is there anything in the PR that needs further explanation?

Fixed the following additions

- Fix Test case end positions

### CODE REVIEW

File: lib/rules/time-min-milliseconds/index.js [hunk 1]
```diff
@@ -62,47 +62,44 @@ const rule = (primary, secondaryOptions) => {
...
-						// Check all time values
-						for (const value of valueList) {
-							if (!isAcceptableTime(value)) {
-								complain(decl, propertyValue.indexOf(value), value.length);
-							}
-						}
-					}
-				}
+				const parsedValue = valueParser(getDeclarationValue(decl));
+				let isValueTimeCount = 0;
```
Comment (ybiquitous) [inline lib/rules/time-min-milliseconds/index.js:66]: [suggest] The `is*` prefix often indicates a boolean variable and so the `isValueTimeCount` name seems a bit confusing to me. How about using `timeValueCount` instead?

```suggestion
				let timeValueCount = 0;
```

File: lib/rules/time-min-milliseconds/index.js [hunk 2]
```diff
@@ -62,47 +62,44 @@ const rule = (primary, secondaryOptions) => {
...
+
+				parsedValue.walk(({ value, sourceIndex }) => {
+					isValueTimeCount = valueTimeCheck(value, isValueTimeCount);
```
Comment (ybiquitous) [inline lib/rules/time-min-milliseconds/index.js:69]: [suggest] To make the purpose of the `valueTimeCheck` function clearer, how about renaming it to `calcTimeValueCount`?

```suggestion
					timeValueCount = calcTimeValueCount(value, timeValueCount);
```

File: lib/rules/time-min-milliseconds/index.js [hunk 3]
```diff
@@ -62,47 +62,44 @@ const rule = (primary, secondaryOptions) => {
...
+
+					if (isAcceptableTime(value) || (ignoreDelay && isValueTimeCount !== 1)) return;
```
Comment (ybiquitous) [inline lib/rules/time-min-milliseconds/index.js:71]: [suggest] I'm a bit concerned about performance degradation due to extra calls of `valueParse.unit()` inside `valueTimeCheck()` and `isAcceptableTime()`. How about passing a `import('postcss-value-parser').Dimension` object instead of a value string like this?

```js
const dimension = valueParser.unit(value);
isValueTimeCount = valueTimeCheck(dimension, value, isValueTimeCount);

if (isAcceptableTime(dimension) || (ignoreDelay && isValueTimeCount !== 1)) return;
```

**Review by ybiquitous — COMMENTED** [review]
@kawaguchi1102 Thanks for creating the PR. The change looks almost good to me.

I've left some refactoring suggestions, so please consider addressing them.

File: lib/rules/time-min-milliseconds/index.js (hunk 3 above)
Comment (jeddy3) [reply lib/rules/time-min-milliseconds/index.js:71]: Agreed. I suggest we also use the [`getDimension()`](https://github.com/stylelint/stylelint/blob/main/lib/utils/getDimension.js) util rather than use `valueParser.unit()` directly as it's safer for non-standard syntax.

Comment (kawaguchi1102) [reply lib/rules/time-min-milliseconds/index.js:71]: @ybiquitous @jeddy3 
Thanks for the great advice!
I think these fixed can be done by tomorrow.

**Comment by kawaguchi1102** [comment]
The refactor has been completed.
I hope I am not mistaken in this refactor.

File: lib/rules/time-min-milliseconds/index.js [hunk 4]
```diff
@@ -52,57 +53,45 @@ const rule = (primary, secondaryOptions) => {
...
+				complain(decl, sourceIndex, value.length);
+			});
 		});
 
 		/**
-		 * Get the duration within an `animation` or `transition` shorthand property value.
-		 *
-		 * @param {string[]} valueList
-		 * @returns {string | undefined}
+		 * @param {import('postcss-value-parser').Dimension | {unit: null, number: null}} dimension
```
Comment (ybiquitous) [inline lib/rules/time-min-milliseconds/index.js:82]: [trivial] It seems we can simplify the type a bit as follows, but acceptable to keep it as-is. Perhaps, it's good to change the return type of `getDimension()`.

```suggestion
		 * @param {{unit: string | null, number: string | null}} dimension
```

File: lib/rules/time-min-milliseconds/index.js [hunk 5]
```diff
@@ -118,27 +107,27 @@ const rule = (primary, secondaryOptions) => {
 		}
 
 		/**
-		 * @param {string} time
+		 * @param {import('postcss-value-parser').Dimension | {unit: null, number: null}} valueNode
 		 * @returns {boolean}
 		 */
-		function isAcceptableTime(time) {
-			const parsedTime = valueParser.unit(time);
+		function isAcceptableTime(valueNode) {
```
Comment (ybiquitous) [inline lib/rules/time-min-milliseconds/index.js:113]: [suggest] The name `dimension` seems more accurate:

```suggestion
		function isAcceptableTime(dimension) {
```

File: lib/rules/time-min-milliseconds/index.js [hunk 6]
```diff
@@ -118,27 +107,27 @@ const rule = (primary, secondaryOptions) => {
...
 
-			const numTime = Number(parsedTime.number);
+			const numTime = Number(number);
 
 			if (numTime <= 0) {
 				return true;
 			}
 
-			const unit = parsedTime.unit.toLowerCase();
+			const _unit = unit.toLowerCase();
```
Comment (ybiquitous) [inline lib/rules/time-min-milliseconds/index.js:124]: [suggest] Using the `_` prefix for variables is rare in our code base. How about renaming the variable like this?

```suggestion
			const timeUnit = unit.toLowerCase();
```

**Review by ybiquitous — COMMENTED** [review]
@kawaguchi1102 Thank you, the code is now more straightforward and readable! Almost no problem.
I've left easy refactoring suggestions, so please check them.

**Comment by kawaguchi1102** [comment]
@ybiquitous Thank you for reviewing every detail!
Now we have a cleaner code!

**Review by ybiquitous — APPROVED** [review]
Thank you. LGTM 👍🏼

**Review by jeddy3 — APPROVED** [review]
LGTM, thank you!
