### PR TITLE
Fix false positives for namespaced variables in property-no-unknown

### LINKED ISSUE #4544: Fix false positives for namespaced variables in property-no-unknown
It appears that the `property-no-unknown` rule is incorrectly flagging SCSS `@use` namespaces, when setting a variable within a namespace. This occurs only within `@mixin`s and `@function`s, it doesn't occur when reading or writing module properties in the global scope. It also only occurs while setting a variable - it doesn't occur when reading the variable.

SCSS `@use` and module namespaces are relatively new - [they're described here](https://sass-lang.com/documentation/at-rules/use#loading-members).

```scss
@use 'accoutrement/sass' as a;
@use 'sass:list';

// No stylelint error
a.$sizes: ();

@function clear-sizes() {
  // Lint error: Unexpected unknown property "a.$sizes"   property-no-unknown
  a.$sizes: ();
  @return a.$sizes; // No lint error
}
$s: clear-sizes();

@mixin dump-sizes() {
  // No stylelint error
  $sizes: a.$sizes;
  @debug '# of sizes registered: #{ list.length($sizes) }';
}
@include dump-sizes();
```

The linked file provides a simple repro case with dependencies.
[stylelint-module-property.zip](https://github.com/kristerkari/stylelint-scss/files/4037883/stylelint-module-property.zip)

> Which rule, if any, is the bug related to?

property-no-unknown

> What CSS is needed to reproduce the bug?

```scss
@use 'accoutrement/sass' as a;

@function clear-sizes() {
  // Lint error: Unexpected unknown property "a.$sizes"   property-no-unknown
  a.$sizes: ();
  @return a.$sizes; // No error
}
```

> What stylelint configuration is needed to reproduce the bug?

stylelint.config.js
```js
module.exports = {
  rules: {
    'property-no-unknown': true,
  }
};
```

> Which version of stylelint are you using?

12.0.1

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI: `stylelint **/*.scss`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Yes, it's related to SCSS module namespaces.

> What did you expect to happen?

No lint error.

> What actually happened (e.g. what warnings or errors did you get)?

```shell
$ stylelint **/*.scss

src/stylelint-use-namespace.scss
 9:3  ×  Unexpected unknown property "a.$sizes"   property-no-unknown

error Command failed with exit code 2.
```

I originally posted this bug [in the stylelint-scss project](https://github.com/kristerkari/stylelint-scss/issues/426), but I was directed to post it here.

### PR DESCRIPTION
**Pull request by ryym**
> Which issue, if any, is this issue related to?

Closes #4544

> Is there anything in the PR that needs further explanation?

I didn't add test cases of `isStandardSyntaxDeclaration` for Sass indented syntax because the `postcss-sass` parser does not understand `@use` syntax yet (https://github.com/AleshaOleg/postcss-sass/issues/145).

### CODE REVIEW

File: lib/utils/isStandardSyntaxDeclaration.js [hunk 1]
```diff
@@ -57,5 +57,10 @@ module.exports = function (decl) {
 		return false;
 	}
 
+	// Sass variables within a namespace (e.g. namespace.$var: x)
+	if (prop.includes('.$') && prop[0] !== '.' && prop[prop.length - 1] !== '$') {
+		return false;
+	}
```
Comment (ryym) [inline lib/utils/isStandardSyntaxDeclaration.js:63]: I'm not sure what this function should return for invalid declarations such as `.$var` and `namespace.$`.
For now this branch excludes those invalid `prop`s.

File: lib/utils/isStandardSyntaxDeclaration.js [hunk 2]
```diff
@@ -57,5 +57,10 @@ module.exports = function (decl) {
 		return false;
 	}
 
+	// Sass variables within a namespace (e.g. namespace.$var: x)
+	if (prop.includes('.$') && prop[0] !== '.' && prop[prop.length - 1] !== '$') {
```
Comment (jeddy3) [inline lib/utils/isStandardSyntaxDeclaration.js:61]: Let's just go with `if (prop.includes('.$'))` as the util is more interested in excluding non-standard properties than the validity of name-spaced dollar variables.

**Comment by ryym** [comment]
@ybiquitous @jeddy3 Thanks for your reviewing!
I added the `isScssVariable` function and replaced the duplicate code with it.

**Comment by m-allanson** [comment]
Updated changelog:

> - Fixed: `property-no-unknown` false positives for namespaced variables ([#4803](https://github.com/stylelint/stylelint/pull/4803)).
