### PR TITLE
Fix `selector-not-notation` autofix for "simple" option

### LINKED ISSUE #6606: Fix `selector-not-notation` autofix for `"simple"`
### What steps are needed to reproduce the bug?

```css
.foo:not(.bar, .baz) .content {
    display: none;
}
```

### What Stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "selector-not-notation": "simple"
  }
}
```

### How did you run Stylelint?

CLI `stylelint **/*.{vue,scss}`

### Which version of Stylelint are you using?

14.16.1

### What did you expect to happen?

Autofix to

```css
.foo:not(.bar):not(.baz) .content {
    display: none;
}
```

### What actually happened?

Autofix to

```css
.foo:not(.bar) .content.content {
    display: none;
}
```

### Does the bug relate to non-standard syntax?

No, only native CSS syntax is involved.

### Related issues

* https://github.com/stylelint/stylelint/issues/6236
* https://github.com/stylelint/stylelint/issues/3853

### PR DESCRIPTION
**Pull request by Mouvedia**
> Which issue, if any, is this issue related to?

Closes #6606

### CODE REVIEW

File: lib/rules/selector-not-notation/index.js [hunk 1]
```diff
@@ -152,7 +165,9 @@ function fixSimple(not) {
 	not.nodes.push(firstSelector);
 
 	for (const s of simpleSelectors) {
-		const last = not.parent.last;
+		const last = getLastConsecutiveNot(not.parent.nodes);
+
+		assert(last);
```
Comment (ybiquitous) [inline lib/rules/selector-not-notation/index.js:170]: [suggest] This change will be no longer needed if the suggestion above is applied:

```suggestion
```

File: lib/rules/selector-not-notation/index.js [hunk 2]
```diff
@@ -130,6 +130,19 @@ const rule = (primary, _, context) => {
...
+ * @param {Node[]} nodes
+ */
+const getLastConsecutiveNot = (nodes) => {
+	let i = 0;
+
+	for (; i < nodes.length; i++) {
+		if (!isNot(/** @type {Node} */ (nodes[i]))) break;
+	}
+
+	return nodes[i - 1];
```
Comment (ybiquitous) [inline lib/rules/selector-not-notation/index.js:143]: [suggest] What about making the code readable by `findIndex()` like this? IMHO, an old-style loop using an index is not so readable.

In addition, what about returning `Node` instead of `Node | undefined` by moving `assert()`?

```suggestion
 * @param {Node[]} nodes
 * @returns {Node}
 */
const getLastConsecutiveNot = (nodes) => {
	const index = nodes.findIndex((node) => !isNot(node));
	const found = nodes[index - 1] || nodes[0];

	assert(found);

	return found;
```

**Review by ybiquitous — COMMENTED** [review]
@Mouvedia Thanks for creating the pull request.
I've left a refactoring suggestion, but the direction looks good to me. 👍🏼

File: lib/rules/selector-not-notation/index.js (hunk 2 above)
Comment (Mouvedia) [reply lib/rules/selector-not-notation/index.js:143]: This is obviously more readable and elegant.
Thanks!

Comment (Mouvedia) [reply lib/rules/selector-not-notation/index.js:143]: This is obviously more readable and elegant, thanks!
I see a problem with `const found = nodes[index - 1] || nodes[0];` though.
Ill add a test if it's not already covered.

File: lib/rules/selector-not-notation/__tests__/index.js [hunk 3]
```diff
@@ -68,6 +68,24 @@ testRule({
...
+		{
+			code: ':not(.bar, .baz) .qux :not(.foo) {}',
+			fixed: ':not(.bar):not(.baz) .qux :not(.foo) {}',
+			message: messages.expected('simple'),
+			line: 1,
+			column: 1,
+			endLine: 1,
+			endColumn: 17,
+		},
 		{
```
Comment (Mouvedia) [inline lib/rules/selector-not-notation/__tests__/index.js:89]: I gotta add `:not(.foo) .qux :not(.bar, .baz)` too.

**Review by ybiquitous — APPROVED** [review]
Thanks, LGTM 👍🏼

**Review by jeddy3 — APPROVED** [review]
LGTM, thank you!
