### PR TITLE
Fix `declaration-property-value-no-unknown` false negatives for math functions

### LINKED ISSUE #8891: Add `calc` support to `declaration-property-value-no-unknown`
### What is the problem you're trying to solve?

[`declaration-property-value-no-unknown`](https://stylelint.io/user-guide/rules/declaration-property-value-no-unknown/) is lacking `calc` support. This is detected:

```css
a { height: 2 }
```

but this is not:

```css
a { height: calc(2) }
```

### What solution would you like to see?

Determine the resulting data type of `calc` and then check if it is valid for the property it is being assigned on. Some examples:

```css
a { height: calc(2) } /* ❌ */
a { height: calc(2 + 2) } /* ❌ */
a { height: calc(2 * 2) } /* ❌ */
a { height: calc(2px + 2) } /* ❌ */
a { height: calc(2px * 2) }  /* ✅ */
a { height: calc(var(--foo) + 2) } /* ❌ (assuming variable is unknown) */
a { height: calc(var(--foo) * 2) } /* ✅ (assuming variable is unknown) */
```

### PR DESCRIPTION
**Pull request by ragini-pandey**
## Which issue, if any, is this issue related to?

Fixes #8891

## Is there anything in the PR that needs further explanation?

This PR adds validation for `calc()` expressions in the `declaration-property-value-no-unknown` rule to catch invalid type combinations.

### Changes

1. **Added `@csstools/css-calc` dependency** to validate calc expressions
2. **Enhanced calc validation** by:
   - Attempting to solve calc expressions using `@csstools/css-calc`
   - If the expression can be solved (e.g., `calc(2px * 2)` → `4px`), validating the result with csstree
   - If the expression cannot be solved, checking for invalid type mixing patterns (e.g., `calc(2px + 2)` - adding dimension and unitless number)
3. **Added helper functions**:
   - `validateMathFunctions()` - validates calc/clamp/min/max expressions
   - `hasInvalidTypeMix()` - detects invalid type combinations in expressions
   - `findMathExpression()` - extracts the math expression from the value for error reporting

### Examples

Now correctly reports errors for:

/* Invalid: unitless number for property expecting length */
a { height: calc(2); }
a { height: calc(2 + 2); }

/* Invalid: mixing dimension and unitless number in addition */
a { height: calc(2px + 2); }

Still accepts valid expressions:

/* Valid: results in a length */
a { height: calc(2px * 2); }

/* Valid: mixed units that are both lengths */
a { margin: calc(100% - 10px); }

/* Valid: multiplication with variables */
a { height: calc(var(--foo) * 2); }

The validation is conservative - it only reports errors for clearly invalid patterns while allowing expressions that might be valid but cannot be fully resolved at parse time (like percentage + pixel combinations).

### CODE REVIEW

File: lib/rules/declaration-property-value-no-unknown/index.mjs [hunk 1]
```diff
@@ -22,12 +37,39 @@ import validateOptions from '../../utils/validateOptions.mjs';
 
 const { next: syntaxPatches } = syntaxPatchesJson;
 
+/** Math function names that we validate */
+const MATH_FUNCTIONS = new Set([
```
Comment (ybiquitous) [inline lib/rules/declaration-property-value-no-unknown/index.mjs]: [question] Can we reuse `mathFunctions` here?

https://github.com/stylelint/stylelint/blob/f673be9a8d284fccd8f841584e9053fb68e26300/lib/reference/functions.mjs#L47

Comment (ybiquitous) [inline lib/rules/declaration-property-value-no-unknown/index.mjs]: [suggestion] Please move `MATH_FUNCTIONS` after `const SYNTAX_DESCRIPTOR`.

File: lib/rules/declaration-property-value-no-unknown/index.mjs [hunk 2]
```diff
@@ -230,18 +302,263 @@ const rule = (primary, secondaryOptions) => {
...
+
+	return nodes.some(checkNode);
+}
+
+/**
+ * Validate math functions (calc, min, max, clamp, etc.) in a CSS value.
+ * Uses @csstools/css-calc to solve expressions and validate the result.
+ *
+ * @param {string} value - The CSS property value
+ * @param {import('postcss').Declaration} _decl - The declaration node (unused)
```
Comment (ybiquitous) [inline lib/rules/declaration-property-value-no-unknown/index.mjs]: [suggestion] Any reasons for the unused parameter `_decl`? If not, can you remove it?

**Comment by ybiquitous** [comment]
Plus, can you improve the coverage? There are uncovered lines, ref:
https://app.codecov.io/gh/stylelint/stylelint/pull/9011

File: lib/rules/declaration-property-value-no-unknown/index.mjs [hunk 3]
```diff
@@ -22,12 +37,39 @@ import validateOptions from '../../utils/validateOptions.mjs';
...
+]);
+
 const ruleName = 'declaration-property-value-no-unknown';
 
 const messages = ruleMessages(ruleName, {
 	rejected: (property, value) => `Unexpected unknown value "${value}" for property "${property}"`,
 	rejectedParseError: (property, value) =>
 		`Cannot parse property value "${value}" for property "${property}"`,
+	rejectedMath: (property, expression) =>
+		`Invalid expression "${expression}" for property "${property}"`,
```
Comment (ybiquitous) [inline lib/rules/declaration-property-value-no-unknown/index.mjs]: [suggestion] Can you add `rejectedMath` to the type?

https://github.com/stylelint/stylelint/blob/f673be9a8d284fccd8f841584e9053fb68e26300/types/stylelint/index.d.ts#L656-L658

File: lib/rules/declaration-property-value-no-unknown/index.mjs [hunk 4]
```diff
@@ -230,18 +302,263 @@ const rule = (primary, secondaryOptions) => {
...
-function containsUnsupportedFunction(cssTreeNode) {
-	return Boolean(
-		find(
-			cssTreeNode,
-			(node) => node.type === 'Function' && ['clamp', 'min', 'max', 'env'].includes(node.name),
-		),
-	);
+function containsOnlyEnvFunction(cssTreeNode) {
+	return Boolean(find(cssTreeNode, (node) => node.type === 'Function' && node.name === 'env'));
+}
```
Comment (ybiquitous) [inline lib/rules/declaration-property-value-no-unknown/index.mjs:292]: [suggestion] The original name `containsUnsupportedFunction` seems reasonable. Can you revert the name and refactor the function body?

```js
const UNSUPPORTED_FUNCTIONS = new Set(['env']);

function containsUnsupportedFunction(cssTreeNode) {
	return Boolean(find(cssTreeNode, (node) => node.type === 'Function' && UNSUPPORTED_FUNCTIONS.has(node.name.toLowerCase())));
}
```

File: lib/rules/declaration-property-value-no-unknown/index.mjs [hunk 5]
```diff
@@ -230,18 +302,263 @@ const rule = (primary, secondaryOptions) => {
...
+function validateMathFunctions(value, _decl, prop, forkedLexer, typedCustomPropertyNames) {
+	// If the value doesn't contain any math functions, continue with normal validation
+	if (!containsMathFunction(value)) {
+		return 'continue';
+	}
+
+	// Skip validation if the value contains var() or env() as we can't determine the type
+	if (/\b(?:var|env)\s*\(/i.test(value)) {
+		return 'skip';
+	}
```
Comment (ybiquitous) [inline lib/rules/declaration-property-value-no-unknown/index.mjs:400]: [question] Is this check for `var()` and `env()` necessary? 
`containsOnlyEnvFunction()` seems to check beforehand.

File: lib/rules/declaration-property-value-no-unknown/index.mjs [hunk 6]
```diff
@@ -230,18 +302,263 @@ const rule = (primary, secondaryOptions) => {
...
+	 */
+	const checkNode = (node) => {
+		if (isFunctionNode(node)) {
+			return checkFunctionForTypeMix(node);
+		}
+
+		return false;
+	};
+
+	return nodes.some(checkNode);
```
Comment (ybiquitous) [inline lib/rules/declaration-property-value-no-unknown/index.mjs]: [suggestion] Can you simplify the code like this?

```suggestion
	return nodes.some((node) => isFunctionNode(node) && checkFunctionForTypeMix(node));
```

File: lib/rules/declaration-property-value-no-unknown/index.mjs [hunk 7]
```diff
@@ -230,18 +302,263 @@ const rule = (primary, secondaryOptions) => {
...
+		const funcName = funcNode.getName().toLowerCase();
+
+		if (!MATH_FUNCTIONS.has(funcName)) {
+			return false;
+		}
+
+		// Get the operands and operators at the top level of this function
+		const children = funcNode.value;
+
+		/** @type {Array<{type: 'number' | 'dimension' | 'percentage' | 'other', node: import('@csstools/css-parser-algorithms').ComponentValue}>} */
```
Comment (ybiquitous) [inline lib/rules/declaration-property-value-no-unknown/index.mjs]: [suggestion] The `node` property seems unused. Can we simplify the `operands` array?

```suggestion
		/** @type {Array<'number' | 'dimension' | 'percentage' | 'other'>} */
```

Comment (ragini-pandey) [reply lib/rules/declaration-property-value-no-unknown/index.mjs]: Thank you for the comment.
Agreed, since node isn’t used anywhere, I’ve removed it and simplified the operands array.

File: lib/rules/declaration-property-value-no-unknown/index.mjs (hunk 6 above)
Comment (ragini-pandey) [reply lib/rules/declaration-property-value-no-unknown/index.mjs]: Thanks for the suggestion. 
I’ve updated the code to simplify it as suggested.

File: lib/rules/declaration-property-value-no-unknown/index.mjs (hunk 3 above)
Comment (ragini-pandey) [reply lib/rules/declaration-property-value-no-unknown/index.mjs]: Thanks for the suggestion. I’ve added `rejectedMath` to the type.

File: lib/rules/declaration-property-value-no-unknown/index.mjs (hunk 4 above)
Comment (ragini-pandey) [reply lib/rules/declaration-property-value-no-unknown/index.mjs:292]: Reverted the name to `containsUnsupportedFunction` and refactored the function body.

File: lib/rules/declaration-property-value-no-unknown/index.mjs (hunk 2 above)
Comment (ragini-pandey) [reply lib/rules/declaration-property-value-no-unknown/index.mjs]: Thanks for pointing that out. `_decl` wasn’t needed, so I’ve removed it.

File: lib/rules/declaration-property-value-no-unknown/index.mjs (hunk 1 above)
Comment (ragini-pandey) [reply lib/rules/declaration-property-value-no-unknown/index.mjs]: Moved `MATH_FUNCTIONS` after `SYNTAX_DESCRIPTOR`

Comment (ragini-pandey) [reply lib/rules/declaration-property-value-no-unknown/index.mjs]: Yes sure. I’ve updated the code accordingly.

File: lib/rules/declaration-property-value-no-unknown/index.mjs (hunk 5 above)
Comment (ragini-pandey) [reply lib/rules/declaration-property-value-no-unknown/index.mjs:400]: Thank you for pointing this out.
The `env()` check has been removed. 
The` var()` check is still needed because `containsUnsupportedFunction() `only handles `env()` 
values with `var()` should skip math validation but still go through normal csstree validation.

**Comment by ybiquitous** [comment]
@ragini-pandey Thanks, overall LGTM. 👍🏼 

But there are still uncovered lines. Do you think it's reasonable to cover them by adding test cases?
https://app.codecov.io/gh/stylelint/stylelint/pull/9011

**Review by ybiquitous — COMMENTED** [review]
@romainmenke This PR introduces your package `@csstools/css-calc`.  I'd appreciate it if you could provide any thoughts on using the package. 🙏🏼

File: .changeset/twelve-islands-help.md [hunk 8]
```diff
@@ -0,0 +1,5 @@
+---
+"stylelint": minor
+---
+
+Added: `calc` support to `declaration-property-value-no-unknown`
```
Comment (jeddy3) [inline .changeset/twelve-islands-help.md]:
```suggestion
Fixed: `declaration-property-value-no-unknown` false negatives for math functions
```

Would be more inline with how we've described this type of change in other rules.

File: lib/rules/declaration-property-value-no-unknown/index.mjs [hunk 9]
```diff
@@ -28,6 +44,8 @@ const messages = ruleMessages(ruleName, {
 	rejected: (property, value) => `Unexpected unknown value "${value}" for property "${property}"`,
 	rejectedParseError: (property, value) =>
 		`Cannot parse property value "${value}" for property "${property}"`,
+	rejectedMath: (property, expression) =>
+		`Invalid expression "${expression}" for property "${property}"`,
```
Comment (jeddy3) [inline lib/rules/declaration-property-value-no-unknown/index.mjs]:
```suggestion
		`Unexpected invalid math expression "${expression}" for property "${property}"`,
```

For consistency with [our conventions](https://stylelint.io/developer-guide/rules#add-problem-messages).

**Review by jeddy3 — COMMENTED** [review]
Thank you for the PR.

I've made two minor suggestions.

File: .changeset/twelve-islands-help.md (hunk 8 above)
Comment (ragini-pandey) [reply .changeset/twelve-islands-help.md]: Done

File: lib/rules/declaration-property-value-no-unknown/index.mjs (hunk 9 above)
Comment (ragini-pandey) [reply lib/rules/declaration-property-value-no-unknown/index.mjs]: Done

**Comment by ybiquitous** [comment]
> But there are still uncovered lines. Do you think it's reasonable to cover them by adding test cases?
> https://app.codecov.io/gh/stylelint/stylelint/pull/9011

@ragini-pandey Any updates on the coverage?

**Comment by romainmenke** [comment]
@ybiquitous I will take a look as soon as possible.

-----

My immediate concern is that this library isn't intended for this use case.

It does implement most of the math related features in CSS but its focus is on doing so outside the context of a browser. This means that it can't convert between `rem` and `px` and likewise can't resolve percentage values.

It was created to be able to generate fallback values for relative colors that can contain math expressions. This scope is considerably narrow than validating/linting math expressions in general in the context of a browser.

I did mention this library in the linked issue because it does illustrate some of the complexity involved in handling CSS math expressions. But I did not mean to imply it should be used to solve that issue. I could have stated that more clearly.

-----

That said, if it does seem to work and makes this rule more helpful then that is obviously good.

My concern is that it can only be used in the simplest of cases, e.g. `width: calc(3 + 2)`. As in this case it can simplify the expression to `5` which isn't valid for `width`.

So I wonder if all the analysis can instead be done without this package?

But I need to take a closer look and I am unsure when I will have time for this.

File: lib/rules/declaration-property-value-no-unknown/__tests__/index.mjs [hunk 10]
```diff
@@ -649,3 +786,150 @@ testRule({
 		},
 	],
 });
+
+testRule({
+	ruleName,
+	config: true,
```
Comment (ybiquitous) [inline lib/rules/declaration-property-value-no-unknown/__tests__/index.mjs]: [suggestion] Thanks for adding test cases in the second `testRule()`. The coverage has been much improved. 👍🏼 

In addition, if you don't have any special reason, can you merge the second `testRule()` into the existing first `testRule()`? 🙏🏼 
The two `testRule()` with the same `config: true` might confuse maintainers in the future.

**Comment by ybiquitous** [comment]
@romainmenke Thanks a lot for providing helpful information. Your concern about the `@csstools/css-calc` package makes sense to me, and I understand that your time for OSS is limited. Please take care of your own time. 😃 

It looks like all the test cases added by this PR cover a wide range of use cases, but to be honest, are you concerned that the math function support might be causing a bunch of false positives and reported issues?

Also, could we mitigate this by documenting the limitation in the rule's README?

As much as possible, I'd like to avoid potential issues that can exhaust maintainers.

**Comment by romainmenke** [comment]
First of all, thank you for working on this @ragini-pandey 🙇 
I think this direction is indeed interesting and will help users avoid some issues 🎉 

------

I think the current approach will only cause false negatives and no (or very few) false positives.

We might have to tweak the rule in the future in case math functions are added that do mix numbers with either dimensions or percentages. I recall such a function being discussed in the CSSWG recently but don't remember what it was. I hope I stumble on it again :) But this is the only source of false negatives this approach can cause.

As @ragini-pandey stated the rule is conservative and I think that is the right tradeoff for now :)

----

Some interesting false positives:

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIB0BDABMAOgOzWg7gJZQAuAFvGmCgDZgAUATAAwC2AzmgNRoCMzAUgCUAbhwBfHDiQAjDDjxFSFKrQb0ArMwAOADyHc0W0QoLFylanXr0AzDt2GWegzzvMnzISdxnlltXorBns9TxdDYPdPbzFsSWwQABoQADNCGhgAORRWOEQYXVztTKQwdnZk8AhsdIBzBBBC7QgAJxI0WFSUAFcaDqxfQpIYbCh2SgBtAHJ2EgBPTJpCbBIAWkhawjq1uZQxlFaoaYBdJIk4qs36gDE21hQSRrnFmGXVspr6pFYAK0qUrBtJVEIM8JgQC8lisSBDKBCyCQSMD4AB6VHaADWdSQ2laSGwMHwqKhbxhAAEAByMABstgA7PSNBDzr4IaT3utrttdiR9lBDlA4WgITRHjA5hCJCBxEA)

```css
.a {
  width: calc(20ms + 10%);
}

.b {
  width: calc((50px) + 50);
  width: calc((30px + 20px) + (30 + 20));
  width: calc(calc(30px + 20px) + calc(30 + 20));
}
```

I think that the chance of user error goes up as complexity of the expression increases.
So it would be nice if we can also handle some of these cases.

But we can also do that in a follow up issue.

----

Overal I think this change is good :)
It strikes a good balance between adding some extra reporting and having too much complexity here in Stylelint for something that should be added upstream in csstree.

Thank you again @ragini-pandey for working on this

**Comment by ragini-pandey** [comment]
Thank you for such a detailed and through review @jeddy3 @ybiquitous @romainmenke 
Learned a lot and will carry these learnings forward in upcoming PRs.

**Review by ybiquitous — APPROVED** [review]
@romainmenke Thanks for your thoughts. We can go ahead.

@ragini-pandey Thanks for addressing my requests, LGTM 👍🏼

File: lib/rules/declaration-property-value-no-unknown/index.mjs [hunk 11]
```diff
@@ -1,6 +1,20 @@
-import { find, fork, parse, string } from 'css-tree';
```
Comment (jeddy3) [inline lib/rules/declaration-property-value-no-unknown/index.mjs:1]:
```js
import { find, fork, parse, string } from 'css-tree';
import {
	isFunctionNode,
	isTokenNode,
	parseListOfComponentValues,
} from '@csstools/css-parser-algorithms';
import {
	isTokenDelim,
	isTokenDimension,
	isTokenNumber,
	isTokenPercentage,
	tokenize,
} from '@csstools/css-tokenizer';
import { calc } from '@csstools/css-calc';
import syntaxPatchesJson from '@csstools/css-syntax-patches-for-csstree' with { type: 'json' };

import { isRegExp, isString } from '../../utils/validateTypes.mjs';
import { atRuleRegexes } from '../../utils/regexes.mjs';
import { declarationValueIndex } from '../../utils/nodeFieldIndices.mjs';
import getDeclarationValue from '../../utils/getDeclarationValue.mjs';
import isCustomProperty from '../../utils/isCustomProperty.mjs';
import { isDeclaration } from '../../utils/typeGuards.mjs';
import isDescriptorDeclaration from '../../utils/isDescriptorDeclaration.mjs';
import isStandardSyntaxDeclaration from '../../utils/isStandardSyntaxDeclaration.mjs';
import isStandardSyntaxProperty from '../../utils/isStandardSyntaxProperty.mjs';
import isStandardSyntaxValue from '../../utils/isStandardSyntaxValue.mjs';
import matchesStringOrRegExp from '../../utils/matchesStringOrRegExp.mjs';
import { mathFunctions } from '../../reference/functions.mjs';
import mergeSyntaxDefinitions from '../../utils/mergeSyntaxDefinitions.mjs';
import report from '../../utils/report.mjs';
import ruleMessages from '../../utils/ruleMessages.mjs';
import validateObjectWithArrayProps from '../../utils/validateObjectWithArrayProps.mjs';
import validateObjectWithProps from '../../utils/validateObjectWithProps.mjs';
import validateOptions from '../../utils/validateOptions.mjs';
```

code style nit: external and internal import groups, ordered alphabetically

File: lib/rules/declaration-property-value-no-unknown/index.mjs [hunk 12]
```diff
@@ -20,6 +34,8 @@ import validateObjectWithArrayProps from '../../utils/validateObjectWithArrayPro
 import validateObjectWithProps from '../../utils/validateObjectWithProps.mjs';
 import validateOptions from '../../utils/validateOptions.mjs';
 
+import { mathFunctions } from '../../reference/functions.mjs';
+
 const { next: syntaxPatches } = syntaxPatchesJson;
```
Comment (jeddy3) [inline lib/rules/declaration-property-value-no-unknown/index.mjs:37]:
```suggestion

const HAS_MATH_FUNCTION = new RegExp(`\\b(?:${[...mathFunctions.values()].join('|')})\\(`, 'i');

```

File: lib/rules/declaration-property-value-no-unknown/index.mjs [hunk 13]
```diff
@@ -239,11 +287,248 @@ function containsUnsupportedFunction(cssTreeNode) {
...
+	return { expression: value, startIndex: 0 };
+}
+
+/**
+ * Check if a value contains any math functions
+ * @param {string} value
+ * @returns {boolean}
+ */
+function containsMathFunction(value) {
+	const tokens = tokenize({ css: value });
```
Comment (jeddy3) [inline lib/rules/declaration-property-value-no-unknown/index.mjs:357]:
```suggestion	
	if (!HAS_MATH_FUNCTION.test(value)) return false;
	
	const tokens = tokenize({ css: value });
```

Let's do a cheap check before tokenising.

**Comment by ragini-pandey** [comment]
I’m having trouble hitting 98% coverage. I tried using AI as well, but some negative cases seem impossible to cover.

Screenshot 2026-02-06 at 11 55 23 PM

File: lib/rules/declaration-property-value-no-unknown/index.mjs (hunk 13 above)
Comment (ragini-pandey) [reply lib/rules/declaration-property-value-no-unknown/index.mjs:357]: Done

File: lib/rules/declaration-property-value-no-unknown/index.mjs (hunk 12 above)
Comment (ragini-pandey) [reply lib/rules/declaration-property-value-no-unknown/index.mjs:37]: Done

File: lib/rules/declaration-property-value-no-unknown/index.mjs (hunk 11 above)
Comment (ragini-pandey) [reply lib/rules/declaration-property-value-no-unknown/index.mjs:1]: Done

**Review by jeddy3 — APPROVED** [review]
Thanks for making the changes. LGTM, thank you!

> I’m having trouble hitting 98% coverage

I think that's fine as it's sometimes not possible.

**Comment by ragini-pandey** [comment]
> * #### [codecov/patch](/stylelint/stylelint/pull/9011/checks?check_run_id=62840862367) — 96.55% of diff hit (target 97.99%)


> Thanks for making the changes. LGTM, thank you!
> 
> > I’m having trouble hitting 98% coverage
> 
> I think that's fine as it's sometimes not possible.

Ohk. Understood.
Then how do we merge this PR with failing check of codecov/patc?

**Comment by jeddy3** [comment]
Merged, thank you. Your fix will be included in the next release.

> Then how do we merge this PR with failing check of codecov/patc?

Maintainers have the permissions to do that.
