### PR TITLE
Fix `shorthand-property-no-redundant-values` false negatives for functions

### LINKED ISSUE #7656: Fix `shorthand-property-no-redundant-values` false negatives for `var()`
### What minimal example or steps are needed to reproduce the bug?

```css
a { padding: 0 var(--padding) 0; }
```

### What minimal configuration is needed to reproduce the bug?

```json
{ "rules": { "shorthand-property-no-redundant-values": true } }
```

### How did you run Stylelint?

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcCBOEIBcAEwA6A7baAtIQA4CGUUAlrgObwYBMADCQB4DceAvnnmVj5pylGvQzMMANzJIAFMRHU6ASgldcvXCAA0IAGZUANjAByZALZxEMNpZImAdGADOL3eAi5DtBCBy4GBjYILZoMLhQLiEMANp4QUEhLmgAniZGNESQ3lS0hClkkbJQIQkYALo8Hjk+AGIQSBZkaH4AVi5eHrAk7ogBSSAp6TCZuGgxwSBGLTApITrlyWkZWYS1eQVoRVAlkyEz4fMg1dxAA)

### Which Stylelint-related dependencies are you using?

```json { "stylelint": "15.6.0" } ```

### What did you expect to happen?

fix redundant values

### What actually happened?

nothing

### Do you have a proposal to fix the bug?

--

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

Ref #7656

> Is there anything in the PR that needs further explanation?

I think supporting all functions makes sense, including ~~`var()`~~ or `calc()` etc.
-> Dropped `var()` support. See https://github.com/stylelint/stylelint/issues/7656#issuecomment-2079826514

### CODE REVIEW

File: lib/rules/shorthand-property-no-redundant-values/index.mjs [hunk 1]
```diff
@@ -29,16 +32,6 @@ const propertiesWithShorthandNotation = new Set([
 	'inset',
 ]);
```
Comment (Mouvedia) [inline lib/rules/shorthand-property-no-redundant-values/index.mjs:33]: Can you add the alias of `grid-gap`?
i.e. `gap`

File: lib/rules/shorthand-property-no-redundant-values/index.mjs [hunk 2]
```diff
@@ -122,40 +115,44 @@ const rule = (primary, _secondaryOptions, context) => {
...
 				return;
 			}
 
-			const shortestForm = canCondense(
-				valuesToShorthand[0] || '',
-				valuesToShorthand[1] || '',
-				valuesToShorthand[2] || '',
-				valuesToShorthand[3] || '',
-			);
+			const [top, right, bottom, left] = valuesToShorthand;
```
Comment (Mouvedia) [inline lib/rules/shorthand-property-no-redundant-values/index.mjs:154]:
```suggestion
const [first, second, third, fourth] = valuesToShorthand;
```

e.g. `grid-gap: <'row-gap'> <'column-gap'>`

File: lib/rules/shorthand-property-no-redundant-values/index.mjs (hunk 1 above)
Comment (ybiquitous) [reply lib/rules/shorthand-property-no-redundant-values/index.mjs:33]: Out of scope of the PR. Please add it in another PR?

File: lib/rules/shorthand-property-no-redundant-values/__tests__/index.mjs [hunk 3]
```diff
@@ -78,23 +78,11 @@ testRule({
 			description: 'ignore not shorthandable property',
 		},
 		{
-			code: 'a { border-radius: 1px / 1px }',
+			code: 'a { border-radius: 1px / 1px; }',
 			description: 'ignore ellipse',
 		},
```
Comment (Mouvedia) [inline lib/rules/shorthand-property-no-redundant-values/__tests__/index.mjs:83]: minor
question

Can you add a test for `border-radius: 1px 1px / 1px;`?

File: lib/utils/typeGuards.cjs [hunk 4]
```diff
@@ -53,6 +53,14 @@ function isDocument(node) {
 	return node.type === 'document';
 }
 
+/**
+ * @param {import('postcss-value-parser').Node} node
+ * @returns {node is import('postcss-value-parser').DivNode}
+ */
+function isValueDiv(node) {
```
Comment (Mouvedia) [inline lib/utils/typeGuards.cjs:60]: minor
suggestion

Maybe update 

https://github.com/stylelint/stylelint/blob/68cb920c45641702d76670afb111960cbd743296/lib/rules/font-weight-notation/index.mjs#L188-L190

File: lib/utils/typeGuards.mjs [hunk 5]
```diff
@@ -49,6 +49,14 @@ export function isDocument(node) {
 	return node.type === 'document';
 }
 
+/**
+ * @param {import('postcss-value-parser').Node} node
+ * @returns {node is import('postcss-value-parser').DivNode}
+ */
+export function isValueDiv(node) {
```
Comment (Mouvedia) [inline lib/utils/typeGuards.mjs:56]: minor
suggestion

Maybe update 

https://github.com/stylelint/stylelint/blob/68cb920c45641702d76670afb111960cbd743296/lib/rules/font-weight-notation/index.mjs#L188-L190

File: lib/rules/shorthand-property-no-redundant-values/index.mjs (hunk 2 above)
Comment (ybiquitous) [reply lib/rules/shorthand-property-no-redundant-values/index.mjs:154]: Need to be consistent with canCondense arguments. It is another refactoring chance.

File: lib/utils/typeGuards.mjs (hunk 5 above)
Comment (ybiquitous) [reply lib/utils/typeGuards.mjs:56]: Out of scope. Feel free to do it in another PR.

File: lib/rules/shorthand-property-no-redundant-values/index.cjs [hunk 6]
```diff
@@ -140,6 +140,16 @@ const rule = (primary, _secondaryOptions, context) => {
 					break;
 				}
 
+				// `var()` should be ignored. E.g.
+				//
+				//   --padding: 20px 5px;
+				//   padding: 0 var(--padding) 0;
+				//
+				if (typeGuards.isValueFunction(valueNode) && valueNode.value.toLowerCase() === 'var') {
+					shouldIgnore = true;
```
Comment (Mouvedia) [inline lib/rules/shorthand-property-no-redundant-values/index.cjs:149]: suggestion
refactor

What about a `return` inside both this `if` and the preceding one?
i.e. `shouldIgnore` flag seems unnecessary

File: lib/rules/shorthand-property-no-redundant-values/index.mjs [hunk 7]
```diff
@@ -138,6 +138,16 @@ const rule = (primary, _secondaryOptions, context) => {
...
 
+				// `var()` should be ignored. E.g.
+				//
+				//   --padding: 20px 5px;
+				//   padding: 0 var(--padding) 0;
+				//
+				if (isValueFunction(valueNode) && valueNode.value.toLowerCase() === 'var') {
+					shouldIgnore = true;
+					break;
+				}
```
Comment (Mouvedia) [inline lib/rules/shorthand-property-no-redundant-values/index.mjs:149]: suggestion
refactor

What about a `return` inside both this `if` and the preceding one?
i.e. `shouldIgnore` flag seems unnecessary

Comment (ybiquitous) [reply lib/rules/shorthand-property-no-redundant-values/index.mjs]: Nice catch. Fixed via 101003d36 👍🏼

File: lib/rules/shorthand-property-no-redundant-values/index.mjs [hunk 8]
```diff
@@ -122,40 +115,46 @@ const rule = (primary, _secondaryOptions, context) => {
...
+			if (!isStandardSyntaxProperty(prop)) return;
+
+			if (!isStandardSyntaxValue(value)) return;
 
 			const normalizedProp = vendor.unprefixed(prop.toLowerCase());
 
-			if (hasIgnoredCharacters(value) || !isShorthandProperty(normalizedProp)) {
-				return;
-			}
+			if (!isShorthandProperty(normalizedProp)) return;
```
Comment (Mouvedia) [inline lib/rules/shorthand-property-no-redundant-values/index.mjs:128]: nit

rename to `isSupportedShorthand`
else we would have used `longhandSubPropertiesOfShorthandProperties.keys()`

**Review by Mouvedia — APPROVED** [review]
LGTM

File: lib/rules/shorthand-property-no-redundant-values/index.mjs (hunk 8 above)
Comment (ybiquitous) [reply lib/rules/shorthand-property-no-redundant-values/index.mjs]: Make sense. Done b290aee10

File: lib/rules/shorthand-property-no-redundant-values/__tests__/index.mjs [hunk 9]
```diff
@@ -381,6 +377,23 @@ testRule({
...
+		{
+			code: 'a { margin: some-function(1px + 1px) some-function(1px + 1px); }',
+			fixed: 'a { margin: some-function(1px + 1px); }',
+			message: messages.rejected(
+				'some-function(1px + 1px) some-function(1px + 1px)',
+				'some-function(1px + 1px)',
+			),
+			line: 1,
+			column: 5,
+		},
```
Comment (Mouvedia) [inline lib/rules/shorthand-property-no-redundant-values/__tests__/index.mjs:396]: @ybiquitous

```suggestion
		},
		{
			code: 'a { margin: 0 foo(1px + 1px) 0; }',
			fixed: 'a { margin: 0 foo(1px + 1px); }',
			message: messages.rejected('0 foo(1px + 1px) 0', '0 foo(1px + 1px)',
			),
			line: 0,
			column: 0,
		},
```
