### PR TITLE
Fix `overrides.files` in config to allow basename glob patterns

### LINKED ISSUE #6525: Fix `overrides.files` in config for glob patterns like `*.vue`
### What steps are needed to reproduce the bug?

Well, I'll try to be clear here as it is not easy to explain...

I created a simple repo that you can clone to reproduce the bug: https://github.com/sronveaux/stylelint-bug-report

Here's the smallest code base I managed to get to and that can be used to reproduce the bug:

    filesToLint/
    |    |
    |    ------> test.css
    |    ------> test.html
    |
    stylelintInstall/
    |    |
    |    ------> node_modules/
    |    ------> package.json
    |
    .stylelintrc

The .stylelintrc content is very simple:

    {
      "extends": [
        "stylelint-config-standard"
       ],
      "overrides": [
        {
          "files": ["*.html", "**/*.html"],
          "customSyntax": "postcss-html"
        }
      ]
    }

If I get to the stylelintInstall directory and run the following commands:

    npx stylelint ../filesToLint/*.css
    npx stylelint ../filesToLint/*.html

everything works as expected. However, if configBasedir is added:

    npx stylelint --config-basedir . ../filesToLint/*.html

The .html files cannot be linted anymore and the following message is returned:

    When linting something other than CSS, you should install an appropriate syntax, e.g. "postcss-html", and use the "customSyntax" option

    ../filesToLint/test.html
     1:1  ✖  Unknown word  CssSyntaxError

This can be made working back again by changing the content of the .stylelintrc file like this:

    {
      "extends": [
        "stylelint-config-standard"
       ],
      "overrides": [
        {
          "files": ["../*.html", "../**/*.html"],
          "customSyntax": "postcss-html"
        }
      ]
    }

However this manual patch doesn't work when used in conjuction with extensions like `stylelint-config-standard-vue`, not to mention how it fails when used through the `VSCode extension`...

### What Stylelint configuration is needed to reproduce the bug?

    {
      "extends": [
        "stylelint-config-standard"
       ],
      "overrides": [
        {
          "files": ["*.html", "**/*.html"],
          "customSyntax": "postcss-html"
        }
      ]
    }

### How did you run Stylelint?

CLI

### Which version of Stylelint are you using?

14.16.0 under Windows 11

### What did you expect to happen?

Shouldn't the glob patterns we write in the .stylelintrc file be relative to this config file instead of being interpreted differently when used in conjunction with --config-basedir ?

### What actually happened?

It seems like the file matching in the `overrides` part of the config is dependent on the `config-basedir` as the problem can be solved by changing the glob pattern written in the `overrides` part.

### Does the bug relate to non-standard syntax?

_No response_

### Proposal to fix the bug

Not sure exactly and haven't read the source code long enough, but this could be linked to this part:

https://github.com/stylelint/stylelint/blob/e30ec863f8bc1d5ed87c23e3c5a554a01bc4350b/lib/augmentConfig.js#L106-L113

Here we can see that `configDir` (which is in fact `configBasedir`) is passed twice to the `augmentConfigBasic` function.

https://github.com/stylelint/stylelint/blob/e30ec863f8bc1d5ed87c23e3c5a554a01bc4350b/lib/augmentConfig.js#L34-L63

Then `augmentConfigBasic` seems to call `applyOverrides` with the `rootConfigDir` parameter which perhaps should be the directory where the config file is and not `configBasedir`...

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

Closes #6525

> Is there anything in the PR that needs further explanation?

This change fixes the `overrides.files` property in config to allow basename glob patterns like `*.css` or `*.html`.

For example, let's consider `stylelint-config-standard-vue`:

```js
{
  overrides: [
    {
      files: ["*.vue", "**/*.vue"],
      extends: [/* ... */],
    },
  ]
}
```

People should expect the `*.vue` pattern matches any `.vue` files in any directories.
See <https://github.com/ota-meshi/stylelint-config-standard-vue/blob/v1.0.0/lib/index.js#L6>

See also the `basename` option `micromatch`:
<https://github.com/micromatch/micromatch/tree/4.0.5#optionsbasename>

### CODE REVIEW

File: lib/augmentConfig.js [hunk 1]
```diff
@@ -19,6 +19,18 @@ const path = require('path');
...
+ * @param {string} glob
+ * @param {string} basedir
+ * @returns {string}
+ */
+function absolutizeGlob(glob, basedir) {
+	const result = path.isAbsolute(glob.replace(/^!/, '')) ? glob : globjoin(basedir, glob);
+
+	// Glob patterns for micromatch should be in POSIX-style
+	return normalizePath(result);
+}
```
Comment (ybiquitous) [inline lib/augmentConfig.js:32]: [note] Created the `absolutizeGlob()` function to reduce duplications.

**Review by jeddy3 — APPROVED** [review]
LGTM, thank you!

**Comment by ybiquitous** [comment]
Thanks for the review!
