### PR TITLE
Fix `at-rule-descriptor-no-unknown` false positives for page and margin context properties in `@page`

### LINKED ISSUE #8316: Fix `at-rule-descriptor-no-unknown` false positives for page and margin context properties in `@page`
### What minimal example or steps are needed to reproduce the bug?

```css
@page {
	margin: 2cm;
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "extends": [
    "stylelint-config-standard"
  ]
}
```

### How did you run Stylelint?

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIACAHAhgcxgAmAHQDs8AXAWzQCcMBLA+bAJjFIG5CBfEAGhADNqANjAByaUnEQwAHmJRCAdGADOS7uAgF+GBCHwFs2PCGnEYBKEqP0A2oQMGjS4gE8hA2sQC0kTdQyenNHNKKCM7bABdDjUfLQAxCApyYh0AKyUNNVgUVUQ9BxAnVxh3AmIrQxABNFMnIy5wxxc3D28NLQDiIKgQiqNq2vKQaPYgA)

### Which Stylelint-related dependencies are you using?

```json
{
  "stylelint": "16.13.2",
  "stylelint-config-standard": "37.0.0"
}
```

### What did you expect to happen?

No problems to be reported.

### What actually happened?

The following problems were reported: 

```
2:2-8 error Unexpected unknown descriptor "margin" for at-rule "@page" at-rule-descriptor-no-unknown
```

### Do you have a proposal to fix the bug?

This seems to be valid CSS according to https://developer.mozilla.org/en-US/docs/Web/CSS/@page

### PR DESCRIPTION
**Pull request by jeddy3**
> Which issue, if any, is this issue related to?

Closes #8316 

> Is there anything in the PR that needs further explanation?

I've used the `content` property in some tests because it's one of the margin context properties that isn't a page context one.

### CODE REVIEW

File: lib/reference/properties.mjs [hunk 1]
```diff
@@ -644,3 +644,146 @@ export const longhandTimeProperties = new Set([
...
+	'margin-top',
+	'margin-right',
+	'margin-bottom',
+	'margin-left',
+	'margin',
+	'outline-width',
+	'outline-style',
+	'outline-color',
+	'outline',
+	'padding-top',
```
Comment (Mouvedia) [inline lib/reference/properties.mjs:698]: question
minor

Are `orphans` and `widows` missing from the list?
I am not really sure.

Here are some links that seems to confirm it:

https://olevelexam.com/css-property-orphans
https://web.archive.org/web/20150510080955/https://developer.mozilla.org/en-US/docs/Web/CSS/@page
https://publishing-project.rivendellweb.net/css-paged-media/#controlling-widows-and-orphans

I couldn't find any examples for `page-break-before`/`page-break-after`/`page-break-inside` though.

@romainmenke you might know more?
Are these examples invalid?

Comment (jeddy3) [reply lib/reference/properties.mjs:698]: Let's start with the ones from the spec in this PR. If a user reports `orphans` and `widows` we can handle those in another PR.

File: lib/reference/properties.mjs [hunk 2]
```diff
@@ -644,3 +644,146 @@ export const longhandTimeProperties = new Set([
...
+	'text-transform',
+	'white-space',
+	'word-spacing',
+	'vertical-align',
+	'visibility',
+	'width',
+	'min-width',
+	'max-width',
+	'z-index',
+]);
```
Comment (Mouvedia) [inline lib/reference/properties.mjs:789]: If you import `uniteSets` you could reduce it to:

```suggestion
export const marginContextProperties = uniteSets(pageContextProperties, new Set([
	'unicode-bidi',
	'content',
	'overflow',
	'z-index',
	'vertical-align',
]));
```

I am not sure if that's better to create such a relation though.
i.e. `pageContextProperties` may contain properties that are not part of `marginContextProperties` one day in the future

File: lib/rules/at-rule-descriptor-no-unknown/__tests__/index.mjs [hunk 3]
```diff
@@ -85,5 +97,32 @@ testRule({
...
+			message: messages.rejected('@page', 'content'),
+			line: 1,
+			column: 9,
+			endLine: 1,
+			endColumn: 16,
+			description: 'a margin context property in @page',
+		},
+		{
+			code: '@page { @top-center { bar: 0; } }',
+			message: messages.rejected('@page', 'bar'),
```
Comment (Mouvedia) [inline lib/rules/at-rule-descriptor-no-unknown/__tests__/index.mjs:120]: question

Will it warn twice?
i.e. `@top-center` also contains descriptors
e.g.
```
warnings: [
  {
    /* … */
    message: messages.rejected('@page', 'bar'),
  },
  {
    /* … */
    message: messages.rejected('@top-center', 'bar'),
  },
]
```

Comment (jeddy3) [reply lib/rules/at-rule-descriptor-no-unknown/__tests__/index.mjs:120]: It checks `@top-conter` but in the context of `@page` as CSSTree only has descriptors for `@page`: https://github.com/stylelint/stylelint/pull/8319/commits/34da558ee366c1d9d4d2dd0fc373ea65e290f555.

File: lib/rules/at-rule-descriptor-no-unknown/__tests__/index.mjs [hunk 4]
```diff
@@ -28,6 +28,18 @@ testRule({
...
+			code: '@page { size: landscape; }',
+			description: 'known descriptor in @page',
+		},
+		{
+			code: '@page { color: red; }',
+			description: 'known page context property in @page',
+		},
+		{
+			code: '@page { @top-center { content: "foo"; } }',
+			description: 'known margin context property within margin at-rule',
```
Comment (ryo-manba) [inline lib/rules/at-rule-descriptor-no-unknown/__tests__/index.mjs:41]: 👍

File: lib/reference/properties.mjs [hunk 5]
```diff
@@ -644,3 +644,146 @@ export const longhandTimeProperties = new Set([
 ]);
 
 export const shorthandTimeProperties = new Set(['transition', 'animation']);
+
+export const pageContextProperties = new Set([
```
Comment (ryo-manba) [inline lib/reference/properties.mjs:648]: memo: https://drafts.csswg.org/css-page/#page-property-list

File: lib/reference/properties.mjs [hunk 6]
```diff
@@ -644,3 +644,146 @@ export const longhandTimeProperties = new Set([
...
+	'text-transform',
+	'white-space',
+	'word-spacing',
+	'visibility',
+	'width',
+	'min-width',
+	'max-width',
+]);
+
+export const marginContextProperties = new Set([
```
Comment (ryo-manba) [inline lib/reference/properties.mjs:717]: memo: https://drafts.csswg.org/css-page/#margin-property-list

File: lib/rules/at-rule-descriptor-no-unknown/__tests__/index.mjs [hunk 7]
```diff
@@ -85,5 +97,51 @@ testRule({
...
+			code: '@page { @top-center { bar: 0; } }',
+			message: messages.rejected('@page', 'bar'),
+			line: 1,
+			column: 23,
+			endLine: 1,
+			endColumn: 26,
+			description: 'an unknown descriptor or margin context property in a margin at-rule',
+		},
+		{
+			code: '@page { foo: 0; @top-center { bar: 0; } }',
```
Comment (ryo-manba) [inline lib/rules/at-rule-descriptor-no-unknown/__tests__/index.mjs:128]: That's a good test!

**Review by ryo-manba — APPROVED** [review]
LGTM! Thank you for the quick fix!

File: lib/rules/at-rule-descriptor-no-unknown/__tests__/index.mjs (hunk 3 above)
Comment (Mouvedia) [reply lib/rules/at-rule-descriptor-no-unknown/__tests__/index.mjs:120]: https://csstree.github.io/docs/syntax/#discovery&q=ZGljdC5bdHlwZT0iQXRydWxlIl0%3D

File: lib/rules/at-rule-descriptor-no-unknown/__tests__/index.mjs
Comment (Mouvedia) [inline lib/rules/at-rule-descriptor-no-unknown/__tests__/index.mjs:1]: suggestion
minor

Can you add a reject case for `@page { margin-block: 2px 1px; }`?
i.e. it accepts `margin` but not its logical counterparts

File: lib/rules/at-rule-descriptor-no-unknown/__tests__/index.mjs (hunk 7 above)
Comment (Mouvedia) [reply lib/rules/at-rule-descriptor-no-unknown/__tests__/index.mjs:128]: I agree.
i.e. once `css-tree` will support margin at-rules, it will be triggered
