### PR TITLE
Move config merging block to where it belongs

### LINKED ISSUE #1989: configOverrides is not overriding "processor" config key
## Issue description

I found a bug where documentation for `configOverrides` does not match actual implementation. On the docs, it says that one can override any configs coming either from a file or the `config` object. However, after several attempts to make the property `processors` work, I could see that only `rules` is being actually overwritten by `configOverrides`.

After digging into the code, I found [here](https://github.com/stylelint/stylelint/blob/master/src/augmentConfig.js#L75) that the config implementation does not allow many other settings to be actually overridden. You can see that in the current code, it only merges the object `configOverrides` after several operations in the config pipeline.

### How to reproduce

1. In a separate folder, run: **`npm install stylelint-config-primer stylelint-processor-arbitrary-tags`**

2. Create a file `index.js` with the following content, then run it with `node index.js`

```js
var stylelint = require('stylelint');
var formatter = require('stylelint/dist/formatters/stringFormatter').default;

var code = '<style>.badcss{ prop: val; }</style>';

stylelint.lint({
  code: code,

  config: {
    extends: 'stylelint-config-primer',
    processors: ['stylelint-processor-arbitrary-tags'], // Comment me!
  },

  configOverrides: {
    processors: ['stylelint-processor-arbitrary-tags'],
  }

}).then(function(resultObject) {
  console.log('SUCCESS', formatter(resultObject.results));
}).catch(function(e){
  console.error('ERROR', e);
});
```

### Expected behavior

Commenting line 11 (config.preprocessors) should make this script return the same output, because you have an override there.

### Current behavior

If you comment this line, the override is not being parsed and therefore the results will differ.

### Which version of stylelint are you using?

7.4.2

### PR DESCRIPTION
**Pull request by kriansa**
Fixes #1989.

### CODE REVIEW

File: src/augmentConfig.js [hunk 1]
```diff
@@ -83,15 +86,10 @@ function augmentConfigFull(
...
-
-      if (!configWithOverrides.rules) {
+      if (!augmentedConfig.rules) {
         throw configurationError("No rules found within configuration. Have you provided a \"rules\" property?")
       }
-
-      return configWithOverrides
-    })
-    .then((augmentedConfig) => {
+
```
Comment (ntwb) [inline src/augmentConfig.js]: @kriansa can you remove the extra whitespace on this line please

**Comment by kriansa** [comment]
@davidtheclark I just added the tests. Would you review it again? Thanks.

File: src/__tests__/augmentConfig-test.js [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+      rules: [],
+    },
+    configOverrides: {
+      processors: ["./fixtures/processor-invalid-transformation"],
+    },
+  }).then(({ results }) => {
+    t.equal(results[0].errored, true)
+    t.end()
+  }).catch(t.end)
+})
```
Comment (davidtheclark) [inline src/__tests__/augmentConfig-test.js]: Since these tests are not testing `augmentConfig` specifically, but actually test `standalone`, let's put them in one of the other testfiles named to address `standalone`.

I'm not sure the assertion `t.equal(results[0].errored, true` is specific enough. There could be an error for other reasons. I suggest using one of the plugins that already exists & is involved in tests, adding it via `configOverrides`, then asserting that it caused warnings that would not have been caused if the plugin was not loaded.

**Comment by davidtheclark** [comment]
@kriansa When you finish your next commit, please rebase this branch so that it is up-to-date with master while only containing the commits for your change.

**Comment by kriansa** [comment]
@davidtheclark I just fixed it. Could you review it again?

File: src/__tests__/standalone-test.js [hunk 3]
```diff
@@ -226,4 +226,41 @@ test("standalone with config locatable from process.cwd not file", t => {
   })
 })
 
+test("Setting `plugins` inside `config` object should load the specified plugins", t => {
```
Comment (davidtheclark) [inline src/__tests__/standalone-test.js]: This test isn't necessary, because we already test plugins.

**Comment by kriansa** [comment]
@davidtheclark Fixed.

**Comment by davidtheclark** [comment]
Thanks @kriansa!
