### PR TITLE
Fix `declaration-property-value-no-unknown` range and message for invalid syntax within known functions

### LINKED ISSUE #8302: Fix `declaration-property-value-no-unknown` range and message for invalid syntax within known functions
### What minimal example or steps are needed to reproduce the bug?

```css
box-shadow: 0 4px 8px 0 rgba(#ff611d, 0.5);
```

### What minimal configuration is needed to reproduce the bug?

```js
module.exports = {
  extends: [
    'stylelint-config-standard',
    'stylelint-config-html/astro',
    'stylelint-config-html/vue',
    'stylelint-config-html',
    'stylelint-config-recommended-vue/scss',
    'stylelint-config-recommended-vue',
    'stylelint-prettier/recommended',
  ],
  plugins: ['stylelint-scss'],
  overrides: [
    {
      files: ['**/*.astro', '**/*.vue'],
      customSyntax: 'postcss-html',
    },
    {
      files: ['**/*.scss'],
      customSyntax: 'postcss-scss',
    },
    {
      files: ['*.astro'],
      rules: {
        'custom-property-empty-line-before': null,
      },
    },
  ],
  rules: {
    'length-zero-no-unit': null,
    'import-notation': null,
    'function-no-unknown': [
      true,
      {
        ignoreFunctions: ['env', 'constant', 'math.div', '-', 'red', 'blue', 'green', 'div'],
      },
    ],
    'at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: ['mixin', 'include', 'extend', 'tailwind', 'use'],
      },
    ],
    'alpha-value-notation': null,
    'color-function-notation': null,
    'custom-property-pattern': null,
  },
};

```

### How did you run Stylelint?

`stylelint \"**/*.{astro,vue}\"`

### Which Stylelint-related dependencies are you using?

```json
{
  "stylelint": "16.13.0",
  "stylelint-config-standard": "37.0.0",
  "stylelint-config-html": "1.1.0",
  "stylelint-config-recommended-vue": "1.5.0",
  "stylelint-prettier": "5.0.2"
}
```

### What did you expect to happen?

No problems to be reported.

### What actually happened?

Unexpected unknown value "#ff611d" for property "box-shadow" (declaration-property-value-no-unknown)Stylelint[declaration-property-value-no-unknown](https://stylelint.io/user-guide/rules/declaration-property-value-no-unknown)

### Do you have a proposal to fix the bug?

_No response_

### PR DESCRIPTION
**Pull request by ryo-manba**
> Which issue, if any, is this issue related to?

Closes #8302 

> Is there anything in the PR that needs further explanation?

Improve error message and range when known functions contain invalid values.

### CODE REVIEW

File: lib/rules/declaration-property-value-no-unknown/index.mjs [hunk 1]
```diff
@@ -24,6 +24,8 @@ const messages = ruleMessages(ruleName, {
 	rejected: (property, value) => `Unexpected unknown value "${value}" for property "${property}"`,
 	rejectedParseError: (property, value) =>
 		`Cannot parse property value "${value}" for property "${property}"`,
+	rejectedValueFunction: (property, valueFunction) =>
```
Comment (Mouvedia) [inline lib/rules/declaration-property-value-no-unknown/index.mjs:27]: Let's not add a supplementary type of message.
You can reuse `rejected`, it will remain accurate.

Comment (Mouvedia) [inline lib/rules/declaration-property-value-no-unknown/index.mjs:27]: If we add a new message type it should be scoped.
i.e. the function name should be present
e.g. `Unexpected unknown value "${value}" for function "${name}"`

Either change the message or simple reuse `rejected`.

Comment (jeddy3) [reply lib/rules/declaration-property-value-no-unknown/index.mjs:27]: Let's pass it whole to the existing `rejected` function, e.g.:

'Unexpected unknown value "rgb(255, 255)" for property "color"'

That's clear enough, and an improvement on what we currently have.

**Review by jeddy3 — COMMENTED** [review]
@ryo-manba Thanks for working on this.

The ranges look good. Once we address the message suggestion, I think we can merge.

**Comment by ryo-manba** [comment]
@jeddy3 @Mouvedia 
Thanks for the review! I've fixed it.

**Review by jeddy3 — APPROVED** [review]
Thank you, LGTM.
