### PR TITLE
Fix `font-family-no-missing-generic-family-keyword` false positives for `font-family` descriptor in `@font-palette-values`

### LINKED ISSUE #8139: Fix `font-family-no-missing-generic-family-keyword` false positives for `font-family` descriptor in `@font-palette-values`
### What minimal example or steps are needed to reproduce the bug?

```css
@font-palette-values --example {
  font-family: example;
  override-colors: 0 red;
}

```

### What minimal configuration is needed to reproduce the bug?

```json
"rules": {
  "font-family-no-missing-generic-family-keyword": true
}
```

### How did you run Stylelint?

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIACAzCA7ALgWgA4EMAbGTTGbANyIFcYBnAAm2xgA98BbXYh4AHXQMGaLNhScAloQCe8Bm07cYAbgFCIFGACctE2NkiEIWunIAMDLTCir0AXxAAaECikwAcpziIFXYgDowOjoncAxXAHMEEH50Pkw+EC1qYjpEuVj4rJcMHHEOKWlsdAhsAuCJdAjsCJh0bQkwMUkZbABrGGkAd2ModIZMZJgBeLsBMfRQyHRIgDFjDnxMaIArOgxQ2FwQxFihRLpMaWJCSoSEBkTCJfpz8ZA7IA)

### Which Stylelint-related dependencies are you using?

```json
  "stylelint": "^16.10.0",
  "stylelint-config-standard-scss": "^13.1.0",
```

### What did you expect to happen?

`font-family-no-missing-generic-family-keyword` should ignore the absence of generic font-family keyword when defining font-palette-values, since the color palette definition is only valid when used for color font. 

### What actually happened?

The following problem was reported:

```
2:16-23
ERROR Unexpected missing generic font family (font-family-no-missing-generic-family-keyword)
```

### Do you have a proposal to fix the bug?

_No response_

### PR DESCRIPTION
**Pull request by grommasdietz**
> Which issue, if any, is this issue related to?

Closes #8139

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

### CODE REVIEW

File: lib/rules/font-family-no-missing-generic-family-keyword/index.cjs [hunk 1]
```diff
@@ -63,13 +63,17 @@ const rule = (primary, secondaryOptions) => {
...
+			// Ignore @font-face and @font-palette-values
 			const parent = decl.parent;
 
 			if (parent && typeGuards.isAtRule(parent) && parent.name.toLowerCase() === 'font-face') {
 				return;
 			}
 
+			if (parent && typeGuards.isAtRule(parent) && parent.name.toLowerCase() === 'font-palette-values') {
+				return;
+			}
```
Comment (Mouvedia) [inline lib/rules/font-family-no-missing-generic-family-keyword/index.cjs:75]:
```suggestion
			const parent = decl.parent;
			const rules = ['font-face', 'font-palette-values'];

			if (parent && typeGuards.isAtRule(parent) && rules.includes(parent.name.toLowerCase())) {
				return;
			}
```

File: lib/rules/font-family-no-missing-generic-family-keyword/__tests__/index.mjs [hunk 2]
```diff
@@ -50,6 +50,12 @@ testRule({
 		{
 			code: '@FONT-FACE { font-family: Gentium; }',
 		},
+		{
+			code: "@font-palette-values --foo { font-family: bar; }",
+		},
+		{
+			code: "@FONT-PALETTE-VALUES -foo { font-family: bar; }",
```
Comment (Mouvedia) [inline lib/rules/font-family-no-missing-generic-family-keyword/__tests__/index.mjs:57]: question

Why `-foo` and not `--foo`?

**Comment by grommasdietz** [comment]
Added missing rules on mjs. Think we are done. Adapted the term `rules` as @Mouvedia suggested, but maybe `exceptions` would be more precisely? (Don’t know how it’s handled in other parts of stylelint, though).

In general I tried to clone the repository and edited locally with Visual Studio Code, sadly the lint/prettier setup  did not work out for me. Neither in VS Code, nor via Terminal. It e.g. always used double instead of single quotation marks. So I ended up transferring all the changes manually to open the pull request. Not sure if I did something wrong, I could get it work by manually referring to the npm package, but the terminal build process still ended up in wrong formatting.

Would be happy to contribute in the future, but don’t want to crash with wrong formats or transferring suggestions manually.

File: lib/rules/font-family-no-missing-generic-family-keyword/index.cjs [hunk 3]
```diff
@@ -63,10 +63,10 @@ const rule = (primary, secondaryOptions) => {
 		}
 
 		root.walkDecls(/^font(-family)?$/i, (decl) => {
-			// Ignore @font-face
+			// Ignore @font-face and @font-palette-values
 			const parent = decl.parent;
-
-			if (parent && typeGuards.isAtRule(parent) && parent.name.toLowerCase() === 'font-face') {
+			const rules = ['font-face', 'font-palette-values'];
```
Comment (Mouvedia) [inline lib/rules/font-family-no-missing-generic-family-keyword/index.cjs:68]: `npm run build` should have added the missing newline for you.

Comment (grommasdietz) [reply lib/rules/font-family-no-missing-generic-family-keyword/index.cjs:68]: v23.3.0, but as I said, I can’t really use `npm run format` and `npm run build`, since it’s formatting wrongly. Should I switch node version, does this help?

Comment (Mouvedia) [reply lib/rules/font-family-no-missing-generic-family-keyword/index.cjs:68]: > Should I switch node version, does this help?

I was just curious; 23 is fine.

> …since it’s formatting wrongly

I don't know what's going on, but since there is only one file to edit, what about doing it manually?
i.e.
```suggestion
			const rules = ['font-face', 'font-palette-values'];

```

File: lib/rules/font-family-no-missing-generic-family-keyword/__tests__/index.mjs [hunk 4]
```diff
@@ -50,6 +50,12 @@ testRule({
 		{
 			code: '@FONT-FACE { font-family: Gentium; }',
 		},
+		{
+			code: "@font-palette-values --foo { font-family: bar; }",
+		},
+		{
+			code: "@FONT-PALETTE-VALUES --foo { font-family: bar; }",
+		},
```
Comment (Mouvedia) [inline lib/rules/font-family-no-missing-generic-family-keyword/__tests__/index.mjs:58]:
```suggestion
		{
			code: '@font-palette-values --foo { font-family: bar; }',
		},
		{
			code: '@FONT-PALETTE-VALUES --foo { font-family: bar; }',
		},
```

File: lib/rules/font-family-no-missing-generic-family-keyword/index.mjs [hunk 5]
```diff
@@ -60,10 +60,11 @@ const rule = (primary, secondaryOptions) => {
 		}
 
 		root.walkDecls(/^font(-family)?$/i, (decl) => {
```
Comment (ybiquitous) [inline lib/rules/font-family-no-missing-generic-family-keyword/index.mjs:62]:
```suggestion
		const ignoredAtRules = new Set(['font-face', 'font-palette-values']);

		root.walkDecls(/^font(-family)?$/i, (decl) => {
```

File: lib/rules/font-family-no-missing-generic-family-keyword/index.mjs [hunk 6]
```diff
@@ -60,10 +60,11 @@ const rule = (primary, secondaryOptions) => {
...
-			// Ignore @font-face
+			// Ignore @font-face and @font-palette-values
```
Comment (ybiquitous) [inline lib/rules/font-family-no-missing-generic-family-keyword/index.mjs:63]: [suggestion]

```suggestion
```

File: lib/rules/font-family-no-missing-generic-family-keyword/index.mjs [hunk 7]
```diff
@@ -60,10 +60,11 @@ const rule = (primary, secondaryOptions) => {
...
 			const parent = decl.parent;
+			const rules = ['font-face', 'font-palette-values'];
```
Comment (ybiquitous) [inline lib/rules/font-family-no-missing-generic-family-keyword/index.mjs:65]: [suggestion]

```suggestion
```

**Review by ybiquitous — COMMENTED** [review]
Thanks for the pull request!

I've left some refactoring suggestions, although they're not critical. Can you have a look?

1. Move the ignored at-rules array creation outside the walk loop for performance.
2. Give a clearer name to the array variable for readability.
3. Convert the array to a set for performance.
4. Remove the redundant code comment for readability.

**Review by jeddy3 — APPROVED** [review]
@grommasdietz Thank you for the PR. 

Merging so we can include the fix in our upcoming release, which I'm about to start.
