### PR TITLE
Ignore some properties with 0 value (#4250)

### LINKED ISSUE #4250: False positive `length-zero-no-unit` on `fr` unit
> Clearly describe the bug

There is a false positive for `0fr` when used in multiple values for `grid-template-rows` or similar css-grid properties.

`0fr 1fr` behaves differently to `0 1fr` on this property. The `fr` unit refers to _remaining space_ in the grid. `0` (without a unit) is treated as no height at all.
Using `0 1fr` the second row will overlap the first. Using `0fr 1fr` the height of the first row will be taken in to account and the second row will not overlap. [Here's](https://codepen.io/djfw/pen/ExYbExz) a minimal codepen to display the difference between the two and why this is a false positive.

> Which rule, if any, is the bug related to?

`length-zero-no-unit`

> What CSS is needed to reproduce the bug?

```css
.grid {
  display: grid;
  grid-template-rows: 0fr 1fr;
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "length-zero-no-unit": true
  }
}
```

> Which version of stylelint are you using?

`10.1.0`

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

`stylelint 'src/sass/**/*.scss'`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

I am using scss and `stylelint-scss@3.9.4` but I'm not sure if that matters here (could be wrong of course 🤷‍♂)

> What did you expect to happen?

No warnings to be flagged.

> What actually happened (e.g. what warnings or errors did you get)?

`Unexpected unit (length-zero-no-unit)`

### PR DESCRIPTION
**Pull request by fanich37**
> Which issue, if any, is this issue related to?

It should close #4250 . 

> Is there anything in the PR that needs further explanation?

Nope, the logic of the PR is quite clear.

### CODE REVIEW

**Comment by hudochenkov** [comment]
This is strange. Rule file is not formatted by Prettier. But Prettier is run on pre-commit hook. Could you run `npm install` just to be sure git hooks are installed. And run `npm run prettier:fix` to reformat files.

In one of previous PRs you also had lint errors, because file wasn't formatted with Prettier. Maybe you skipping git hook intentionally?

**Comment by fanich37** [comment]
> This is strange. Rule file is not formatted by Prettier. But Prettier is run on pre-commit hook. Could you run `npm install` just to be sure git hooks are installed. And run `npm run prettier:fix` to reformat files.
> 
> In one of previous PRs you also had lint errors, because file wasn't formatted with Prettier. Maybe you skipping git hook intentionally?

Hm... Hooks are installed but doesn't seem to work. Could it depend on an OS platform? I use Win 10 now and can also check it on Ubuntu.

**Comment by hudochenkov** [comment]
> Could it depend on an OS platform?

It shouldn't be a problem because of OS, but who knows, everything is possible.

I have no idea what could be wrong :(

File: lib/rules/length-zero-no-unit/__tests__/index.js [hunk 1]
```diff
@@ -431,3 +494,15 @@ testRule(rule, {
...
 });
+
+testRule(rule, {
+	ruleName,
+	config: [true],
+	fix: true,
+
+	accept: [
+		{
+			code: '.a { grid-template-rows: 0fr 1fr; }',
```
Comment (hudochenkov) [inline lib/rules/length-zero-no-unit/__tests__/index.js]: I think you can put this test where you added other tests, because stylelint configuration is the same.

Comment (fanich37) [reply lib/rules/length-zero-no-unit/__tests__/index.js]: Ooops... Agree. Put it with other tests.
P.S. The last commit I did from Ubuntu and pre-commit hook worked as expected :confused:

File: lib/rules/length-zero-no-unit/index.js [hunk 2]
```diff
@@ -20,6 +20,13 @@ const messages = ruleMessages(ruleName, {
 	rejected: 'Unexpected unit',
 });
 
+const gridPropertiesToIgnore = [
+	'grid-template-columns',
+	'grid-template-rows',
+	'grid-auto-columns',
+	'grid-auto-rows',
+];
```
Comment (evilebottnawi) [inline lib/rules/length-zero-no-unit/index.js]: What about move this in https://github.com/stylelint/stylelint/tree/master/lib/reference?

Comment (fanich37) [reply lib/rules/length-zero-no-unit/index.js]: Now I think this array can be removed at all. Since ```fr``` unit only works with grid family properties (correct me if it's not so) this check is useless. Do you agree?

Comment (hudochenkov) [reply lib/rules/length-zero-no-unit/index.js]: @fanich37 it makes sense! :)

Comment (fanich37) [reply lib/rules/length-zero-no-unit/index.js]: @hudochenkov @evilebottnawi removed.

File: lib/rules/length-zero-no-unit/index.js [hunk 3]
```diff
@@ -29,6 +29,10 @@ const rule = function(actual, secondary, context) {
 		}
 
 		root.walkDecls((decl) => {
+			if (decl.prop.toLowerCase() === 'line-height') {
```
Comment (evilebottnawi) [inline lib/rules/length-zero-no-unit/index.js]: Not only `line-height` can contains `<length> | <percentage>`, for example https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-width, https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dashoffset and other, you can find them here https://github.com/mdn/data/blob/master/css/properties.json, also let's put them in https://github.com/stylelint/stylelint/tree/master/lib/reference

**Comment by vankop** [comment]
> I think we can create build script to automatically update references required for rules before release

You are totally right =)

File: lib/rules/length-zero-no-unit/index.js (hunk 3 above)
Comment (fanich37) [reply lib/rules/length-zero-no-unit/index.js]: To be honest I completely lost the idea why I'd ignored ```line-height``` 😕 .
This is the same:
```css
line-height: 0;
line-height: 0px;
line-height: 0em;
```
So in case of zero value the dimension unit is useless and the warning should be flagged (or it should be auto-fixed).
The only unit to ignore here is ```fr``` since ```0fr``` and ```0``` mean completely different things.

Comment (evilebottnawi) [reply lib/rules/length-zero-no-unit/index.js]: `line-height: 0;` !== `line-height: 0px;`

Сlarifications and examples - https://github.com/cssnano/cssnano/issues/768

Comment (fanich37) [reply lib/rules/length-zero-no-unit/index.js]: Make sense.
But what the point to ignore ```stroke-width``` for example. It doesn't matter whether it has unit or not. Example: https://jsfiddle.net/vc2otk06/

Comment (evilebottnawi) [reply lib/rules/length-zero-no-unit/index.js]: Oh, yes, my mistake, you are right, don't found other properties with same ability as `line-height` has, let's add tests for this cases:
```css
a { font: normal normal 400 16px/0px cursive; }
```
```css
a { font: normal normal 400 16px/0 cursive; }
```

Comment (fanich37) [reply lib/rules/length-zero-no-unit/index.js]: The funny thing is these cases don't break tests in master branch but they have to.
I add some logic to process ```font``` declaration and update test cases.

**Comment by hudochenkov** [comment]
> -   Fixed: `length-zero-no-unit` false positives for `line-height`, and for `fr` units ([#4394](https://github.com/stylelint/stylelint/pull/4394)).
