### PR TITLE
Fix `custom-property-no-missing-var-function` false positives for style query in `if()` function

### LINKED ISSUE #8805: Fix `custom-property-no-missing-var-function` false positives for style query in `if()` function
### What minimal example or steps are needed to reproduce the bug?

```css
button {
	--state: normal;
	background-color: if(
		style(--state: hover): gray;
		else: white;
	);
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "custom-property-no-missing-var-function": true
  }
}
```

### How did you run Stylelint?

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcIBGBXALmiA7ABMAOlvmgLQkDOaAhmjPDlhAE4C2VANgNyHFJVgBrAOZMIKLFBKR2zegEsAZgAoeaYpQCe7GErKUadHAAsIANxhMAlPRFUN3ImtrtyhgO5G5tB8UsOAvoQgADQgCnLaAHJULHCIMAAeMQAO2gB0YOTkIeDY4UIIIAS4OPggTCja5GX0xTj1peAolBAsJMmiyRZoGiSMJCxyWXJYQiSmVEwkCuJgaHLYNThoFTCE9YFY-jmQWPkAYsxsaIUAVuTYObDJ2Yh1jZra7CNqCI3sBpRlwesPPU8vKR5ORjfQSSZQJZlD60L4gQjbfxAA)

### Which Stylelint-related dependencies are you using?

```json
{
  "stylelint": "16.25.0"
}
```

### What did you expect to happen?

We don't need `var()` function to enclose the custom property, where in the style query condition (`style()`) of `if()` function. `custom-property-no-missing-var-function` should not report the error.

### What actually happened?

```
4:9-16 error Unexpected missing var function for "--state" (custom-property-no-missing-var-function)
```

### Do you have a proposal to fix the bug?

Note that `if()` function will also raise `declaration-property-value-no-unknown` error, for temporarily solution please see #8779 . Since there are too many new CSS features raise `declaration-property-value-no-unknown` errors, I don't think it's worth creating issues for each of them.

Due to this issue is not related to upstream (MDN, CSSTree), I think this issue can be fixed manually by PR. However after fixing, it might solve `custom-property-no-missing-var-function` error only, you will still get the `declaration-property-value-no-unknown` error.

### PR DESCRIPTION
**Pull request by sajdakabir**
> Which issue, if any, is this issue related to?

Closes #8805 

> Is there anything in the PR that needs further explanation?

No; the changes special-case style() queries inside if() by threading an insideStyleQuery flag through  "custom-property-no-missing-var-function" update the generated CJS bundle, and add targeted tests to cover the new behavior.

### CODE REVIEW

**Comment by otomad** [comment]
Can you also add these tests:

1. Error code:

```css
a {
    --foo: 1;
    --bar: 2;
    color: if(
        style(--foo: --bar): red;
        else: green;
    );
}
```
After auto fix (Correct code):

```css
a {
    --foo: 1;
    --bar: 2;
    color: if(
        style(--foo: var(--bar)): red;
        else: green;
    );
}
```

2. Error code:

```css
a {
    --foo: 1;
    --color: red;
    color: if(
        style(--foo: 1): --color;
        else: green;
    );
}
```
After auto fix (Correct code):

```css
a {
    --foo: 1;
    --color: red;
    color: if(
        style(--foo: 1): var(--color);
        else: green;
    );
}
```

**Comment by sajdakabir** [comment]
@otomad i have updated the pr accordingly to requested changes

File: lib/rules/custom-property-no-missing-var-function/index.mjs [hunk 1]
```diff
@@ -61,25 +61,26 @@ const rule = (primary) => {
 
 		root.walkDecls((decl) => {
 			const { prop, value } = decl;
-
 			if (!value.includes('--')) return;
```
Comment (otomad) [inline lib/rules/custom-property-no-missing-var-function/index.mjs:65]:
```suggestion
			const { prop, value } = decl;

			if (!value.includes('--')) return;
```

File: lib/rules/custom-property-no-missing-var-function/index.mjs [hunk 2]
```diff
@@ -88,23 +89,47 @@ const rule = (primary) => {
...
+					// but still check the value part after the colon
+					let foundColon = false;
+
+					node.nodes.forEach((arg) => {
+						if (arg.type === 'div' && arg.value === ':') {
+							foundColon = true;
+						} else if (!foundColon && isDashedIdent(arg)) {
+							// This is the property name in the query - skip it
+							return;
+						} else if (foundColon) {
```
Comment (otomad) [inline lib/rules/custom-property-no-missing-var-function/index.mjs:101]:
```suggestion
						} else if (!foundColon && isDashedIdent(arg)) {
							// This is the property name in the query - skip it
						} else if (foundColon) {
```

File: lib/rules/custom-property-no-missing-var-function/__tests__/index.mjs [hunk 3]
```diff
@@ -86,6 +86,22 @@ testRule({
...
+			description: 'declared custom property in style() query within if() function',
+		},
+		{
+			code: ':root { --theme: dark; } a { color: if(style(--theme: light): black; else: white;); }',
+			description: 'declared custom property in style() query condition',
+		},
+		{
+			code: 'a { --foo: 1; --bar: 2; color: if(style(--foo: 1): if(style(--bar: 2): red; else: blue;); else: green;); }',
+			description: 'nested if() with multiple style() queries',
+		},
```
Comment (otomad) [inline lib/rules/custom-property-no-missing-var-function/__tests__/index.mjs:104]: Also add the accept tests

```suggestion
		},
		{
			code: 'a { --foo: 1; --bar: 2; color: if(style(--foo: var(--bar)): red; else: green;); }',
			description: 'nested if() with multiple style() queries',
		},
		{
			code: 'a { --foo: 1; --color: red; color: if(style(--foo: 1): var(--color); else: green;); }',
			description: 'nested if() with multiple style() queries',
		},
```

File: lib/rules/custom-property-no-missing-var-function/__tests__/index.mjs [hunk 4]
```diff
@@ -224,5 +240,23 @@ testRule({
 			],
 			description: 'nested var() with second-level fallback missing var() syntax',
 		},
+		{
+			code: 'a { --foo: 1; --bar: 2; color: if( style(--foo: --bar): red; else: green; ); }',
+			message: messages.rejected('--bar'),
+			line: 1,
+			column: 49,
+			endLine: 1,
+			endColumn: 54,
```
Comment (otomad) [inline lib/rules/custom-property-no-missing-var-function/__tests__/index.mjs]: Consistent coding style.

```suggestion
			code: 'a { --foo: 1; --bar: 2; color: if(style(--foo: --bar): red; else: green;); }',
			message: messages.rejected('--bar'),
			line: 1,
			column: 48,
			endLine: 1,
			endColumn: 53,
```

File: lib/rules/custom-property-no-missing-var-function/__tests__/index.mjs [hunk 5]
```diff
@@ -224,5 +240,23 @@ testRule({
...
+			description: 'custom property in style() query value missing var() syntax',
+		},
+		{
+			code: 'a { --foo: 1; --color: red; color: if( style(--foo: 1): --color; else: green; ); }',
+			message: messages.rejected('--color'),
+			line: 1,
+			column: 57,
+			endLine: 1,
+			endColumn: 64,
```
Comment (otomad) [inline lib/rules/custom-property-no-missing-var-function/__tests__/index.mjs]: Consistent coding style.

```suggestion
			code: 'a { --foo: 1; --color: red; color: if(style(--foo: 1): --color; else: green;); }',
			message: messages.rejected('--color'),
			line: 1,
			column: 56,
			endLine: 1,
			endColumn: 63,
```

**Review by otomad — CHANGES_REQUESTED** [review]

**Comment by otomad** [comment]
Sorry I have no edit permission, so I just reviewed it by adding suggested changes in the comments.

**Comment by sajdakabir** [comment]
@otomad thanks for the review. I’ve completed the updates please let me know if you need any other changes.

File: lib/rules/custom-property-no-missing-var-function/index.mjs (hunk 1 above)
Comment (otomad) [inline lib/rules/custom-property-no-missing-var-function/index.mjs:65]: I don't know if you should add an empty line before `if (!value.includes('--')) return;` to solve the lint problem.

**Review by otomad — APPROVED** [review]

File: lib/rules/custom-property-no-missing-var-function/index.mjs [hunk 6]
```diff
@@ -67,19 +67,21 @@ const rule = (primary) => {
...
 			});
 		});
 
 		/**
 		 * @param {Node} node
 		 * @param {import('postcss').Declaration} decl
+		 * @param {boolean} insideStyleQuery - Whether we're inside a style() query
 		 */
-		function check(node, decl) {
+		function check(node, decl, insideStyleQuery) {
```
Comment (Mouvedia) [inline lib/rules/custom-property-no-missing-var-function/index.mjs]: question

It seems `check` is never called with `insideStyleQuery === true`.
Hence `insideStyleQuery` is never set to `true`.

```suggestion
		function check(node, decl, insideStyleQuery = false) {
```
then revert l70 and l105.

What are you planning to use `passStyleQuery`/`insideStyleQuery` for?

**Comment by sajdakabir** [comment]
@Mouvedia i have  remove unused insideStyleQuery parameter

File: lib/rules/custom-property-no-missing-var-function/index.mjs [hunk 7]
```diff
@@ -97,14 +114,17 @@ const rule = (primary) => {
 
 			if (!isDashedIdent(node)) return;
 
-			if (!knownCustomProperties.has(node.value)) return;
+			// Strip trailing semicolons for lookup and reporting
```
Comment (romainmenke) [inline lib/rules/custom-property-no-missing-var-function/index.mjs]:
```suggestion
			// `postcss-value-parser` incorrectly includes semicolons in word tokens.
```

Maybe document why we need to do this.

File: lib/rules/custom-property-no-missing-var-function/index.mjs [hunk 8]
```diff
@@ -119,7 +139,10 @@ const rule = (primary) => {
  * @param {Node} node
  */
 function isDashedIdent({ type, value }) {
-	return type === 'word' && value.startsWith('--');
+	// Strip trailing semicolons that may be part of conditional syntax
+	const cleanValue = value.replace(/;+$/, '');
+
+	return type === 'word' && cleanValue.startsWith('--');
```
Comment (romainmenke) [inline lib/rules/custom-property-no-missing-var-function/index.mjs]: I don't think this is needed.
It didn't make sense to me to strip trailing chars, when only checking the start.

Can you revert to:

```js
/**
 * @param {Node} node
 */
function isDashedIdent({ type, value }) {
	return type === 'word' && value.startsWith('--');
}
```

**Review by romainmenke — COMMENTED** [review]
Thank you @sajdakabir,

I've left a couple of suggestions, please take a look when you have time.

**Comment by ybiquitous** [comment]
@sajdakabir This PR includes extra files, such as `.changeset/chubby-donkeys-remain.md`. Can you rebase the main branch, please? 🙏🏼

**Comment by jeddy3** [comment]
@sajdakabir Thanks for making the requested changes and for rebasing.

I'll merge so that we can include this fix in the release I'm just about to start.
