### PR TITLE
Fix resolution of configs, plugins, processors, and custom syntaxes in Yarn PnP environments

### LINKED ISSUE #8971: Fix `ConfigurationError: Could not find ...` error for Yarn PnP
## What did you expect to happen?

Stylelint should be able to resolve extended configs (`stylelint-config-standard-scss`) when using Yarn Berry with PnP mode.

## What actually happened?

```
ConfigurationError: Could not find "stylelint-config-standard-scss". Do you need to install the package or use the "configBasedir" option?
    at getModulePath (file:///.yarn/__virtual__/stylelint-virtual-.../node_modules/stylelint/lib/utils/getModulePath.mjs:29:9)
    at loadExtendedConfig (file:///.yarn/__virtual__/stylelint-virtual-.../node_modules/stylelint/lib/augmentConfig.mjs:224:21)
```

## How can I reproduce it?

1. Create a Yarn Berry project with PnP enabled (`nodeLinker: pnp`)
2. Add `stylelint@^17.0.0` and `stylelint-config-standard-scss@^17.0.0` to devDependencies
3. Create `stylelint.config.mjs`:
```js
export default {
  extends: ['stylelint-config-standard-scss'],
};
```
4. Run `yarn stylelint "**/*.css"`

## Expected behavior

Stylelint should resolve the config from the package's dependencies.

## Environment

- Node.js: 22.18.0
- Yarn: 4.12.0 (with PnP)
- stylelint: 17.0.0
- stylelint-config-standard-scss: 17.0.0
- OS: macOS

This worked in stylelint v16.

### PR DESCRIPTION
**Pull request by adalinesimonian**
Fixes #8971.

The import-meta-resolve polyfill does not integrate with Yarn PnP's module resolution because it doesn't respect ESM loader hooks.

This change detects when the PnP runtime is loaded and uses its API to perform resolution where possible.

### CODE REVIEW

File: lib/utils/resolveSilent.mjs [hunk 1]
```diff
@@ -8,6 +10,68 @@ import { fileURLToPath, pathToFileURL } from 'node:url';
...
+ * @param {string} specifier The module specifier to resolve.
+ * @param {string} issuer The directory to resolve from. Must end with /.
+ * @returns {string | undefined} The resolved path, or undefined if resolution fails.
+ */
+function resolvePnP(specifier, issuer) {
+	// Only available in PnP environments.
+	if (!process.versions.pnp) {
+		return undefined;
+	}
+
```
Comment (ybiquitous) [inline lib/utils/resolveSilent.mjs]: [suggestion] Minor. This `.pnp` check is duplicated with `if (isBareSpecifier && process.versions.pnp)`. Can we remove it?

```diff
-if (!process.versions.pnp) {
-	return undefined;
-}
```

File: lib/utils/resolveSilent.mjs [hunk 2]
```diff
@@ -8,6 +10,68 @@ import { fileURLToPath, pathToFileURL } from 'node:url';
...
+	// Module.findPnpApi is added by Yarn PnP at runtime.
+	const mod =
+		/** @type {typeof module & { findPnpApi?: (issuer: string) => { resolveRequest: (specifier: string, issuer: string) => string | null, resolveToUnqualified: (specifier: string, issuer: string) => string | null } | null }} */ (
```
Comment (ybiquitous) [inline lib/utils/resolveSilent.mjs]: [suggestion] This one-line `@type` is hard to read. What if switching to `@typedef` like this?

```js
/**
 * @typedef {{
 *   resolveRequest: (request: string, issuer: string | null) => string | null;
 *   resolveToUnqualified: (request: string, issuer: string | null) => string | null;
 * }} PnpApi
 * @typedef {(lookupSource: URL | string) => PnpApi | null} FindPnpApi
 */

// ...

const mod = /** @type {typeof module & { findPnpApi?: FindPnpApi }} */ (module);
```

**Review by ybiquitous — APPROVED** [review]
Thank you, LGTM 👍🏼

I've left a few minor suggestions to improve code readability, but they don't block this PR.

File: lib/utils/resolveSilent.mjs (hunk 1 above)
Comment (adalinesimonian) [reply lib/utils/resolveSilent.mjs]: Removed.

File: lib/utils/resolveSilent.mjs (hunk 2 above)
Comment (adalinesimonian) [reply lib/utils/resolveSilent.mjs]: Extracted to a `@typedef`.

**Review by ybiquitous — APPROVED** [review]

**Comment by jeddy3** [comment]
Tested locally with NPM, Yarn, Bun and PNPM package managers on the CLI and using the VS Code extension.

Thank you for the fix!
