### PR TITLE
Fix TypeError with benchmark-rule script

### LINKED ISSUE #3804: Fix TypeError with benchmark-rule script
> Clearly describe the bug

When running the command in [the documentation](https://github.com/stylelint/stylelint/blob/f865f3df5d67f97aa2d694d56f81d1ba5613f8b7/docs/developer-guide/rules.md#improving-the-performance-of-a-new-or-an-existing-rule), the following error is raised:

```
$ npm run benchmark-rule -- selector-combinator-space-after never

> stylelint@9.8.0 benchmark-rule /Users/koba/git/stylelint/stylelint
> node scripts/benchmark-rule.js "selector-combinator-space-after" "never"

/Users/koba/git/stylelint/stylelint/scripts/benchmark-rule.js:34
const rule = rules[ruleName].apply(null, normalizeRuleSettings(parsedOptions));
                             ^

TypeError: Cannot read property 'apply' of undefined
    at Object.<anonymous> (/Users/koba/git/stylelint/stylelint/scripts/benchmark-rule.js:34:30)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:308:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:878:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stylelint@9.8.0 benchmark-rule: `node scripts/benchmark-rule.js "selector-combinator-space-after" "never"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stylelint@9.8.0 benchmark-rule script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/koba/.npm/_logs/2018-11-12T15_37_35_699Z-debug.log
```

> Which rule, if any, is the bug related to?

There may be something wrong in `scripts/benchmark-rule.js`.

https://github.com/stylelint/stylelint/blob/f865f3df5d67f97aa2d694d56f81d1ba5613f8b7/scripts/benchmark-rule.js#L34

> What CSS is needed to reproduce the bug?

N/A

> What stylelint configuration is needed to reproduce the bug?

N/A

> Which version of stylelint are you using?

`9.8.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI script for developers.

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

N/A

> What did you expect to happen?

- Benchmark for all existing rules succeed.
- All examples of the benchmark script in documentation are fixed.

> What actually happened (e.g. what warnings or errors did you get)?

`npm run benchmark-rule` command failed.

### PR DESCRIPTION
**Pull request by cahamilton**
> Which issue, if any, is this issue related to?

Fixes #3804 

> Is there anything in the PR that needs further explanation?

Not specifically. Addresses issue with current benchmark script throwing a TypeError - which looks like it was caused by a refactor here: https://github.com/stylelint/stylelint/commit/973e07b81244eb359cfe5ee8cdf63a2ab4fba72c#diff-1b5afd6b670c8bdd40102c599cbc9697

PR contains code fixes and updates to documentation for the benchmarking script.

### CODE REVIEW

File: scripts/benchmark-rule.js [hunk 1]
```diff
@@ -6,13 +6,19 @@ const chalk = require("chalk");
...
 
 const ruleName = process.argv[2];
 const ruleOptions = process.argv[3];
+const ruleContext = process.argv[4];
 
-if (!ruleName || !ruleOptions) {
-  throw new Error("You must specify a rule name and rule options");
+if (!rules.includes(ruleName)) {
+  throw new Error("You must specify a valid rule name");
+}
```
Comment (ybiquitous) [inline scripts/benchmark-rule.js]: I think very nice for splitted `ruleName` and `ruleOptions` checks!

Further, how about replace `rules.includes(ruleName)` like this? 👇 

```js
const ruleFunc = requireRule(ruleName)
if (!ruleFunc) {
  throw new Error("You must specify a valid rule name");
}
```

Because `requireRule()` do `rules.includes(ruleName)` within it; it's doing the same thing.
In addition, by doing so `const rules = require("../lib/rules")` can be removed!

https://github.com/stylelint/stylelint/blob/c8354d8e4cc42b095393b854d3eff9f8987c65df/lib/requireRule.js#L6-L12

Comment (cahamilton) [reply scripts/benchmark-rule.js]: You are correct, good spot. Not sure how I missed that one. 

Just pushed that change now :+1:

Comment (ybiquitous) [reply scripts/benchmark-rule.js]: Thank you!
